const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),ts=require('typescript');
function fixture(){let resolve,calls=[],cancelCalls=[];const result=new Promise(r=>resolve=r),operation={op_id:'op',job_id:'job',dataset_version_id:'v1',cohort_sha256:'cohort',evaluation_binding_sha256:'binding',compute_profile_id:'server',device:'cpu',task:'classification',labelset_id:'default',state:'running'};
const api={evaluation:{getResults:async(job,options)=>{calls.push({job,options});return result;},getRemoteOperations:async()=>({operations:[{...operation,op_id:'wrong',dataset_version_id:'other'},operation]}),cancelRemoteOperation:async(id,binding)=>{cancelCalls.push({id,binding});return {...operation,cancel_requested_at:'now'};},getOverkillUnderkill:async()=>({}),getHeatmap:async()=>({})}};
const file=path.join(__dirname,'useEvaluationStore.ts'),m=new Module(file,module);m.filename=file;m.paths=Module._nodeModulePaths(__dirname);const req=m.require.bind(m);m.require=name=>name==='../services/api'?{api,getApiBaseUrl:async()=>''}:name==='./useTrainingStore'?{useTrainingStore:{getState:()=>({isCurrentData:true,status:'completed',jobId:'job'})}}:name==='../utils/classSemantics'?{classRole:()=>null,isDefectClass:()=>false}:req(name);m._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,file);
const store=m.exports.useEvaluationStore,source={folderPath:'/source',task:'classification',evaluationDatasetVersionId:'v1',computeProfileId:'server',device:'cpu'};return{store,state:()=>store.getState(),source,calls,cancelCalls,resolve,operation};}
test('production store passes frozen version and selected target/device and retains actual identity',async()=>{const f=fixture();const pending=f.state().loadEvaluation('job',f.source);assert.equal(f.calls[0].options.evaluationDatasetVersionId,'v1');assert.equal(f.calls[0].options.computeProfileId,'server');assert.equal(f.calls[0].options.device,'cpu');f.resolve({job_id:'job',metrics:{},common_cohort:{dataset_version_id:'v1',cohort_sha256:'cohort'},compute_profile_id:'server',device:'cpu',remote_operation_id:'op'});await pending;assert.equal(f.state().executionEvidence.common_cohort.cohort_sha256,'cohort');});
test('pending evaluation readback selects exact cohort target and cancellation sends immutable binding',async()=>{const f=fixture();const pending=f.state().loadEvaluation('job',f.source);await f.state().refreshRemoteOperation();assert.equal(f.state().remoteOperation.op_id,'op');await f.state().cancelRemoteEvaluation();assert.deepEqual(f.cancelCalls,[{id:'op',binding:{job_id:'job',cohort_sha256:'cohort',evaluation_binding_sha256:'binding'}}]);assert.equal(f.state().remoteOperation.cancel_requested_at,'now');f.resolve({job_id:'job',metrics:{},common_cohort:{dataset_version_id:'v1'},compute_profile_id:'server',device:'cpu'});await pending;});
test('source invalidation discards pending result and operation and forbids stale cancellation',async()=>{const f=fixture();const pending=f.state().loadEvaluation('job',f.source);await f.state().refreshRemoteOperation();f.state().invalidateForDataChange();assert.equal(f.state().remoteOperation,null);await f.state().cancelRemoteEvaluation();assert.equal(f.cancelCalls.length,0);f.resolve({job_id:'job',metrics:{accuracy:1}});await pending;assert.deepEqual(f.state().metrics,{});});
test('wrong returned cohort or profile refuses rather than labelling it requested target',async()=>{const f=fixture();const pending=f.state().loadEvaluation('job',f.source);f.resolve({job_id:'job',metrics:{accuracy:1},common_cohort:{dataset_version_id:'other'},compute_profile_id:'server'});await assert.rejects(pending,/cohort|코호트|버전/);assert.deepEqual(f.state().metrics,{});});
test('selected frozen-cohort result never launches legacy job-only analysis or report',async()=>{const f=fixture();let analysis=0;f.store.setState({loadOverkillUnderkill:async()=>{analysis++;}});const pending=f.state().loadEvaluation('job',f.source);f.resolve({job_id:'job',metrics:{},common_cohort:{dataset_version_id:'v1'},compute_profile_id:'server',device:'cpu'});await pending;assert.equal(analysis,0);await assert.rejects(()=>f.state().exportReport('json'),/코호트/);});
test('readback delayed across invalidation does not restore old cancellation identity',async()=>{const f=fixture();let reply;f.store.setState({remoteRequest:{jobId:'job',source:f.source,generation:0}});const pending=f.state().loadEvaluation('job',f.source);const read=f.state().refreshRemoteOperation();f.state().invalidateForDataChange();await read;assert.equal(f.state().remoteOperation,null);f.resolve({job_id:'job',metrics:{}});await pending;});
test('cohort transfer preparing operation is available for bound cancellation',async()=>{const f=fixture();f.operation.state='preparing';const pending=f.state().loadEvaluation('job',f.source);await f.state().refreshRemoteOperation();assert.equal(f.state().remoteOperation?.op_id,'op');f.resolve({job_id:'job',metrics:{},common_cohort:{dataset_version_id:'v1'},compute_profile_id:'server',device:'cpu'});await pending;});
