const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),ts=require('typescript'),test=require('node:test');
function load(file,mocks={}){const name=path.resolve(__dirname,file);if(!fs.existsSync(name))return {};const m=new Module(name,module);m.filename=name;m.paths=Module._nodeModulePaths(path.dirname(name));const req=m.require.bind(m);m.require=ref=>mocks[ref]??req(ref);m._compile(ts.transpileModule(fs.readFileSync(name,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText,name);return m.exports;}
function harness(){let cursor=0;const slots=[],effects=[];const react={useState:initial=>{const i=cursor++;if(!(i in slots))slots[i]=typeof initial==='function'?initial():initial;return[slots[i],v=>slots[i]=typeof v==='function'?v(slots[i]):v];},useRef:initial=>{const i=cursor++;if(!(i in slots))slots[i]={current:initial};return slots[i];},useEffect:(fn,deps)=>{const i=cursor++;if(!slots[i]||deps.some((v,j)=>v!==slots[i].deps[j])){slots[i]?.cleanup?.();slots[i]={deps};effects.push(()=>{slots[i].cleanup=fn();});}}};const jsx=(type,props)=>({type,props:props||{}});return{react,mocks:{react,'react/jsx-runtime':{jsx,jsxs:jsx},'lucide-react':{}},render:fn=>{cursor=0;const tree=fn();effects.splice(0).forEach(fn=>fn());return tree;}};}
const settle=()=>new Promise(setImmediate);
function nodes(tree){const found=[];function visit(v){if(Array.isArray(v))v.forEach(visit);else if(v&&typeof v==='object'){found.push(v);visit(v.props?.children);}}visit(tree);return found;}
const packageRow=id=>({package_id:id,name:id,package_path:`/project/exports/flows/${id}`,integrity:'verified',scope_matches:true,manifest_sha256:`hash-${id}`,parity:{status:'not_run'},optimization_jobs:[]});
const project={id:'project',project_dir:'/project',source_dataset_dir:'/source',task:'segmentation'};
function scopeMock(){const scope={current:{key:'scope'}};return{useDeliveryScope:()=>({scope,key:'scope',project,projectDir:'/project'})};}

test('export task B actually reselects the saved package and reopens B while A was selected',async()=>{
 const h=harness(),rows=['A','B'].map(packageRow);let saved='A',handoff={kind:'export',jobId:'B',taskKey:'export:local:B',selectionId:'first'};const opened=[];
 const m=load('PackageLibraryPanel.tsx',{...h.mocks,'../../services/api':{api:{dataset:{getImages:async()=>({items:[]})}}},'../../services/productDeliveryApi':{productDeliveryApi:{packages:async()=>({packages:rows,selected_package_id:saved}),select:async id=>{saved=id;return rows.find(row=>row.package_id===id);}}},'../runtime/useDeliveryScope':scopeMock(),'../runtime/deliveryContracts':load('../runtime/deliveryContracts.ts'),'../training/useTaskHandoff':{useTaskHandoff:()=>handoff}});
 const render=()=>h.render(()=>m.PackageLibraryPanel({sourceFolder:'/source',task:'segmentation',onSelected:row=>opened.push(row.package_id)}));render();await settle();const tree=render();assert.equal(saved,'B');assert.deepEqual(opened,['B']);assert.ok(nodes(tree).some(node=>node.type==='article'&&node.props.className.includes('border-cyan-500')&&nodes(node).some(child=>child.type==='b'&&child.props.children==='B')));
 saved='A';handoff={...handoff,selectionId:'second'};render();await settle();render();assert.equal(saved,'B','Selecting the same task again must reopen it after a different manual selection');
});
test('deployment picker restores export B through selection instead of retaining empty or old path',async()=>{
 const h=harness(),rows=['A','B'].map(packageRow);let saved='A',value=rows[0].package_path;
 const m=load('../runtime/SavedPackagePicker.tsx',{...h.mocks,'../../services/productDeliveryApi':{productDeliveryApi:{packages:async()=>({packages:rows,selected_package_id:saved}),select:async id=>{saved=id;return rows.find(row=>row.package_id===id);}}},'./useDeliveryScope':scopeMock(),'../training/useTaskHandoff':{useTaskHandoff:()=>({kind:'export',jobId:'B',taskKey:'export:local:B'})}});
 const render=()=>h.render(()=>m.SavedPackagePicker({value,onChange:next=>value=next}));render();await settle();const tree=render();assert.equal(saved,'B');assert.equal(value,rows[1].package_path);assert.equal(nodes(tree).find(node=>node.type==='select').props.value,'B');
});
test('requested optimization record B reopens despite newer per-package record A',async()=>{
 const h=harness(),state={projectDir:'/project'};const store=selector=>selector(state);let value='A';const oldStorage=Object.getOwnPropertyDescriptor(global,'localStorage');Object.defineProperty(global,'localStorage',{configurable:true,value:{getItem:()=>value,setItem:(_,id)=>value=id}});
 const job=id=>({job_id:id,status:'failed',package_path:`/project/exports/flows/candidate-${id}`,options:{package_dir:'/project/exports/flows/source',input_receipt:{source_dataset_path:'/source'}},error:'fixture conversion stopped',result:null});
 const m=load('RuntimeOptimizationPanel.tsx',{...h.mocks,'../../stores/useProjectStore':{useProjectStore:store},'../../services/api':{api:{dataset:{getImages:async()=>({items:[]})}}},'../../services/runtimeDeploymentApi':{runtimeDeploymentApi:{capabilities:async()=>({openvino:{available:false,devices:[],error:'missing dependency'}}),job:async id=>job(id)}}});
 try{const render=()=>h.render(()=>m.RuntimeOptimizationPanel({packagePath:'/project/exports/flows/source',sourceFolder:'/source',task:'segmentation',initialJobId:'B'}));render();await settle();const tree=render();assert.ok(nodes(tree).some(node=>node.props['aria-label']==='선택한 최적화 작업'&&JSON.stringify(node.props.children).includes('B')));assert.equal(value,'B');}finally{if(oldStorage)Object.defineProperty(global,'localStorage',oldStorage);else delete global.localStorage;}
});

test('inspection handoff selects exact run B and rejects a missing run without newest fallback',async()=>{
 const m=load('inspectionHistorySelection.ts');assert.equal(typeof m.openSelectedInspectionRun,'function');const runs=[{run_id:'A'},{run_id:'B'}];
 const row=await m.openSelectedInspectionRun(runs,'B',async id=>({run_id:id,rows:[]}));assert.equal(row.run_id,'B');await assert.rejects(()=>m.openSelectedInspectionRun(runs,'missing',async id=>({run_id:id})),/찾지 못/);await assert.rejects(()=>m.openSelectedInspectionRun(runs,'B',async()=>({run_id:'A'})),/일치/);
});
test('optimization task reopens its source package and refuses another source receipt',async()=>{
 const m=load('deliveryTaskSelection.ts',{'../runtime/deliveryContracts':load('../runtime/deliveryContracts.ts')});assert.equal(typeof m.reopenOptimizationTask,'function');const rows=['A','B'].map(packageRow);let selected='A';
 const record={job_id:'opt-B',status:'failed',options:{package_dir:rows[1].package_path,input_receipt:{source_dataset_path:'/source'}}};
 const api={job:async()=>record,packages:async()=>({packages:rows}),select:async id=>{selected=id;return rows.find(row=>row.package_id===id);}};
 const result=await m.reopenOptimizationTask('opt-B','/source',api,()=>true);assert.equal(selected,'B');assert.equal(result.job.job_id,'opt-B');assert.equal(result.package.package_id,'B');
 await assert.rejects(()=>m.reopenOptimizationTask('opt-B','/other',api,()=>true),/소스/);selected='A';assert.equal(await m.reopenOptimizationTask('opt-B','/source',api,()=>false),null);assert.equal(selected,'A');
});
test('flow package workspace opens the exact optimization task and its input package',async()=>{
 const h=harness(),state={projectDir:'/project',project,setStep:async()=>{}};const store=selector=>selector(state);store.getState=()=>state;const Optimization=()=>null;const rows=['A','B'].map(packageRow);let selected='A';
 const record={job_id:'opt-B',status:'failed',options:{package_dir:rows[1].package_path,input_receipt:{source_dataset_path:'/source'}}};
 const m=load('FlowPackagePanel.tsx',{...h.mocks,'../../services/flowPackageExport':{flowPackageExport:{prerequisites:async()=>({status:'blocked',approval_revision_ids:{},models:[],approval_created:false}),exportFlow:async()=>{throw new Error('not exported in this test');}}},'./flowPackageRelease':load('flowPackageRelease.ts'),'../../services/api':{api:{export:{edgeTargets:async()=>({host:{os:'linux',architecture:'x86_64'},supported:{linux:['x86_64'],windows:['x86_64'],macos:['arm64']}})},flowchart:{listPipelines:async()=>({pipelines:[]})},dataset:{getImages:async()=>({items:[]})}}},'../../stores/useDatasetStore':{useDatasetStore:{getState:()=>({folderPath:'/source'})}},'../../stores/useProjectStore':{useProjectStore:store},'../../stores/useFlowchartStore':{useFlowchartStore:selector=>selector({pipelineDirty:false})},'../flowchart/flowHandoff':{},'../flowchart/SavedFlowIdentityCard':{},'./edgeDeployment':{canVerifyFlowOnHost:()=>true},'../../services/runtimeDeploymentApi':{runtimeDeploymentApi:{capabilities:async()=>({torch_devices:['cpu']}),job:async()=>record}},'../../services/productDeliveryApi':{productDeliveryApi:{packages:async()=>({packages:rows}),select:async id=>{selected=id;return rows.find(row=>row.package_id===id);}}},'./RuntimeOptimizationPanel':{RuntimeOptimizationPanel:Optimization},'./PackageLibraryPanel':{PackageLibraryPanel:()=>null},'../common/ImageLibraryBrowser':{ImageLibraryBrowser:()=>null},'../runtime/RuntimeServicePanel':{RuntimeServicePanel:()=>null},'../runtime/useDeliveryScope':scopeMock(),'../training/useTaskHandoff':{useTaskHandoff:()=>({kind:'optimization',jobId:'opt-B',taskKey:'optimization:local:opt-B'})},'./deliveryTaskSelection':load('deliveryTaskSelection.ts',{'../runtime/deliveryContracts':load('../runtime/deliveryContracts.ts')})});
 const render=()=>h.render(()=>m.FlowPackagePanel({sourceFolder:'/source',task:'segmentation'}));render();await settle();const tree=render();const panel=nodes(tree).find(row=>row.type===Optimization);assert.equal(selected,'B');assert.ok(panel,'exact optimization panel is visible');assert.equal(panel.props.packagePath,rows[1].package_path);assert.equal(panel.props.initialJobId,'opt-B');
});
test('batch history workspace shows selected run B rather than newest run A',async()=>{
 const h=harness(),store=value=>{const fn=selector=>selector?selector(value):value;fn.getState=()=>value;return fn;};
 const projectStore=store({projectDir:'/project',project,task:'segmentation',setStep:async()=>{}}),datasetStore=store({folderPath:'/source',datasetKey:'/source\0segmentation',hasSelectedFolder:true,importError:null,sourceSaveError:null,isLoading:false,isSplitting:false,split:{test:0,val:0,train:0},sourceImages:0}),flowStore=store({contextRevision:0,pipelineDirty:false,executionChoiceOverride:'local_cpu',setExecutionChoice:()=>{}});const requests=[];
 const oldStorage=Object.getOwnPropertyDescriptor(global,'localStorage'),oldWindow=global.window;Object.defineProperty(global,'localStorage',{configurable:true,value:{getItem:()=>null}});global.window={addEventListener(){},removeEventListener(){}};
 const runs=['A','B'].map(run_id=>({run_id,source_folder:'/source',task:'segmentation',scope:'test',pipeline_name:run_id,saved_version_id:null,pipeline_hash:'hash',model_sha256:{},status:'completed',created_at:'2026-10-01',total:0,counts:{}}));
 const m=load('BatchInspectionPanel.tsx',{...h.mocks,'../../services/api':{api:{flowchart:{listPipelines:async()=>({pipelines:[]})},inspections:{listRuns:async()=>({runs}),getRun:async id=>{requests.push(id);return {...runs.find(row=>row.run_id===id),rows:[]};}}}},'../flowchart/flowExecution':{},'../../stores/useComputeStore':{useComputeStore:store({profiles:[],selectedProfileId:null,isLoaded:true,load:async()=>{}})},'../../stores/useDatasetStore':{useDatasetStore:datasetStore},'../../stores/useFlowchartStore':{useFlowchartStore:flowStore},'../../stores/useProjectStore':{useProjectStore:projectStore},'../../stores/useInspectionRunStore':{useInspectionRunStore:store({setRunning(){}})},'../flowchart/flowHandoff':{activeSavedVersion:()=>undefined},'../flowchart/SavedFlowIdentityCard':{},'./ReviewQueuePanel':{ReviewQueuePanel:()=>null},'./batchInspection':load('batchInspection.ts',{'../flowchart/flowchartStartup':{getFlowchartModelTask:()=>null}}),'../training/useTaskHandoff':{useTaskHandoff:()=>({kind:'inspection',jobId:'B',taskKey:'inspection:local:B'})},'./inspectionHistorySelection':load('inspectionHistorySelection.ts')});
 try{const render=()=>h.render(()=>m.BatchInspectionPanel());render();await settle();const tree=render();assert.deepEqual(requests,['B']);const identity=nodes(tree).find(row=>row.props['aria-label']==='선택한 검사 실행 식별자');assert.ok(identity);assert.ok(nodes(identity).some(row=>row.props.title==='B'));assert.equal(nodes(tree).find(row=>row.type==='button'&&row.props['aria-pressed']).props['aria-pressed'],true);}finally{global.window=oldWindow;if(oldStorage)Object.defineProperty(global,'localStorage',oldStorage);else delete global.localStorage;}
});
