import {useEffect,useState} from 'react';
import {api} from '../../services/api';
import {productDeliveryApi,type PackageLibrary,type SavedPackage} from '../../services/productDeliveryApi';
import {useDeliveryScope} from '../runtime/useDeliveryScope';
import {packageHandoff} from '../runtime/deliveryContracts';
import type {ImageMeta,VisionTask} from '../../types';
import {useTaskHandoff} from '../training/useTaskHandoff';
import {RuntimeFlowReviewPanel} from './RuntimeFlowReviewPanel';

export function PackageLibraryPanel({sourceFolder,task,refreshKey=0,onOptimize,onDeploy,onSelected}:{sourceFolder:string;task:VisionTask;refreshKey?:number;onOptimize?:(row:SavedPackage)=>void;onDeploy?:(row:SavedPackage)=>void;onSelected?:(row:SavedPackage)=>void}){
 const {scope,key}=useDeliveryScope(sourceFolder+task);const [library,setLibrary]=useState<PackageLibrary|null>(null),[selected,setSelected]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[images,setImages]=useState<ImageMeta[]>([]),[image,setImage]=useState(''),[device,setDevice]=useState('cpu'),[notice,setNotice]=useState('');
 const handoff=useTaskHandoff();const requestedPackage=handoff?.kind==='export'?handoff.jobId:undefined;
 const refresh=async()=>{const started=scope.current;const value=await productDeliveryApi.packages();if(scope.current===started){setLibrary(value);setSelected(value.selected_package_id||'');}};
 useEffect(()=>{let active=true;const started=scope.current;setLibrary(null);setSelected('');setError('');setNotice('');setImages([]);setImage('');setBusy(false);Promise.all([productDeliveryApi.packages(),sourceFolder?api.dataset.getImages({folder_path:sourceFolder,task,limit:32}):Promise.resolve({items:[]})]).then(async([value,input])=>{if(!active||scope.current!==started)return;setLibrary(value);setImages(input.items);setImage(input.items[0]?.file_path||'');if(requestedPackage){const target=value.packages.find(row=>row.package_id===requestedPackage);if(!target)throw new Error(`선택한 패키지 ${requestedPackage}을 보관함에서 찾지 못했습니다.`);packageHandoff(target);const reopened=await productDeliveryApi.select(requestedPackage);packageHandoff(reopened);if(active&&scope.current===started){setSelected(reopened.package_id);onSelected?.(reopened);setNotice(`작업 센터에서 선택한 패키지 ${reopened.name} 다시 열기 완료`);}}else setSelected(value.selected_package_id||'');}).catch(e=>{if(active&&scope.current===started)setError(String(e.message||e));});return()=>{active=false;};},[key,refreshKey,requestedPackage,handoff?.taskKey,handoff?.selectionId]);
 const action=async(fn:()=>Promise<void>)=>{const started=scope.current;setBusy(true);setError('');try{await fn();}catch(e){if(scope.current===started)setError(String((e as Error).message||e));}finally{if(scope.current===started)setBusy(false);}};
 const select=async(id:string,callback?:(row:SavedPackage)=>void)=>{const started=scope.current;const row=await productDeliveryApi.select(id);packageHandoff(row);if(scope.current===started){setSelected(id);onSelected?.(row);callback?.(row);}};
 const row=library?.packages.find(value=>value.package_id===selected);
 return <section aria-label="저장된 검사 패키지 보관함" className="mt-4 rounded-lg border border-slate-600 bg-[#101925] p-4 text-xs text-slate-200">
  <div className="flex justify-between gap-2"><div><h3 className="text-sm font-semibold">검사 패키지 보관함</h3><p className="mt-1 text-slate-400">저장한 전체 플로우를 다시 열어 검증·최적화·배포합니다.</p></div><button type="button" disabled={busy} onClick={()=>void action(refresh)} className="rounded border border-slate-600 px-3 py-2">새로고침</button></div>
  {!library&&<p role="status" className="mt-2">저장된 패키지 확인 중…</p>}{library?.packages.length===0&&<p className="mt-3 text-slate-400">전체 플로우를 내보내면 이곳에 보관됩니다.</p>}
  <div className="mt-3 space-y-2">{library?.packages.map(value=><article key={value.package_id} className={`rounded border p-3 ${selected===value.package_id?'border-cyan-500':'border-slate-700'}`}><div className="flex flex-wrap justify-between gap-2"><b className="break-all">{value.name}</b><span>{value.integrity==='verified'?'무결성 확인':'무결성 실패'} · {value.scope_matches?'현재 소스와 일치':'소스 연결 확인 필요'} · {value.approval_present?'승인 정보 포함':'배포 승인 전'}</span></div><p className="mt-1 text-slate-400">{value.models?.map(model=>model.task).join(' → ')||'모델 정보 확인 필요'} · 내보내기 비교 {value.parity.status==='passed'?'일치':value.parity.status==='failed'?'실패':value.parity.status==='mismatch'?'불일치':'실행 전'}{value.version_id?` · 플로우 ${value.version_id.slice(0,8)}`:''}</p>{value.parity.execution_target&&<p className="mt-1 text-slate-400">검증 대상: {value.parity.execution_target==='selected_compute'?`${value.parity.compute_profile_name||value.parity.compute_profile_id}${value.parity.compute_gpu_selector?` · GPU 선택 ${value.parity.compute_gpu_selector}`:''}`:'이 컴퓨터'} · {value.parity.device||'장치 확인 필요'}</p>}<div className="mt-2 flex flex-wrap gap-2"><button type="button" disabled={busy||value.integrity!=='verified'||!value.scope_matches} onClick={()=>void action(()=>select(value.package_id))} className="rounded border border-slate-600 px-3 py-2 disabled:opacity-40">{selected===value.package_id?'선택됨':'다시 열기'}</button>{onOptimize&&<button type="button" disabled={busy||value.integrity!=='verified'||!value.scope_matches} onClick={()=>void action(()=>select(value.package_id,onOptimize))} className="rounded border border-violet-700 px-3 py-2 disabled:opacity-40">최적화로 이동</button>}{onDeploy&&<button type="button" disabled={busy||value.integrity!=='verified'||!value.scope_matches} onClick={()=>void action(()=>select(value.package_id,onDeploy))} className="rounded border border-blue-700 px-3 py-2 disabled:opacity-40">배포 준비</button>}</div><details className="mt-2 text-slate-400"><summary>파일·버전 상세</summary><p className="mt-1 break-all">{value.package_path}</p><p className="break-all">manifest {value.manifest_sha256||'—'}</p>{value.optimization_jobs.map(job=><p key={job.job_id}>최적화 {job.job_id.slice(0,8)} · {job.status}</p>)}</details>{value.error&&<p role="alert" className="mt-2 text-amber-300">{value.error}</p>}</article>)}</div>
  {row&&<fieldset className="mt-3 rounded border border-slate-700 p-3"><legend>선택한 패키지로 실제 입력 확인</legend><div className="flex flex-wrap gap-2"><select aria-label="패키지 확인 이미지" className="min-w-0 flex-1 rounded bg-slate-800 p-2" value={image} onChange={e=>setImage(e.target.value)}><option value="">이미지 선택</option>{images.map(value=><option key={value.file_path} value={value.file_path}>{value.file_name}</option>)}</select><input aria-label="패키지 검증 실행 장치" className="w-28 rounded bg-slate-800 p-2" value={device} onChange={e=>setDevice(e.target.value)}/><button type="button" disabled={busy||!image} onClick={()=>void action(async()=>{const started=scope.current;const receipt=await productDeliveryApi.verify(row.package_id,image,device);if(scope.current===started)setNotice(`실제 입력 실행 완료 · ${String(receipt.result.final_verdict)} · 이 장치 실행 기록 저장`);})} className="rounded bg-cyan-700 px-3 py-2 disabled:opacity-40">이미지 1장 검사</button></div><p className="mt-2 text-slate-400">실행 기록은 장치 검증표에 남으며 운영 승인은 별도입니다. 현재 단일 입력의 최대 실행 시간은 30초입니다.</p></fieldset>}
  {row?.integrity==='verified'&&row.scope_matches&&row.approval_present&&row.runtime?.device==='openvino:CPU'&&<RuntimeFlowReviewPanel key={row.package_id} packagePath={row.package_path}/>}
  {notice&&<p role="status" className="mt-3 text-emerald-300">{notice}</p>}{error&&<p role="alert" className="mt-3 break-all text-red-300">{error}</p>}
 </section>;
}
