import {useEffect,useRef,useState} from 'react';
import {api} from '../../services/api';
import {runtimeDeploymentApi,type OptimizationJob,type RuntimeHeldoutResult} from '../../services/runtimeDeploymentApi';
import type {ImageMeta,VisionTask} from '../../types';
import {useProjectStore} from '../../stores/useProjectStore';
import {RuntimeFlowReviewPanel} from './RuntimeFlowReviewPanel';

export function RuntimeOptimizationPanel({packagePath,sourceFolder,task,initialJobId}:{packagePath:string;sourceFolder:string;task:VisionTask;initialJobId?:string}){
  const projectDir=useProjectStore(s=>s.projectDir);
  const [devices,setDevices]=useState<string[]>([]),[device,setDevice]=useState('CPU'),[precision,setPrecision]=useState<'fp32'|'fp16'|'int8'>('fp32');
  const [calibration,setCalibration]=useState<ImageMeta[]>([]),[validation,setValidation]=useState<ImageMeta[]>([]);
  const [selectedCal,setSelectedCal]=useState<string[]>([]),[selectedVal,setSelectedVal]=useState<string[]>([]);
  const [job,setJob]=useState<OptimizationJob|null>(null),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false);
  const storageKey=`runtime-optimization:${JSON.stringify([projectDir,packagePath,sourceFolder,task])}`;
  const scope=useRef(storageKey);scope.current=storageKey;
  const pollFault=useRef<string|null>(null);
  const [reviewer,setReviewer]=useState(''),[reason,setReason]=useState(''),[reviewed,setReviewed]=useState(false),[maxDrift,setMaxDrift]=useState(.001);
  const [revisions,setRevisions]=useState<Record<string,string>|null>(null),[approved,setApproved]=useState<{package_path:string;release_policy_path:string}|null>(null);
  const [heldout,setHeldout]=useState<RuntimeHeldoutResult|null>(null),[heldoutIndex,setHeldoutIndex]=useState(0);
  const active=job && ['queued','running','stopping'].includes(job.status);
  const boundJob=(value:OptimizationJob,expectedId?:string)=>{
    if(typeof value?.job_id!=='string'||!value.job_id||(expectedId&&value.job_id!==expectedId))throw new Error('최적화 작업 ID가 요청과 다릅니다.');
    if(value.options?.package_dir!==packagePath||value.options?.input_receipt?.source_dataset_path!==sourceFolder)throw new Error('최적화 작업의 패키지·원본 소스가 현재 선택과 다릅니다.');
    return value;
  };
  useEffect(()=>{let current=true;pollFault.current=null;setJob(null);setError(null);setBusy(false);setSelectedCal([]);setSelectedVal([]);setApproved(null);setRevisions(null);setReviewed(false);setReviewer('');setReason('');setHeldout(null);setHeldoutIndex(0);
    Promise.all([runtimeDeploymentApi.capabilities(),api.dataset.getImages({folder_path:sourceFolder,task,split:'train',limit:128}),api.dataset.getImages({folder_path:sourceFolder,task,split:'test',limit:128})]).then(async([cap,train,test])=>{
      const heldout=test.items.length?test:await api.dataset.getImages({folder_path:sourceFolder,task,split:'val',limit:128});if(!current)return;
      setDevices(cap.openvino.devices);setDevice(cap.openvino.devices[0]||'CPU');if(!cap.openvino.available)setError(cap.openvino.error||'OpenVINO 의존성 설치가 필요합니다.');
      setCalibration(train.items);setValidation(heldout.items);setSelectedCal(train.items.slice(0,8).map(x=>x.file_path));setSelectedVal(heldout.items.slice(0,8).map(x=>x.file_path));
    }).catch(e=>{if(current)setError(e instanceof Error?e.message:String(e));});return()=>{current=false;};
  },[packagePath,sourceFolder,task,storageKey]);
  useEffect(()=>{let current=true;setJob(null);const id=initialJobId||localStorage.getItem(storageKey);if(id)runtimeDeploymentApi.job(id).then(reopened=>{if(current){setJob(boundJob(reopened,id));localStorage.setItem(storageKey,reopened.job_id);}}).catch(e=>{if(current)setError(e instanceof Error?e.message:String(e));});return()=>{current=false;};},[initialJobId,storageKey,packagePath,sourceFolder]);
  useEffect(()=>{if(!job||!active)return;let current=true;const poll=setInterval(()=>{runtimeDeploymentApi.job(job.job_id).then(value=>{if(current){setJob(boundJob(value,job.job_id));const resolved=pollFault.current;if(resolved){setError(previous=>previous===resolved?null:previous);pollFault.current=null;}}}).catch(e=>{if(current){pollFault.current=String(e);setError(pollFault.current);}});},700);return()=>{current=false;clearInterval(poll);};},[job?.job_id,active,storageKey]);
  useEffect(()=>{if(job?.status!=='completed')return;let current=true;runtimeDeploymentApi.prerequisites(job.job_id).then(value=>{if(current)setRevisions(value.approval_revision_ids);}).catch(e=>{if(current)setError(e instanceof Error?e.message:String(e));});return()=>{current=false;};},[job?.job_id,job?.status]);
  useEffect(()=>{setHeldout(null);if(job?.status!=='completed')return;let current=true;runtimeDeploymentApi.heldout(job.job_id,heldoutIndex).then(value=>{if(current)setHeldout(value);}).catch(e=>{if(current)setError(e instanceof Error?e.message:String(e));});return()=>{current=false;};},[job?.job_id,job?.status,heldoutIndex]);
  const run=async()=>{const started=storageKey;setBusy(true);setError(null);try{const value=await runtimeDeploymentApi.optimize({package_dir:packagePath,source_dataset_path:sourceFolder,precision,device,cpu_threads:1,calibration_images:precision==='int8'?selectedCal:[],validation_images:selectedVal});if(scope.current===started){setJob(boundJob(value));localStorage.setItem(storageKey,value.job_id);}}catch(e){if(scope.current===started)setError(e instanceof Error?e.message:String(e));}finally{if(scope.current===started)setBusy(false);}};
  const approve=async()=>{if(!job||!revisions)return;const started=storageKey;setBusy(true);setError(null);try{const result=await runtimeDeploymentApi.approve(job.job_id,{reviewer,reason,holdout_reviewed:true,maximum_absolute_drift:maxDrift,approval_revision_ids:revisions});if(scope.current===started)setApproved(result);}catch(e){if(scope.current===started)setError(e instanceof Error?e.message:String(e));}finally{if(scope.current===started)setBusy(false);}};
  const cancel=async()=>{if(!job)return;const started=storageKey;setError(null);try{const value=await runtimeDeploymentApi.cancel(job.job_id);if(scope.current===started)setJob(boundJob(value,job.job_id));}catch(e){if(scope.current===started)setError(String(e));}};
  const choices=(title:string,items:ImageMeta[],selected:string[],set:(value:string[])=>void)=><fieldset className="rounded border border-slate-700 p-2"><legend>{title}</legend><div className="max-h-24 overflow-auto">{items.length===0?<span className="text-amber-300">명시된 split의 이미지가 없습니다.</span>:items.map(item=><label key={item.file_path} className="flex items-center gap-2"><input type="checkbox" disabled={!!active||busy} checked={selected.includes(item.file_path)} onChange={e=>set(e.target.checked?[...selected,item.file_path]:selected.filter(p=>p!==item.file_path))}/>{item.file_name}</label>)}</div></fieldset>;
  return <section aria-label="Runtime 최적화와 양자화" className="mt-3 grid gap-3 rounded border border-violet-800 p-3 text-xs text-slate-300">
    <h4 className="font-semibold text-violet-200">OpenVINO 변환·양자화</h4>
    {job&&<p aria-label="선택한 최적화 작업" className="break-all font-mono">최적화 작업 {job.job_id} · 입력 패키지 {packagePath}</p>}
    <div className="flex flex-wrap items-center gap-3"><label>검증 장치 <select value={device} disabled={!!active||busy} onChange={e=>setDevice(e.target.value)} className="bg-slate-900">{devices.map(d=><option key={d}>{d}</option>)}</select></label><label>정밀도 <select value={precision} disabled={!!active||busy} onChange={e=>setPrecision(e.target.value as typeof precision)} className="bg-slate-900"><option value="fp32">FP32</option><option value="fp16">FP16 가중치</option><option value="int8">INT8 (실제 이미지 보정)</option></select></label></div>
    {precision==='int8'&&choices('보정 이미지 · train',calibration,selectedCal,setSelectedCal)}{choices('변환 오차 검증 · test / val',validation,selectedVal,setSelectedVal)}
    <div className="flex gap-2"><button type="button" disabled={devices.length===0||!selectedVal.length||(precision==='int8'&&!selectedCal.length)||!!active||busy} onClick={()=>void run()} className="rounded bg-violet-700 px-3 py-2 disabled:opacity-50">{busy?'요청 중...':'독립 후보 패키지 생성'}</button>{active&&<button type="button" onClick={()=>void cancel()} className="rounded border border-slate-600 px-3">변환 중단</button>}</div>
    {error&&<p role="alert" className="text-rose-300">{error}</p>}{job&&<p role="status">진행 상태: {job.status}{job.error?` · ${job.error}`:''}</p>}
    {job?.result&&<><p className="break-all font-mono">{job.result.package_path}</p><table className="w-full"><thead><tr><th>모델</th><th>정밀도</th><th>최대 오차</th><th>검증 이미지</th><th>CPU 기준 / 변환 ms</th></tr></thead><tbody>{job.result.models.map(model=><tr key={model.job_id}><td>{model.task}</td><td>{model.precision}</td><td>{model.metrics.max_absolute_error.toPrecision(3)}</td><td>{model.metrics.validation_image_count}</td><td>{model.metrics.reference_latency_mean_ms.toFixed(2)} / {model.metrics.latency_mean_ms.toFixed(2)}</td></tr>)}</tbody></table><p className="text-amber-300">변환 오차와 실행 속도를 측정했습니다. 모델 품질 승인과 대상 GPU·NPU·보드 검증은 별도입니다.</p><code>python run_flow.py --image /absolute/image.png --deadline-ms 30000</code>
      <p>전체 flow holdout 비교: {job.result.heldout_flow_passed_count} / {job.result.heldout_flow_count} 동일 판정·공간 결과</p>
      {heldout&&<details open className="rounded border border-slate-700 p-2"><summary>실제 holdout 원본 모델 / 변환 모델 결과</summary><div className="my-2 flex items-center gap-2"><button type="button" disabled={heldoutIndex===0} onClick={()=>setHeldoutIndex(i=>i-1)}>이전</button><span>{heldoutIndex+1} / {heldout.total} · {heldout.comparison.status}</span><button type="button" disabled={heldoutIndex+1>=heldout.total} onClick={()=>setHeldoutIndex(i=>i+1)}>다음</button></div><p className="break-all text-[10px]">원본 SHA256: {heldout.image_sha256}</p><div className="mt-2 grid grid-cols-2 gap-2">{[['원본 모델',heldout.reference],['변환 모델',heldout.candidate]].map(([label,result])=>{const output=result as RuntimeHeldoutResult['reference'];return <div key={String(label)}><b>{String(label)} · {output.final_verdict} · ROI {output.roi_count}</b>{output.crops.map(crop=><div key={crop.roi_id} className="mt-2"><p>{crop.predicted_class||crop.recognized_text||crop.roi_id} · {crop.verdict} · score {crop.defect_score.toPrecision(4)} · area {crop.defect_area_px??'—'}</p>{crop.crop_thumbnail&&<img src={crop.crop_thumbnail} alt={String(label)+' ROI '+crop.roi_id} className="max-h-32 max-w-full"/>}{crop.mask&&<img src={crop.mask.startsWith('data:')?crop.mask:'data:image/png;base64,'+crop.mask} alt={String(label)+' mask '+crop.roi_id} className="max-h-32 max-w-full"/>}</div>)}</div>;})}</div>{heldout.comparison.mismatched_fields.length>0&&<p className="mt-2 text-amber-300">차이 필드: {heldout.comparison.mismatched_fields.join(', ')}</p>}</details>}
      <fieldset className="grid gap-2 rounded border border-amber-800 p-3"><legend>정밀도·Runtime 별도 승인</legend><p>모든 연결 모델의 현재 활성 승인과 실제 holdout 해시를 확인한 뒤 새 승인 패키지를 만듭니다.</p><div className="flex flex-wrap gap-2"><label>검토자 <input value={reviewer} onChange={e=>setReviewer(e.target.value)} className="bg-slate-900"/></label><label>최대 절대 오차 <input type="number" min={0} step={.001} value={maxDrift} onChange={e=>setMaxDrift(Number(e.target.value))} className="w-24 bg-slate-900"/></label></div><label>검토 근거<textarea value={reason} onChange={e=>setReason(e.target.value)} className="mt-1 w-full bg-slate-900"/></label><label className="flex gap-2"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>holdout 원본·변환 결과와 측정 오차를 직접 검토했습니다.</label><button type="button" disabled={!revisions||!heldout||!reviewer.trim()||reason.trim().length<8||!reviewed||!Number.isFinite(maxDrift)||maxDrift<0||busy} onClick={()=>void approve()} className="rounded border border-amber-600 py-2 disabled:opacity-50">검토 후 새 승인 패키지 생성</button></fieldset>
      {approved&&<div role="status" className="break-all text-emerald-300">승인 패키지: {approved.package_path}<br/>외부 승인 정책: {approved.release_policy_path}</div>}
      {approved&&<RuntimeFlowReviewPanel packagePath={approved.package_path}/>}
    </>}
  </section>;
}
