import {useEffect,useRef,useState} from 'react';
import type {DistributionState,ManualDelivery,NativeSignature,UpdateChannel} from '../../../types/electron';
const button='rounded border border-slate-600 px-3 py-2 disabled:opacity-40';
const signatureLabel:Record<NativeSignature['status'],string>={verified:'OS 서명 검증 통과',unsigned:'배포자 서명 없음',invalid:'서명 검증 실패',unavailable:'이 환경에서 서명 검증 도구 필요',development:'개발 실행 · 배포 인증 미확인'};

export function DistributionSettingsPanel(){
 const [state,setState]=useState<DistributionState|null>(null),[delivery,setDelivery]=useState<ManualDelivery|null>(null),[channel,setChannel]=useState<UpdateChannel['channel']>('stable'),[url,setURL]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const generation=useRef(0);
 const apply=(result:DistributionState)=>{setState(result);setChannel(result.update.configuration?.channel||'stable');setURL(result.update.configuration?.manifest_url||'');};
 useEffect(()=>{const started=++generation.current;if(!window.api?.getDistributionStatus){setError('배포 상태 확인은 데스크톱 앱에서 사용할 수 있습니다.');return;}
  window.api.getDistributionStatus().then(result=>{if(generation.current===started)apply(result);}).catch(cause=>{if(generation.current===started)setError(String(cause.message||cause));});return()=>{generation.current++;};},[]);
 const action=async(operation:()=>Promise<void>)=>{const started=++generation.current;setBusy(true);setError('');try{await operation();}catch(cause){if(generation.current===started)setError(String((cause as Error).message||cause));}finally{if(generation.current===started)setBusy(false);}};
 return <fieldset className="space-y-3 rounded border border-slate-700 p-3"><legend>데스크톱 배포·업데이트</legend>
  {state&&<><p>설치 앱 {state.app_version} · {state.platform} {state.architecture}</p><p>{signatureLabel[state.signature.status]}{state.signature.publisher?' · 배포자 '+state.signature.publisher:''}</p><details className="text-xs text-slate-400"><summary>서명 검사 세부사항</summary><p>{state.signature.reason}</p><p>확인 {state.signature.checked_at}</p><p>macOS 공증과 실제 설치 검증은 별도 배포 절차입니다.</p></details></>}
  <label className="block">릴리스 채널<select aria-label="릴리스 채널" className="ml-2 rounded bg-slate-800 p-2" disabled={busy} value={channel} onChange={e=>setChannel(e.target.value as UpdateChannel['channel'])}><option value="stable">안정 버전</option><option value="beta">베타 버전</option></select></label>
  <label className="block">실제 HTTPS 릴리스 목록 주소<input aria-label="HTTPS 릴리스 목록 주소" className="mt-1 w-full rounded bg-slate-800 p-2" type="url" value={url} disabled={busy} onChange={e=>setURL(e.target.value)}/></label>
  <div className="flex flex-wrap gap-2"><button type="button" className={button} disabled={busy||!url.trim()||!window.api?.configureUpdateChannel} onClick={()=>void action(async()=>{const started=generation.current;const result=await window.api.configureUpdateChannel({channel,manifest_url:url.trim()});if(generation.current===started){apply(result);setDelivery(null);}})}>채널 저장</button><button type="button" className={button} disabled={busy||!state?.update.configured} onClick={()=>void action(async()=>{const started=generation.current;const result=await window.api.checkForUpdate();if(generation.current===started){apply(result);setDelivery(null);}})}>새 버전 확인</button><button type="button" className={button} disabled={busy||!state?.update.release} onClick={()=>void action(async()=>{const started=generation.current;const result=await window.api.downloadUpdate();if(generation.current===started)setDelivery(result);})}>패키지 다운로드·검증</button><button type="button" className={button} disabled={busy||!state?.update.configured} onClick={()=>void action(async()=>{const started=generation.current;const result=await window.api.configureUpdateChannel(null);if(generation.current===started){apply(result);setDelivery(null);}})}>채널 해제</button></div>
  <p className="text-slate-400">{!state?.update.configured?'배포 담당자가 제공한 실제 릴리스 목록 주소를 설정하세요.':state.update.status==='up_to_date'?'설정한 채널에 더 새 버전이 없습니다.':state.update.release?'새 버전 '+state.update.release.version+' · 다운로드 후 해시와 서명을 확인합니다.':'채널 설정됨 · 새 버전 확인 필요'} 자동 설치는 지원하지 않습니다.</p>
  {delivery&&<div className="rounded border border-slate-600 p-2" role="status"><p>다운로드 {delivery.version} · 크기·SHA256 일치 · {signatureLabel[delivery.signature.status]}</p><p>{delivery.handoff_ready?'설치 앱과 배포자 일치 확인. 프로젝트 백업 후 수동으로 설치하세요.':'설치 앱과 일치하는 배포자 서명이 확인돼야 설치 전달 준비가 완료됩니다.'}</p><details className="mt-2 break-all text-xs text-slate-400"><summary>저장 위치·검증 해시</summary><p>{delivery.path}</p><p>{delivery.sha256}</p><p>{delivery.signature.reason}</p></details></div>}
  <details className="text-xs text-slate-400"><summary>릴리스 목록 형식·제한</summary><p>JSON 필드: version, channel, platform(darwin/win32/linux), arch(arm64/x64), url, sha256, size. 앱의 OS·아키텍처와 같은 채널이어야 합니다. 패키지는 목록과 동일한 HTTPS 서버에 있어야 하며 목록 64 KiB, 패키지 1 GiB 이하입니다. ZIP은 배포자 서명을 별도로 검증해야 합니다.</p></details>
  {busy&&<p role="status">배포 상태 확인 중…</p>}{error&&<p role="alert" className="break-all text-red-300">{error}</p>}
 </fieldset>;
}
