import {useEffect,useRef,useState} from 'react';
import type {DistributionState,ManualDelivery,NativeSignature,UpdateChannel} from '../../../types/electron';
import {host} from '../../services/hostAdapter';
const button='rounded border border-slate-600 px-3 py-2 disabled:opacity-40';
const signatureLabel:Record<NativeSignature['status'],string>={verified:'OS 서명 검증 통과',unsigned:'배포자 서명 없음',invalid:'서명 검증 실패',unavailable:'이 환경에서 서명 검증 도구 필요',development:'개발 실행 · 배포 인증 미확인'};
const recoveryLabel:Record<string,string>={downloading:'다운로드 진행 중',verifying:'서명 확인 중',interrupted:'다운로드가 중단되었습니다. 새 버전을 다시 확인한 뒤 다운로드하세요.',failed:'다운로드·검증에 실패했습니다. 새 버전을 다시 확인하세요.',downloaded_unverified:'패키지는 저장됐지만 전달 검증이 중단됐습니다. 새 버전을 다시 확인하세요.',publisher_required:'패키지 해시는 확인됐습니다. 설치 앱과 일치하는 배포자 서명이 필요합니다.',handoff_ready:'검증한 패키지가 저장됐습니다. 프로젝트 백업 후 수동으로 설치하세요.',invalidated:'저장 패키지 또는 설치 앱이 변경됐습니다. 새 버전을 다시 확인하세요.'};

export function DistributionSettingsPanel(){
 const [state,setState]=useState<DistributionState|null>(null),[delivery,setDelivery]=useState<ManualDelivery|null>(null),[channel,setChannel]=useState<UpdateChannel['channel']>('stable'),[url,setURL]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const generation=useRef(0);
 const apply=(result:DistributionState)=>{setState(result);setChannel(result.update.configuration?.channel||'stable');setURL(result.update.configuration?.manifest_url||'');};
 useEffect(()=>{const started=++generation.current;if(!host.can('updates')){setError('배포 상태 확인은 데스크톱 앱에서 사용할 수 있습니다.');return;}
  host.updates.status().then(result=>{if(generation.current===started)apply(result);}).catch(cause=>{if(generation.current===started)setError(String(cause.message||cause));});return()=>{generation.current++;};},[]);
 const action=async(operation:()=>Promise<void>)=>{const started=++generation.current;setBusy(true);setError('');try{await operation();}catch(cause){if(generation.current===started){setError(String((cause as Error).message||cause));try{const result=await host.updates.status();if(generation.current===started)apply(result);}catch{}}}finally{if(generation.current===started)setBusy(false);}};
 return <fieldset className="space-y-3 rounded border border-slate-700 p-3"><legend>데스크톱 배포·업데이트</legend>
  {state&&<><p>설치 앱 {state.app_version} · {state.platform} {state.architecture}</p><p>{signatureLabel[state.signature.status]}{state.signature.publisher?' · 배포자 '+state.signature.publisher:''}</p><details className="text-xs text-slate-400"><summary>서명 검사 세부사항</summary><p>{state.signature.reason}</p><p>확인 {state.signature.checked_at}</p><p>macOS 공증과 실제 설치 검증은 별도 배포 절차입니다.</p></details></>}
  {state?.backend&&<details className="break-all text-xs text-slate-400"><summary>독립 백엔드·오프라인 준비 기록</summary><p>{state.backend.status==='development'?'개발 소스 실행 · 대상 OS 독립 빌드 필요':state.backend.status==='inventory_bound'?'실행 파일·대상 OS·빌드 식별자 일치':state.backend.status==='missing'?'독립 백엔드 빌드 목록 없음':'독립 백엔드 빌드 목록 불일치'}</p><p>빌드 당시 시작·재시작 검증 {state.backend.startup_acceptance==='passed'?'기록 있음':'기록 필요'}</p>{state.backend.signature&&<p>백엔드 {signatureLabel[state.backend.signature.status]}</p>}{state.backend.build_identity_sha256&&<p>빌드 SHA-256 {state.backend.build_identity_sha256}</p>}{state.backend.offline&&<><p>검사 모델은 내보낸 패키지에 포함돼야 합니다. 저장되지 않은 사전학습 가중치를 사용한 학습에는 네트워크가 필요합니다.</p><p>추가 설치 필요 기능: {state.backend.offline.optional_features_unavailable.join(', ')||'목록 없음'}</p></>}<p>최종 설치 앱의 시작, 배포자 서명, macOS 공증, 실제 카메라·PLC와 모델 품질 승인은 별도 확인이 필요합니다.</p>{state.backend.reason&&<p>{state.backend.reason}</p>}</details>}
  <label className="block">릴리스 채널<select aria-label="릴리스 채널" className="ml-2 rounded bg-slate-800 p-2" disabled={busy} value={channel} onChange={e=>setChannel(e.target.value as UpdateChannel['channel'])}><option value="stable">안정 버전</option><option value="beta">베타 버전</option></select></label>
  <label className="block">실제 HTTPS 릴리스 목록 주소<input aria-label="HTTPS 릴리스 목록 주소" className="mt-1 w-full rounded bg-slate-800 p-2" type="url" value={url} disabled={busy} onChange={e=>setURL(e.target.value)}/></label>
  <div className="flex flex-wrap gap-2"><button type="button" className={button} disabled={busy||!url.trim()||!host.can('updates')} onClick={()=>void action(async()=>{const started=generation.current;const result=await host.updates.configure({channel,manifest_url:url.trim()});if(generation.current===started){apply(result);setDelivery(null);}})}>채널 저장</button><button type="button" className={button} disabled={busy||!state?.update.configured} onClick={()=>void action(async()=>{const started=generation.current;const result=await host.updates.check();if(generation.current===started){apply(result);setDelivery(null);}})}>새 버전 확인</button><button type="button" className={button} disabled={busy||!state?.update.release} onClick={()=>void action(async()=>{const started=generation.current;const result=await host.updates.download();if(generation.current===started){setDelivery(result);const refreshed=await host.updates.status();if(generation.current===started)apply(refreshed);}})}>패키지 다운로드·검증</button><button type="button" className={button} disabled={busy||!state?.update.configured} onClick={()=>void action(async()=>{const started=generation.current;const result=await host.updates.configure(null);if(generation.current===started){apply(result);setDelivery(null);}})}>채널 해제</button></div>
  <p className="text-slate-400">{!state?.update.configured?'배포 담당자가 제공한 실제 릴리스 목록 주소를 설정하세요.':state.update.status==='up_to_date'?'설정한 채널에 더 새 버전이 없습니다.':state.update.release?'새 버전 '+state.update.release.version+' · 다운로드 후 해시와 서명을 확인합니다.':'채널 설정됨 · 새 버전 확인 필요'} 자동 설치는 지원하지 않습니다.</p>
  <button type="button" className={button} disabled={busy||!host.can('updates')} onClick={()=>void action(async()=>{const started=generation.current;const result=await host.updates.verifyOffline();if(result&&generation.current===started){setDelivery(result);const refreshed=await host.updates.status();if(generation.current===started)apply(refreshed);}})}>오프라인 패키지 검증</button>
  <p className="text-xs text-slate-400">오프라인 검증은 릴리스 목록 서명과 전체 파일을 확인합니다. 학습·검사 종료와 프로젝트 백업 후 직접 설치하세요.</p>
  {delivery&&<div className="rounded border border-slate-600 p-2" role="status"><p>{delivery.offline?'오프라인 검증':'다운로드'} {delivery.version} · 크기·SHA256 일치 · {signatureLabel[delivery.signature.status]}</p>{delivery.offline&&<p>전체 파일 {delivery.artifacts_verified}개 검증 · 추가 runtime pack은 설치 전 별도 호환성 검증 필요</p>}<p>{delivery.handoff_ready?'설치 앱과 배포자 일치 확인. 프로젝트 백업 후 수동으로 설치하세요.':'설치 앱과 일치하는 배포자 서명이 확인돼야 설치 전달 준비가 완료됩니다.'}</p><details className="mt-2 break-all text-xs text-slate-400"><summary>저장 위치·검증 해시</summary><p>{delivery.path}</p><p>{delivery.sha256}</p><p>{delivery.signature.reason}</p></details></div>}
  {state?.update.recovery&&<div className="rounded border border-slate-600 p-2" role="status"><p>마지막 전달 {state.update.recovery.version} · {recoveryLabel[state.update.recovery.status]||'전달 상태 확인 필요'}</p><p className="mt-1 text-slate-400">설치 완료 여부는 수동 설치 후 앱 버전과 실제 실행으로 확인하세요.</p><details className="mt-2 break-all text-xs text-slate-400"><summary>전달 복구 기록</summary><p>확인 {state.update.recovery.checked_at}</p><p>릴리스 목록 SHA-256 {state.update.recovery.manifest_sha256}</p><p>후보 파일 SHA-256 {state.update.recovery.candidate_sha256}</p><p>기존 실행 파일 SHA-256 {state.update.recovery.installed_sha256||'미확인'}</p>{state.update.recovery.candidate_path&&<p>{state.update.recovery.candidate_path}</p>}</details></div>}
  <details className="text-xs text-slate-400"><summary>릴리스 목록 형식·제한</summary><p>설치 앱은 고정 발행자 키로 서명된 canonical JSON 목록이 필요합니다. 개발 실행의 단순 JSON 목록은 설치 승인 근거가 아닙니다. 앱의 OS·아키텍처와 같은 채널이어야 합니다. 패키지는 목록과 동일한 HTTPS 서버에 있어야 하며 목록 64 KiB, 패키지 1 GiB 이하입니다. ZIP은 배포자 서명을 별도로 검증해야 합니다.</p></details>
  {busy&&<p role="status">배포 상태 확인 중…</p>}{error&&<p role="alert" className="break-all text-red-300">{error}</p>}
 </fieldset>;
}
