const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),test=require('node:test'),ts=require('typescript');
function harness({legacy=false,role='owner'}={}){
 const file=path.join(__dirname,'FleetPanel.tsx'),source=process.env.MV_FLEET_BASE?require('node:child_process').execFileSync('git',['show','HEAD:src/renderer/components/runtime/FleetPanel.tsx'],{cwd:path.resolve(__dirname,'../../../..'),encoding:'utf8'}):fs.readFileSync(file,'utf8');
 let cursor=0,generation=0,identity='actor-a',resolve,resolveMigration;let storage='legacy_project_database';const slots=[],effects=[],listeners=[],calls=[],scope={current:{key:'same-project'}};
 const react={createElement:(type,props,...children)=>({type,props:props||{},children:children.flat()}),useRef:initial=>{const i=cursor++;if(!(i in slots))slots[i]={current:initial};return slots[i];},useState:initial=>{const i=cursor++;if(!(i in slots))slots[i]=typeof initial==='function'?initial():initial;return[slots[i],v=>{slots[i]=typeof v==='function'?v(slots[i]):v;}];},useEffect:(fn,deps)=>{const i=cursor++;if(!slots[i]||deps.some((d,j)=>d!==slots[i].deps[j])){slots[i]?.cleanup?.();slots[i]={deps};effects.push(()=>{slots[i].cleanup=fn();});}}};
 const request=async(route,options)=>{calls.push({route,options});if(options&&route.endsWith('/credentials/migrate'))return new Promise(r=>resolveMigration=r);if(options)return {};if(route==='/api/fleet/targets')return {targets:[{target_id:'a',name:'A',url:'loopback',...(legacy?{credential_storage:storage}:{})}]};if(route==='/api/fleet/capabilities')return {can_rollback:true,can_emergency_rollback:true,actor_role:role};return new Promise(r=>resolve=r);};
 const m=new Module(file,module);m.filename=file;m.paths=Module._nodeModulePaths(__dirname);m.require=name=>name==='react'?react:name.includes('services/api')?{request,getProjectContextGeneration:()=>generation,getApiPersistenceIdentity:()=>identity,subscribeProjectContext:fn=>{listeners.push(fn);return()=>{};}}:name.includes('useDeliveryScope')?{useDeliveryScope:(extra='')=>{const key='same-project'+extra;if(scope.current.key!==key)scope.current={key};return {projectDir:'p',scope,key};}}:name.includes('useProjectStore')?{useProjectStore:{getState:()=>({projectDir:'p'})}}:name.includes('SavedPackagePicker')?{SavedPackagePicker:()=>null}:name.includes('emergencyRollbackPolicy')?{emergencyAcknowledged:()=>false}:name.includes('fleetRollouts')?{fleetRollouts:{list:async()=>({rollouts:[]})},rolloutControls:()=>null}:Module.prototype.require.call(m,name);
 m._compile("const React=require('react');\n"+ts.transpileModule(source,{compilerOptions:{jsx:ts.JsxEmit.React,module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,file);
 const render=()=>{cursor=0;const tree=m.exports.FleetPanel();effects.splice(0).forEach(fn=>fn());return tree;};const nodes=tree=>{const found=[];const walk=n=>{if(n&&typeof n==='object'){found.push(n);n.children?.forEach(walk);}};walk(tree);return found;};
 return{render,nodes,calls,advance:()=>{generation++;identity='actor-b';listeners.forEach(fn=>fn());},resolve:v=>resolve(v),finishMigration:()=>{storage='server_secret_v1';resolveMigration({target_id:'a',credential_storage:storage});}};
}
const tick=()=>new Promise(setImmediate);
test('retained fleet register callback refuses changed project/account authority',async()=>{const h=harness();h.render();await tick();const tree=h.render(),action=h.nodes(tree).find(n=>n.type==='button'&&n.children.includes('연결 설정 저장')).props.onClick;h.advance();action();await tick();assert.equal(h.calls.filter(c=>c.options).length,0);});
test('late live target readback cannot populate a new project/account panel',async()=>{const h=harness();h.render();await tick();const select=h.nodes(h.render()).find(n=>n.props['aria-label']==='현장 장비 선택');select.props.onChange({target:{value:'a'}});h.advance();h.render();h.resolve({target:{target_id:'a'},runtime:{status:'ready',manifest_sha256:'stale-manifest'},history:[],matches_active:true});await tick();assert.ok(!h.nodes(h.render()).some(n=>n.children.some(c=>typeof c==='string'&&c.includes('stale-manifest'))));});

function textNode(h,text){return h.nodes(h.render()).find(n=>n.children.includes(text));}
async function selectedLegacy(h){h.render();await tick();h.nodes(h.render()).find(n=>n.props['aria-label']==='현장 장비 선택').props.onChange({target:{value:'a'}});h.resolve({target:{target_id:'a'},runtime:{status:'disconnected'},history:[],matches_active:false});await tick();}
test('credential migration refuses reviewer authority and a retained stale owner callback',async()=>{
 for(const role of ['reviewer','owner']){const h=harness({legacy:true,role});await selectedLegacy(h);h.nodes(h.render()).find(n=>n.props['aria-label']==='인증값 이동 사유').props.onChange({target:{value:'Move this exact configured target to server storage'}});const button=textNode(h,'인증값을 서버 저장소로 옮기기');if(role==='reviewer')assert.equal(button.props.disabled,true);else h.advance();button.props.onClick();await tick();assert.equal(h.calls.filter(c=>c.route.endsWith('/credentials/migrate')).length,0);}
});
test('credential migration blocks duplicate synchronous activation and late account readback',async()=>{
 const h=harness({legacy:true});await selectedLegacy(h);h.nodes(h.render()).find(n=>n.props['aria-label']==='인증값 이동 사유').props.onChange({target:{value:'Move this exact configured target to server storage'}});const callback=textNode(h,'인증값을 서버 저장소로 옮기기').props.onClick;callback();callback();await tick();assert.equal(h.calls.filter(c=>c.route.endsWith('/credentials/migrate')).length,1);h.advance();h.render();h.finishMigration();await tick();assert.ok(!textNode(h,'인증값 이동 확인됨'));assert.equal(h.calls.filter(c=>c.options).length,1);
});
