const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),ts=require('typescript');
function hooks(){let cursor=0;const slots=[],effects=[];return{react:{useState:v=>{const i=cursor++;if(!(i in slots))slots[i]=typeof v==='function'?v():v;return[slots[i],v=>slots[i]=typeof v==='function'?v(slots[i]):v];},useRef:v=>{const i=cursor++;return slots[i]??(slots[i]={current:v});},useEffect:(fn,deps)=>{const i=cursor++;if(!slots[i]||deps.some((v,j)=>v!==slots[i].deps[j])){slots[i]?.cleanup?.();slots[i]={deps};effects.push(()=>slots[i].cleanup=fn());}}},render:fn=>{cursor=0;const result=fn();effects.splice(0).forEach(fn=>fn());return result;},unmount:()=>slots.forEach(s=>s?.cleanup?.())};}
const jsx=(type,props)=>({type,props:props||{},children:[props?.children].flat().filter(Boolean)});
function nodes(t){return t&&typeof t==='object'?[t,...(t.children||[]).flat().flatMap(nodes)]:[];}
const settle=()=>new Promise(setImmediate);
function fixture(){
 const h=hooks();let generation=1,scope='p',subscriber,handler,downloads=0;const calls=[];const props={ready:true,canReview:true};
 const mocks={'react':h.react,'react/jsx-runtime':{jsx,jsxs:jsx},'../../stores/useProjectStore':{useProjectStore:selector=>selector({language:'ko'})},'./useDeliveryScope':{useDeliveryScope:()=>({key:scope})},'../../services/api':{getProjectContextGeneration:()=>generation,subscribeProjectContext:fn=>{subscriber=fn;return()=>{};},request:async(route,options)=>{calls.push({route,options});return handler?handler(route,options):snapshot;}}};
 const file=path.resolve(__dirname,'InspectionQueuePanel.tsx'),m=new Module(file,module);m.filename=file;m.paths=Module._nodeModulePaths(__dirname);m.require=id=>mocks[id]||require(id);m._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText,file);
 const snapshot={jobs:[{job_id:'old-job',image_path:'old.png',state:'error',attempts:1,retry_count:0,replay_count:0,runtime_binding:{},image_sha256:'a'.repeat(64)}],total:1,limit:50,offset:0,has_more:false,outstanding:0,capacity:100,max_attempts:3,max_queue_age_seconds:3600};
 const originalDocument=globalThis.document;globalThis.document={createElement:()=>{downloads++;return{click(){}};}};
 const render=()=>h.render(()=>m.exports.InspectionQueuePanel(props)),button=(t,name)=>nodes(t).find(n=>n.type==='button'&&n.children.includes(name));
 const open=async()=>{render().props.onToggle({currentTarget:{open:true}});render();await settle();return render();};
 return{render,button,open,calls,props,snapshot,setHandler:fn=>handler=fn,switchAccount:()=>{generation++;subscriber?.();},switchProject:()=>{scope='other';generation++;subscriber?.();},downloads:()=>downloads,close:()=>{h.unmount();globalThis.document=originalDocument;}};
}
test('late queue response cannot expose previous same-project account records',async()=>{const f=fixture();try{let resolve;f.setHandler(()=>new Promise(done=>resolve=done));await f.open();const oldReply=resolve;f.switchAccount();f.render();oldReply(f.snapshot);await settle();const t=f.render();assert.equal(nodes(t).filter(n=>n.type==='article').length,0);}finally{f.close();}});
test('a stale retry handler cannot mutate after reviewer permission is withdrawn',async()=>{const f=fixture();try{const t=await f.open(),retry=f.button(t,'동일 검사 재시도');assert.ok(retry);f.props.canReview=false;f.render();const before=f.calls.length;await retry.props.onClick();assert.equal(f.calls.length,before);assert.equal(f.button(f.render(),'동일 검사 재시도').props.disabled,true);}finally{f.close();}});
test('late export from another project cannot trigger a file download',async()=>{const f=fixture();try{const t=await f.open();let resolve;f.setHandler(route=>route.includes('queue-export')?new Promise(done=>resolve=done):Promise.resolve(f.snapshot));const pending=f.button(t,'JSON 결과 내보내기').props.onClick();f.switchProject();f.render();resolve({filename:'old.json',format:'json',content:'old account bytes',count:1,total:1,truncated:false});await pending;await settle();assert.equal(f.downloads(),0);}finally{f.close();}});

test('part history binds its query and refuses an export from an earlier part selection',async()=>{const f=fixture();try{let tree=await f.open();nodes(tree).find(n=>n.props['aria-label']==='조회할 부품 ID').props.onChange({target:{value:'PART-002'}});tree=f.render();f.button(tree,'부품 이력 조회').props.onClick();tree=f.render();await settle();tree=f.render();assert.ok(f.calls.some(c=>c.route.includes('part_id=PART-002')));let reply;f.setHandler(route=>route.includes('queue-export')?new Promise(done=>reply=done):Promise.resolve(f.snapshot));const pending=f.button(tree,'JSON 결과 내보내기').props.onClick();nodes(tree).find(n=>n.props['aria-label']==='조회할 부품 ID').props.onChange({target:{value:'PART-003'}});f.button(f.render(),'부품 이력 조회').props.onClick();f.render();reply({filename:'part2.json',format:'json',content:'old part bytes',count:1,total:1,truncated:false});await pending;assert.equal(f.downloads(),0);}finally{f.close();}});

test('taking reinspection identity never submits and refuses a retained callback after permission withdrawal',async()=>{const f=fixture();try{let taken=0;f.props.canInspect=true;f.props.onReinspect=()=>taken++;f.snapshot.jobs[0].image_id='PART-001';f.snapshot.jobs[0].state='completed';const tree=await f.open(),choose=f.button(tree,'재검사 정보 가져오기');choose.props.onClick();assert.equal(taken,1);assert.equal(f.calls.filter(c=>c.options?.method).length,0);f.props.canInspect=false;f.render();choose.props.onClick();assert.equal(taken,1);assert.equal(f.button(f.render(),'재검사 정보 가져오기').props.disabled,true);}finally{f.close();}});
