import {useEffect,useRef,useState} from 'react';
import {api,request,getProjectContextGeneration,subscribeProjectContext} from '../../services/api';
import {useDeliveryScope} from './useDeliveryScope';
import {useProjectStore} from '../../stores/useProjectStore';
import type {SavedFlowVersion} from '../../services/api';
import {ManualOperationsReviewPanel} from './ManualOperationsReviewPanel';
type Model={job_id:string;task:string;family_dataset_path?:string;retrainable:boolean};
type Cycle={cycle_id:string;status:string;phase:string;created_at:number;error:string|null;result:Record<string,unknown>;events:{phase:string;at:number}[]};
type Policy={task:string;parent_job_id:string;family_dataset_path:string|null;reviewer:string;process_existing:boolean;auto_label:boolean;confidence_threshold:number;label_device:string;auto_retrain:boolean;require_label_review:boolean;training_device:string;preset:'fast'|'precision';budget:{max_trials:number;max_total_epochs:number;max_seconds:number};base_config:Record<string,unknown>;epochs_per_trial:number;auto_approve:boolean;auto_deploy:boolean;approval_policy_authorized:boolean;pipeline_id:string|null;pipeline_version_id:string|null;inference_device:string;minimum_sample_count:number;minimum_metrics:Record<string,number>;maximum_metrics:Record<string,number>;watch_interval_seconds:number;new_data_validation_fraction:number};
type State={active:boolean;policy:(Policy&{holdout:Record<string,unknown>;revision:number})|null;cycles:Cycle[];watcher:{running:boolean;stopping:boolean;pid:number|null}};
const defaults:Policy={task:'classification',parent_job_id:'',family_dataset_path:null,reviewer:'',process_existing:false,auto_label:false,confidence_threshold:.95,label_device:'cpu',auto_retrain:false,require_label_review:true,training_device:'cpu',preset:'fast',budget:{max_trials:1,max_total_epochs:2,max_seconds:600},base_config:{},epochs_per_trial:2,auto_approve:false,auto_deploy:false,approval_policy_authorized:false,pipeline_id:null,pipeline_version_id:null,inference_device:'cpu',minimum_sample_count:8,minimum_metrics:{},maximum_metrics:{},watch_interval_seconds:30,new_data_validation_fraction:.2};
const phaseNames:Record<string,string>={discover:'입력 확인',automatic_labels:'자동 라벨',retraining:'재학습',fixed_holdout_evaluation:'고정 시험 데이터 평가',quality_approval:'품질 기준 승인',finish:'결과 저장'};
const statuses:Record<string,string>={idle:'새 입력 없음',running:'진행 중',needs_review:'라벨 검수 필요',awaiting_approval:'후보 승인 대기',awaiting_flow_review:'후보 플로우 검토 대기',completed:'완료',deployed:'배포 적용 확인됨',approved:'승인됨',approved_deployment_cancelled:'승인됨 · 배포 취소',blocked:'입력 변경 확인 필요',failed:'실패',cancelled:'취소됨',interrupted:'중단됨'};
const control='w-full rounded border border-slate-600 bg-[#0D1622] p-2 text-xs';
export function ModelOperationsPanel(){
  const project=useProjectStore(s=>s.project);const projectDir=useProjectStore(s=>s.projectDir);const {key}=useDeliveryScope();const [authority,setAuthority]=useState(getProjectContextGeneration());const scope=`${key}\u0000${authority}`;const scopeRef=useRef(scope);scopeRef.current=scope;
  const [state,setState]=useState<State|null>(null),[models,setModels]=useState<Model[]>([]),[flows,setFlows]=useState<SavedFlowVersion[]>([]),[form,setForm]=useState<Policy>(defaults),[config,setConfig]=useState('{}'),[bounds,setBounds]=useState('{"minimum":{},"maximum":{}}'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[expanded,setExpanded]=useState('');
  useEffect(()=>subscribeProjectContext(()=>{scopeRef.current='';setState(null);setModels([]);setFlows([]);setBusy(false);setError('');setAuthority(getProjectContextGeneration());}),[]);
  const load=async()=>{if(scopeRef.current!==scope||getProjectContextGeneration()!==authority)return null;const started=scope;const result=await request<State>('/api/model-operations');if(scopeRef.current===started)setState(result);return result;};
  useEffect(()=>{let current=true;setState(null);setModels([]);setFlows([]);setForm(defaults);setError('');setBusy(false);setConfig('{}');setBounds('{"minimum":{},"maximum":{}}');setExpanded('');
    if(!project?.source_dataset_dir)return;
    Promise.all([request<State>('/api/model-operations'),request<{models:Model[]}>('/api/model-operations/models'),api.flowchart.listPipelines(project.source_dataset_dir)]).then(([result,catalog,saved])=>{
      if(!current||scopeRef.current!==scope)return;setState(result);setModels(catalog.models);setFlows(saved.pipelines);
      if(result.policy){const selected=Object.fromEntries(Object.keys(defaults).map(key=>[key,result.policy![key as keyof Policy]])) as Policy;setForm(selected);setConfig(JSON.stringify(selected.base_config,null,2));setBounds(JSON.stringify({minimum:selected.minimum_metrics,maximum:selected.maximum_metrics},null,2));}
    }).catch(cause=>{if(current)setError(String(cause.message||cause));});return()=>{current=false;};
  },[scope]);
  useEffect(()=>{if(!state?.active&&!state?.watcher.running&&!state?.cycles.some(c=>c.status==='running'))return;const timer=setInterval(()=>void load().catch(cause=>{if(scopeRef.current===scope)setError(String(cause.message||cause));}),3000);return()=>clearInterval(timer);},[scope,state?.active,state?.watcher.running,state?.cycles]);
  const action=async(path:string,payload?:unknown,method='POST')=>{if(scopeRef.current!==scope||getProjectContextGeneration()!==authority)return;const started=scope;setBusy(true);setError('');try{await request('/api/model-operations'+path,{method,...(payload!==undefined?{body:JSON.stringify(payload)}:{})});if(scopeRef.current===started)await load();}catch(cause){if(scopeRef.current===started)setError(String((cause as Error).message||cause));}finally{if(scopeRef.current===started)setBusy(false);}};
  const set=<K extends keyof Policy>(key:K,value:Policy[K])=>setForm(current=>({...current,[key]:value}));
  const save=()=>{try{const criteria=JSON.parse(bounds);void action('/policy',{...form,base_config:JSON.parse(config),minimum_metrics:criteria.minimum||{},maximum_metrics:criteria.maximum||{}},'PUT');}catch{setError('학습 설정과 품질 기준의 JSON을 확인하세요.');}};
  if(!projectDir||!project?.source_dataset_dir)return null;
  const selectedModel=models.find(m=>m.job_id===form.parent_job_id&&m.task===form.task);
  return <details className="mt-3 rounded-lg border border-slate-700 bg-[#142131] p-3"><summary className="cursor-pointer text-sm font-semibold text-cyan-200">새 데이터 · 자동 라벨 · 모델 개선 운영</summary><div className="mt-3 space-y-3 text-xs text-slate-200">
    <p className="leading-5 text-slate-400">독립 test 분할을 고정하고 새 이미지나 변경된 라벨에서 후보를 만듭니다. 검수 대기 라벨, 학습 후보, 승인 모델과 장비 적용 결과를 단계별로 보존합니다.</p>
    <div className="grid gap-2 sm:grid-cols-2"><label className="sm:col-span-2">시작 모델<select aria-label="운영 시작 모델" className={control} value={form.parent_job_id} onChange={e=>{const m=models.find(row=>row.job_id===e.target.value);if(m)setForm(f=>({...f,parent_job_id:m.job_id,task:m.task,family_dataset_path:m.family_dataset_path||null,auto_label:false,auto_approve:false,auto_deploy:false,approval_policy_authorized:false}));}}><option value="">완료 모델 선택</option>{models.map(m=><option key={`${m.task}:${m.job_id}`} value={m.job_id}>{m.task} · {m.job_id} · {m.retrainable?'설정 재사용 가능':'라벨 추론용'}</option>)}</select></label>
    <label>정책 검토자<input aria-label="자동 운영 정책 검토자" className={control} value={form.reviewer} onChange={e=>set('reviewer',e.target.value)}/></label><label>감시 간격 (초)<input type="number" min="5" max="86400" aria-label="새 데이터 감시 간격" className={control} value={form.watch_interval_seconds} onChange={e=>set('watch_interval_seconds',Number(e.target.value))}/></label>
    <label className="flex items-center gap-2"><input type="checkbox" checked={form.process_existing} onChange={e=>set('process_existing',e.target.checked)}/>기존 이미지도 새 입력으로 처리</label><label className="flex items-center gap-2"><input type="checkbox" checked={form.auto_label} disabled={!['classification','detection','segmentation','ocr','rotated_detection'].includes(form.task)} onChange={e=>set('auto_label',e.target.checked)}/>높은 신뢰도 라벨을 검수 대기로 저장</label>
    <label>자동 라벨 최소 신뢰도<input aria-label="자동 라벨 최소 신뢰도" type="number" min=".5" max="1" step=".01" className={control} value={form.confidence_threshold} onChange={e=>set('confidence_threshold',Number(e.target.value))}/></label><label>라벨 실행 장치<input aria-label="자동 라벨 장치" className={control} value={form.label_device} onChange={e=>set('label_device',e.target.value)} placeholder="cpu / cuda:0 / mps"/></label>
    <label className="flex items-center gap-2"><input type="checkbox" checked={form.auto_retrain} disabled={!selectedModel?.retrainable} onChange={e=>set('auto_retrain',e.target.checked)}/>새 검수 데이터에서 부모 모델 재학습</label><label className="flex items-center gap-2"><input type="checkbox" checked={form.require_label_review} onChange={e=>set('require_label_review',e.target.checked)}/>사람의 라벨 승인 후 학습</label>
    <label>학습 장치<input aria-label="운영 재학습 장치" className={control} value={form.training_device} onChange={e=>set('training_device',e.target.value)}/></label><label>후보 학습 epoch<input type="number" min="1" max="500" className={control} value={form.epochs_per_trial} onChange={e=>{const n=Number(e.target.value);setForm(f=>({...f,epochs_per_trial:n,budget:{...f.budget,max_total_epochs:n}}));}}/></label><label>최대 학습 시간 (초)<input aria-label="운영 학습 시간 예산" type="number" min="1" max="86400" className={control} value={form.budget.max_seconds} onChange={e=>set('budget',{...form.budget,max_seconds:Number(e.target.value)})}/></label><label>새 데이터의 val 비율<input type="number" min="0" max=".5" step=".05" className={control} value={form.new_data_validation_fraction} onChange={e=>set('new_data_validation_fraction',Number(e.target.value))}/></label>
    <label className="sm:col-span-2">특수 모델의 검수 입력 폴더<input aria-label="운영 검수 입력 경로" className={control} value={form.family_dataset_path||''} onChange={e=>set('family_dataset_path',e.target.value||null)}/></label></div>
    <details><summary className="cursor-pointer text-slate-300">학습 설정 · 자동 승인과 배포 정책</summary><div className="mt-2 space-y-2"><label className="block">학습 설정 JSON<textarea aria-label="운영 학습 설정" rows={4} className={`${control} font-mono`} value={config} onChange={e=>setConfig(e.target.value)}/></label>
    <label className="flex items-center gap-2"><input type="checkbox" aria-label="자동 승인 정책 승인" checked={form.approval_policy_authorized} onChange={e=>set('approval_policy_authorized',e.target.checked)}/>고정 test 정답을 검토했고 아래 자동 승인 정책을 승인합니다.</label>
    <label className="flex items-center gap-2"><input type="checkbox" checked={form.auto_approve} disabled={!form.auto_retrain||!form.approval_policy_authorized||form.task==='defect_gan'} onChange={e=>set('auto_approve',e.target.checked)}/>기준 모델 대비 신규 미검·과검이 없고 품질 기준을 통과하면 승인</label>
    <label className="block">특수 모델 품질 기준 (minimum / maximum)<textarea aria-label="자동 승인 품질 기준" rows={4} className={`${control} font-mono`} value={bounds} onChange={e=>setBounds(e.target.value)}/></label><label>최소 test 수<input type="number" min="8" className={control} value={form.minimum_sample_count} onChange={e=>set('minimum_sample_count',Number(e.target.value))}/></label>
    <label className="block">적용할 저장 플로우<select aria-label="자동 배포 저장 플로우" className={control} value={form.pipeline_version_id||''} onChange={e=>{const f=flows.find(row=>row.version_id===e.target.value);setForm(current=>({...current,pipeline_version_id:f?.version_id||null,pipeline_id:f?.pipeline_id||null}));}}><option value="">플로우 선택</option>{flows.map(f=><option key={f.version_id} value={f.version_id}>{f.name} · {f.saved_at}{f.is_active?' · 활성':''}</option>)}</select></label><label className="flex items-center gap-2"><input type="checkbox" checked={form.auto_deploy} disabled={!form.auto_approve||!form.pipeline_version_id} onChange={e=>set('auto_deploy',e.target.checked)}/>승인 후보를 플로우에 넣고 독립 검사 서비스에 적용</label><p className="text-slate-400">test 데이터 변경·중복, 품질 회귀, 승인 불일치나 장비 응답 불일치는 적용을 막고 기록합니다. 학습과 독립 검사 서비스는 별도 프로세스로 실행됩니다.</p></div></details>
    <div className="flex flex-wrap gap-2"><button className="rounded bg-cyan-700 px-3 py-2 disabled:opacity-40" disabled={busy||!form.parent_job_id||!form.reviewer.trim()} onClick={save}>정책 검증·저장</button><button className="rounded border border-slate-600 px-3 py-2 disabled:opacity-40" disabled={busy||!state?.policy||state.watcher.running} onClick={()=>void action('/run',{background:true})}>한 번 실행</button><button className="rounded border border-slate-600 px-3 py-2 disabled:opacity-40" disabled={busy||!state?.policy||state.watcher.running} onClick={()=>void action('/watch/start')}>감시 시작</button><button className="rounded border border-amber-700 px-3 py-2 disabled:opacity-40" disabled={busy} onClick={()=>void action('/cancel')}>실행·감시 취소</button><button className="px-2 text-cyan-200" onClick={()=>void load().catch(cause=>setError(String(cause.message||cause)))}>새로고침</button></div>
    {state?.policy&&<p className="text-slate-400">정책 v{state.policy.revision} · 고정 test {Object.keys(state.policy.holdout).length}장 · 감시 {state.watcher.running?(state.watcher.stopping?'종료 요청됨':'동작 중'):'중지됨'}</p>}
    <div className="max-h-72 space-y-2 overflow-auto">{state?.cycles.map(c=><article key={c.cycle_id} className="rounded border border-slate-700 p-2"><button className="w-full text-left" onClick={()=>setExpanded(expanded===c.cycle_id?'':c.cycle_id)}>{new Date(c.created_at*1000).toLocaleString()} · {statuses[c.status]||c.status} · {phaseNames[c.phase]||c.phase}</button>{c.error&&<p className="mt-1 break-all text-amber-200">{c.error}</p>}{expanded===c.cycle_id&&<><ManualOperationsReviewPanel cycleId={c.cycle_id} flows={flows}/><pre className="mt-2 max-h-56 overflow-auto whitespace-pre-wrap break-all text-[10px] text-slate-400">{JSON.stringify(c.result,null,2)}</pre></>}</article>)}</div>{error&&<p role="alert" className="break-all text-red-300">{error}</p>}
  </div></details>;
}
