const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),ts=require('typescript');
function hooks(){let cursor=0;const slots=[],effects=[];return{react:{useState:v=>{const i=cursor++;if(!(i in slots))slots[i]=typeof v==='function'?v():v;return[slots[i],v=>slots[i]=typeof v==='function'?v(slots[i]):v];},useRef:v=>{const i=cursor++;return slots[i]??(slots[i]={current:v});},useEffect:(fn,deps)=>{const i=cursor++;if(!slots[i]||deps.some((v,j)=>v!==slots[i].deps[j])){slots[i]?.cleanup?.();slots[i]={deps};effects.push(()=>slots[i].cleanup=fn());}}},render:fn=>{cursor=0;const result=fn();effects.splice(0).forEach(fn=>fn());return result;},unmount:()=>slots.forEach(s=>s?.cleanup?.())};}
const jsx=(type,props)=>({type,props:props||{},children:[props?.children].flat().filter(Boolean)});
function nodes(t){return t&&typeof t==='object'?[t,...(t.children||[]).flat().flatMap(nodes)]:[];}
const settle=()=>new Promise(setImmediate);
function fixture(){
 const h=hooks();let generation=1,scope='p',subscriber,handler,downloads=0;const calls=[];const props={canConfigure:true};
 const mocks={'react':h.react,'react/jsx-runtime':{jsx,jsxs:jsx},'../../stores/useProjectStore':{useProjectStore:selector=>selector({language:'ko'})},'./useDeliveryScope':{useDeliveryScope:()=>({key:scope})},'../../services/api':{getProjectContextGeneration:()=>generation,subscribeProjectContext:fn=>{subscriber=fn;return()=>{};},request:async(route,options)=>{calls.push({route,options});return handler?handler(route,options):snapshot;}}};
 const file=path.resolve(__dirname,'OperationsObservabilityPanel.tsx'),m=new Module(file,module);m.filename=file;m.paths=Module._nodeModulePaths(__dirname);m.require=id=>mocks[id]||require(id);m._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText,file);
 const snapshot={service:'ready',readiness:{available:true,status:'ready'},external_telemetry:false,can_configure:true,policy:{revision:1,enabled:false,external_telemetry:false},metrics:{disk:{available:true,free_bytes:1e10},gpu:{available:false,devices:[],reason:'none'}},queue:{outstanding:0,capacity:100},training_events:{available:true},logs:{items:[{id:1,job_id:'owned',trace_id:'owned',kind:'training',state:'completed',at:1,event:'epoch_progress',message:'Owned epoch',payload:{loss:.5}}],total:1,has_more:false},notifications:{items:[],total:0},error_catalog:{}};
 const originalDocument=globalThis.document;globalThis.document={createElement:()=>{downloads++;return{click(){}};}};
 const render=()=>h.render(()=>m.exports.OperationsObservabilityPanel(props)),button=(t,name)=>nodes(t).find(n=>n.type==='button'&&n.children.includes(name));
 const open=async()=>{render().props.onToggle({currentTarget:{open:true}});render();await settle();return render();};
 return{render,button,open,calls,props,snapshot,setHandler:fn=>handler=fn,switchAccount:()=>{generation++;subscriber?.();},switchProject:()=>{scope='other';generation++;subscriber?.();},downloads:()=>downloads,close:()=>{h.unmount();globalThis.document=originalDocument;}};
}
test('late logs cannot expose prior account history',async()=>{const f=fixture();try{let resolve;f.setHandler(()=>new Promise(done=>resolve=done));await f.open();const previous=resolve;f.switchAccount();f.render();previous(f.snapshot);await settle();assert.equal(nodes(f.render()).filter(n=>n.type==='article').length,0);}finally{f.close();}});
test('retained policy callback refuses mutation after authority withdrawal',async()=>{const f=fixture();try{const tree=await f.open(),save=f.button(tree,'알림 정책 저장');f.props.canConfigure=false;f.render();const before=f.calls.length;await save.props.onClick();assert.equal(f.calls.length,before);assert.equal(f.button(f.render(),'알림 정책 저장').props.disabled,true);}finally{f.close();}});
test('late filtered reply cannot expose the prior job cohort',async()=>{const f=fixture();try{let tree=await f.open();let resolve;f.setHandler(()=>new Promise(done=>resolve=done));nodes(tree).find(n=>n.props['aria-label']==='운영 로그 작업 ID').props.onChange({target:{value:'first'}});f.button(f.render(),'작업 이력 조회').props.onClick();tree=f.render();const old=resolve;nodes(tree).find(n=>n.props['aria-label']==='운영 로그 작업 ID').props.onChange({target:{value:'second'}});f.button(f.render(),'작업 이력 조회').props.onClick();f.render();old(f.snapshot);await settle();assert.equal(nodes(f.render()).filter(n=>n.type==='article').length,0);assert.ok(f.calls.at(-1).route.includes('job_id=second'));}finally{f.close();}});
