import type { Language } from '../../types';

const ENGLISH: Record<string, string> = {
  "검사할 프로젝트를 여세요.": "Open a project for inspection.",
  "운영자 검사 작업 공간": "Operator inspection workspace",
  "운영자 검사": "Operator inspection",
  "현재 품목·저장 레시피·입력·판정을 확인합니다.": "Check the current product, saved recipe, inputs and verdicts.",
  "상태 확인": "Refresh status",
  "실제 서비스 상태 확인됨": "Live service status checked",
  "검사 서비스": "Inspection service",
  "실행 응답 확인": "Runtime response confirmed",
  "중지됨": "Stopped",
  "상태 확인 필요": "Check status",
  "승인 적용 기록과 실행 버전 일치": "Runtime matches the approved deployment",
  "승인 기록과 실행 버전 확인 필요": "Check the approved deployment against the runtime",
  "검사 시작": "Start inspection",
  "검사 중지": "Stop inspection",
  "검사 서비스 시작 응답 확인": "Service start response confirmed",
  "검사 서비스 중지 응답 확인": "Service stop response confirmed",
  "입력 상태": "Input health",
  "원본 입력 폴더 ": "Source folder ",
  "확인": "Available",
  "사용 불가": "Unavailable",
  "수동 입력 ": "Manual input ",
  "준비됨": "Ready",
  "서비스 준비 필요": "Service readiness required",
  "폴더·카메라·PLC 응답 상세": "Folder, camera and PLC response details",
  "현재 검사 레시피": "Current inspection recipe",
  "실행 레시피 없음": "No running recipe",
  "실행 장치 ": "Device ",
  "적용 버전·해시": "Deployment version and hash",
  "실행 응답 없음": "No runtime response",
  "적용 ": "Deployment ",
  "현재 레시피로 이미지 검사": "Inspect an image with the current recipe",
  "운영자 검사 이미지": "Operator inspection image",
  "검사 입력": "Submit inspection",
  "검사 문맥이 바뀌었습니다.": "The inspection context changed.",
  "검사 권한과 현재 실행 레시피 상태를 다시 확인하세요.": "Recheck inspection permission and the current running recipe.",
  "검사 입력 등록됨 · 아래 결과에서 완료 상태 확인": "Inspection submitted; check completion in the results below",
  "선택 다시 확인": "Recheck selection",
  "선택 해제": "Clear selection",
  "현재 선택: ": "Selected: ",
  "선택한 이미지 확인 중…": "Checking the selected image…",
  "선택 이미지 ": "Selected image ",
  "내용 바뀜": "Content changed",
  "옮겨짐": "Moved",
  "찾을 수 없음": "Missing",
  "읽지 못함": "Unreadable",
  " 선택 다시 확인 또는 선택 해제를 사용하세요.": " Use Recheck selection or Clear selection.",
  " · 검사를 진행하려면 이미지를 명시적으로 다시 선택하거나 선택 해제하세요.": "; explicitly reselect or clear the image before inspecting.",
  "검증된 데이터 버전이 없어 경로만 저장합니다. 처음 64장 목록에서 다시 확인하며, 이미지 내용 변경은 확인할 수 없습니다.": "Without a verified data version, only the path is saved. It is rechecked against the first 64 images; content changes cannot be verified.",
  "입력 연결 설정": "Input connection settings",
  "운영자 입력 방식": "Operator input mode",
  "수동 이미지 입력": "Manual image input",
  "프로젝트 폴더 감시": "Watch a project folder",
  "카메라·RTSP": "Camera / RTSP",
  "운영자 감시 입력 폴더": "Operator watched folder",
  "프로젝트 소스와 카메라 ID를 확인한 뒤 입력 설정을 다시 저장하세요.": "Check the project source and camera ID, then save the input settings again.",
  "운영자 카메라 ID": "Operator camera ID",
  "RTSP는 명시적 ID · USB는 자동 ID 가능": "Explicit ID for RTSP; automatic ID available for USB",
  "카메라 ID는 주소와 구분되는 영문·숫자 식별자입니다. 기록 시간은 호스트 읽기 완료이며 센서 시각·보이지 않는 프레임 손실·실장비 검증은 별도입니다.": "The opaque camera ID is separate from its address. Recorded time is host read completion; sensor time, unseen loss and physical equipment validation are separate.",
  "운영자 카메라 주소": "Operator camera address",
  "0 또는 rtsp://camera-address": "0 or rtsp://camera-address",
  "입력 설정 검증·저장": "Validate and save input settings",
  "입력 설정 저장됨 · 명시적으로 서비스 중지 후 시작하여 적용": "Input settings saved; explicitly stop and start the service to apply them",
  "입력 설정 저장됨 · 다음 서비스 시작에 적용": "Input settings saved; apply on the next service start",
  "감시 폴더는 현재 프로젝트 원본 안에서 선택합니다. 설정 저장과 실제 연결 응답을 구분하며, 서비스 재시작 후 위 입력 상태에서 확인합니다.": "Select a watched folder inside the current project source. Saving settings does not confirm a connection; check input health after restarting the service.",
  "프로젝트 소스가 변경됐습니다. 입력 설정을 다시 확인하세요.": "The project source changed. Recheck input settings.",
  "최근 검사와 REVIEW": "Recent inspections and REVIEW",
  "모델 판정과 운영자 검수를 각각 보존합니다. REVIEW·오류·전송 실패는 정상 판정으로 바꾸지 않습니다.": "Model verdicts and operator reviews are kept separately. REVIEW, errors and delivery failures stay explicit.",
  "저장된 검사 결과가 없습니다.": "No inspection results have been saved.",
  "모델 ": "Model ",
  "진행 중": "In progress",
  " · 운영 ": " · Operator ",
  "검수 열기": "Open review",
  "ACK 전송 재시도": "Retry ACK delivery",
  "전송 재시도 등록됨 · ACK 결과 확인 필요": "Delivery retry submitted; check the ACK result",
  "검수 ": "Review ",
  "검사 결과 검수 · 모델 ": "Inspection review · Model ",
  "운영자 판정": "Operator verdict",
  "운영자 검수 판정": "Operator review verdict",
  "검토자": "Reviewer",
  "운영자 검토자": "Operator reviewer",
  "검수 근거": "Review reason",
  "운영자 검수 근거": "Operator review reason",
  "검수 기록 저장": "Save review",
  "운영자 검수 기록 저장됨": "Operator review saved",
  "요청·실제 응답 확인 중…": "Waiting for the actual response…"
};

export function operatorText(language: Language, korean: string): string {
  return language === 'en' ? ENGLISH[korean] ?? korean : korean;
}
