import {useEffect,useState,useRef} from 'react';
import {useProjectStore} from '../../stores/useProjectStore';
import {operatorText} from './operatorCopy';
import {getProjectContextGeneration,request} from '../../services/api';
import {useDeliveryScope} from './useDeliveryScope';
import {useOperatorImageChoice} from './useOperatorImageChoice';
import {ImageSearchSelect} from '../common/ImageSearchSelect';
import {InspectionQueuePanel} from './InspectionQueuePanel';
type OperatorResult={job_id:string;image_path:string;source:string;state:string;verdict:string|null;model_verdict:string|null;error?:string;created_at:string;operator_review?:{verdict:string;reviewer:string;reason:string}|null};
type OperatorState={permissions:{can_control:boolean;can_inspect:boolean;can_review:boolean;can_configure:boolean};project:{name:string;task:string};runtime_matches_active:boolean;input_health:{source_exists:boolean;manual_input:string;adapters:Record<string,unknown>;configuration:{mode:'manual'|'folder'|'camera';folder:string|null;camera:string|null;needs_reconfiguration?:boolean}};service:{runtime:{status:string;manifest_sha256?:string;pipeline_id?:string;device?:string};active:{deployment_id:string;release:{manifest_sha256:string}}|null};results:OperatorResult[]};
const button='rounded border border-slate-600 px-3 py-2 disabled:opacity-40';
export function OperatorWorkspace(){
 const language=useProjectStore(s=>s.language),t=(text:string)=>operatorText(language,text);
 const {scope,key,project,projectDir}=useDeliveryScope(),[state,setState]=useState<OperatorState|null>(null),[selected,setSelected]=useState(''),[reviewer,setReviewer]=useState(''),[reason,setReason]=useState(''),[verdict,setVerdict]=useState('REVIEW'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[helpOpen,setHelpOpen]=useState(false);
 const choice=useOperatorImageChoice({projectId:project?.id,projectDir,source:project?.source_dataset_dir||'',task:project?.task||'segmentation',labelset:project?.active_labelset_id,deliveryKey:key});
 const image=choice.path,generation=getProjectContextGeneration(),authority=useRef(choice.token);authority.current=choice.token;
 const current=()=>authority.current===choice.token&&getProjectContextGeneration()===generation;
 const [inputMode,setInputMode]=useState<'manual'|'folder'|'camera'>('manual'),[inputFolder,setInputFolder]=useState(''),[camera,setCamera]=useState('');const editingInputs=useRef(false);
 const refresh=async()=>{if(!current())return;const started=scope.current;const result=await request<OperatorState>('/api/product-delivery/operator');if(current()&&scope.current===started)setState(result);};
 useEffect(()=>{let live=true;const started=scope.current;setState(null);setSelected('');setReviewer('');setReason('');setError('');setNotice('');setBusy(false);setInputMode('manual');setInputFolder(project?.source_dataset_dir||'');setCamera('');editingInputs.current=false;
 const update=()=>request<OperatorState>('/api/product-delivery/operator').then(result=>{if(live&&current()&&scope.current===started){setState(result);if(!editingInputs.current){setInputMode(result.input_health.configuration.mode);setInputFolder(result.input_health.configuration.folder||project?.source_dataset_dir||'');setCamera(result.input_health.configuration.camera||'');}}}).catch(e=>{if(live&&current()&&scope.current===started)setError(String(e.message||e));});if(project){void update();}const timer=setInterval(()=>{if(live&&project)void update();},3000);return()=>{live=false;clearInterval(timer);};},[key,choice.token]);
 const action=async<T,>(fn:()=>Promise<T>,message:string|((result:T)=>string),permission?:keyof OperatorState['permissions'])=>{if(!current()||(permission&&!permissionGate.current[permission]))return;const started=scope.current;setBusy(true);setError('');setNotice('');try{const result=await fn();if(current()&&scope.current===started){await refresh();if(current()&&scope.current===started)setNotice(typeof message==='function'?message(result):message);}}catch(e){if(current()&&scope.current===started)setError(String((e as Error).message||e));}finally{if(current()&&scope.current===started)setBusy(false);}};
 useEffect(()=>{const listener=(event:KeyboardEvent)=>{if(event.key==='F1'){event.preventDefault();setHelpOpen(value=>!value);}else if(event.key==='Escape')setHelpOpen(false);};document.addEventListener('keydown',listener);return()=>document.removeEventListener('keydown',listener);},[]);
 const reviewRow=state?.results.find(row=>row.job_id===selected);
 const permissions=state?.permissions||{can_control:false,can_inspect:false,can_review:false,can_configure:false};
 const permissionGate=useRef(permissions);permissionGate.current={...permissions};
 const inspectionGate=useRef({canInspect:false,runtimeMatches:false});
 inspectionGate.current={canInspect:permissions.can_inspect,runtimeMatches:Boolean(state?.runtime_matches_active)};
 if(!project)return <p className="p-4 text-slate-400">{t("검사할 프로젝트를 여세요.")}</p>;
 return <section aria-label={t("운영자 검사 작업 공간")} className="space-y-4 p-4 text-sm text-slate-200"><header className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-semibold">{t("운영자 검사")}</h2><button type="button" aria-expanded={helpOpen} aria-controls="operator-help" className={button+' mt-2'} onClick={()=>setHelpOpen(value=>!value)}>{language==='ko'?'작업자 도움말 (F1)':'Operator help (F1)'}</button><p className="mt-1 text-slate-400">{project.name} · {t("현재 품목·저장 레시피·입력·판정을 확인합니다.")}</p></div><button type="button" disabled={busy} className={button} onClick={()=>void action(refresh,t("실제 서비스 상태 확인됨"))}>{t("상태 확인")}</button></header>
  {helpOpen&&<aside id="operator-help" aria-label={language==='ko'?'작업자 도움말':'Operator help'} className="rounded border border-sky-700 p-4"><h3 className="font-semibold">{language==='ko'?'검사 운영 순서':'Inspection workflow'}</h3><ol className="mt-2 list-decimal space-y-1 pl-5"><li>{language==='ko'?'현재 프로젝트, 승인 적용 버전, 입력 상태를 확인하세요.':'Check the current project, approved deployment version and input health.'}</li><li>{language==='ko'?'검사 시작 후 실행 버전 일치를 확인하고 이미지를 명시적으로 선택하세요.':'Start the service, confirm its version matches, and explicitly select an image.'}</li><li>{language==='ko'?'검사 입력 후 완료 상태를 확인하세요. REVIEW·오류·전송 실패는 검토 대상입니다.':'Submit an inspection and check completion. REVIEW, errors and delivery failures need review.'}</li><li>{language==='ko'?'검수 근거를 저장하면 모델 원본 판정과 별도로 남습니다. 입력 설정 변경은 안내에 따라 중지 후 시작하여 적용하세요.':'Save a review reason separately from the original model verdict. Apply input changes by stopping and starting as instructed.'}</li></ol><p className="mt-2 text-slate-400">{language==='ko'?'Tab/Shift+Tab 이동 · Enter/Space 버튼 실행 · F1 도움말 열기/닫기 · Esc 도움말 닫기. 권한이 없는 작업은 키보드로도 실행할 수 없습니다.':'Tab/Shift+Tab to navigate; Enter/Space to activate buttons; F1 to toggle help; Esc to close help. Keyboard actions use the same permissions.'}</p><p className="mt-2 text-slate-400">{language==='ko'?'연결 오류: 상태 확인 → 입력 경로·활성 버전 확인 → 필요한 경우 명시적으로 중지 후 시작. ACK 오류는 결과 행의 재시도와 응답을 확인하세요.':'For connection errors, refresh status and check the input path and active version; explicitly stop and start when required. For ACK errors, retry from the result row and check its response.'}</p></aside>}
  <div className="grid gap-3 md:grid-cols-3"><article className="rounded border border-slate-600 p-4"><h3 className="font-semibold">{t("검사 서비스")}</h3><p className="mt-2">{state?.service.runtime.status==='ready'?t("실행 응답 확인"):state?.service.runtime.status==='stopped'?t("중지됨"):t("상태 확인 필요")}</p><p className="mt-1 text-slate-400">{state?.runtime_matches_active?t("승인 적용 기록과 실행 버전 일치"):t("승인 기록과 실행 버전 확인 필요")}</p><div className="mt-3 flex flex-wrap gap-2"><button type="button" disabled={busy||!permissions.can_control||!state?.service.active} className={button} onClick={()=>void action(()=>request('/api/runtime-services/start',{method:'POST'}),t("검사 서비스 시작 응답 확인"),'can_control')}>{t("검사 시작")}</button><button type="button" disabled={busy||!permissions.can_control||state?.service.runtime.status==='stopped'} className={button} onClick={()=>void action(()=>request('/api/runtime-services/stop',{method:'POST'}),t("검사 서비스 중지 응답 확인"),'can_control')}>{t("검사 중지")}</button></div></article><article className="rounded border border-slate-600 p-4"><h3 className="font-semibold">{t("입력 상태")}</h3><p className="mt-2">{t("원본 입력 폴더 ")}{state?.input_health.source_exists?t("확인"):t("사용 불가")}</p><p className="mt-1">{t("수동 입력 ")}{state?.input_health.manual_input==='available'?t("준비됨"):t("서비스 준비 필요")}</p><details className="mt-2 text-slate-400"><summary>{t("폴더·카메라·PLC 응답 상세")}</summary><pre className="mt-1 overflow-auto whitespace-pre-wrap text-xs">{JSON.stringify(state?.input_health.adapters||{},null,2)}</pre></details></article><article className="rounded border border-slate-600 p-4"><h3 className="font-semibold">{t("현재 검사 레시피")}</h3><p className="mt-2 break-all">{state?.service.runtime.pipeline_id||t("실행 레시피 없음")}</p><p className="mt-1">{t("실행 장치 ")}{state?.service.runtime.device||'—'}</p><details className="mt-2 text-slate-400"><summary>{t("적용 버전·해시")}</summary><p className="mt-1 break-all font-mono text-xs">{state?.service.runtime.manifest_sha256||t("실행 응답 없음")}</p><p className="text-xs">{t("적용 ")}{state?.service.active?.deployment_id||'—'}</p></details></article></div>
  <section className="rounded border border-slate-600 p-4"><h3 className="font-semibold">{t("현재 레시피로 이미지 검사")}</h3><div className="mt-3 flex gap-2"><div className="min-w-0 flex-1"><ImageSearchSelect key={choice.token} language={language} label={t("운영자 검사 이미지")} value={image} onChange={()=>{}} onIdentityChange={row=>choice.select(row)} onLegacyChange={path=>choice.selectLegacy(path)} disabled={busy||choice.phase!=='ready'} autoSelectFirst={false} folder={project?.source_dataset_dir} task={project?.task}/></div><button type="button" disabled={busy||!permissions.can_inspect||!choice.canInspect||!state?.runtime_matches_active} className={button} onClick={()=>{if(!choice.canInspect||!choice.isCurrent()||!permissions.can_inspect||!state?.runtime_matches_active)return;void action(async()=>{const image_path=await choice.verifyForInspect();if(!current())throw new Error(t("검사 문맥이 바뀌었습니다."));if(!inspectionGate.current.canInspect||!inspectionGate.current.runtimeMatches)throw new Error(t("검사 권한과 현재 실행 레시피 상태를 다시 확인하세요."));return request('/api/product-delivery/operator/inspect',{method:'POST',body:JSON.stringify({image_path})});},t("검사 입력 등록됨 · 아래 결과에서 완료 상태 확인"));}}>{t("검사 입력")}</button></div>
   <div className="mt-2 flex flex-wrap gap-2"><button type="button" disabled={busy||choice.phase==='loading'} className={button} onClick={choice.refresh}>{t("선택 다시 확인")}</button><button type="button" disabled={busy||!choice.storageKey} className={button} onClick={choice.clear}>{t("선택 해제")}</button></div>
   {image&&<p className="mt-2 break-all text-slate-400">{t("현재 선택: ")}{choice.selection?.file_name||image.split(/[\\/]/).pop()} · {image}</p>}
   {choice.phase==='loading'&&<p role="status" className="mt-2 text-blue-300">{t("선택한 이미지 확인 중…")}</p>}
   {choice.error&&<p role="alert" className="mt-2 break-all text-amber-300">{choice.error}{t(" 선택 다시 확인 또는 선택 해제를 사용하세요.")}</p>}
   {choice.phase==='ready'&&choice.status!=='empty'&&choice.status!=='found'&&<p role="alert" className="mt-2 text-amber-300">{t("선택 이미지 ")}{({changed:t("내용 바뀜"),moved:t("옮겨짐"),missing:t("찾을 수 없음"),unreadable:t("읽지 못함")} as const)[choice.status]}{t(" · 검사를 진행하려면 이미지를 명시적으로 다시 선택하거나 선택 해제하세요.")}</p>}
   {choice.mode==='legacy'&&<p className="mt-2 text-amber-300">{t("검증된 데이터 버전이 없어 경로만 저장합니다. 처음 64장 목록에서 다시 확인하며, 이미지 내용 변경은 확인할 수 없습니다.")}</p>}
  </section>
  <details className="rounded border border-slate-600 p-4"><summary className="cursor-pointer font-semibold">{t("입력 연결 설정")}</summary><div className="mt-3 flex flex-wrap gap-2"><select aria-label={t("운영자 입력 방식")} value={inputMode} disabled={busy||!permissions.can_configure} onChange={e=>{if(!current()||!permissionGate.current.can_configure)return;editingInputs.current=true;setInputMode(e.target.value as typeof inputMode);}} className="rounded bg-slate-800 p-2"><option value="manual">{t("수동 이미지 입력")}</option><option value="folder">{t("프로젝트 폴더 감시")}</option><option value="camera">{t("카메라·RTSP")}</option></select>{inputMode==='folder'&&<input aria-label={t("운영자 감시 입력 폴더")} value={inputFolder} disabled={busy||!permissions.can_configure} onChange={e=>{if(!current()||!permissionGate.current.can_configure)return;editingInputs.current=true;setInputFolder(e.target.value);}} className="min-w-0 flex-1 rounded bg-slate-800 p-2"/>}{inputMode==='camera'&&<input aria-label={t("운영자 카메라 주소")} autoComplete="off" value={camera} disabled={busy||!permissions.can_configure} onChange={e=>{if(!current()||!permissionGate.current.can_configure)return;editingInputs.current=true;setCamera(e.target.value);}} placeholder={t("0 또는 rtsp://camera-address")} className="min-w-0 flex-1 rounded bg-slate-800 p-2"/>}<button type="button" disabled={busy||!permissions.can_configure} className={button} onClick={()=>void action(async()=>{const started=scope.current;const result=await request<{restart_required:boolean}>('/api/product-delivery/operator/inputs',{method:'PUT',body:JSON.stringify({mode:inputMode,folder:inputFolder||null,camera:camera||null})});if(current()&&scope.current===started){editingInputs.current=false;}return result;},result=>result.restart_required?t("입력 설정 저장됨 · 명시적으로 서비스 중지 후 시작하여 적용"):t("입력 설정 저장됨 · 다음 서비스 시작에 적용"),'can_configure')}>{t("입력 설정 검증·저장")}</button></div><p className="mt-2 text-slate-400">{t("감시 폴더는 현재 프로젝트 원본 안에서 선택합니다. 설정 저장과 실제 연결 응답을 구분하며, 서비스 재시작 후 위 입력 상태에서 확인합니다.")}</p>{state?.input_health.configuration.needs_reconfiguration&&<p className="mt-2 text-amber-300">{t("프로젝트 소스가 변경됐습니다. 입력 설정을 다시 확인하세요.")}</p>}</details>
  <section className="rounded border border-slate-600 p-4"><h3 className="font-semibold">{t("최근 검사와 REVIEW")}</h3><p className="mt-1 text-slate-400">{t("모델 판정과 운영자 검수를 각각 보존합니다. REVIEW·오류·전송 실패는 정상 판정으로 바꾸지 않습니다.")}</p>{state?.results.length===0&&<p className="mt-3">{t("저장된 검사 결과가 없습니다.")}</p>}<div className="mt-3 max-h-96 space-y-2 overflow-auto">{state?.results.map(row=><article key={row.job_id} className={`rounded border p-3 ${row.verdict==='REVIEW'?'border-amber-700':'border-slate-700'}`}><div className="flex flex-wrap justify-between gap-2"><span>{row.image_path.split(/[\\/]/).pop()} · {row.source}</span><b>{t("모델 ")}{row.model_verdict||t("진행 중")}{t(" · 운영 ")}{row.operator_review?.verdict||row.verdict||t("진행 중")}</b></div><p className="mt-1 text-xs text-slate-400">{row.state} · {row.created_at}</p><div className="mt-2 flex flex-wrap gap-2"><button type="button" disabled={busy||!permissions.can_review||['queued','running'].includes(row.state)} className={button} onClick={()=>{if(!current()||!permissionGate.current.can_review)return;setSelected(row.job_id);setReason('');setVerdict(row.operator_review?.verdict||'REVIEW');}}>{t("검수 열기")}</button>{row.state==='delivery_error'&&permissions.can_review&&<button type="button" disabled={busy} className={button} onClick={()=>void action(()=>request(`/api/product-delivery/operator/results/${encodeURIComponent(row.job_id)}/retry-delivery`,{method:'POST'}),t("전송 재시도 등록됨 · ACK 결과 확인 필요"),'can_review')}>{t("ACK 전송 재시도")}</button>}</div>{row.error&&<p role="alert" className="mt-2 text-amber-300">{row.error}</p>}{row.operator_review&&<p className="mt-2 text-xs text-slate-400">{t("검수 ")}{row.operator_review.reviewer} · {row.operator_review.reason}</p>}</article>)}</div></section>
  {reviewRow&&<fieldset disabled={busy||!permissions.can_review} className="rounded border border-amber-700 p-4"><legend>{t("검사 결과 검수 · 모델 ")}{reviewRow.model_verdict}</legend><div className="grid gap-3 md:grid-cols-3"><label>{t("운영자 판정")}<select aria-label={t("운영자 검수 판정")} value={verdict} onChange={e=>{if(current()&&permissionGate.current.can_review)setVerdict(e.target.value);}} className="mt-1 w-full rounded bg-slate-800 p-2"><option>REVIEW</option><option>NG</option><option>OK</option></select></label><label>{t("검토자")}<input aria-label={t("운영자 검토자")} value={reviewer} onChange={e=>{if(current()&&permissionGate.current.can_review)setReviewer(e.target.value);}} className="mt-1 w-full rounded bg-slate-800 p-2"/></label><label>{t("검수 근거")}<input aria-label={t("운영자 검수 근거")} value={reason} onChange={e=>{if(current()&&permissionGate.current.can_review)setReason(e.target.value);}} className="mt-1 w-full rounded bg-slate-800 p-2"/></label></div><button type="button" disabled={busy||!permissions.can_review||!reviewer.trim()||reason.trim().length<3} className={button+' mt-3'} onClick={()=>void action(()=>request(`/api/product-delivery/operator/results/${encodeURIComponent(selected)}/review`,{method:'POST',body:JSON.stringify({verdict,reviewer,reason})}),t("운영자 검수 기록 저장됨"),'can_review')}>{t("검수 기록 저장")}</button></fieldset>}
  <InspectionQueuePanel ready={state?.service.runtime.status==='ready'} canReview={permissions.can_review}/>
  {busy&&<p role="status" className="text-blue-300">{t("요청·실제 응답 확인 중…")}</p>}{notice&&<p role="status" className="text-emerald-300">{notice}</p>}{error&&<p role="alert" className="break-all text-red-300">{error}</p>}
 </section>;
}
