import {useEffect,useState,useRef} from 'react';
import {getProjectContextGeneration,request} from '../../services/api';
import {useDeliveryScope} from './useDeliveryScope';
import {useOperatorImageChoice} from './useOperatorImageChoice';
import {ImageSearchSelect} from '../common/ImageSearchSelect';
type OperatorResult={job_id:string;image_path:string;source:string;state:string;verdict:string|null;model_verdict:string|null;error?:string;created_at:string;operator_review?:{verdict:string;reviewer:string;reason:string}|null};
type OperatorState={permissions:{can_control:boolean;can_inspect:boolean;can_review:boolean;can_configure:boolean};project:{name:string;task:string};runtime_matches_active:boolean;input_health:{source_exists:boolean;manual_input:string;adapters:Record<string,unknown>;configuration:{mode:'manual'|'folder'|'camera';folder:string|null;camera:string|null;needs_reconfiguration?:boolean}};service:{runtime:{status:string;manifest_sha256?:string;pipeline_id?:string;device?:string};active:{deployment_id:string;release:{manifest_sha256:string}}|null};results:OperatorResult[]};
const button='rounded border border-slate-600 px-3 py-2 disabled:opacity-40';
export function OperatorWorkspace(){
 const {scope,key,project,projectDir}=useDeliveryScope(),[state,setState]=useState<OperatorState|null>(null),[selected,setSelected]=useState(''),[reviewer,setReviewer]=useState(''),[reason,setReason]=useState(''),[verdict,setVerdict]=useState('REVIEW'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const choice=useOperatorImageChoice({projectId:project?.id,projectDir,source:project?.source_dataset_dir||'',task:project?.task||'segmentation',labelset:project?.active_labelset_id,deliveryKey:key});
 const image=choice.path,generation=getProjectContextGeneration(),authority=useRef(choice.token);authority.current=choice.token;
 const current=()=>authority.current===choice.token&&getProjectContextGeneration()===generation;
 const [inputMode,setInputMode]=useState<'manual'|'folder'|'camera'>('manual'),[inputFolder,setInputFolder]=useState(''),[camera,setCamera]=useState('');const editingInputs=useRef(false);
 const refresh=async()=>{if(!current())return;const started=scope.current;const result=await request<OperatorState>('/api/product-delivery/operator');if(current()&&scope.current===started)setState(result);};
 useEffect(()=>{let live=true;const started=scope.current;setState(null);setSelected('');setReviewer('');setReason('');setError('');setNotice('');setBusy(false);setInputMode('manual');setInputFolder(project?.source_dataset_dir||'');setCamera('');editingInputs.current=false;
 const update=()=>request<OperatorState>('/api/product-delivery/operator').then(result=>{if(live&&current()&&scope.current===started){setState(result);if(!editingInputs.current){setInputMode(result.input_health.configuration.mode);setInputFolder(result.input_health.configuration.folder||project?.source_dataset_dir||'');setCamera(result.input_health.configuration.camera||'');}}}).catch(e=>{if(live&&current()&&scope.current===started)setError(String(e.message||e));});if(project){void update();}const timer=setInterval(()=>{if(live&&project)void update();},3000);return()=>{live=false;clearInterval(timer);};},[key,choice.token]);
 const action=async(fn:()=>Promise<unknown>,message:string)=>{if(!current())return;const started=scope.current;setBusy(true);setError('');setNotice('');try{await fn();if(current()&&scope.current===started){await refresh();if(current()&&scope.current===started)setNotice(message);}}catch(e){if(current()&&scope.current===started)setError(String((e as Error).message||e));}finally{if(current()&&scope.current===started)setBusy(false);}};
 const reviewRow=state?.results.find(row=>row.job_id===selected);
 const permissions=state?.permissions||{can_control:false,can_inspect:false,can_review:false,can_configure:false};
 const inspectionGate=useRef({canInspect:false,runtimeMatches:false});
 inspectionGate.current={canInspect:permissions.can_inspect,runtimeMatches:Boolean(state?.runtime_matches_active)};
 if(!project)return <p className="p-4 text-slate-400">검사할 프로젝트를 여세요.</p>;
 return <section aria-label="운영자 검사 작업 공간" className="space-y-4 p-4 text-sm text-slate-200"><header className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-semibold">운영자 검사</h2><p className="mt-1 text-slate-400">{project.name} · 현재 품목·저장 레시피·입력·판정을 확인합니다.</p></div><button type="button" disabled={busy} className={button} onClick={()=>void action(refresh,'실제 서비스 상태 확인됨')}>상태 확인</button></header>
  <div className="grid gap-3 md:grid-cols-3"><article className="rounded border border-slate-600 p-4"><h3 className="font-semibold">검사 서비스</h3><p className="mt-2">{state?.service.runtime.status==='ready'?'실행 응답 확인':state?.service.runtime.status==='stopped'?'중지됨':'상태 확인 필요'}</p><p className="mt-1 text-slate-400">{state?.runtime_matches_active?'승인 적용 기록과 실행 버전 일치':'승인 기록과 실행 버전 확인 필요'}</p><div className="mt-3 flex flex-wrap gap-2"><button type="button" disabled={busy||!permissions.can_control||!state?.service.active} className={button} onClick={()=>void action(()=>request('/api/runtime-services/start',{method:'POST'}),'검사 서비스 시작 응답 확인')}>검사 시작</button><button type="button" disabled={busy||!permissions.can_control||state?.service.runtime.status==='stopped'} className={button} onClick={()=>void action(()=>request('/api/runtime-services/stop',{method:'POST'}),'검사 서비스 중지 응답 확인')}>검사 중지</button></div></article><article className="rounded border border-slate-600 p-4"><h3 className="font-semibold">입력 상태</h3><p className="mt-2">원본 입력 폴더 {state?.input_health.source_exists?'확인':'사용 불가'}</p><p className="mt-1">수동 입력 {state?.input_health.manual_input==='available'?'준비됨':'서비스 준비 필요'}</p><details className="mt-2 text-slate-400"><summary>폴더·카메라·PLC 응답 상세</summary><pre className="mt-1 overflow-auto whitespace-pre-wrap text-xs">{JSON.stringify(state?.input_health.adapters||{},null,2)}</pre></details></article><article className="rounded border border-slate-600 p-4"><h3 className="font-semibold">현재 검사 레시피</h3><p className="mt-2 break-all">{state?.service.runtime.pipeline_id||'실행 레시피 없음'}</p><p className="mt-1">실행 장치 {state?.service.runtime.device||'—'}</p><details className="mt-2 text-slate-400"><summary>적용 버전·해시</summary><p className="mt-1 break-all font-mono text-xs">{state?.service.runtime.manifest_sha256||'실행 응답 없음'}</p><p className="text-xs">적용 {state?.service.active?.deployment_id||'—'}</p></details></article></div>
  <section className="rounded border border-slate-600 p-4"><h3 className="font-semibold">현재 레시피로 이미지 검사</h3><div className="mt-3 flex gap-2"><div className="min-w-0 flex-1"><ImageSearchSelect key={choice.token} label="운영자 검사 이미지" value={image} onChange={()=>{}} onIdentityChange={row=>choice.select(row)} onLegacyChange={path=>choice.selectLegacy(path)} disabled={busy||choice.phase!=='ready'} autoSelectFirst={false} folder={project?.source_dataset_dir} task={project?.task}/></div><button type="button" disabled={busy||!permissions.can_inspect||!choice.canInspect||!state?.runtime_matches_active} className={button} onClick={()=>{if(!choice.canInspect||!choice.isCurrent()||!permissions.can_inspect||!state?.runtime_matches_active)return;void action(async()=>{const image_path=await choice.verifyForInspect();if(!current())throw new Error('검사 문맥이 바뀌었습니다.');if(!inspectionGate.current.canInspect||!inspectionGate.current.runtimeMatches)throw new Error('검사 권한과 현재 실행 레시피 상태를 다시 확인하세요.');return request('/api/product-delivery/operator/inspect',{method:'POST',body:JSON.stringify({image_path})});},'검사 입력 등록됨 · 아래 결과에서 완료 상태 확인');}}>검사 입력</button></div>
   <div className="mt-2 flex flex-wrap gap-2"><button type="button" disabled={busy||choice.phase==='loading'} className={button} onClick={choice.refresh}>선택 다시 확인</button><button type="button" disabled={busy||!choice.storageKey} className={button} onClick={choice.clear}>선택 해제</button></div>
   {image&&<p className="mt-2 break-all text-slate-400">현재 선택: {choice.selection?.file_name||image.split(/[\\/]/).pop()} · {image}</p>}
   {choice.phase==='loading'&&<p role="status" className="mt-2 text-blue-300">선택한 이미지 확인 중…</p>}
   {choice.error&&<p role="alert" className="mt-2 break-all text-amber-300">{choice.error} 선택 다시 확인 또는 선택 해제를 사용하세요.</p>}
   {choice.phase==='ready'&&choice.status!=='empty'&&choice.status!=='found'&&<p role="alert" className="mt-2 text-amber-300">선택 이미지 {({changed:'내용 바뀜',moved:'옮겨짐',missing:'찾을 수 없음',unreadable:'읽지 못함'} as const)[choice.status]} · 검사를 진행하려면 이미지를 명시적으로 다시 선택하거나 선택 해제하세요.</p>}
   {choice.mode==='legacy'&&<p className="mt-2 text-amber-300">검증된 데이터 버전이 없어 경로만 저장합니다. 처음 64장 목록에서 다시 확인하며, 이미지 내용 변경은 확인할 수 없습니다.</p>}
  </section>
  <details className="rounded border border-slate-600 p-4"><summary className="cursor-pointer font-semibold">입력 연결 설정</summary><div className="mt-3 flex flex-wrap gap-2"><select aria-label="운영자 입력 방식" value={inputMode} disabled={busy} onChange={e=>{editingInputs.current=true;setInputMode(e.target.value as typeof inputMode);}} className="rounded bg-slate-800 p-2"><option value="manual">수동 이미지 입력</option><option value="folder">프로젝트 폴더 감시</option><option value="camera">카메라·RTSP</option></select>{inputMode==='folder'&&<input aria-label="운영자 감시 입력 폴더" value={inputFolder} onChange={e=>{editingInputs.current=true;setInputFolder(e.target.value);}} className="min-w-0 flex-1 rounded bg-slate-800 p-2"/>}{inputMode==='camera'&&<input aria-label="운영자 카메라 주소" autoComplete="off" value={camera} onChange={e=>{editingInputs.current=true;setCamera(e.target.value);}} placeholder="0 또는 rtsp://camera-address" className="min-w-0 flex-1 rounded bg-slate-800 p-2"/>}<button type="button" disabled={busy||!permissions.can_configure} className={button} onClick={()=>void action(async()=>{const started=scope.current;const result=await request<{restart_required:boolean}>('/api/product-delivery/operator/inputs',{method:'PUT',body:JSON.stringify({mode:inputMode,folder:inputFolder||null,camera:camera||null})});if(current()&&scope.current===started){editingInputs.current=false;setNotice(result.restart_required?'입력 설정 저장됨 · 명시적으로 서비스 중지 후 시작하여 적용':'입력 설정 저장됨 · 다음 서비스 시작에 적용');}},'입력 설정 저장됨 · 다음 서비스 시작에 적용')}>입력 설정 검증·저장</button></div><p className="mt-2 text-slate-400">감시 폴더는 현재 프로젝트 원본 안에서 선택합니다. 설정 저장과 실제 연결 응답을 구분하며, 서비스 재시작 후 위 입력 상태에서 확인합니다.</p>{state?.input_health.configuration.needs_reconfiguration&&<p className="mt-2 text-amber-300">프로젝트 소스가 변경됐습니다. 입력 설정을 다시 확인하세요.</p>}</details>
  <section className="rounded border border-slate-600 p-4"><h3 className="font-semibold">최근 검사와 REVIEW</h3><p className="mt-1 text-slate-400">모델 판정과 운영자 검수를 각각 보존합니다. REVIEW·오류·전송 실패는 정상 판정으로 바꾸지 않습니다.</p>{state?.results.length===0&&<p className="mt-3">저장된 검사 결과가 없습니다.</p>}<div className="mt-3 max-h-96 space-y-2 overflow-auto">{state?.results.map(row=><article key={row.job_id} className={`rounded border p-3 ${row.verdict==='REVIEW'?'border-amber-700':'border-slate-700'}`}><div className="flex flex-wrap justify-between gap-2"><span>{row.image_path.split(/[\\/]/).pop()} · {row.source}</span><b>모델 {row.model_verdict||'진행 중'} · 운영 {row.operator_review?.verdict||row.verdict||'진행 중'}</b></div><p className="mt-1 text-xs text-slate-400">{row.state} · {row.created_at}</p><div className="mt-2 flex flex-wrap gap-2"><button type="button" disabled={busy||!permissions.can_review||['queued','running'].includes(row.state)} className={button} onClick={()=>{if(!current())return;setSelected(row.job_id);setReason('');setVerdict(row.operator_review?.verdict||'REVIEW');}}>검수 열기</button>{row.state==='delivery_error'&&permissions.can_review&&<button type="button" disabled={busy} className={button} onClick={()=>void action(()=>request(`/api/product-delivery/operator/results/${encodeURIComponent(row.job_id)}/retry-delivery`,{method:'POST'}),'전송 재시도 등록됨 · ACK 결과 확인 필요')}>ACK 전송 재시도</button>}</div>{row.error&&<p role="alert" className="mt-2 text-amber-300">{row.error}</p>}{row.operator_review&&<p className="mt-2 text-xs text-slate-400">검수 {row.operator_review.reviewer} · {row.operator_review.reason}</p>}</article>)}</div></section>
  {reviewRow&&<fieldset className="rounded border border-amber-700 p-4"><legend>검사 결과 검수 · 모델 {reviewRow.model_verdict}</legend><div className="grid gap-3 md:grid-cols-3"><label>운영자 판정<select aria-label="운영자 검수 판정" value={verdict} onChange={e=>setVerdict(e.target.value)} className="mt-1 w-full rounded bg-slate-800 p-2"><option>REVIEW</option><option>NG</option><option>OK</option></select></label><label>검토자<input aria-label="운영자 검토자" value={reviewer} onChange={e=>setReviewer(e.target.value)} className="mt-1 w-full rounded bg-slate-800 p-2"/></label><label>검수 근거<input aria-label="운영자 검수 근거" value={reason} onChange={e=>setReason(e.target.value)} className="mt-1 w-full rounded bg-slate-800 p-2"/></label></div><button type="button" disabled={busy||!permissions.can_review||!reviewer.trim()||reason.trim().length<3} className={button+' mt-3'} onClick={()=>void action(()=>request(`/api/product-delivery/operator/results/${encodeURIComponent(selected)}/review`,{method:'POST',body:JSON.stringify({verdict,reviewer,reason})}),'운영자 검수 기록 저장됨')}>검수 기록 저장</button></fieldset>}
  {busy&&<p role="status" className="text-blue-300">요청·실제 응답 확인 중…</p>}{notice&&<p role="status" className="text-emerald-300">{notice}</p>}{error&&<p role="alert" className="break-all text-red-300">{error}</p>}
 </section>;
}
