const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),ts=require('typescript'),test=require('node:test');
const settle=()=>new Promise(setImmediate);
function load(file,mocks){const name=path.resolve(__dirname,file),m=new Module(name,module);m.filename=name;m.paths=Module._nodeModulePaths(path.dirname(name));const original=m.require.bind(m);m.require=ref=>mocks[ref]??original(ref);m._compile(ts.transpileModule(fs.readFileSync(name,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText,name);return m.exports;}
function fixture(){
 let cursor=0,language='ko';const slots=[],effects=[],data=new Map(),requests=[];
 const react={useState:initial=>{const i=cursor++;if(!(i in slots))slots[i]=typeof initial==='function'?initial():initial;return[slots[i],value=>slots[i]=typeof value==='function'?value(slots[i]):value];},useRef:initial=>{const i=cursor++;return slots[i]??(slots[i]={current:initial});},useEffect:(fn,deps)=>{const i=cursor++;if(!slots[i]||deps.some((v,j)=>v!==slots[i].deps[j])){slots[i]?.cleanup?.();slots[i]={deps};effects.push(()=>slots[i].cleanup=fn());}}};
 const jsx=(type,props)=>({type,props:props||{}}),ImageSearchSelect=()=>null;
 const project={id:'p',name:'Synthetic',source_dataset_dir:'/s',task:'segmentation',active_labelset_id:'labels'};
 const scope={current:{key:'d'}};let generation=0,subscriber,authority={workspace_id:'w',project_id:'p',actor_id:'a',mode:'local'};
 const state={permissions:{can_control:true,can_inspect:true,can_review:true,can_configure:true},runtime_matches_active:true,input_health:{source_exists:true,manual_input:'available',adapters:{},configuration:{mode:'manual',folder:null,camera:null}},service:{runtime:{status:'ready',pipeline_id:'recipe'},active:{deployment_id:'active',release:{manifest_sha256:'a'.repeat(64)}}},results:[]};
 const api={library:{resolve:async saved=>({results:saved.map(row=>({...row,status:'found',current:{...row,valid:1},candidates:[]}))})},dataset:{getImages:async()=>({items:[]})}};
 const services={api,request:async(url,options)=>{requests.push({url,options});return state;},getProjectContext:()=>authority,getProjectContextGeneration:()=>generation,getApiPersistenceIdentity:()=> 'local',subscribeProjectContext:fn=>{subscriber=fn;return()=>{};}};
 const mocks={'./OperationsObservabilityPanel':{OperationsObservabilityPanel:()=>null},'./InspectionQueuePanel':{InspectionQueuePanel:()=>null},'./operatorCopy':load('operatorCopy.ts',{}),'../../stores/useProjectStore':{useProjectStore:select=>select({language})},react,'react/jsx-runtime':{jsx,jsxs:jsx},'../../services/api':services,'./useDeliveryScope':{useDeliveryScope:()=>({scope,key:scope.current.key,project,projectDir:'/project'})},'../common/ImageSearchSelect':{ImageSearchSelect}};
 if(fs.existsSync(path.resolve(__dirname,'useOperatorImageChoice.ts')))mocks['./useOperatorImageChoice']=load('useOperatorImageChoice.ts',mocks);
 const component=load('OperatorWorkspace.tsx',mocks).OperatorWorkspace;
 const oldDocument=global.document;global.document={addEventListener(){},removeEventListener(){}};
 const oldStorage=Object.getOwnPropertyDescriptor(global,'localStorage'),oldInterval=global.setInterval,oldClear=global.clearInterval;
 Object.defineProperty(global,'localStorage',{configurable:true,value:{getItem:key=>data.get(key)??null,setItem:(key,value)=>data.set(key,value)}});global.setInterval=()=>1;global.clearInterval=()=>{};
 const nodes=tree=>!tree||typeof tree!=='object'?[]:[tree,...[tree.props.children].flat(Infinity).flatMap(nodes)];
 const key='modu:operator-image:v1:["local","w","a","p","/project","/s","segmentation","labels"]';
 const choice={image_uuid:'a',sha256:'a'.repeat(64),relative_path:'ok/a.png',file_name:'a.png',file_path:'/s/ok/a.png',valid:true};
 return{language:next=>{language=next;},api,services,state,requests,data,key,choice,render:()=>{cursor=0;const tree=component();effects.splice(0).forEach(fn=>fn());return tree;},nodes,selector:tree=>nodes(tree).find(n=>n.type===ImageSearchSelect),button:(tree,text)=>nodes(tree).find(n=>n.type==='button'&&n.props.children===text),authority:()=>{authority={...authority,actor_id:'b'};generation++;subscriber?.(authority);},close:()=>{global.document=oldDocument;global.setInterval=oldInterval;global.clearInterval=oldClear;if(oldStorage)Object.defineProperty(global,'localStorage',oldStorage);else delete global.localStorage;}};
}
test('operator requires explicit identity choice and retains runtime/permission gate without automatic inspect',async()=>{const f=fixture();try{let tree=f.render();await settle();tree=f.render();assert.equal(f.selector(tree).props.autoSelectFirst,false);assert.equal(f.button(tree,'검사 입력').props.disabled,true);assert.equal(typeof f.selector(tree).props.onIdentityChange,'function');await f.selector(tree).props.onIdentityChange(f.choice);await settle();tree=f.render();assert.equal(f.button(tree,'검사 입력').props.disabled,false);assert.equal(f.requests.filter(r=>r.url.endsWith('/inspect')).length,0);f.state.permissions.can_inspect=false;assert.equal(f.button(f.render(),'검사 입력').props.disabled,true);f.state.permissions.can_inspect=true;f.state.runtime_matches_active=false;assert.equal(f.button(f.render(),'검사 입력').props.disabled,true);f.state.runtime_matches_active=true;f.button(f.render(),'검사 입력').props.onClick();await settle();assert.deepEqual(JSON.parse(f.requests.find(r=>r.url.endsWith('/inspect')).options.body),{image_path:'/s/ok/a.png'});}finally{f.close();}});
test('changed saved identity stays visibly selected with blocked inspect and explicit clear controls',async()=>{const f=fixture();try{f.data.set(f.key,JSON.stringify(f.choice));f.api.library.resolve=async saved=>({results:saved.map(row=>({...row,status:'changed',current:{...row,valid:1,sha256:'b'.repeat(64)},candidates:[]}))});f.render();await settle();const tree=f.render();assert.equal(f.selector(tree).props.value,'/s/ok/a.png');assert.equal(f.button(tree,'검사 입력').props.disabled,true);assert.ok(f.button(tree,'선택 해제'));assert.ok(f.button(tree,'선택 다시 확인'));assert.ok(f.nodes(tree).some(n=>n.props.role==='alert'));assert.equal(f.requests.filter(r=>r.url.endsWith('/inspect')).length,0);}finally{f.close();}});
test('callbacks from earlier authority cannot inspect or change the new selection',async()=>{const f=fixture();try{f.data.set(f.key,JSON.stringify(f.choice));f.render();await settle();const old=f.render();assert.equal(f.button(old,'검사 입력').props.disabled,false);f.authority();f.render();f.button(old,'검사 입력').props.onClick();await f.selector(old).props.onIdentityChange({...f.choice,image_uuid:'old'});await settle();assert.equal(f.requests.filter(r=>r.url.endsWith('/inspect')).length,0);assert.equal(f.selector(f.render()).props.value,'');assert.equal(JSON.parse(f.data.get(f.key)).image_uuid,'a');}finally{f.close();}});

test('a late final health response cannot publish the old action notice in a new authority',async()=>{const f=fixture();try{f.render();await settle();const tree=f.render(),pending=[];f.services.request=async()=>new Promise(resolve=>pending.push(resolve));f.button(tree,'상태 확인').props.onClick();await settle();pending[0](f.state);await settle();assert.equal(pending.length,2);f.authority();f.render();pending[1](f.state);await settle();assert.ok(!f.nodes(f.render()).some(n=>n.props.children==='실제 서비스 상태 확인됨'));}finally{f.close();}});

test('a delayed identity check cannot inspect after runtime or permission readiness is withdrawn',async()=>{for(const gate of ['runtime','permission']){const f=fixture();try{f.data.set(f.key,JSON.stringify(f.choice));f.render();await settle();let tree=f.render();assert.equal(f.button(tree,'검사 입력').props.disabled,false);let answer;f.api.library.resolve=saved=>new Promise(resolve=>{answer=()=>resolve({results:saved.map(row=>({...row,status:'found',current:{...row,valid:1},candidates:[]}))});});f.button(tree,'검사 입력').props.onClick();await settle();if(gate==='runtime')f.state.runtime_matches_active=false;else f.state.permissions.can_inspect=false;tree=f.render();assert.equal(f.button(tree,'검사 입력').props.disabled,true);answer();await settle();assert.equal(f.requests.filter(r=>r.url.endsWith('/inspect')).length,0);}finally{f.close();}}});

 test('configuration restart guidance is kept after the final health refresh',async()=>{const f=fixture();try{f.render();await settle();const tree=f.render();const original=f.services.request;f.services.request=async(url,options)=>url.endsWith('/inputs')?(f.requests.push({url,options}),{restart_required:true}):original(url,options);f.button(tree,'입력 설정 검증·저장').props.onClick();await settle();assert.ok(f.nodes(f.render()).some(n=>n.props.children==='입력 설정 저장됨 · 명시적으로 서비스 중지 후 시작하여 적용'));}finally{f.close();}});
 test('withdrawn permissions refuse retained control, input and review callbacks',async()=>{const f=fixture();try{f.state.results=[{job_id:'j',image_path:'/s/a.png',source:'manual',state:'completed',verdict:'REVIEW',model_verdict:'NG',created_at:'now'}];f.render();await settle();let tree=f.render();f.button(tree,'검수 열기').props.onClick();tree=f.render();const fields=f.nodes(tree);fields.find(n=>n.props['aria-label']==='운영자 검토자').props.onChange({target:{value:'Operator'}});fields.find(n=>n.props['aria-label']==='운영자 검수 근거').props.onChange({target:{value:'Fixture review'}});const old=f.render();Object.keys(f.state.permissions).forEach(k=>f.state.permissions[k]=false);tree=f.render();const mode=f.nodes(tree).find(n=>n.props['aria-label']==='운영자 입력 방식');assert.equal(mode.props.disabled,true);for(const text of ['검사 시작','검사 중지','입력 설정 검증·저장','검수 기록 저장'])f.button(old,text).props.onClick();await settle();assert.equal(f.requests.filter(r=>r.options?.method).length,0);}finally{f.close();}});

test('operator language changes without losing the current input choice',async()=>{const f=fixture();try{f.render();await settle();let tree=f.render();await f.selector(tree).props.onIdentityChange(f.choice);await settle();f.language('en');tree=f.render();assert.ok(f.button(tree,'Submit inspection'));assert.equal(f.selector(tree).props.value,'/s/ok/a.png');assert.ok(f.nodes(tree).some(n=>n.props.children==='Recent inspections and REVIEW'));f.language('ko');assert.ok(f.button(f.render(),'검사 입력'));assert.equal(f.requests.filter(r=>r.options?.method).length,0);}finally{f.close();}});
