import type {WorkflowStep} from '../wizard/workflowReadiness';
import {useEffect,useState} from 'react';
import {api} from '../../services/api';
import {host} from '../../services/hostAdapter';
import {productDeliveryApi,type HardwareState,type InstallationState} from '../../services/productDeliveryApi';
import {PackageLibraryPanel} from '../inference/PackageLibraryPanel';
import {RuntimeOptimizationPanel} from '../inference/RuntimeOptimizationPanel';
import {RuntimeServicePanel} from './RuntimeServicePanel';
import {OperatorWorkspace} from './OperatorWorkspace';
import {useDeliveryScope} from './useDeliveryScope';
import {deviceStateLabel} from './deliveryContracts';
import {DistributionSettingsPanel} from './DistributionSettingsPanel';
import {ProjectCompatibilityPanel} from './ProjectCompatibilityPanel';
import {RuntimePackPanel} from './RuntimePackPanel';
const button='rounded border border-slate-600 px-3 py-2 disabled:opacity-40';
export function ProductDeliveryWorkspace({onNavigate}:{onNavigate?:(step:WorkflowStep)=>void}={}){
 const {scope,key,project,projectDir}=useDeliveryScope();const [tab,setTab]=useState('packages'),[optimization,setOptimization]=useState(''),[deployment,setDeployment]=useState(''),[hardware,setHardware]=useState<HardwareState[]>([]),[install,setInstall]=useState<InstallationState|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [diagnosticSections,setDiagnosticSections]=useState<Array<'installation'|'packages'|'hardware'|'operator_errors'>>(['installation','packages','hardware','operator_errors']);
 const refresh=async()=>{const started=scope.current;const [devices,environment]=await Promise.all([productDeliveryApi.hardware(),productDeliveryApi.installation()]);if(scope.current===started){setHardware(devices.devices);setInstall(environment);}};
 useEffect(()=>{let live=true;const started=scope.current;setOptimization('');setDeployment('');setInstall(null);setHardware([]);setError('');setNotice('');setBusy(false);if(project)Promise.all([productDeliveryApi.hardware(),productDeliveryApi.installation()]).then(([h,i])=>{if(live&&scope.current===started){setHardware(h.devices);setInstall(i);}}).catch(e=>{if(live&&scope.current===started)setError(String(e.message||e));});return()=>{live=false;};},[key]);
 const action=async(fn:()=>Promise<void>)=>{const started=scope.current;setBusy(true);setError('');try{await fn();}catch(e){if(scope.current===started)setError(String((e as Error).message||e));}finally{if(scope.current===started)setBusy(false);}};
 if(!project||!projectDir)return <p className="p-4 text-slate-400">프로젝트를 열면 패키지·운영·설치 준비를 확인할 수 있습니다.</p>;
 return <section aria-label="제품 배포와 운영 작업 공간" className="p-4 text-sm text-slate-200"><header><h2 className="text-xl font-semibold">배포·운영</h2><p className="mt-1 text-slate-400">저장한 패키지, 실제 실행 장치, 운영 판정과 설치 준비를 연결합니다.</p></header><nav aria-label="배포 운영 화면" className="my-4 flex flex-wrap gap-2">{[['packages','패키지·배포'],['operator','운영자 검사'],['hardware','장치 검증'],['installation','설치·진단']].map(([id,label])=><button type="button" key={id} onClick={()=>setTab(id)} aria-pressed={tab===id} className={button+(tab===id?' bg-blue-900':'')}>{label}</button>)}</nav>
  {tab==='packages'&&<><PackageLibraryPanel sourceFolder={project.source_dataset_dir||''} task={project.task} onOptimize={row=>{setOptimization(row.package_path);setDeployment('');}} onDeploy={row=>{setDeployment(row.package_path);setOptimization('');}}/>{optimization&&project.source_dataset_dir&&<RuntimeOptimizationPanel key={optimization} packagePath={optimization} sourceFolder={project.source_dataset_dir} task={project.task}/>}<RuntimeServicePanel onNavigate={onNavigate} key={deployment||'runtime'} projectDir={projectDir} initialPackagePath={deployment}/></>}
  {tab==='operator'&&<OperatorWorkspace/>}
  {tab==='hardware'&&<section className="rounded border border-slate-600 p-4"><div className="flex justify-between gap-2"><h3 className="font-semibold">실제 장치 검증표</h3><button type="button" disabled={busy} onClick={()=>void action(refresh)} className={button}>실행 기록 새로고침</button></div><p className="my-3 text-slate-400">설정 가능, 이 프로젝트의 실제 입력 실행, 현재 승인 적용을 구분합니다. 패키지 보관함의 이미지 검사로 실행 기록을 남깁니다.</p><div className="overflow-auto"><table className="w-full text-left"><thead><tr><th className="p-2">장치</th><th className="p-2">상태</th><th className="p-2">실행 기록</th></tr></thead><tbody>{hardware.map(row=><tr key={row.device} className="border-t border-slate-700"><td className="p-2">{row.device}</td><td className="p-2">{deviceStateLabel(row)}</td><td className="p-2">{row.evidence.length?`${row.evidence.length}회 · ${new Date(row.evidence.at(-1)!.observed_at*1000).toLocaleString()}`:'대상 장치 실행 필요'}<details className="mt-1 text-xs text-slate-400"><summary>패키지·입력 해시</summary>{row.evidence.map((entry,index)=><p key={index} className="break-all">{entry.manifest_sha256} · 입력 {entry.image_sha256} · {entry.verdict}</p>)}</details></td></tr>)}</tbody></table></div><p className="mt-3 text-amber-200">MIG·NPU·Edge 보드는 실제 대상에서 실행 기록을 확보해야 합니다. 다른 장치의 CPU 시험을 대신 사용하지 않습니다.</p></section>}
  {tab==='installation'&&<section className="space-y-4 rounded border border-slate-600 p-4"><h3 className="font-semibold">설치·프로젝트 호환성</h3><DistributionSettingsPanel/><ProjectCompatibilityPanel key={key}/><RuntimePackPanel key={key}/>{!install?<p role="status">실행 환경 확인 중…</p>:<><p>실행 백엔드 {install.app_version||'버전 확인 필요'} · {install.host.os} {install.host.architecture} · Python {install.host.python}</p><p className={install.project.compatible?'text-emerald-300':'text-red-300'}>프로젝트 schema {install.project.schema_version} · {install.project.compatible?'이 앱에서 열기 가능':'이 버전에서 열기 지원 안 됨'} · {install.project.migration_performed?'구형 형식 변환·원본 백업 기록 있음':'현재 형식 확인'}</p><p>Python 버전 {install.python_supported?'지원':'호환 환경 필요'} · 필수 패키지 {Object.entries(install.runtime_dependencies).filter(([,value])=>!value).map(([name])=>name).join(', ')||'확인됨'}</p><fieldset className="rounded border border-slate-700 p-3"><legend>SDK 설치 준비</legend>{Object.entries(install.sdk).map(([name,value])=><p key={name} className="py-1">{name} · {value.ready?'현재 환경 준비 확인':'필수 환경 준비 필요'}{value.requires_embedded_python?' · CPython 실행 환경·개발 헤더·대상 아키텍처 의존성 필요':''}{name==='C#'?' · .NET 및 동일 C ABI 라이브러리 필요':''}</p>)}<p className="mt-2 text-slate-400">C++·C#은 Python을 포함하는 브리지입니다. 클라이언트 HTTP 방식은 별도 인터페이스입니다.</p></fieldset><fieldset className="rounded border border-slate-700 p-3"><legend>버전 변경 준비</legend>{install.update.actions.map(value=><p key={value} className="mt-1">{value==='Export a project archive before changing app versions'?'앱 버전을 변경하기 전에 프로젝트 백업을 저장하세요.':'프로젝트 형식과 실행 의존성을 확인한 뒤 다시 여세요.'}</p>)}<div className="mt-3 flex flex-wrap gap-2"><button type="button" disabled={busy} className={button} onClick={()=>void action(async()=>{const started=scope.current;const destination=await host.selectFolder({title:'프로젝트 백업 저장 위치'});if(!destination||scope.current!==started)return;const result=await api.project.backup(destination);if(scope.current===started)setNotice('프로젝트 백업 저장됨 · '+result.archive_path);})}>버전 변경 전 백업</button><button type="button" disabled={busy} className={button} onClick={()=>void action(refresh)}>호환성 다시 확인</button></div><p className="mt-2 text-slate-400">데스크톱 배포 상태와 실행 백엔드 호환성은 위의 각 검사 결과를 확인하세요. 공유 서버에 연결한 경우 실행 백엔드는 서버 환경입니다.</p></fieldset></>}
   <fieldset className="rounded border border-slate-700 p-3"><legend>문제 보고 자료</legend><div className="my-3 flex flex-wrap gap-3">{([['installation','버전·의존성'],['packages','패키지'],['hardware','장치 실행'],['operator_errors','검사·오류']] as const).map(([id,label])=><label key={id} className="flex gap-2"><input type="checkbox" disabled={busy} checked={diagnosticSections.includes(id)} onChange={e=>setDiagnosticSections(previous=>e.target.checked?[...previous,id]:previous.filter(value=>value!==id))}/>{label}</label>)}</div><p className="text-slate-400">버전·패키지 ID·실행 상태·오류 종류를 저장합니다. 원본 이미지·인증값·개인 파일 경로는 포함하지 않습니다.</p><button type="button" disabled={busy||diagnosticSections.length===0} className={button+' mt-3'} onClick={()=>void action(async()=>{const started=scope.current;const result=await productDeliveryApi.diagnostics(diagnosticSections);if(scope.current!==started)return;const link=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(result.bundle,null,2)],{type:'application/json'}));link.href=url;link.download=result.filename;link.click();URL.revokeObjectURL(url);setNotice('비식별 진단 JSON 저장 요청 완료');})}>진단 자료 저장</button></fieldset>
  </section>}
  {notice&&<p role="status" className="mt-3 text-emerald-300">{notice}</p>}{error&&<p role="alert" className="mt-3 break-all text-red-300">{error}</p>}
 </section>;
}
