import {useRef,useState} from 'react';
import {productDeliveryApi,type MigrationPreview} from '../../services/productDeliveryApi';
import {host} from '../../services/hostAdapter';
const button='rounded border border-slate-600 px-3 py-2 disabled:opacity-40';
export function ProjectCompatibilityPanel(){
 const [directory,setDirectory]=useState(''),[preview,setPreview]=useState<MigrationPreview|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const generation=useRef(0);const [globalPreview,setGlobalPreview]=useState<{inventory:{file_count:number;byte_count:number};blockers:string[];ownership_policy:string}|null>(null);
 const action=async(operation:(started:number)=>Promise<void>)=>{const started=++generation.current;setBusy(true);setError('');try{await operation(started);}catch(cause){if(generation.current===started)setError(String((cause as Error).message||cause));}finally{if(generation.current===started)setBusy(false);}};
 return <fieldset className="space-y-3 rounded border border-slate-700 p-3"><legend>다른 프로젝트 열기 전 형식 검사</legend><p className="text-slate-400">미래 버전은 파일을 바꾸지 않고 차단합니다. 구형 매니페스트 변환은 전체 프로젝트·원본 데이터의 개수·해시를 확인하고 백업·복구 기록을 먼저 남깁니다. 실행 중인 작업·불확실한 예약은 먼저 정리해야 합니다. 외부 프로그램의 파일 쓰기는 지원하지 않습니다.</p>
 <button type="button" className={button} disabled={busy} onClick={()=>void action(async started=>{const selected=await host.selectFolder({title:'project.json이 있는 프로젝트'});if(!selected||generation.current!==started)return;setDirectory(selected);setPreview(null);const result=await productDeliveryApi.previewMigration(selected);if(generation.current===started)setPreview(result);})}>프로젝트 선택·검사</button>
 {preview&&<><p>형식 {preview.schema_version??'구형 · schema 없음'} → 지원 형식 {preview.current_schema_version} · {preview.migration_required?'백업 후 변환 필요':'현재 형식 확인됨'}</p><button type="button" className={button} disabled={busy||!preview.migration_required||preview.can_apply===false} onClick={()=>void action(async started=>{const result=await productDeliveryApi.applyMigration(directory,preview.manifest_sha256,preview.source_snapshot?.sha256);if(generation.current===started)setPreview(result);})}>원본 백업·형식 변환</button>{preview.backup_relative_path&&<p role="status">변환 완료 · 전체 백업 검증·변환 기록 보관됨</p>}{preview.inventory&&<p>검사 파일 {preview.inventory.file_count}개 · {preview.inventory.byte_count} bytes</p>}{preview.blockers?.map((message,index)=><p role="alert" key={index}>{message}</p>)}{preview.transactions?.map(transaction=><article key={transaction.migration_id}><p>{transaction.status} · 백업 {transaction.backup_file_count}개</p><button type="button" className={button} disabled={busy||!transaction.can_restore} onClick={()=>void action(async started=>{const result=await productDeliveryApi.recoverMigration(directory,transaction.migration_id,"restore");if(generation.current===started)setPreview(result);})}>이 변환의 원본 복구</button>{transaction.status==="prepared"&&<button type="button" className={button} disabled={busy||!transaction.can_restore} onClick={()=>void action(async started=>{const result=await productDeliveryApi.recoverMigration(directory,transaction.migration_id,"finish");if(generation.current===started)setPreview(result);})}>중단된 변환 검증·완료</button>}<p className="text-slate-400">변환 뒤 파일 쓰기가 발생하면 오래된 백업 복구를 거부합니다.</p></article>)}<details className="break-all text-xs text-slate-400"><summary>프로젝트·변환 기록</summary><p>{directory}</p><p>{preview.manifest_sha256}</p><p>{preview.backup_relative_path}</p></details></>}
 <button type="button" className={button} disabled={busy} onClick={()=>void action(async started=>{const result=await productDeliveryApi.globalMigration();if(generation.current===started)setGlobalPreview(result);})}>설치 전역 저장소 읽기 전용 검사</button>{globalPreview&&<section><p>전역 파일 {globalPreview.inventory.file_count}개 · {globalPreview.inventory.byte_count} bytes</p><p>전역 활성화는 지원하지 않습니다. 복사된 토큰·예약을 실행 권한으로 사용하지 않습니다.</p>{globalPreview.blockers.map((message,index)=><p role="status" key={index}>{message}</p>)}</section>}
 {busy&&<p role="status">프로젝트 형식 확인 중…</p>}{error&&<p role="alert" className="break-all text-red-300">{error}</p>}
 </fieldset>;
}
