import {useState} from 'react';
import {adapterFormFromConfig,adapterConfigFromForm,type AdapterConfig,type AdapterForm} from './deliveryContracts';
import {productDeliveryApi} from '../../services/productDeliveryApi';
import {useDeliveryScope} from './useDeliveryScope';

export function ProtocolSettingsPanel({value,onChange,disabled,onSave}:{value:string;onChange:(value:string)=>void;disabled:boolean;onSave:()=>void}){
 const {scope}=useDeliveryScope();const [busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState(''),[mode,setMode]=useState<'success'|'reject'|'timeout'>('success');
 let config:AdapterConfig|null=null,form:AdapterForm|null=null;try{config=JSON.parse(value);form=adapterFormFromConfig(config!);}catch{/* Advanced JSON remains editable while malformed. */}
 const change=(key:keyof AdapterForm,next:string|boolean)=>{try{if(!form||!config)return;onChange(JSON.stringify(adapterConfigFromForm({...form,[key]:next},config),null,2));setError('');}catch(e){setError(String((e as Error).message||e));}};
 const input=(label:string,key:keyof AdapterForm)=><label className="block">{label}<input aria-label={label} disabled={disabled||busy} className="mt-1 w-full rounded bg-slate-800 p-2" value={String(form?.[key]??'')} onChange={e=>change(key,e.target.value)}/></label>;
 const test=async(protocol:'http'|'modbus')=>{const started=scope.current;setBusy(true);setNotice('');setError('');try{const result=await productDeliveryApi.protocol(protocol,mode);if(scope.current===started)setNotice(`${protocol==='http'?'HTTP':'Modbus'} 로컬 ${mode} 시험: ${result.acknowledged?'ACK 확인':'ACK 실패 확인'} · ${result.error||'계약 응답 정상'} · 실제 장비 검증 아님`);}catch(e){if(scope.current===started)setError(String((e as Error).message||e));}finally{if(scope.current===started)setBusy(false);}};
 return <details className="mt-3 rounded border border-slate-600 p-3"><summary className="cursor-pointer font-semibold">PLC·MES 연결 설정과 로컬 시험</summary><p className="my-2 text-slate-400">설정 저장 후 서비스를 명시적으로 다시 시작해야 적용됩니다. 로컬 시험은 새 loopback 수신기와 실제 어댑터만 사용합니다.</p>
  {form&&<div className="space-y-3"><label className="flex gap-2"><input type="checkbox" disabled={disabled||busy} checked={form.enabled} onChange={e=>change('enabled',e.target.checked)}/>현장 결과 전송 사용</label><label className="flex gap-2"><input type="checkbox" disabled={disabled||busy} checked={form.modbusEnabled} onChange={e=>change('modbusEnabled',e.target.checked)}/>Modbus TCP 사용</label>{form.modbusEnabled&&<div className="grid grid-cols-2 gap-2">{input('PLC 호스트','host')}{input('PLC 포트','port')}{input('Unit ID','unit')}{input('결과 레지스터','resultRegister')}{input('ACK 레지스터','ackRegister')}{input('순번 레지스터 (선택)','sequenceRegister')}{input('PLC 응답 제한 (초)','timeout')}{input('ACK 제한 (초)','ackTimeout')}</div>}<label className="flex gap-2"><input type="checkbox" disabled={disabled||busy} checked={form.mesEnabled} onChange={e=>change('mesEnabled',e.target.checked)}/>HTTP MES 사용</label>{form.mesEnabled&&<div className="grid grid-cols-2 gap-2">{input('MES HTTP 주소','mesUrl')}{input('HTTP 제한 (초)','mesTimeout')}<label className="col-span-2">새 MES 인증값 (비우면 저장값 유지)<input type="password" autoComplete="off" disabled={disabled||busy} className="mt-1 w-full rounded bg-slate-800 p-2" value={String(config?.mes?.token||'')} onChange={e=>{if(config)onChange(JSON.stringify({...config,mes:{...config.mes,token:e.target.value||null}},null,2));}}/></label><label className="col-span-2 flex gap-2"><input type="checkbox" disabled={disabled||busy} checked={form.clearToken} onChange={e=>change('clearToken',e.target.checked)}/>저장된 인증값 삭제</label></div>}</div>}
  <details className="mt-3"><summary className="cursor-pointer text-slate-400">고급 JSON · 필드/판정/ACK 매핑</summary><textarea aria-label="PLC MES 고급 설정 JSON" rows={12} disabled={disabled||busy} className="mt-2 w-full rounded bg-slate-800 p-2 font-mono text-xs" value={value} onChange={e=>onChange(e.target.value)}/></details><button type="button" disabled={disabled||busy||!config} onClick={onSave} className="mt-2 rounded bg-blue-700 px-3 py-2 disabled:opacity-40">설정 검증·저장</button>
  <fieldset className="mt-3 rounded border border-slate-700 p-3"><legend>실장비 없는 로컬 계약 시험</legend><div className="flex flex-wrap gap-2"><select aria-label="프로토콜 로컬 시험 종류" value={mode} onChange={e=>setMode(e.target.value as typeof mode)} disabled={busy} className="rounded bg-slate-800 p-2"><option value="success">정상 ACK</option><option value="reject">ACK 거부</option><option value="timeout">응답 시간 초과</option></select><button type="button" disabled={busy} onClick={()=>void test('modbus')} className="rounded border border-slate-600 px-3 py-2">Modbus 로컬 시험</button><button type="button" disabled={busy} onClick={()=>void test('http')} className="rounded border border-slate-600 px-3 py-2">HTTP 로컬 시험</button></div><p className="mt-2 text-slate-500">현장 주소에 데이터를 보내지 않습니다. 기본 어댑터의 ACK 동작을 확인하며 저장한 장비 매핑 검증은 별도입니다.</p></fieldset>
  {notice&&<p role="status" className="mt-2 text-cyan-200">{notice}</p>}{error&&<p role="alert" className="mt-2 text-red-300">{error}</p>}
 </details>;
}
