const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),ts=require('typescript');
const jsx=(type,props)=>({type,props:props||{},children:[props?.children].flat().filter(Boolean)});
const nodes=t=>t&&typeof t==='object'?[t,...(t.children||[]).flat().flatMap(nodes)]:[];
function fixture(){let cursor=0,generation=1,key='owned',subscriber;const slots=[],effects=[],calls=[],changes=[];
 const react={useState:v=>{const i=cursor++;if(!(i in slots))slots[i]=typeof v==='function'?v():v;return[slots[i],v=>slots[i]=typeof v==='function'?v(slots[i]):v];},useRef:v=>{const i=cursor++;return slots[i]??(slots[i]={current:v});},useEffect:(fn,deps)=>{const i=cursor++;if(!slots[i]||deps.some((v,j)=>v!==slots[i].deps[j])){slots[i]?.cleanup?.();slots[i]={deps};effects.push(()=>slots[i].cleanup=fn());}}};
 let protocol=async()=>({acknowledged:true});const props={value:'{"enabled":false,"modbus":null,"mes":null}',disabled:false,onChange:v=>changes.push(v),onSave:()=>calls.push('save')};
 const mocks={'react':react,'react/jsx-runtime':{jsx,jsxs:jsx},'./useDeliveryScope':{useDeliveryScope:()=>({key,scope:{current:key}})},'../../services/api':{getProjectContextGeneration:()=>generation,subscribeProjectContext:fn=>{subscriber=fn;return()=>{};}},'../../services/productDeliveryApi':{productDeliveryApi:{protocol:(...args)=>{calls.push(args);return protocol();}}}};
 const contract=path.resolve(__dirname,'deliveryContracts.ts'),cm=new Module(contract,module);cm.filename=contract;cm.paths=Module._nodeModulePaths(__dirname);cm._compile(ts.transpileModule(fs.readFileSync(contract,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,contract);mocks['./deliveryContracts']=cm.exports;
 const file=path.resolve(__dirname,'ProtocolSettingsPanel.tsx'),m=new Module(file,module);m.filename=file;m.paths=Module._nodeModulePaths(__dirname);m.require=id=>mocks[id]||require(id);m._compile(ts.transpileModule(process.env.MV_PROTOCOL_BASE?require('node:child_process').execFileSync('git',['show','HEAD:src/renderer/components/runtime/ProtocolSettingsPanel.tsx'],{encoding:'utf8'}):fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText,file);
 const render=()=>{cursor=0;const tree=m.exports.ProtocolSettingsPanel(props);effects.splice(0).forEach(fn=>fn());return tree;};
 return{props,calls,changes,render,button:(t,label)=>nodes(t).find(n=>n.type==='button'&&n.children.includes(label)),switchAccount:()=>{generation++;subscriber?.();},switchProject:()=>{key='other';generation++;subscriber?.();},setProtocol:fn=>protocol=fn,close:()=>slots.forEach(s=>s?.cleanup?.())};
}
test('retained protocol controls refuse save, edit and requests after disabling',async()=>{const f=fixture();try{const t=f.render(),save=f.button(t,'설정 검증·저장'),run=f.button(t,'HTTP 로컬 시험'),edit=nodes(t).find(n=>n.props['aria-label']==='PLC MES 고급 설정 JSON');f.props.disabled=true;f.render();save.props.onClick();edit.props.onChange({target:{value:'{}'}});await run.props.onClick();assert.deepEqual(f.calls,[]);assert.deepEqual(f.changes,[]);}finally{f.close();}});
test('retained protocol callbacks refuse old account and changed configuration',async()=>{const f=fixture();try{let t=f.render(),save=f.button(t,'설정 검증·저장');f.props.value='{"enabled":true,"modbus":null,"mes":null}';f.render();save.props.onClick();assert.deepEqual(f.calls,[]);t=f.render();const old=f.button(t,'HTTP 로컬 시험');f.switchAccount();await old.props.onClick();assert.deepEqual(f.calls,[]);}finally{f.close();}});
test('late protocol reply cannot expose the prior project result',async()=>{const f=fixture();try{let resolve;f.setProtocol(()=>new Promise(done=>resolve=done));const t=f.render();f.button(t,'HTTP 로컬 시험').props.onClick();f.render();f.switchProject();f.render();resolve({acknowledged:true});await new Promise(setImmediate);assert.equal(nodes(f.render()).filter(n=>n.props.role==='status').length,0);}finally{f.close();}});
