import {useEffect,useState} from 'react';
import {productDeliveryApi,type SavedPackage} from '../../services/productDeliveryApi';
import {useDeliveryScope} from './useDeliveryScope';
import {useTaskHandoff} from '../training/useTaskHandoff';
export function SavedPackagePicker({value,onChange,disabled=false}:{value:string;onChange:(value:string)=>void;disabled?:boolean}){
 const {scope,key}=useDeliveryScope();const [rows,setRows]=useState<SavedPackage[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const handoff=useTaskHandoff();const requestedPackage=handoff?.kind==='export'?handoff.jobId:undefined;
 useEffect(()=>{let live=true;const started=scope.current;setRows([]);setError('');productDeliveryApi.packages().then(async r=>{if(!live||scope.current!==started)return;setRows(r.packages);const id=requestedPackage||(!value?r.selected_package_id:null);if(id){const target=r.packages.find(row=>row.package_id===id);if(!target)throw new Error(`선택한 패키지 ${id}을 보관함에서 찾지 못했습니다.`);if(target.integrity!=='verified'||!target.scope_matches)throw new Error('선택한 패키지의 무결성·소스 연결을 확인하세요.');const reopened=await productDeliveryApi.select(id);if(live&&scope.current===started)onChange(reopened.package_path);}}).catch(e=>{if(live&&scope.current===started)setError(String(e.message||e));});return()=>{live=false;};},[key,requestedPackage,handoff?.taskKey,handoff?.selectionId]);
 return <div className="col-span-2"><label>보관함 패키지<select aria-label="배포할 저장 패키지" value={rows.find(r=>r.package_path===value)?.package_id||''} disabled={disabled||busy} className="mt-1 w-full rounded bg-slate-800 p-2" onChange={e=>{const id=e.target.value;if(!id){onChange('');return;}const started=scope.current;setBusy(true);setError('');productDeliveryApi.select(id).then(r=>{if(scope.current===started)onChange(r.package_path);}).catch(error=>{if(scope.current===started)setError(String(error.message||error));}).finally(()=>{if(scope.current===started)setBusy(false);});}}><option value="">저장된 패키지 선택</option>{rows.map(row=><option key={row.package_id} value={row.package_id} disabled={row.integrity!=='verified'||!row.scope_matches}>{row.name} · {row.approval_present?'승인 포함':'모델 승인 필요'}{!row.scope_matches?' · 소스 확인 필요':''}</option>)}</select></label>{error&&<p role="alert" className="mt-1 text-red-300">{error}</p>}</div>;
}
