const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),ts=require('typescript'),test=require('node:test');
function load(file,mocks={}){const name=path.resolve(__dirname,file);if(!fs.existsSync(name))return {};const m=new Module(name,module);m.filename=name;m.paths=Module._nodeModulePaths(path.dirname(name));const req=m.require.bind(m);m.require=ref=>mocks[ref]??req(ref);m._compile(ts.transpileModule(fs.readFileSync(name,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText,name);return m.exports;}
function harness(){let cursor=0;const slots=[],effects=[];return {react:{useState:initial=>{const i=cursor++;if(!(i in slots))slots[i]=typeof initial==='function'?initial():initial;return [slots[i],v=>slots[i]=typeof v==='function'?v(slots[i]):v];},useRef:initial=>{const i=cursor++;return slots[i]??(slots[i]={current:initial});},useEffect:(fn,deps)=>{const i=cursor++;if(!slots[i]||deps.some((v,j)=>v!==slots[i].deps[j])){slots[i]?.cleanup?.();slots[i]={deps};effects.push(()=>slots[i].cleanup=fn());}}},render:fn=>{cursor=0;const r=fn();effects.splice(0).forEach(fn=>fn());return r;}};}
const settle=()=>new Promise(setImmediate);
const image=(id='a',sha='a'.repeat(64))=>({image_uuid:id,sha256:sha,relative_path:`ok/${id}.png`,file_name:`${id}.png`,file_path:`/s/ok/${id}.png`,valid:true,size:1,width:1,height:1,label:null,split:null,error_code:null,error_detail:null,annotation_labels:[],annotation_error:null,tags:[],product:null,lot:null,workflow_state:'unworked',usage_state:'active'});
const pick=(row=image())=>({image_uuid:row.image_uuid,sha256:row.sha256,relative_path:row.relative_path,file_name:row.file_name,file_path:row.file_path});
const found=saved=>({results:saved.map(row=>({...row,status:'found',current:{...row,valid:1},candidates:[]}))});
function fixture(resolve=async saved=>found(saved),listing=async()=>({items:[image()]})){
 const h=harness(),data=new Map(),writes=[];let context={workspace_id:'w',project_id:'p',actor_id:'a',mode:'local'},generation=0,subscriber,backend='local';
 const args={projectId:'p',projectDir:'/project',source:'/s',task:'segmentation',labelset:'default',deliveryKey:'d'};
 const api={library:{resolve},dataset:{getImages:listing}};
 const m=load('useOperatorImageChoice.ts',{react:h.react,'../../services/api':{api,getApiPersistenceIdentity:()=>backend,getProjectContext:()=>context,getProjectContextGeneration:()=>generation,subscribeProjectContext:fn=>{subscriber=fn;return()=>{};}}});
 assert.equal(typeof m.useOperatorImageChoice,'function','operator selection persistence hook is required');
 const old=Object.getOwnPropertyDescriptor(global,'localStorage');Object.defineProperty(global,'localStorage',{configurable:true,value:{getItem:key=>data.get(key)??null,setItem:(key,value)=>{data.set(key,value);writes.push([key,value]);}}});
 const key='modu:operator-image:v1:["local","w","a","p","/project","/s","segmentation","default"]';
 return {render:()=>h.render(()=>m.useOperatorImageChoice(args)),args,data,writes,key,api,authority:actor=>{context={...context,actor_id:actor};generation++;subscriber?.(context);},transport:()=>{backend='shared:https://example.test';context=null;generation++;subscriber?.(context);},close:()=>{if(old)Object.defineProperty(global,'localStorage',old);else delete global.localStorage;}};
}
test('reopening resolves one stored identity without auto selecting or rewriting bytes',async()=>{
 const f=fixture();try{f.data.set(f.key,JSON.stringify(pick()));assert.equal(f.render().canInspect,false);await settle();const state=f.render();assert.equal(state.canInspect,true);assert.equal(state.path,'/s/ok/a.png');assert.equal(f.writes.length,0);assert.equal(state.storageKey,f.key);}finally{f.close();}
});
test('empty selection remains empty until an explicit valid hashed image choice',async()=>{
 const f=fixture();try{f.render();await settle();let state=f.render();assert.equal(state.path,'');assert.equal(state.canInspect,false);await state.select(image('b'));state=f.render();assert.equal(state.path,'/s/ok/b.png');assert.equal(state.canInspect,true);assert.equal(JSON.parse(f.data.get(f.key)).image_uuid,'b');await state.select({...image('c'),sha256:null});assert.equal(f.render().path,'/s/ok/b.png');await state.select({...image('c'),valid:false});assert.equal(f.render().path,'/s/ok/b.png');}finally{f.close();}
});
for(const status of ['changed','missing','moved','unreadable'])test(`${status} identity stays visible and blocks inspection until explicit reselection`,async()=>{
 const f=fixture(async saved=>({results:saved.map(row=>({...row,status,current:status==='missing'?null:{...row,sha256:'b'.repeat(64),valid:status==='unreadable'?0:1},candidates:[]}))}));try{const raw=JSON.stringify(pick());f.data.set(f.key,raw);f.render();await settle();const state=f.render();assert.equal(state.path,'/s/ok/a.png');assert.equal(state.status,status);assert.equal(state.canInspect,false);assert.equal(f.data.get(f.key),raw);f.api.library.resolve=async saved=>found(saved);await state.select(image('b'));assert.equal(f.render().canInspect,true);assert.equal(f.render().path,'/s/ok/b.png');}finally{f.close();}
});
test('inconsistent found response cannot approve changed hash, moved path, unreadable or mismatched UUID',async()=>{
 for(const mutation of [{sha256:'b'.repeat(64)},{file_path:'/s/moved.png'},{relative_path:'new/a.png'},{valid:0},{image_uuid:'other'}]){const f=fixture(async saved=>({results:saved.map(row=>({...row,status:'found',current:{...row,valid:1,...mutation},candidates:[]}))}));try{f.data.set(f.key,JSON.stringify(pick()));f.render();await settle();assert.equal(f.render().canInspect,false);assert.equal(f.render().path,'/s/ok/a.png');}finally{f.close();}}
});
test('network failure retains selected path and original storage, retry revalidates it',async()=>{
 const f=fixture();try{const raw=JSON.stringify(pick());f.data.set(f.key,raw);f.api.library.resolve=async()=>{throw new Error('offline');};f.render();await settle();let state=f.render();assert.equal(state.path,'/s/ok/a.png');assert.equal(state.canInspect,false);assert.match(state.error,/offline/);assert.equal(f.data.get(f.key),raw);f.api.library.resolve=async saved=>found(saved);state.refresh();f.render();await settle();assert.equal(f.render().canInspect,true);assert.equal(f.writes.length,0);}finally{f.close();}
});
test('invalid storage survives retry and explicit clear is persisted as empty',async()=>{
 for(const raw of ['', '{broken','[]',JSON.stringify({...pick(),sha256:null}),JSON.stringify({...pick(),file_path:''})]){const f=fixture();try{f.data.set(f.key,raw);f.render();await settle();let state=f.render();assert.equal(state.canInspect,false);assert.equal(state.phase,'failed');assert.equal(f.data.get(f.key),raw);assert.equal(f.writes.length,0);state.refresh();f.render();await settle();assert.equal(f.data.get(f.key),raw);state=f.render();state.clear();f.render();assert.equal(f.data.get(f.key),'null');assert.equal(f.data.get(f.key+':path'),'null');f.render().refresh();f.render();await settle();assert.equal(f.render().path,'');assert.equal(f.render().canInspect,false);}finally{f.close();}}
});
test('legacy paths use separate storage, revalidate in listing and never replace missing with first image',async()=>{
 const f=fixture(async()=>{throw Object.assign(new Error('no index'),{status:409});});try{f.data.set(f.key+':path',JSON.stringify('/s/missing.png'));f.render();await settle();let state=f.render();assert.equal(state.mode,'legacy');assert.equal(state.path,'/s/missing.png');assert.equal(state.canInspect,false);assert.equal(state.status,'missing');await state.selectLegacy('/s/ok/a.png');state=f.render();assert.equal(state.canInspect,true);assert.equal(f.data.get(f.key),'null');assert.equal(f.data.get(f.key+':path'),'"/s/ok/a.png"');state.clear();f.render().refresh();f.render();await settle();assert.equal(f.render().path,'');assert.equal(f.render().canInspect,false);}finally{f.close();}
});
test('legacy listing network errors and invalid path storage preserve bytes and block inspection',async()=>{
 for(const raw of ['{broken','[]','"/s/ok/a.png"']){const f=fixture(async()=>{throw Object.assign(new Error('no index'),{status:409});},async()=>{throw new Error('listing offline');});try{f.data.set(f.key+':path',raw);f.render();await settle();assert.equal(f.render().canInspect,false);assert.equal(f.render().phase,'failed');assert.equal(f.data.get(f.key+':path'),raw);assert.equal(f.writes.length,0);}finally{f.close();}}
});
test('late response and callbacks cannot cross actor, transport, source or refresh boundaries',async()=>{
 for(const [change,visiblePath] of [[f=>f.authority('b'),''],[f=>f.transport(),''],[f=>{f.args.source='/other';f.args.deliveryKey='other';},''],[f=>f.render().refresh(),'/s/ok/a.png']]){const pending=[];const f=fixture(saved=>new Promise(resolve=>pending.push({saved,resolve})));try{f.data.set(f.key,JSON.stringify(pick()));const old=f.render();change(f);f.render();pending[0].resolve(found(pending[0].saved));await settle();assert.equal(f.render().canInspect,false);const before=f.data.get(f.key);await old.select(image('old'));old.clear();assert.equal(f.data.get(f.key),before);assert.equal(f.render().path,visiblePath);pending[1].resolve(found(pending[1].saved));await settle();assert.notEqual(f.render().path,'/s/ok/old.png');}finally{f.close();}}
});
test('explicit clear during a pending resolve prevents a late response from restoring selection',async()=>{
 const pending=[];const f=fixture(saved=>new Promise(resolve=>pending.push({saved,resolve})));try{f.data.set(f.key,JSON.stringify(pick()));f.render();f.render().clear();pending[0].resolve(found(pending[0].saved));await settle();assert.equal(f.render().path,'');assert.equal(f.render().canInspect,false);assert.equal(f.data.get(f.key),'null');}finally{f.close();}
});
test('all namespace fields isolate saved choices',async()=>{
 for(const field of ['projectId','projectDir','source','task','labelset']){const f=fixture();try{f.data.set(f.key,JSON.stringify(pick()));f.render();await settle();assert.equal(f.render().canInspect,true);f.args[field]='other';f.render();await settle();assert.equal(f.render().path,'');assert.equal(f.render().canInspect,false);assert.equal(JSON.parse(f.data.get(f.key)).image_uuid,'a');}finally{f.close();}}
});
test('clear while initial revision detection is pending still permits explicit legacy selection',async()=>{
 let reject;const f=fixture(()=>new Promise((_,r)=>{reject=r;}));try{f.render();f.api.library.resolve=async()=>{throw Object.assign(new Error('no index'),{status:409});};f.render().clear();f.render();reject(Object.assign(new Error('no index'),{status:409}));await settle();f.render();await settle();let state=f.render();assert.equal(state.mode,'legacy');assert.equal(state.path,'');await state.selectLegacy('/s/ok/a.png');assert.equal(f.render().canInspect,true);}finally{f.close();}
});
test('inspection revalidates legacy listing and rejects a disappeared selected path',async()=>{
 const f=fixture(async()=>{throw Object.assign(new Error('no index'),{status:409});});try{f.data.set(f.key+':path','"/s/ok/a.png"');f.render();await settle();let state=f.render();assert.equal(state.canInspect,true);f.api.dataset.getImages=async()=>({items:[{file_path:'/s/other.png'}]});await assert.rejects(()=>state.verifyForInspect(),/이미지/);state=f.render();assert.equal(state.canInspect,false);assert.equal(state.path,'/s/ok/a.png');assert.equal(f.data.get(f.key+':path'),'"/s/ok/a.png"');}finally{f.close();}
});
test('loss of accepted index keeps stored identity visible but never downgrades it silently to executable path',async()=>{
 const f=fixture(async()=>{throw Object.assign(new Error('no index'),{status:409});});try{const raw=JSON.stringify(pick());f.data.set(f.key,raw);f.render();await settle();let state=f.render();assert.equal(state.path,'/s/ok/a.png');assert.equal(state.canInspect,false);assert.equal(state.mode,'legacy');assert.equal(state.selection.image_uuid,'a');assert.equal(f.data.get(f.key),raw);await state.selectLegacy('/s/ok/a.png');state=f.render();assert.equal(state.canInspect,true);assert.equal(state.selection,null);assert.equal(f.data.get(f.key+':path'),'"/s/ok/a.png"');}finally{f.close();}
});
test('latest indexed identity dominates both stale legacy path and prior legacy clear on lost index',async()=>{
 for(const raw of ['"/s/ok/a.png"','null']){const f=fixture(async()=>{throw Object.assign(new Error('no index'),{status:409});},async()=>({items:[image('a'),image('b')]}));try{const saved=JSON.stringify(pick(image('b')));f.data.set(f.key,saved);f.data.set(f.key+':path',raw);f.render();await settle();let state=f.render();assert.equal(state.path,'/s/ok/b.png');assert.equal(state.selection.image_uuid,'b');assert.equal(state.canInspect,false);assert.equal(f.data.get(f.key),saved);assert.equal(f.data.get(f.key+':path'),raw);await state.selectLegacy('/s/ok/a.png');state=f.render();assert.equal(state.canInspect,true);assert.equal(f.data.get(f.key),'null');state.refresh();f.render();await settle();assert.equal(f.render().path,'/s/ok/a.png');assert.equal(f.render().canInspect,true);}finally{f.close();}}
});
test('failed explicit legacy revalidation cannot retire indexed identity',async()=>{
 const f=fixture(async()=>{throw Object.assign(new Error('no index'),{status:409});},async()=>({items:[image('a')]}));try{const raw=JSON.stringify(pick(image('b')));f.data.set(f.key,raw);f.render();await settle();await f.render().selectLegacy('/s/ok/missing.png');assert.equal(f.render().canInspect,false);assert.equal(f.data.get(f.key),raw);assert.equal(f.data.get(f.key+':path'),undefined);}finally{f.close();}
});
test('malformed resolver results block restoration and explicit selection without overwriting prior bytes',async()=>{
 const mutations=[()=>({results:[{...pick(image('b')),status:'unexpected'}]}),()=>({results:[]}),()=>({results:[{...pick(image('b')),status:'missing',current:null,candidates:[]},{...pick(image('b')),status:'missing',current:null,candidates:[]}]}),()=>({results:[{...pick(image('b')),status:'missing',current:null,candidates:[]},{...pick(image('extra')),status:'missing',current:null,candidates:[]}]}),()=>({results:{}}),()=>({results:[{...pick(image('b')),status:'found',current:{...pick(image('b')),valid:1,sha256:null},candidates:[]}]}),()=>({results:[{...pick(image('b')),status:'found',current:{...pick(image('b')),valid:1,file_path:''},candidates:[]}]}),()=>({results:[{...pick(image('b')),status:'found',current:{...pick(image('b')),valid:'yes'},candidates:[]}]}),()=>({results:[{...pick(image('b')),status:'found',current:{...pick(image('b')),valid:1},candidates:null}]})];
 for(const mutate of mutations){const f=fixture();try{const raw=JSON.stringify(pick());f.data.set(f.key,raw);f.render();await settle();const state=f.render();assert.equal(state.canInspect,true);f.api.library.resolve=async()=>mutate();await state.select(image('b'));const failed=f.render();assert.equal(failed.phase,'failed');assert.equal(failed.canInspect,false);assert.ok(failed.error);assert.equal(f.data.get(f.key),raw);failed.refresh();f.render();await settle();assert.equal(f.render().phase,'failed');assert.equal(f.data.get(f.key),raw);}finally{f.close();}}
});
