import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {execFileSync} from 'node:child_process';
import type {Page} from '@playwright/test';import {test,expect,type Workspace,type Evidence} from './fixtures/test';
const harness=require('./fixtures/harness.cjs');type Api=(route:string,body?:any)=>Promise<any>;test.use({actionTimeout:10_000});
async function exercise(page:Page,workspace:Workspace,evidence:Evidence,api:Api,url?:string){
 const helper=path.join(harness.REPO_ROOT,'scripts/e2e/fixtures/anomaly_calibration_data.py');
 const fixture=JSON.parse(execFileSync(harness.resolvePython(),[helper,workspace.root],{encoding:'utf8',timeout:15_000}));
 await api('/api/project/create',{name:'Independent normal calibration across three anomaly methods',task:'anomaly'});await api('/api/project/update',{source_dataset_dir:fixture.source});const project=await api('/api/project/current');await api('/api/dataset/import',{folder_path:fixture.source,task:'anomaly'});
 const split=JSON.parse(execFileSync(harness.resolvePython(),[helper,workspace.root,JSON.stringify(project)],{encoding:'utf8',timeout:15_000}));
 if(url)await page.goto(url);else await page.reload();await expect(page.getByTitle('프로젝트 관리',{exact:true})).toContainText(project.name);
 const stage=(i:number)=>page.getByRole('navigation',{name:'Workflow Stages'}).getByRole('button').nth(i).click();const models=[];
 for(const method of ['padim','patchcore','dino_synthetic']){
  await stage(2);if(method==='dino_synthetic')await page.getByLabel('이상탐지 검사 목적',{exact:true}).selectOption('region');await page.getByLabel('학습 모델 구조',{exact:true}).selectOption(method);
  const synthetic=method==='dino_synthetic',weights=fixture[synthetic?'dino_weights':'resnet_weights'],hash=fixture[synthetic?'dino_sha256':'resnet_sha256'];
  await expect(page.getByLabel('이상탐지 검사 목적',{exact:true})).toHaveValue('image');
  if(synthetic){await expect(page.getByLabel('이상탐지 검사 목적',{exact:true}).locator('option[value="region"]')).toHaveAttribute('disabled','');await page.getByLabel('합성 결함 학습 횟수',{exact:true}).fill('2');await page.getByLabel('원본 패치 크기',{exact:true}).fill('32');await page.getByLabel('패치 간격',{exact:true}).fill('32');await page.getByLabel('원본당 학습 패치 수',{exact:true}).fill('2');await page.getByLabel('추론 배치 크기',{exact:true}).fill('4');}
  else{await page.getByLabel('이상탐지 검사 목적',{exact:true}).selectOption('region');await page.getByLabel('이상탐지 입력 크기',{exact:true}).fill('64');}
  const weightDetails=page.locator('details').filter({has:page.locator('summary').filter({hasText:'사전학습 파일 가져오기 · 상세 설정'})});if(await weightDetails.getAttribute('open')===null)await weightDetails.locator('summary').click();await page.getByLabel('사전학습 가중치 파일',{exact:true}).fill(weights);
  const deviceDetails=page.locator('details').filter({has:page.locator('summary').filter({hasText:'다음 학습 배치·로컬 장치 설정'})});if(await deviceDetails.getAttribute('open')===null)await deviceDetails.locator('summary').click();await page.getByLabel('다음 학습 배치 크기',{exact:true}).fill('2');await page.getByLabel('다음 학습 로컬 장치',{exact:true}).selectOption('cpu');
  let waiting=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/training-workspace/readiness'&&r.request().method()==='POST');await page.getByRole('button',{name:'로컬 준비 검사',exact:true}).click();let response=await waiting;expect(response.ok(),await response.text()).toBe(true);const ready=await response.json();expect(ready.ready).toBe(true);expect(ready.weights.sha256).toBe(hash);
  const budget=page.locator('details').filter({has:page.locator('summary').filter({hasText:'학습 실행 예산·대기열'})});if(await budget.getAttribute('open')===null)await budget.locator('summary').click();await page.getByLabel('학습 시간 제한 (분)',{exact:true}).fill('2');
  waiting=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/training/start'&&r.request().method()==='POST');await page.getByRole('button',{name:'선택 설정으로 학습 시작',exact:true}).click();response=await waiting;expect(response.ok(),await response.text()).toBe(true);const posted=response.request().postDataJSON(),accepted=await response.json(),jobId=accepted.job_id;expect(posted.config_overrides.anomaly_method).toBe(method);expect(posted.config_overrides.anomaly_mode).toBe(synthetic?'classification':'segmentation');expect(posted.device).toBe('cpu');if(synthetic)expect(posted.config_overrides.epochs).toBe(2);
  let terminal:any;await expect.poll(async()=>{terminal=await api('/api/training/status?job_id='+jobId);if(['failed','cancelled','aborted'].includes(terminal.status))throw Error(JSON.stringify(terminal));return terminal.status;},{timeout:125_000}).toBe('completed');await expect(page.getByRole('region',{name:'학습 로그'})).toContainText('완료',{timeout:20_000});
  const metadata=JSON.parse(fs.readFileSync(path.join(project.models_dir,jobId,'model_meta.json'),'utf8'));expect(metadata.pretrained_sha256).toBe(hash);expect(metadata.calibration).toMatchObject({split:'val',normal_image_count:2,quality_approved:false,population_fpr_verified:false});expect(metadata.map_semantics).toBe(synthetic?'patch_score':'pixel_score');expect(metadata.score_spec.domain).toBe(synthetic?'probability':'distance');
  waiting=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/evaluation/results'&&r.request().method()==='GET');await stage(3);response=await waiting;expect(response.ok(),await response.text()).toBe(true);const evaluated=await response.json();expect(evaluated.job_id).toBe(jobId);expect(evaluated.metrics).toMatchObject({evaluated_split:'test',calibration_content_separation_verified:true,calibration_overlap:false,threshold_basis:'heldout_normal_calibration',active_threshold:metadata.anomaly_threshold});expect(evaluated.test_predictions).toHaveLength(3);expect(evaluated.metrics.calibration).toEqual(metadata.calibration);if(!synthetic){expect(evaluated.metrics.pixel_missing_masks).toBe(0);expect(evaluated.metrics.pixel_evaluated_images).toBe(3);}
  await expect(page.getByText('임계값 보정: 별도 검증 정상 이미지 · 정상 2장',{exact:false})).toBeVisible();await expect(page.getByRole('button',{name:'평가 임계값 적용',exact:true})).toBeDisabled();await evidence.screenshot(page,method+'-fixed-heldout-calibration');
  await stage(4);await page.getByRole('button',{name:'단일 모델 검사 원본 이미지 → 모델 → 최종 판정',exact:true}).click();const dialog=page.getByRole('dialog',{name:'레시피 미리보기·모델 매핑',exact:true});await expect(dialog).toBeVisible();await dialog.getByLabel('검사 모델 레시피 모델',{exact:true}).selectOption(jobId);await dialog.getByLabel('검사 모델 클래스 적용 범위',{exact:true}).selectOption('all');await dialog.getByRole('button',{name:'매핑 확인·새 초안으로 채택',exact:true}).click();await expect(dialog).toHaveCount(0);
  await page.getByRole('button',{name:'플로우 저장',exact:true}).click();const save=page.getByRole('dialog',{name:'검사 규칙 변경 저장',exact:true});await expect(save).toBeVisible();await save.getByLabel('변경 사유',{exact:true}).fill(method+' independent validation-normal calibration candidate');waiting=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/flowchart/pipeline'&&r.request().method()==='POST');await save.getByRole('button',{name:'변경 저장',exact:true}).click();response=await waiting;expect(response.ok(),await response.text()).toBe(true);const saved=await response.json();
  await page.reload();await stage(4);await expect(page.getByText('모델 1/1 연결',{exact:true})).toBeVisible();await evidence.screenshot(page,method+'-calibrated-recipe-reopened');const reopened=await api('/api/flowchart/pipeline/active?source_dataset_path='+encodeURIComponent(fixture.source)),pipeline=reopened.pipeline||reopened;const inspection=pipeline.nodes.find((n:any)=>n.data.node_type==='inspection');expect(inspection.data).toMatchObject({model_job_id:jobId,threshold:metadata.anomaly_threshold,score_spec:metadata.score_spec});
  const source=fixture.files.find((f:any)=>f.split==='test'&&f.label==='defect').path;const flow=await api('/api/flowchart/run',{image_path:source,pipeline,execution_target:'local',device:'cpu'});expect(['OK','NG']).toContain(flow.final_verdict);expect(flow.crops).toHaveLength(1);expect(flow.crops[0].score_spec).toEqual(metadata.score_spec);expect(flow.crops[0].score_spec.threshold).toBe(metadata.anomaly_threshold);
  const offline=JSON.parse(execFileSync(harness.resolvePython(),[path.join(harness.REPO_ROOT,'scripts/e2e/fixtures/anomaly_package_readback.py')],{input:JSON.stringify({project_dir:project.project_dir,job_id:jobId,method,pipeline,flow_result:flow,source}),encoding:'utf8',timeout:70_000,maxBuffer:8*1024*1024}));expect(offline.comparison.status).toBe('passed');
  models.push({method,ready,posted,terminal,metadata,jobId,evaluated,saved,reopened,pipeline,source,flow,offline});
 }
 for(const file of fixture.files){expect(crypto.createHash('sha256').update(fs.readFileSync(file.path)).digest('hex')).toBe(file.sha256);evidence.addFile(file.path);if(file.mask){expect(crypto.createHash('sha256').update(fs.readFileSync(file.mask)).digest('hex')).toBe(file.mask_sha256);evidence.addFile(file.mask);}}evidence.addFile(split.split_path);
 evidence.note('anomaly_calibration_qualification',{fixture,project,split,models,actual_app_button_training:true,actual_cached_pretrained:true,actual_cpu:true,actual_independent_calibration:true,actual_heldout_fixed_threshold:true,actual_purpose_guard:true,actual_reopen:true,actual_fresh_candidate_package:true,no_original_mutation:true,gpu_verified:false,quality_approval:false});
}
test('all anomaly methods learn from normals fix val calibration evaluate test reopen and export',{tag:'@owned-model'},async({page,request,renderer,workspace,evidence})=>{test.setTimeout(480_000);const api:Api=async(route,body)=>{const r=body===undefined?await request.get(renderer.origin+route):route.endsWith('/update')?await request.put(renderer.origin+route,{data:body}):await request.post(renderer.origin+route,{data:body});expect(r.ok(),await r.text()).toBe(true);return r.json();};await exercise(page,workspace,evidence,api,renderer.url);});
test('native all anomaly methods preserve independent calibration through heldout and offline recipes',{tag:['@electron','@owned-model']},async({electronSession,workspace,evidence})=>{test.setTimeout(480_000);const {window}=electronSession;const backend=await electronSession.waitForBackend();const api:Api=(route,body)=>window.evaluate(async({port,route,body})=>{const r=await fetch(`http://127.0.0.1:${port}${route}`,{...(body===undefined?{}:{method:route.endsWith('/update')?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})});if(!r.ok)throw Error(`Owned API ${r.status}: ${await r.text()}`);return r.json();},{port:backend.port,route,body});await exercise(window,workspace,evidence,api);});
