import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {execFileSync} from 'node:child_process';
import type {Page,Route} from '@playwright/test';
import {test,expect,type Workspace,type Evidence} from './fixtures/test';
import {installDesktopHostShim} from './fixtures/desktop-host-shim';
const harness=require('./fixtures/harness.cjs');
type Api=(route:string,body?:any,method?:string)=>Promise<any>;
const sha=(file:string)=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
test.use({actionTimeout:10_000});

async function exercise(page:Page,workspace:Workspace,evidence:Evidence,api:Api,url?:string){
 const name='Completed model flag controls',tool=path.join(harness.REPO_ROOT,'scripts/e2e/fixtures/derived_workflow_data.py');
 const seed=(project?:any)=>JSON.parse(execFileSync(harness.resolvePython(),[tool,workspace.root,...(project?[JSON.stringify(project)]:[])],{encoding:'utf8',timeout:15_000}));
 const fixture=seed();await api('/api/project/create',{name,task:'classification'});const project=await api('/api/project/update',{source_dataset_dir:fixture.source},'PUT');await api('/api/dataset/import',{folder_path:fixture.source,task:'classification'});const split=seed(project);
 const jobs:any[]=[],models:Record<string,Record<string,string>>={};
 for(let index=0;index<2;index++){
  const accepted=await api('/api/training/start',{task:'classification',preset:'fast',dataset_path:fixture.source,device:'cpu',queue:false,max_runtime_s:90,config_overrides:{backbone:'resnet18',pretrained:false,epochs:2,image_size:64,batch_size:4,num_workers:0,learning_rate:.001,seed:71+index}});
  let terminal:any;await expect.poll(async()=>{terminal=await api('/api/training/status?job_id='+accepted.job_id);if(['failed','cancelled'].includes(terminal.status))throw Error(JSON.stringify(terminal));return terminal.status;},{timeout:95_000}).toBe('completed');
  const root=path.join(project.models_dir,accepted.job_id);expect(fs.existsSync(root)).toBe(true);models[accepted.job_id]={};for(const file of ['best_model.pt','model_meta.json','job_receipt.json']){const target=path.join(root,file);expect(fs.existsSync(target)).toBe(true);models[accepted.job_id][file]=sha(target);evidence.addFile(target);}jobs.push({accepted,terminal});
 }
 const first=jobs[0].accepted.job_id,second=jobs[1].accepted.job_id,catalog=await api('/api/flowchart/models/catalog?source_dataset_path='+encodeURIComponent(fixture.source));expect(catalog.models.map((m:any)=>m.job_id)).toContain(first);expect(catalog.models.map((m:any)=>m.job_id)).toContain(second);
 const stage=(index:number)=>page.getByRole('navigation',{name:'Workflow Stages'}).getByRole('button').nth(index).click();
 const reload=async(index:number)=>{if(url)await page.goto(url);else await page.reload();await expect(page.getByTitle('프로젝트 관리',{exact:true})).toContainText(name);await stage(index);};
 await reload(1);await page.getByRole('button',{name:'이미지 정보·검토',exact:true}).click();await page.getByRole('region',{name:'이미지 정보와 검토 기록'}).getByLabel('작업자·검토자 이름').fill('fixture-model-organizer');await stage(0);
 const toggle=()=>page.getByRole('button',{name:'태그 색상·플래그',exact:true}).click(),panel=page.getByRole('region',{name:'프로젝트 태그 색상과 모델 플래그'}),select=panel.getByLabel('플래그를 지정할 모델'),flags=panel.getByLabel('모델 사용자 플래그'),save=panel.getByRole('button',{name:'저장',exact:true}).nth(2),prefFile=path.join(project.project_dir,'preferences.json');
 let posts=0,deployments=0;page.on('request',r=>{const u=new URL(r.url());if(r.method()==='POST'&&u.pathname==='/api/training/start')posts++;if(r.method()!=='GET'&&u.pathname.startsWith('/api/model-deployments'))deployments++;});
 const apply=async(status=200)=>{const event=page.waitForResponse(r=>r.request().method()==='PATCH'&&new URL(r.url()).pathname==='/api/project/preferences');await save.click();const r=await event;expect(r.status(),await r.text()).toBe(status);return r.json();};
 await toggle();await expect(select).toBeEnabled();await expect(select).toHaveValue('');await expect(save).toBeDisabled();await flags.fill('Important');await expect(save).toBeDisabled();expect(fs.existsSync(prefFile)).toBe(false);
 await select.selectOption(first);await expect(flags).toHaveValue('');await flags.fill('x'.repeat(41));await apply(422);await expect(panel.getByRole('alert')).toContainText('at most twenty');expect(fs.existsSync(prefFile)).toBe(false);
 await flags.fill('Best, Important, Best');const initial=await apply();expect(initial.model_flags).toEqual({[first]:['Best','Important']});await expect(select.locator(`option[value="${first}"]`)).toContainText('[Best] [Important]');
 const beforeCancel=sha(prefFile);await flags.fill('unsubmitted-model-mark');await stage(1);expect(sha(prefFile)).toBe(beforeCancel);await stage(0);await toggle();await expect(select).toHaveValue('');await select.selectOption(first);await expect(flags).toHaveValue('Best, Important');expect(sha(prefFile)).toBe(beforeCancel);
 const fail=async(route:Route)=>route.request().method()==='PATCH'?route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({detail:'Controlled model mark unavailable'})}):route.continue();
 await flags.fill('Important');await page.route('**/api/project/preferences',fail);await apply(503);await expect(panel.getByRole('alert')).toContainText('Controlled model mark unavailable');expect(sha(prefFile)).toBe(beforeCancel);await evidence.screenshot(page,'actual-model-flag-transport-error-no-model-change');await page.unroute('**/api/project/preferences',fail);await apply();
 const beforeOther=await api('/api/project/preferences');const other=await api('/api/project/preferences',{expected_revision:beforeOther.revision,actor:'fixture-other-model-organizer',changes:{model_flags:{[second]:['Second-model']},labelset_flags:{default:['baseline']},tag_colors:{'inspection-ready':'#24a7cb'}}},'PATCH');const otherHash=sha(prefFile);
 await flags.fill('Best, Important');await apply(409);await expect(panel.getByRole('alert')).toContainText('Preferences changed');expect(sha(prefFile)).toBe(otherHash);expect((await api('/api/project/preferences')).revision).toBe(other.revision);await evidence.screenshot(page,'actual-model-flag-revision-conflict-preserves-other-model');
 await toggle();await toggle();await expect(select).toBeEnabled();await select.selectOption(first);await expect(flags).toHaveValue('Important');await flags.fill('Best, Important');const merged=await apply();expect(merged.model_flags).toEqual({[first]:['Best','Important'],[second]:['Second-model']});expect(merged.labelset_flags.default).toEqual(['baseline']);expect(merged.tag_colors['inspection-ready']).toBe('#24a7cb');
 await select.selectOption(second);await expect(flags).toHaveValue('Second-model');await flags.fill('');const cleared=await apply();expect(cleared.model_flags[second]).toEqual([]);expect(cleared.model_flags[first]).toEqual(['Best','Important']);
 await flags.fill('Second-model');await apply();const finalHash=sha(prefFile),final=await api('/api/project/preferences');expect(JSON.parse(fs.readFileSync(prefFile,'utf8'))).toEqual(final);await reload(0);await toggle();await expect(select).toBeEnabled();await expect(select).toHaveValue('');await expect(save).toBeDisabled();await select.selectOption(first);await expect(flags).toHaveValue('Best, Important');await select.selectOption(second);await expect(flags).toHaveValue('Second-model');await evidence.screenshot(page,'actual-two-completed-model-flags-reopened-independent');expect(sha(prefFile)).toBe(finalHash);
 for(const [id,original]of Object.entries(models))for(const [file,digest]of Object.entries(original))expect(sha(path.join(project.models_dir,id,file))).toBe(digest);for(const image of fixture.images){expect(sha(image.path)).toBe(image.sha256);evidence.addFile(image.path);}for(const file of [split.split_path,prefFile])evidence.addFile(file);
 expect(posts).toBe(0);expect(deployments).toBe(0);const active=await api('/api/model-deployments/active?'+new URLSearchParams({source_dataset_path:fixture.source,task:'classification'}));expect(active.active).toBeNull();
 evidence.note('completed_model_flag_controls',{actual_ui_and_backend:true,actual_two_completed_cpu_jobs:true,pretrained_false:true,empty_selection_disabled:true,invalid_41_char_actual_422:true,duplicate_flags_normalized:true,unsubmitted_cancel_no_save:true,explicit_controlled_503_preserved_bytes:true,actual_409_preserved_separate_model:true,explicit_refresh_and_retry:true,empty_flag_explicit_clear_only_selected:true,separate_models_tags_labelsets_preserved:true,actual_reload_and_explicit_reselection:true,checkpoint_meta_receipts_original_hashes_preserved:true,no_additional_training_by_flag_controls:true,no_deployment_mutation:true,active_deployment:null,jobs,models,preferences:final,source_hashes:fixture.images,synthetic_not_representative_quality:true,human_quality_approval:false,independent_acceptance:false});
}
test('completed model flags remain marks through invalid input cancel stale writes and reopen',async({page,request,renderer,workspace,evidence})=>{test.setTimeout(240_000);await installDesktopHostShim(page,renderer.port);const api:Api=async(route,body,method)=>{const r=await request.fetch(renderer.origin+route,{method:method||(body===undefined?'GET':'POST'),...(body===undefined?{}:{data:body})});expect(r.ok(),await r.text()).toBe(true);return r.json();};await exercise(page,workspace,evidence,api,renderer.url);});
test('native completed model flags remain marks through invalid input cancel stale writes and reopen',{tag:'@electron'},async({electronSession,workspace,evidence})=>{test.setTimeout(240_000);const {window}=electronSession,status=await electronSession.waitForBackend();const api:Api=(route,body,method)=>window.evaluate(async({port,route,body,method})=>{const r=await fetch(`http://127.0.0.1:${port}${route}`,{method:method||(body===undefined?'GET':'POST'),...(body===undefined?{}:{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})});if(!r.ok)throw Error(`Owned completed-model flag HTTP ${r.status}: ${await r.text()}`);return r.json();},{port:status.port,route,body,method});await exercise(window,workspace,evidence,api);});
