import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {execFileSync} from 'node:child_process';import type {Page} from '@playwright/test';
import {test,expect,type Workspace,type Evidence} from './fixtures/test';import {installDesktopHostShim} from './fixtures/desktop-host-shim';import {png} from './qa/appFlow';
const harness=require('./fixtures/harness.cjs');type Api=(route:string,body?:unknown,method?:string)=>Promise<any>;
async function exercise(page:Page,w:Workspace,e:Evidence,api:Api,native:boolean,url?:string){
 const source=path.join(w.root,'manual-comparison-source'),originals:Record<string,string>={};
 for(const split of ['train','val','test'])for(const label of ['OK','NG']){const folder=path.join(source,split,label);fs.mkdirSync(folder,{recursive:true});const file=path.join(folder,label+'.png');fs.writeFileSync(file,png(64,3,(x,y)=>[label==='OK'?220:40,x,y]));originals[file]=crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');}
 const project=await api('/api/project/create',{name:'Manual comparison choice',task:'classification'});await api('/api/project/update',{source_dataset_dir:source},'PUT');await api('/api/dataset/import',{folder_path:source,task:'classification'});
 const fixture=JSON.parse(execFileSync(harness.resolvePython(),[path.join(harness.REPO_ROOT,'scripts/e2e/fixtures/comparison_models.py'),source,project.models_dir],{cwd:harness.REPO_ROOT,env:{...process.env,VISION_AI_STUDIO_USER_DATA_DIR:w.userData},encoding:'utf8',timeout:60_000}));
 if(url)await page.goto(url);else await page.reload();await expect(page.getByTitle('프로젝트 관리',{exact:true})).toContainText(project.name);await page.getByRole('navigation',{name:'Workflow Stages'}).getByRole('button').nth(3).click();
 const panel=page.getByRole('region',{name:'현행과 후보 모델 비교'}),baseline=panel.getByLabel('비교 기준 모델',{exact:true}),candidate=panel.getByLabel('후보 모델',{exact:true});
 await baseline.selectOption('job_fixture_candidate');await candidate.selectOption('');
 await page.getByLabel('평가 모델',{exact:true}).selectOption('job_fixture_candidate');await expect(candidate).toBeEnabled();await expect(candidate).toHaveValue('');await expect(panel.getByRole('button',{name:'동일 test 이미지로 비교',exact:true})).toBeDisabled();
 await candidate.selectOption('job_fixture_incumbent');await page.getByLabel('평가 모델',{exact:true}).selectOption('job_fixture_incumbent');await expect(candidate).toBeEnabled();await expect(baseline).toHaveValue('job_fixture_candidate');await expect(candidate).toHaveValue('job_fixture_incumbent');
 const pending=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/evaluation/model-comparisons/jobs'&&r.request().method()==='POST');await panel.getByRole('button',{name:'동일 test 이미지로 비교',exact:true}).click();const response=await pending;expect(response.ok(),await response.text()).toBe(true);const body=response.request().postDataJSON();expect(body.incumbent_job_id).toBe('job_fixture_candidate');expect(body.candidate_job_id).toBe('job_fixture_incumbent');
 const created=await response.json(),query='?'+new URLSearchParams({source_dataset_path:source,task:'classification'});let job:any;await expect.poll(async()=>{job=await api('/api/evaluation/model-comparisons/jobs/'+created.job_id+query);if(job.status==='failed')throw Error(JSON.stringify(job));return job.status;},{timeout:60_000}).toBe('completed');
 const report=await api('/api/evaluation/model-comparisons/'+job.report_id+query);expect(report.incumbent_job_id).toBe(body.incumbent_job_id);expect(report.candidate_job_id).toBe(body.candidate_job_id);expect(report.images).toHaveLength(2);expect(report.summary.error_images).toBe(0);expect((await api('/api/model-deployments/active'+query)).active).toBeNull();
 for(const [file,hash] of Object.entries(originals))expect(crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex')).toBe(hash);
 await expect(panel.getByLabel('저장된 모델 비교',{exact:true})).toHaveValue(job.report_id);await e.screenshot(page,`${native?'native':'browser'}-manual-comparison-submitted-pair`);e.note('manual_comparison_choice',{project_id:project.id,fixture,originals,body,job,report,explicit_empty_preserved:true,recommendation_cannot_reverse_manual_pair:true,actual_cpu_comparison:true,actual_training:false,synthetic_not_quality_approval:true,native});
}
test('manual comparison pair and explicit empty survive evaluation model changes',async({page,request,renderer,workspace,evidence})=>{await installDesktopHostShim(page,renderer.port);const api:Api=async(route,body,method)=>{const r=await request.fetch(renderer.origin+route,{method:method||(body===undefined?'GET':'POST'),...(body===undefined?{}:{data:body})});expect(r.ok(),await r.text()).toBe(true);return r.json();};await exercise(page,workspace,evidence,api,false,renderer.url);});
test('native manual comparison pair and explicit empty survive evaluation model changes',{tag:'@electron'},async({electronSession,workspace,evidence})=>{const {window}=electronSession,status=await electronSession.waitForBackend();const api:Api=(route,body,method)=>window.evaluate(async({port,route,body,method})=>{const r=await fetch(`http://127.0.0.1:${port}${route}`,{method:method||(body===undefined?'GET':'POST'),...(body===undefined?{}:{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})});if(!r.ok)throw Error(`Owned comparison API ${r.status}: ${await r.text()}`);return r.json();},{port:status.port,route,body,method});await exercise(window,workspace,evidence,api,true);});
