import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {execFileSync} from 'node:child_process';
import type {Page} from '@playwright/test';import {test,expect,type Workspace,type Evidence} from './fixtures/test';
const harness=require('./fixtures/harness.cjs');type Api=(route:string,body?:any)=>Promise<any>;test.use({actionTimeout:10_000});
async function exercise(page:Page,workspace:Workspace,evidence:Evidence,api:Api,url?:string){
 const failures:any[]=[];page.on('requestfailed',request=>{failures.push({url:request.url(),failure:request.failure()});evidence.note('request_failures',failures);});
 const fixtureScript=path.join(harness.REPO_ROOT,'scripts/e2e/fixtures/gan_adoption_data.py');
 const fixture=JSON.parse(execFileSync(harness.resolvePython(),[fixtureScript,workspace.root],{encoding:'utf8',timeout:15_000}));
 await api('/api/project/create',{name:'Core model explicit target trials',task:'classification'});await api('/api/project/update',{source_dataset_dir:fixture.source});let project=await api('/api/project/current');await api('/api/dataset/import',{folder_path:fixture.source,task:'classification'});
 const split=JSON.parse(execFileSync(harness.resolvePython(),[fixtureScript,workspace.root,JSON.stringify(project)],{encoding:'utf8',timeout:15_000}));
 if(url)await page.goto(url);else await page.reload();await expect(page.getByTitle('프로젝트 관리',{exact:true})).toContainText(project.name);
 const stage=async(index:number)=>page.getByRole('navigation',{name:'Workflow Stages'}).getByRole('button').nth(index).click();await stage(2);
 const family=async(name:string)=>page.getByRole('region',{name:'모델 학습 허브'}).getByRole('button',{name:new RegExp('^'+name)}).click();
 async function trainClassifier(){
  await family('이미지 분류');await page.getByRole('combobox',{name:'학습 모델 구조',exact:true}).selectOption('efficientnet_b0');await page.getByLabel('수동 학습 횟수',{exact:true}).fill('1');await page.getByLabel('수동 학습 입력 크기',{exact:true}).fill('64');
  const device=page.getByLabel('다음 학습 로컬 장치',{exact:true});if(!await device.isVisible())await page.locator('summary').filter({hasText:'다음 학습 배치·로컬 장치 설정'}).click();await page.getByLabel('다음 학습 배치 크기',{exact:true}).fill('2');await device.selectOption('cpu');
  const budget=page.getByLabel('학습 시간 제한 (분)',{exact:true});if(!await budget.isVisible())await page.locator('summary').filter({hasText:'학습 실행 예산·대기열'}).click();await budget.fill('2');
  const waiting=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/training/start'&&r.request().method()==='POST');await page.getByRole('button',{name:'선택 설정으로 학습 시작',exact:true}).click();const response=await waiting;expect(response.ok(),await response.text()).toBe(true);const posted=response.request().postDataJSON(),accepted=await response.json();expect(posted).toMatchObject({task:'classification',device:'cpu',config_overrides:{backbone:'efficientnet_b0',epochs:1,image_size:64,batch_size:2}});
  let terminal:any;await expect.poll(async()=>{terminal=await api('/api/training/status?job_id='+accepted.job_id);if(['failed','cancelled','aborted'].includes(terminal.status))throw Error(JSON.stringify(terminal));return terminal.status;},{timeout:125_000}).toBe('completed');await expect(page.getByRole('region',{name:'학습 로그'})).toContainText('완료',{timeout:20_000});
  const metadata=JSON.parse(fs.readFileSync(path.join(project.models_dir,accepted.job_id,'model_meta.json'),'utf8'));return {job_id:accepted.job_id,posted,terminal,metadata};
 }
 const trained=await trainClassifier();await stage(5);const panel=page.getByRole('region',{name:'일반 모델 단일 실행'});await expect(panel).toBeVisible();await panel.getByLabel('단일 모델 실행 장치',{exact:true}).selectOption('cpu');const image=fixture.files.find((r:any)=>r.split==='test');await panel.getByLabel('단일 모델 원본 이미지',{exact:true}).selectOption(image.path);
 let waiting=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/model-execution/recipes'&&r.request().method()==='POST');await panel.getByRole('button',{name:'단일 모델 예측 실행',exact:true}).click();let response=await waiting;expect(response.ok(),await response.text()).toBe(true);const prediction=await response.json();expect(response.request().postDataJSON()).toMatchObject({task:'classification',stage:'predict',execution_target:'local',device:'cpu',params:{job_id:trained.job_id,image_path:image.path}});await expect(panel.getByAltText('단일 모델 예측 미리 보기')).toBeVisible();expect(prediction.source_sha256).toBe(image.sha256);
 const history=panel.getByRole('region',{name:'저장된 실행 위치 기록'});await expect(history).toContainText(prediction.execution.evidence_sha256);
 waiting=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/model-execution/recipes'&&r.request().method()==='POST');await page.getByRole('button',{name:'추론 속도 벤치마크 실행',exact:true}).click();response=await waiting;expect(response.ok(),await response.text()).toBe(true);const benchmark=await response.json();expect(response.request().postDataJSON()).toMatchObject({task:'classification',stage:'benchmark',execution_target:'local',device:'cpu',params:{job_id:trained.job_id,iterations:25}});expect(benchmark).toMatchObject({input_kind:'synthetic_random_tensor',measurement_scope:'model_forward_only',inspection_or_pipeline_timing:false,iterations:25});expect(benchmark.mean_latency_ms).toBeGreaterThan(0);await expect(history).toContainText(benchmark.execution.evidence_sha256);await history.scrollIntoViewIfNeeded();await evidence.screenshot(page,'actual-core-cpu-trials-and-receipts');
 const receipts=[];for(const row of [prediction,benchmark])receipts.push(await api('/api/model-execution/recipes/'+row.execution.receipt_id));
 await page.reload();await expect(page.getByTitle('프로젝트 관리',{exact:true})).toContainText(project.name);await stage(5);await expect(history).toContainText(benchmark.execution.evidence_sha256);
 const profile={id:'unreachable-core-loopback',name:'Unavailable owned core target',ssh_target:'127.0.0.1',ssh_port:1,remote_root:path.join(workspace.root,'unreachable-core'),runtime_kind:'python',runtime_value:'python3'};await api('/api/compute/profiles',profile);await page.reload();await stage(5);await page.getByRole('combobox').filter({has:page.locator('option[value="unreachable-core-loopback"]')}).first().selectOption(profile.id);await panel.getByLabel('단일 모델 실행 장치',{exact:true}).selectOption('cpu');
 const posts:string[]=[];const observe=(req:any)=>{if(req.method()==='POST')posts.push(new URL(req.url()).pathname);};page.on('request',observe);waiting=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/model-execution/recipes'&&r.request().method()==='POST');await page.getByRole('button',{name:'추론 속도 벤치마크 실행',exact:true}).click();response=await waiting;expect(response.status()).toBe(503);expect(response.request().postDataJSON()).toMatchObject({stage:'benchmark',execution_target:'selected_compute',compute_profile_id:profile.id,device:'cpu'});await expect(page.getByRole('alert').last()).toBeVisible();page.off('request',observe);expect(posts.filter(route=>route==='/api/model-execution/recipes'||route.startsWith('/api/evaluation/')||route.endsWith('/predict'))).toEqual(['/api/model-execution/recipes']);await evidence.screenshot(page,'selected-core-benchmark-no-local-fallback');
 for(const row of fixture.files)expect(crypto.createHash('sha256').update(fs.readFileSync(row.path)).digest('hex')).toBe(row.sha256);
 evidence.note('core_target_qualification',{project,fixture,split,trained,prediction,benchmark,receipts,failed_status:response.status(),failed_body:await response.json(),posts,actual_gui_cpu_training:true,actual_predict:true,actual_benchmark:true,automatic_receipt:true,reopen:true,source_unchanged:true,real_ssh_gpu_success:false});
}

test('actual core CPU prediction benchmark receipts and selected failure',{tag:'@owned-model'},async({page,request,renderer,workspace,evidence})=>{test.setTimeout(300_000);const api:Api=async(route,body)=>{const r=body===undefined?await request.get(renderer.origin+route):route.endsWith('/update')?await request.put(renderer.origin+route,{data:body}):await request.post(renderer.origin+route,{data:body});expect(r.ok(),await r.text()).toBe(true);return r.json();};await exercise(page,workspace,evidence,api,renderer.url);});
test('native core CPU trials reopen and refuse unavailable selected target',{tag:['@electron','@owned-model']},async({electronSession,workspace,evidence})=>{test.setTimeout(300_000);const {window}=electronSession;const backend=await electronSession.waitForBackend();const api:Api=(route,body)=>window.evaluate(async({port,route,body})=>{const r=await fetch(`http://127.0.0.1:${port}${route}`,{...(body===undefined?{}:{method:route.endsWith('/update')?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})});if(!r.ok)throw Error(`Owned API ${r.status}: ${await r.text()}`);return r.json();},{port:backend.port,route,body});await exercise(window,workspace,evidence,api);});
