import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {execFileSync} from 'node:child_process';
import type {Page} from '@playwright/test';import {test,expect,type Workspace,type Evidence} from './fixtures/test';
const harness=require('./fixtures/harness.cjs');type Api=(route:string,body?:any)=>Promise<any>;test.use({actionTimeout:10_000});
async function exercise(page:Page,workspace:Workspace,evidence:Evidence,api:Api,url?:string){
 const failures:any[]=[];page.on('requestfailed',request=>{failures.push({url:request.url(),failure:request.failure()});evidence.note('request_failures',failures);});
 const fixtureScript=path.join(harness.REPO_ROOT,'scripts/e2e/fixtures/gan_adoption_data.py');
 const fixture=JSON.parse(execFileSync(harness.resolvePython(),[fixtureScript,workspace.root],{encoding:'utf8',timeout:15_000}));
 await api('/api/project/create',{name:'Core model explicit target trials',task:'classification'});await api('/api/project/update',{source_dataset_dir:fixture.source});let project=await api('/api/project/current');await api('/api/dataset/import',{folder_path:fixture.source,task:'classification'});
 const split=JSON.parse(execFileSync(harness.resolvePython(),[fixtureScript,workspace.root,JSON.stringify(project)],{encoding:'utf8',timeout:15_000}));
 if(url)await page.goto(url);else await page.reload();await expect(page.getByTitle('프로젝트 관리',{exact:true})).toContainText(project.name);
 const stage=async(index:number)=>page.getByRole('navigation',{name:'Workflow Stages'}).getByRole('button').nth(index).click();await stage(2);
 const family=async(name:string)=>page.getByRole('region',{name:'모델 학습 허브'}).getByRole('button',{name:new RegExp('^'+name)}).click();
 async function trainClassifier(){
  await family('이미지 분류');await page.getByRole('combobox',{name:'학습 모델 구조',exact:true}).selectOption('efficientnet_b0');await page.getByLabel('수동 학습 횟수',{exact:true}).fill('1');await page.getByLabel('수동 학습 입력 크기',{exact:true}).fill('64');
  const device=page.getByLabel('다음 학습 로컬 장치',{exact:true});if(!await device.isVisible())await page.locator('summary').filter({hasText:'다음 학습 배치·로컬 장치 설정'}).click();await page.getByLabel('다음 학습 배치 크기',{exact:true}).fill('2');await device.selectOption('cpu');
  const budget=page.getByLabel('학습 시간 제한 (분)',{exact:true});if(!await budget.isVisible())await page.locator('summary').filter({hasText:'학습 실행 예산·대기열'}).click();await budget.fill('2');
  const waiting=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/training/start'&&r.request().method()==='POST');await page.getByRole('button',{name:'선택 설정으로 학습 시작',exact:true}).click();const response=await waiting;expect(response.ok(),await response.text()).toBe(true);const posted=response.request().postDataJSON(),accepted=await response.json();expect(posted).toMatchObject({task:'classification',device:'cpu',config_overrides:{backbone:'efficientnet_b0',epochs:1,image_size:64,batch_size:2}});
  let terminal:any;await expect.poll(async()=>{terminal=await api('/api/training/status?job_id='+accepted.job_id);if(['failed','cancelled','aborted'].includes(terminal.status))throw Error(JSON.stringify(terminal));return terminal.status;},{timeout:125_000}).toBe('completed');await expect(page.getByRole('region',{name:'학습 로그'})).toContainText('완료',{timeout:20_000});
  const metadata=JSON.parse(fs.readFileSync(path.join(project.models_dir,accepted.job_id,'model_meta.json'),'utf8'));return {job_id:accepted.job_id,posted,terminal,metadata};
 }
 const trained=await trainClassifier();
 const version=await api('/api/dataset/versions',{name:'Independent original heldout evaluation'});
 await stage(3);await page.getByLabel('평가 모델',{exact:true}).selectOption(trained.job_id);await page.getByLabel('평가 데이터 버전',{exact:true}).selectOption(version.id);await page.getByLabel('평가 장치',{exact:true}).selectOption('cpu');
 const execute=async()=>{const waiting=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/model-execution/recipes'&&r.request().method()==='POST');await page.getByRole('button',{name:'선택 코호트 평가',exact:true}).click();return waiting;};
 let response=await execute();expect(response.ok(),await response.text()).toBe(true);const result=await response.json();
 expect(response.request().postDataJSON()).toMatchObject({task:'classification',stage:'evaluate',execution_target:'local',device:'cpu',params:{job_id:trained.job_id,dataset_path:fixture.source,evaluation_dataset_version_id:version.id}});
 expect(result.common_cohort).toMatchObject({dataset_version_id:version.id,image_count:3,split:'test'});expect(result.metrics).toMatchObject({evaluated_split:'test',selection_overlap:false});expect(result.quality_approved).toBe(false);expect(result.execution.runtime).toMatchObject({device:'cpu'});
 const heldout=fixture.files.filter((row:any)=>row.split==='test');expect(result.test_predictions.map((row:any)=>row.file_path).sort()).toEqual(heldout.map((row:any)=>row.path).sort());
 for(const row of result.test_predictions)expect(row.input_sha256).toBe(heldout.find((image:any)=>image.path===row.file_path).sha256);
 await expect(page.getByLabel('평가 실행 기록',{exact:true})).toContainText(result.execution.evidence_sha256);await evidence.screenshot(page,'actual-local-core-heldout-evaluation');
 const original=await api('/api/model-execution/recipes/'+result.execution.receipt_id);expect(original.result.common_cohort).toEqual(result.common_cohort);
 await page.reload();await expect(page.getByTitle('프로젝트 관리',{exact:true})).toContainText(project.name);await stage(3);
 await page.getByLabel('평가 모델',{exact:true}).selectOption(trained.job_id);await page.getByLabel('평가 데이터 버전',{exact:true}).selectOption(version.id);await page.getByLabel('평가 장치',{exact:true}).selectOption('cpu');
 response=await execute();expect(response.ok(),await response.text()).toBe(true);const reopened=await response.json();expect(reopened.common_cohort).toEqual(result.common_cohort);expect(reopened.metrics).toEqual(result.metrics);expect(reopened.execution.receipt_id).not.toBe(result.execution.receipt_id);expect(await api('/api/model-execution/recipes/'+result.execution.receipt_id)).toEqual(original);
 const profile={id:'unreachable-cohort-loopback',name:'Unavailable owned cohort target',ssh_target:'127.0.0.1',ssh_port:1,remote_root:path.join(workspace.root,'unreachable-cohort'),runtime_kind:'python',runtime_value:'python3'};
 await api('/api/compute/profiles',profile);await api('/api/compute/selection',{compute_profile_id:profile.id});await page.reload();await expect(page.getByTitle('프로젝트 관리',{exact:true})).toContainText(project.name);await stage(3);
 await page.getByLabel('평가 모델',{exact:true}).selectOption(trained.job_id);await page.getByLabel('평가 데이터 버전',{exact:true}).selectOption(version.id);await page.getByLabel('평가 장치',{exact:true}).selectOption('cpu');
 const posts:string[]=[];const observe=(req:any)=>{if(req.method()==='POST')posts.push(new URL(req.url()).pathname);};page.on('request',observe);
 response=await execute();expect(response.status()).toBe(503);expect(response.request().postDataJSON()).toMatchObject({execution_target:'selected_compute',compute_profile_id:profile.id,device:'cpu'});const refusal=await response.json();expect(refusal.detail).toContain('no local fallback');page.off('request',observe);expect(posts).toEqual(['/api/model-execution/recipes']);await expect(page.getByRole('alert').filter({hasText:'no local fallback'}).first()).toBeVisible();await evidence.screenshot(page,'selected-core-cohort-no-host-fallback');
 for(const row of fixture.files)expect(crypto.createHash('sha256').update(fs.readFileSync(row.path)).digest('hex')).toBe(row.sha256);
 evidence.note('core_cohort_target',{project,fixture,split,trained,version,result,reopened,original,refusal,posts,actual_gui_cpu_training:true,actual_heldout_evaluation:true,canonical_receipt_reopened:true,source_unchanged:true,real_ssh_gpu_success:false,quality_approved:false});
}

test('actual core heldout evaluation follows local Compute and refuses selected failure',{tag:'@owned-model'},async({page,request,renderer,workspace,evidence})=>{test.setTimeout(300_000);const api:Api=async(route,body)=>{const r=body===undefined?await request.get(renderer.origin+route):route.endsWith('/update')||route.endsWith('/selection')?await request.put(renderer.origin+route,{data:body}):await request.post(renderer.origin+route,{data:body});expect(r.ok(),await r.text()).toBe(true);return r.json();};await exercise(page,workspace,evidence,api,renderer.url);});
test('native core heldout evaluation receipts survive restart and selected failure',{tag:['@electron','@owned-model']},async({electronSession,workspace,evidence})=>{test.setTimeout(300_000);const {window}=electronSession;const backend=await electronSession.waitForBackend();const api:Api=(route,body)=>window.evaluate(async({port,route,body})=>{const r=await fetch(`http://127.0.0.1:${port}${route}`,{...(body===undefined?{}:{method:route.endsWith('/update')||route.endsWith('/selection')?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})});if(!r.ok)throw Error(`Owned API ${r.status}: ${await r.text()}`);return r.json();},{port:backend.port,route,body});await exercise(window,workspace,evidence,api);});
