import crypto from 'node:crypto';
import {execFileSync} from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import type {Page} from '@playwright/test';
import {test,expect,type Workspace,type Evidence} from './fixtures/test';
import {installDesktopHostShim} from './fixtures/desktop-host-shim';
const harness=require('./fixtures/harness.cjs');
test.use({actionTimeout:10_000});
type Api=(route:string,body?:unknown,method?:string)=>Promise<any>;
const sha=(bytes:Buffer)=>crypto.createHash('sha256').update(bytes).digest('hex');

async function exercise(page:Page,workspace:Workspace,evidence:Evidence,api:Api,native:boolean,url?:string){
 const prefix=native?'native':'browser',name='Derived workflow qualification';
 const seed=(project?:any)=>JSON.parse(execFileSync(harness.resolvePython(),[path.join(harness.REPO_ROOT,'scripts/e2e/fixtures/derived_workflow_data.py'),workspace.root,...(project?[JSON.stringify(project)]:[])],{encoding:'utf8',timeout:15_000}));
 const fixture=seed();await api('/api/project/create',{name,task:'classification'});
 const project=await api('/api/project/update',{source_dataset_dir:fixture.source},'PUT');
 await api('/api/dataset/import',{folder_path:fixture.source,task:'classification'});const split=seed(project);
 const original=path.join(fixture.source,'train/NG/train_NG_00.png');
 const labels=[{id:'box',type:'bbox',label:'NG',category_id:1,bbox:[8,10,40,44],direction_deg:20,text:'A01'}];
 await api('/api/annotations/save',{image_id:path.basename(original,'.png'),image_path:original,image_width:64,image_height:64,actor:'fixture-editor',annotations:labels});
 const originalLabels=await api('/api/annotations/'+path.basename(original,'.png')+'?file_path='+encodeURIComponent(original));
 const explicitTruth=[];
 for(const image of fixture.images.filter((r:any)=>r.split==='test')){
  const row=await api('/api/dataset/metadata/image?image_path='+encodeURIComponent(image.path));const verdict=image.relative_path.includes('/OK/')?'OK':'NG';
  const truth=await api('/api/image-truth',{image_path:image.path,task:'classification',classes:['OK','NG'],verdict,defect_classes:verdict==='NG'?['NG']:[],reviewer:'controlled-synthetic-fixture',expected_revision:0,expected_image_revision:row.revision,note:'Known generated class; no representative process quality claim'},'PUT');expect(truth.verdict).toBe(verdict);explicitTruth.push(truth);
 }
 const train=async(source:string,parent?:string,version?:string)=>{
  const accepted=await api('/api/training/start',{task:'classification',preset:'fast',dataset_path:source,device:'cpu',queue:false,max_runtime_s:90,config_overrides:{backbone:'resnet18',pretrained:false,epochs:parent?1:6,image_size:64,batch_size:4,num_workers:0,learning_rate:parent?1e-12:.001},...(parent?{warm_start_job_id:parent}:{}),...(version?{dataset_version_id:version}:{})});
  let terminal:any;await expect.poll(async()=>{terminal=await api('/api/training/status?job_id='+accepted.job_id);if(['failed','cancelled'].includes(terminal.status))throw Error(JSON.stringify(terminal));return terminal.status;},{timeout:95_000}).toBe('completed');return {accepted,terminal};
 };
 const originalSnapshot=await api('/api/dataset/versions',{name:'Before derived edits',note:'Controlled synthetic data; not quality acceptance'});
 const baseline=await train(fixture.source,undefined,originalSnapshot.id);
 const pipeline=await api('/api/flowchart/templates/single-segmentation?inspection_task=classification&job_id='+baseline.accepted.job_id);
 const saved=await api('/api/flowchart/pipeline?'+new URLSearchParams({source_dataset_path:fixture.source,recipe_task:'classification'}),pipeline);
 const cohort=await api('/api/flow-evaluations/cohorts',{version_id:saved.version_id,name:'Unchanged synthetic test cohort'});expect(cohort.count).toBe(16);expect(cohort.scope.classes).toEqual(['OK','NG']);expect(cohort.samples.filter((r:any)=>r.truth.verdict==='OK')).toHaveLength(8);expect(cohort.samples.filter((r:any)=>r.truth.verdict==='NG')).toHaveLength(8);
 const navigate=async(stage=0)=>{if(url)await page.goto(url);else await page.reload();await expect(page.getByTitle('프로젝트 관리',{exact:true})).toContainText(name);await page.getByRole('navigation',{name:'Workflow Stages'}).getByRole('button').nth(stage).click();};
 await navigate();await page.getByRole('button',{name:path.basename(original)+' 라벨링에서 열기',exact:true}).click();
 await page.getByRole('button',{name:'이미지 정보·검토',exact:true}).click();const review=page.getByRole('region',{name:'이미지 정보와 검토 기록'});await review.getByLabel('작업자·검토자 이름').fill('fixture-editor');await page.getByRole('button',{name:'이미지 정보·검토',exact:true}).click();
 await page.locator('summary').filter({hasText:'원본 보존 이미지 편집'}).click();const edit=page.getByRole('region',{name:'파생 이미지 편집'});
 await edit.getByLabel('파생 이미지 정렬 각도').fill('30');let wire=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/data-workbench/derived'&&r.request().method()==='POST');await edit.getByRole('button',{name:'정렬 새 버전 저장',exact:true}).click();let response=await wire;expect(response.ok(),await response.text()).toBe(true);const aligned=await response.json();expect(aligned.operation).toEqual({kind:'align',degrees:30});expect(aligned.annotations[0]).toMatchObject({type:'polygon',direction_deg:50,text:'A01'});
 await expect(edit.getByLabel('파생 편집 기준 버전')).toHaveValue(aligned.id);await expect(edit.getByRole('img',{name:'편집 원본과 변환 라벨 미리보기'})).toHaveAttribute('viewBox',`0 0 ${aligned.size.join(' ')}`);
 await edit.getByLabel('파생 이미지 밝기 배율').fill('0.7');wire=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/data-workbench/derived'&&r.request().method()==='POST');await edit.getByRole('button',{name:'밝기 새 버전 저장',exact:true}).click();response=await wire;expect(response.ok(),await response.text()).toBe(true);const bright=await response.json();expect(bright.parent_id).toBe(aligned.id);expect(bright.source_sha256).toBe(aligned.source_sha256);
 await expect(edit.getByLabel('파생 편집 기준 버전')).toHaveValue(bright.id);await expect(edit.getByRole('button',{name:'검수한 파생본으로 새 학습 데이터 저장',exact:true})).toBeDisabled();
 await edit.getByLabel('파생본 검수 근거').fill('Controlled synthetic coordinates and blank edges inspected; not quality acceptance');await edit.getByRole('button',{name:'변환 이미지·라벨 검수 후 채택 후보',exact:true}).click();await expect(edit.getByText('채택 후보 · fixture-editor',{exact:false})).toBeVisible();await evidence.screenshot(page,`${prefix}-aligned-labels-explicit-review`);
 await navigate();await page.getByRole('button',{name:path.basename(original)+' 라벨링에서 열기',exact:true}).click();await page.locator('summary').filter({hasText:'원본 보존 이미지 편집'}).click();await expect(edit.getByLabel('파생 편집 기준 버전')).toBeVisible();await edit.getByLabel('파생 편집 기준 버전').selectOption(bright.id);await expect(edit.getByText('채택 후보 · fixture-editor',{exact:false})).toBeVisible();
 await edit.getByLabel('파생본 새 학습 데이터 이름').fill('Reviewed derived training source');await edit.getByRole('button',{name:'검수한 파생본으로 새 학습 데이터 저장',exact:true}).click();await expect(edit.getByRole('status')).toContainText('새 학습 데이터 Reviewed derived training source');
 const version=(await api('/api/data-workbench/derived-adoptions')).versions[0];expect(version.fixed_cohorts.map((r:any)=>r.cohort_id)).toContain(cohort.cohort_id);expect(version.fixed_test_records).toHaveLength(16);expect((await api('/api/project/current')).source_dataset_dir).toBe(fixture.source);
 await page.getByRole('navigation',{name:'Workflow Stages'}).getByRole('button').nth(0).click();await page.getByRole('button',{name:'파생 편집 · 검수한 학습 데이터 버전',exact:true}).click();const versions=page.getByRole('region',{name:'파생 편집 데이터 버전'});
 await versions.getByRole('button',{name:'검수한 파생 버전을 데이터 원본으로 선택',exact:true}).click();await expect.poll(async()=>(await api('/api/project/current')).source_dataset_dir).toBe(version.source_dataset_path);await expect(versions.getByRole('button',{name:'검증한 편집 전 원본으로 돌아가기',exact:true})).toBeEnabled();await versions.getByRole('button',{name:'닫기',exact:true}).click();
 const adopted=version.adopted[0],image=path.join(version.source_dataset_path,adopted.relative_path);let row=await api('/api/dataset/metadata/image?image_path='+encodeURIComponent(image));expect(row).toMatchObject({workflow_state:'needs_review',usage_state:'not_used'});
 await page.getByRole('button',{name:path.basename(image)+' 라벨링에서 열기',exact:true}).click();await page.getByRole('button',{name:'이미지 정보·검토',exact:true}).click();await review.getByLabel('작업자·검토자 이름').fill('fixture-reviewer');await review.getByRole('button',{name:'라벨 승인',exact:true}).click();await expect.poll(async()=>(await api('/api/dataset/metadata/image?image_path='+encodeURIComponent(image))).workflow_state).toBe('approved');
 await page.getByRole('navigation',{name:'Workflow Stages'}).getByRole('button').nth(0).click();await page.getByRole('button',{name:'이미지 검토·그룹 분할·라벨 교환',exact:true}).click();const data=page.getByRole('region',{name:'데이터 검토와 라벨 교환'});
 // The derivative is beyond the first page. The explicit approved-state filter
 // brings the one reviewed new input into view, without including every row.
 await data.getByLabel('검토 상태 필터').selectOption('approved');await data.getByLabel(adopted.relative_path+' 선택',{exact:true}).check();await data.getByLabel('선택 이미지 학습 사용 여부').selectOption('active');await data.getByRole('button',{name:'선택 이미지에 정보 적용',exact:true}).click();await expect.poll(async()=>(await api('/api/dataset/metadata/image?image_path='+encodeURIComponent(image))).usage_state).toBe('active');
 row=await api('/api/dataset/metadata/image?image_path='+encodeURIComponent(image));const snapshot=await api('/api/dataset/versions',{name:'Reviewed derived input',note:'New branch and labels bound; original heldout immutable'});const candidate=await train(version.source_dataset_path,baseline.accepted.job_id,snapshot.id);
 await navigate(3);
 // Evaluation hydrates the preferred model asynchronously and reloads the
 // comparison catalog. Wait for that exact job before choosing the manual
 // pair, so a late catalog load cannot disable the button during the click.
 await expect(page.getByText(`[${candidate.accepted.job_id}]`,{exact:true})).toBeVisible();
 const compare=page.getByRole('region',{name:'현행과 후보 모델 비교'});
 const incumbentChoice=compare.getByLabel('비교 기준 모델',{exact:true}),candidateChoice=compare.getByLabel('후보 모델',{exact:true});
 await incumbentChoice.selectOption(baseline.accepted.job_id);await candidateChoice.selectOption(candidate.accepted.job_id);
 await expect(incumbentChoice).toHaveValue(baseline.accepted.job_id);await expect(candidateChoice).toHaveValue(candidate.accepted.job_id);
 await expect(compare).toContainText('실행 위치: 로컬 CPU');await expect(compare.getByLabel('test 이미지 수',{exact:true})).toHaveValue('0');
 const compareButton=compare.getByRole('button',{name:'동일 test 이미지로 비교',exact:true});await expect(compareButton).toBeEnabled();
 wire=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/evaluation/model-comparisons/jobs'&&r.request().method()==='POST');
 await compareButton.click();response=await wire;expect(response.ok(),await response.text()).toBe(true);
 const submittedComparison=response.request().postDataJSON();expect(submittedComparison).toMatchObject({source_dataset_path:version.source_dataset_path,task:'classification',incumbent_job_id:baseline.accepted.job_id,candidate_job_id:candidate.accepted.job_id,full_test:true,execution_target:'local_cpu',compute_profile_id:null,device:'cpu'});
 const comparisonJob=await response.json();const query='?'+new URLSearchParams({source_dataset_path:version.source_dataset_path,task:'classification'});let completed:any;await expect.poll(async()=>{completed=await api('/api/evaluation/model-comparisons/jobs/'+comparisonJob.job_id+query);if(completed.status==='failed')throw Error(JSON.stringify(completed));return completed.status;},{timeout:65_000}).toBe('completed');
 const comparison=await api('/api/evaluation/model-comparisons/'+completed.report_id+query);expect(comparison.images).toHaveLength(16);expect(comparison.summary.error_images).toBe(0);expect(comparison.summary.known_ok_images).toBe(8);expect(comparison.summary.known_ng_images).toBe(8);const assessment=await api('/api/model-deployments/assess/'+completed.report_id+query);expect(assessment.reasons.join(' ')).not.toMatch(/계보|출처|체크포인트|stale/i);
 const approval=page.getByRole('region',{name:'모델 승인과 롤백'});await approval.getByRole('button',{name:'새로고침',exact:true}).click();await approval.getByRole('combobox',{name:'저장된 후보 비교',exact:true}).selectOption(completed.report_id);await expect(approval.getByText(`후보 ${candidate.accepted.job_id}`,{exact:false})).toBeVisible();await expect(approval.getByRole('checkbox')).not.toBeChecked();await expect(approval.getByRole('button',{name:'후보 승인 revision 저장',exact:true})).toBeDisabled();expect((await api('/api/model-deployments/active'+query)).active).toBeNull();await evidence.screenshot(page,`${prefix}-same-fixed-heldout-comparison-assessment`);
 await navigate();await page.getByRole('button',{name:'파생 편집 · 검수한 학습 데이터 버전',exact:true}).click();await expect(versions.getByRole('article',{name:version.name})).toBeVisible();await versions.getByRole('button',{name:'검증한 편집 전 원본으로 돌아가기',exact:true}).click();await expect.poll(async()=>(await api('/api/project/current')).source_dataset_dir).toBe(fixture.source);await evidence.screenshot(page,`${prefix}-verified-original-source-return`);
 for(const image of fixture.images){expect(sha(fs.readFileSync(image.path))).toBe(image.sha256);expect(sha(fs.readFileSync(path.join(version.source_dataset_path,image.relative_path)))).toBe(image.sha256);evidence.addFile(image.path);}
 expect((await api('/api/annotations/'+path.basename(original,'.png')+'?file_path='+encodeURIComponent(original))).annotations).toEqual(originalLabels.annotations);
 for(const file of [split.split_path,path.join(path.dirname(version.source_dataset_path),'record.json'),bright.file_path,path.join(bright.dataset_path,'review.json'),image])evidence.addFile(file);
 evidence.note('derived_workflow_closure',{project,fixture,split,original,originalLabels,explicitTruth,originalSnapshot,baseline,pipeline,saved,cohort,aligned,bright,version,row,snapshot,candidate,submittedComparison,comparisonJob,completed,comparison,assessment,exact_candidate_evaluation_hydrated_before_comparison:true,actual_ui_edit_review_adopt_select_include_compare_return:true,actual_original_and_warm_start_cpu_training:true,reapproval_connected_human_attestation_unchecked:true,synthetic_not_quality_or_independent_human_approval:true});
}
test('derived edits reach reviewed new data actual retraining fixed comparison and verified undo',async({page,request,renderer,workspace,evidence})=>{test.setTimeout(300_000);await installDesktopHostShim(page,renderer.port);const api:Api=async(route,body,method)=>{const r=await request.fetch(renderer.origin+route,{method:method||(body===undefined?'GET':'POST'),...(body===undefined?{}:{data:body})});expect(r.ok(),await r.text()).toBe(true);return r.json();};await exercise(page,workspace,evidence,api,false,renderer.url);});
test('native derived review branch retraining comparison and original return',{tag:'@electron'},async({electronSession,workspace,evidence})=>{test.setTimeout(300_000);const {window}=electronSession,status=await electronSession.waitForBackend();const api:Api=(route,body,method)=>window.evaluate(async({port,route,body,method})=>{const r=await fetch(`http://127.0.0.1:${port}${route}`,{method:method||(body===undefined?'GET':'POST'),...(body===undefined?{}:{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})});if(!r.ok)throw Error(`Owned derivative API ${r.status}: ${await r.text()}`);return r.json();},{port:status.port,route,body,method});await exercise(window,workspace,evidence,api,true);});

// SOURCE-only appendix. Root must execute and qualify each owning case.
const derivedHandoff=require('./fixtures/remaining-project-handoff') as typeof import('./fixtures/remaining-project-handoff');
type DerivedHandoffScope={tag:'A'|'B';project:any;source:string;original:string;fixture:any;labels:any;annotation:any;metadata:any;actor:string;reason:string;degrees:number;factor:number;pixels:any;split:any;aligned?:any;bright?:any;adoption?:any;reopen?:any};
function derivedHandoffRaw(info:fs.Stats){return [info.dev,info.ino,info.mode,info.nlink,info.size,info.mtimeMs,info.ctimeMs];}
function derivedHandoffFile(file:string){
 const before=fs.lstatSync(file);expect(before.isSymbolicLink()).toBe(false);expect(before.isFile()).toBe(true);
 const fd=fs.openSync(file,fs.constants.O_RDONLY|fs.constants.O_NOFOLLOW);let primary:unknown,bytes:Buffer|undefined;
 try{expect(derivedHandoffRaw(fs.fstatSync(fd))).toEqual(derivedHandoffRaw(before));bytes=fs.readFileSync(fd);expect(bytes.length).toBe(before.size);expect(derivedHandoffRaw(fs.fstatSync(fd))).toEqual(derivedHandoffRaw(before));}
 catch(error){primary=error;}finally{try{fs.closeSync(fd);}catch(error){if(primary===undefined)primary=error;}}
 if(primary!==undefined)throw primary;expect(derivedHandoffRaw(fs.lstatSync(file))).toEqual(derivedHandoffRaw(before));return {bytes:bytes!,pin:{sha256:sha(bytes!),size:bytes!.length,raw:derivedHandoffRaw(before)}};
}
function derivedHandoffSave(e:Evidence,w:Workspace,label:string,bytes:Buffer){
 const file=path.join(w.logs,label+'.json'),fd=fs.openSync(file,fs.constants.O_WRONLY|fs.constants.O_CREAT|fs.constants.O_EXCL,0o600);let primary:unknown;
 try{fs.writeFileSync(fd,bytes);fs.fsyncSync(fd);}catch(error){primary=error;}finally{try{fs.closeSync(fd);}catch(error){if(primary===undefined)primary=error;}}
 if(primary!==undefined)throw primary;const saved=derivedHandoffFile(file).pin;expect(saved.sha256).toBe(sha(bytes));e.addFile(file);return {path:file,...saved};
}
function derivedHandoffTree(root:string){
 if(!fs.existsSync(root))return {root,kind:'missing',rows:{}};
 const rows:Record<string,unknown>={};const visit=(file:string)=>{
  const info=fs.lstatSync(file),relative=path.relative(root,file).split(path.sep).join('/')||'.';expect(info.isSymbolicLink()).toBe(false);
  if(info.isDirectory()){rows[relative]={kind:'directory',raw:derivedHandoffRaw(info)};for(const name of fs.readdirSync(file).sort())visit(path.join(file,name));expect(derivedHandoffRaw(fs.lstatSync(file))).toEqual(derivedHandoffRaw(info));}
  else{expect(info.isFile()).toBe(true);rows[relative]={kind:'regular',...derivedHandoffFile(file).pin};}
 };visit(root);return {root,kind:'directory',rows};
}
function derivedHandoffSnapshot(scope:DerivedHandoffScope){
 const roots={source:scope.source,annotations:scope.project.annotations_dir,dataset:scope.project.dataset_dir,reports:scope.project.reports_dir,labelsets:path.join(scope.project.project_dir,'labelsets'),branch:scope.adoption?.source_dataset_path??null,versionRecord:scope.adoption?.source_dataset_path?path.dirname(scope.adoption.source_dataset_path):null};
 const rows:Record<string,unknown>={},failures:any[]=[];
 for(const [kind,root] of Object.entries(roots)){try{expect(typeof root).toBe('string');rows[kind]=derivedHandoffTree(root!);}catch(error){rows[kind]={root,kind:'unavailable',error:String(error)};failures.push({role:kind,error:String(error)});}}
 return {roots:rows,failures};
}
const derivedHandoffPixels=String.raw`
from pathlib import Path
from PIL import Image,ImageEnhance
import hashlib,json,sys
original,out=map(Path,sys.argv[1:3]);degrees=float(sys.argv[3]);factor=float(sys.argv[4]);tag=sys.argv[5]
# B differs before import/baseline, inside the controlled generated fixture only.
if tag=='B':
 with Image.open(original) as opened:image=opened.convert('RGB');image.putpixel((17,19),(211,72,133));image.save(original,format='PNG')
out.mkdir();result={};source_hash=hashlib.sha256(original.read_bytes()).hexdigest()
with Image.open(original) as opened:
 image=opened.convert('RGB');aligned=image.rotate(-degrees,resample=Image.Resampling.BICUBIC,expand=True)
 for name,edited in [('align',aligned),('brightness',ImageEnhance.Brightness(aligned).enhance(factor))]:
  target=out/(name+'.png');edited.save(target,format='PNG');result[name]={'path':str(target),'sha256':hashlib.sha256(target.read_bytes()).hexdigest(),'size':list(edited.size),'decoded_rgb_sha256':hashlib.sha256(edited.tobytes()).hexdigest()}
assert hashlib.sha256(original.read_bytes()).hexdigest()==source_hash
print(json.dumps({'source_sha256':source_hash,'expected':result,'application_transform_imported':False,'model_execution':False}))
`;
const derivedHandoffRecords=String.raw`
from pathlib import Path
from PIL import Image
import hashlib,json,sys
value=json.loads(sys.argv[1]);digest=lambda v:hashlib.sha256(json.dumps(v,ensure_ascii=False,sort_keys=True,separators=(',',':'),allow_nan=False).encode()).hexdigest()
file_hash=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();result={}
for name in ('aligned','bright'):
 response=value[name];directory=Path(response['dataset_path']);record=json.loads((directory/'version.json').read_text());body={k:v for k,v in record.items() if k!='evidence_sha256'}
 assert digest(body)==record['evidence_sha256'];assert record['source_sha256']==file_hash(value['original']);assert record['derived_sha256']==file_hash(record['file_path'])
 assert set(record['annotation_files_sha256'])=={'annotations.json','images/derived.json','masks/derived.png'}
 for rel,sha in record['annotation_files_sha256'].items():assert file_hash(directory/rel)==sha
 assert {k:v for k,v in response.items() if k not in ('image_url','review','review_revision')}==record
 annotations=json.loads((directory/'annotations.json').read_text());labelme=json.loads((directory/'images'/'derived.json').read_text())
 assert annotations['annotations']==record['annotations'];assert [annotations['image_width'],annotations['image_height']]==record['size'];assert labelme['derived_version_id']==record['id'];assert [labelme['imageWidth'],labelme['imageHeight']]==record['size'];assert len(labelme['shapes'])==1
 assert labelme['shapes'][0]['shape_type']=='polygon';assert labelme['shapes'][0]['points']==record['annotations'][0]['polygon'];assert labelme['shapes'][0]['flags']['studio_direction_deg']==record['annotations'][0]['direction_deg']
 with Image.open(record['file_path']) as image:assert list(image.size)==record['size'];rgb=hashlib.sha256(image.convert('RGB').tobytes()).hexdigest()
 with Image.open(directory/'masks'/'derived.png') as mask:assert list(mask.size)==record['size'];assert set(mask.getdata())=={0,1}
 result[name]={'record_sha256':file_hash(directory/'version.json'),'evidence_sha256':record['evidence_sha256'],'decoded_rgb_sha256':rgb,'annotation_files':record['annotation_files_sha256']}
review=json.loads((Path(value['bright']['dataset_path'])/'review.json').read_text());assert digest({k:v for k,v in review.items() if k!='record_sha256'})==review['record_sha256'];assert review['revision']==1;assert review['version_sha256']==value['bright']['evidence_sha256'];assert review['history']==[review['review']];assert review['review']==value['bright']['review'];assert review['review']['decision']=='approve'
record_path=Path(value['adoption']['source_dataset_path']).parent/'record.json';adoption=json.loads(record_path.read_text());assert digest({k:v for k,v in adoption.items() if k!='record_sha256'})==adoption['record_sha256'];assert adoption==value['adoption'];assert adoption['activated'] is False;assert len(adoption['adopted'])==1
for row in adoption['base_files']:assert file_hash(Path(adoption['source_dataset_path'])/row['relative_path'])==row['sha256'];assert file_hash(Path(value['source'])/row['relative_path'])==row['sha256']
new=adoption['adopted'][0];assert file_hash(Path(adoption['source_dataset_path'])/new['relative_path'])==value['bright']['derived_sha256'];assert new['origin']['version_id']==value['bright']['id'];assert new['origin']['parent_id']==value['aligned']['id'];assert new['origin']['version_sha256']==value['bright']['evidence_sha256'];assert new['workflow_state']=='needs_review';assert new['usage_state']=='not_used';assert new['truth_verdict']=='UNKNOWN';assert adoption['split_assignments'][new['relative_path']]=='train'
assert digest(adoption['fixed_test_records'])==adoption['fixed_test_sha256'];assert len(adoption['fixed_test_records'])==16
result.update(review_record_sha256=file_hash(Path(value['bright']['dataset_path'])/'review.json'),adoption_record_sha256=file_hash(record_path),fixed_test_sha256=adoption['fixed_test_sha256'],application_derive_or_adoption_imported=False,model_execution=False)
print(json.dumps(result))
`;
async function derivedSavedProjectHandoff(page:Page,w:Workspace,e:Evidence,api:Api,origin:string,url:string){
 const scopeRows:DerivedHandoffScope[]=[],uiWrites:any[]=[],readOnlyWrites:any[]=[],wireProofs:any[]=[],opens:any[]=[],controls:any[]=[],snapshots:Record<string,any>={},states:Record<string,any>={},after:Record<string,any>={},readbacks:any[]=[];let readonly=false,primary:unknown;
 const observe=(request:import('@playwright/test').Request)=>{const u=new URL(request.url());if(u.origin!==origin||!u.pathname.startsWith('/api/')||['GET','HEAD','OPTIONS'].includes(request.method()))return;let body:unknown;try{body=request.postDataJSON();}catch{body=request.postData();}const row={method:request.method(),path:u.pathname,body,main_frame:request.frame()===page.mainFrame()};uiWrites.push(row);if(readonly&&!(row.method==='POST'&&row.path==='/api/project/open'&&scopeRows.some(s=>(body as any)?.project_dir===s.project.project_dir)))readOnlyWrites.push(row);};
 const panel=()=>page.getByRole('region',{name:'파생 이미지 편집',exact:true});
 const enter=async(s:DerivedHandoffScope)=>{
  await expect(page.getByTitle('프로젝트 관리',{exact:true})).toContainText(s.project.name);await page.getByRole('navigation',{name:'Workflow Stages'}).getByRole('button').nth(0).click();await page.getByRole('button',{name:path.basename(s.original)+' 라벨링에서 열기',exact:true}).click();await expect(page.getByTestId('annotation-save-button')).toHaveText('Saved');
  const focus=page.getByRole('button',{name:'집중 편집',exact:true});if(await focus.getAttribute('aria-pressed')==='true')await focus.click();const summary=page.locator('summary').filter({hasText:'원본 보존 이미지 편집 · 파생 버전'});if(await summary.locator('..').getAttribute('open')===null)await summary.click();await expect(panel().getByLabel('파생 편집 기준 버전',{exact:true})).toBeVisible();
 };
 const actualPost=async(s:DerivedHandoffScope,route:string,body:unknown,button:import('@playwright/test').Locator,label:string)=>{
  const deadline=performance.now()+10_000,waiting=page.waitForResponse(r=>r.request().frame()===page.mainFrame()&&new URL(r.url()).origin===origin&&new URL(r.url()).pathname===route&&r.request().method()==='POST',{timeout:10_000});await derivedHandoff.handoffWithin(button.click(),deadline,'derived actual UI '+label);const response=await derivedHandoff.handoffWithin(waiting,deadline,'derived actual response');expect(response.request().postDataJSON()).toEqual(body);expect(response.status()).toBe(200);const bytes=await derivedHandoff.handoffWithin(response.body(),deadline,'derived full response');expect(bytes.length).toBeLessThanOrEqual(1024*1024);expect(await derivedHandoff.handoffWithin(response.finished(),deadline,'derived response finished')).toBeNull();
  const saved=derivedHandoffSave(e,w,'derived-'+s.tag+'-'+label+'-actual-response',bytes);const row={tag:s.tag,project_id:s.project.id,source:s.source,path:route,method:'POST',status:200,request:body,response_sha256:sha(bytes),response_bytes:bytes.length,original_response_file:saved,headers:{project:await response.request().headerValue('x-vision-project'),context:await response.request().headerValue('x-vision-context')},actual_main_frame:true,finished:true};wireProofs.push(row);return JSON.parse(bytes.toString('utf8'));
 };
 const savedState=async(s:DerivedHandoffScope)=>({project:await api('/api/project/current'),labelsets:await api('/api/project/labelsets'),preferences:await api('/api/project/preferences'),team:await api('/api/team-data'),readiness:await api('/api/team-data/readiness'),metadata:await api('/api/dataset/metadata?limit=100'),split:await api('/api/dataset/metadata/split'),annotation:await api('/api/annotations/'+path.basename(s.original,'.png')+'?file_path='+encodeURIComponent(s.original)),history:await api('/api/data-workbench/derived?image_path='+encodeURIComponent(s.original)),adoptions:await api('/api/data-workbench/derived-adoptions')});
 const originalIntact=async(s:DerivedHandoffScope)=>{for(const image of s.fixture.images){expect(derivedHandoffFile(image.path).pin.sha256).toBe(image.sha256);e.addFile(image.path);if(s.adoption){const copy=path.join(s.adoption.source_dataset_path,image.relative_path);expect(derivedHandoffFile(copy).pin.sha256).toBe(image.sha256);e.addFile(copy);}}expect((await api('/api/annotations/'+path.basename(s.original,'.png')+'?file_path='+encodeURIComponent(s.original))).annotations).toEqual(s.annotation.annotations);};
 try{
  page.on('request',observe);
  for(const tag of ['A','B'] as const){
   const fixtureRoot=path.join(w.root,'derived-handoff-fixture-'+tag);fs.mkdirSync(fixtureRoot);const fixture=JSON.parse(execFileSync(harness.resolvePython(),[path.join(harness.REPO_ROOT,'scripts/e2e/fixtures/derived_workflow_data.py'),fixtureRoot],{encoding:'utf8',timeout:15_000}));const original=path.join(fixture.source,'train/NG/train_NG_00.png'),degrees=tag==='A'?30:-20,factor=tag==='A'?.7:1.3;
   const pixels=JSON.parse(execFileSync(harness.resolvePython(),['-c',derivedHandoffPixels,original,path.join(w.logs,'derived-'+tag+'-independent-pixels'),String(degrees),String(factor),tag],{encoding:'utf8',timeout:15_000}));fixture.images=fixture.images.map((row:any)=>({...row,sha256:derivedHandoffFile(row.path).pin.sha256}));expect(pixels.source_sha256).toBe(derivedHandoffFile(original).pin.sha256);for(const value of Object.values(pixels.expected) as any[])e.addFile(value.path);
   await api('/api/project/create',{name:'Owned saved derived handoff '+tag,task:'classification'});const project=await api('/api/project/update',{source_dataset_dir:fixture.source},'PUT');await api('/api/dataset/import',{folder_path:fixture.source,task:'classification'});
   const assignments=Object.fromEntries(fixture.images.map((r:any)=>[r.relative_path,r.split]));const splitPath=path.join(project.dataset_dir,'splits',sha(Buffer.from(fixture.source))+'.json');fs.mkdirSync(path.dirname(splitPath),{recursive:true});const split={folder_path:fixture.source,assignments,seed:104};fs.writeFileSync(splitPath,JSON.stringify(split),{flag:'wx'});e.addFile(splitPath);
   const actor='derived-handoff-'+tag,reason='Synthetic '+tag+' explicit pixels and transformed labels inspected; no quality or human approval';const labels=[{id:'owned-box-'+tag,type:'bbox',label:'NG',category_id:1,bbox:[8,10,40,44],direction_deg:tag==='A'?20:80,text:'OWN-'+tag}];await api('/api/annotations/save',{image_id:path.basename(original,'.png'),image_path:original,image_width:64,image_height:64,actor,annotations:labels});const annotation=await api('/api/annotations/'+path.basename(original,'.png')+'?file_path='+encodeURIComponent(original)),metadata=await api('/api/dataset/metadata/image?image_path='+encodeURIComponent(original));const s:DerivedHandoffScope={tag,project,source:fixture.source,original,fixture,labels,annotation,metadata,actor,reason,degrees,factor,pixels,split:{...split,path:splitPath}};scopeRows.push(s);
   await page.goto(url);await enter(s);await page.getByRole('button',{name:'이미지 정보·검토',exact:true}).click();await page.getByRole('region',{name:'이미지 정보와 검토 기록'}).getByLabel('작업자·검토자 이름',{exact:true}).fill(actor);await page.getByRole('button',{name:'이미지 정보·검토',exact:true}).click();await panel().getByLabel('파생 편집 기준 버전',{exact:true}).selectOption('');await panel().getByLabel('파생 이미지 정렬 각도',{exact:true}).fill(String(degrees));
   s.aligned=await actualPost(s,'/api/data-workbench/derived',{image_path:original,expected_revision:metadata.revision,expected_sha256:pixels.source_sha256,operation:{kind:'align',degrees},actor},panel().getByRole('button',{name:'정렬 새 버전 저장',exact:true}),'align');expect(s.aligned).toMatchObject({source_path:original,source_sha256:pixels.source_sha256,parent_id:null,actor,operation:{kind:'align',degrees},size:pixels.expected.align.size,derived_sha256:pixels.expected.align.sha256,omitted_annotation_ids:[]});expect(derivedHandoffFile(s.aligned.file_path).bytes).toEqual(derivedHandoffFile(pixels.expected.align.path).bytes);expect(s.aligned.annotations).toHaveLength(1);
   const [width,height]=s.aligned.size,radians=degrees*Math.PI/180,co=Math.cos(radians),si=Math.sin(radians),points=[[8,10],[40,10],[40,44],[8,44]].map(([x,y])=>[co*(x-32)-si*(y-32)+width/2,si*(x-32)+co*(y-32)+height/2]);const transformed=s.aligned.annotations[0];expect(transformed).toMatchObject({id:labels[0].id,type:'polygon',label:'NG',category_id:1,text:labels[0].text,direction_deg:(labels[0].direction_deg+degrees+360)%360});for(let n=0;n<4;n++)for(let axis=0;axis<2;axis++)expect(transformed.polygon[n][axis]).toBeCloseTo(points[n][axis],12);expect(transformed.points).toEqual(transformed.polygon);expect(transformed.bbox).toEqual([Math.min(...transformed.polygon.map((p:any)=>p[0])),Math.min(...transformed.polygon.map((p:any)=>p[1])),Math.max(...transformed.polygon.map((p:any)=>p[0])),Math.max(...transformed.polygon.map((p:any)=>p[1]))]);
   await expect(panel().getByLabel('파생 편집 기준 버전',{exact:true})).toHaveValue(s.aligned.id);await panel().getByLabel('파생 이미지 밝기 배율',{exact:true}).fill(String(factor));s.bright=await actualPost(s,'/api/data-workbench/derived',{image_path:original,expected_revision:metadata.revision,expected_sha256:pixels.source_sha256,operation:{kind:'brightness',factor},actor,parent_id:s.aligned.id},panel().getByRole('button',{name:'밝기 새 버전 저장',exact:true}),'brightness');expect(s.bright).toMatchObject({parent_id:s.aligned.id,source_path:original,source_sha256:pixels.source_sha256,actor,operation:{kind:'brightness',factor},size:pixels.expected.brightness.size,derived_sha256:pixels.expected.brightness.sha256});expect(s.bright.annotations).toEqual(s.aligned.annotations);expect(derivedHandoffFile(s.bright.file_path).bytes).toEqual(derivedHandoffFile(pixels.expected.brightness.path).bytes);
   const approve=panel().getByRole('button',{name:'변환 이미지·라벨 검수 후 채택 후보',exact:true});await panel().getByLabel('파생본 검수 근거',{exact:true}).fill('');await expect(approve).toBeDisabled();await expect(panel().getByRole('button',{name:'검수한 파생본으로 새 학습 데이터 저장',exact:true})).toBeDisabled();await panel().getByLabel('파생본 검수 근거',{exact:true}).fill(reason);await expect(approve).toBeEnabled();s.bright=await actualPost(s,'/api/data-workbench/derived/'+s.bright.id+'/review',{expected_revision:0,actor,decision:'approve',note:reason},approve,'review');expect(s.bright.review_revision).toBe(1);expect(s.bright.review).toMatchObject({decision:'approve',actor,note:reason,derived_sha256:pixels.expected.brightness.sha256});await expect(panel().getByText('채택 후보 · '+actor,{exact:false})).toBeVisible();await e.screenshot(page,'derived-'+tag+'-saved-align-brightness-explicit-review');
   await panel().getByLabel('파생본 새 학습 데이터 이름',{exact:true}).fill('Owned reviewed derived '+tag);s.adoption=await actualPost(s,'/api/data-workbench/derived-adoptions',{version_ids:[s.bright.id],actor,name:'Owned reviewed derived '+tag},panel().getByRole('button',{name:'검수한 파생본으로 새 학습 데이터 저장',exact:true}),'adoption');expect(s.adoption).toMatchObject({kind:'derived-edits',actor,name:'Owned reviewed derived '+tag,scope:{project_id:project.id,source_dataset_path:s.source,task:'classification',labelset_id:project.active_labelset_id},parent_source_dataset_path:s.source,activated:false});expect(s.adoption.adopted).toHaveLength(1);expect(s.adoption.fixed_test_records).toHaveLength(16);expect(path.relative(project.dataset_dir,s.adoption.source_dataset_path).startsWith('..')).toBe(false);const adopted=s.adoption.adopted[0];expect(adopted).toMatchObject({source_sha256:s.bright.derived_sha256,truth_verdict:'UNKNOWN',usage_state:'not_used',workflow_state:'needs_review',origin:{kind:'derived-edit',version_id:s.bright.id,parent_id:s.aligned.id,version_sha256:s.bright.evidence_sha256,original_relative_path:'train/NG/train_NG_00.png',original_sha256:pixels.source_sha256}});expect(s.adoption.split_assignments[adopted.relative_path]).toBe('train');
   for(const image of fixture.images){expect(s.adoption.split_assignments[image.relative_path]).toBe(image.split);}await originalIntact(s);await page.getByRole('navigation',{name:'Workflow Stages'}).getByRole('button').nth(0).click();await page.getByRole('button',{name:'파생 편집 · 검수한 학습 데이터 버전',exact:true}).click();const versions=page.getByRole('region',{name:'파생 편집 데이터 버전',exact:true}),article=versions.getByRole('article',{name:s.adoption.name,exact:true});await expect(article).toBeVisible();const importWire=page.waitForResponse(r=>r.request().frame()===page.mainFrame()&&new URL(r.url()).origin===origin&&new URL(r.url()).pathname==='/api/dataset/import'&&r.request().method()==='POST'&&r.request().postDataJSON()?.folder_path===s.adoption.source_dataset_path,{timeout:10_000});const choiceWire=page.waitForResponse(r=>r.request().frame()===page.mainFrame()&&new URL(r.url()).origin===origin&&new URL(r.url()).pathname==='/api/project/update'&&r.request().method()==='PUT'&&r.request().postDataJSON()?.source_dataset_dir===s.adoption.source_dataset_path,{timeout:10_000});await article.getByRole('button',{name:'검수한 파생 버전을 데이터 원본으로 선택',exact:true}).click();const chosen=await choiceWire;expect(chosen.request().postDataJSON()).toEqual({source_dataset_dir:s.adoption.source_dataset_path});expect(chosen.status()).toBe(200);const chosenBytes=await chosen.body();expect(await chosen.finished()).toBeNull();expect(JSON.parse(chosenBytes.toString('utf8')).source_dataset_dir).toBe(s.adoption.source_dataset_path);await expect.poll(async()=>(await api('/api/project/current')).source_dataset_dir,{timeout:10_000}).toBe(s.adoption.source_dataset_path);const imported=await importWire;expect(imported.status()).toBe(200);expect(imported.request().postDataJSON()).toEqual({folder_path:s.adoption.source_dataset_path,task:'classification',validate_images:true});expect(await imported.finished()).toBeNull();await expect(page.getByRole('button',{name:'파생 편집 · 검수한 학습 데이터 버전',exact:true})).toBeEnabled();
   await page.reload();await expect(page.getByTitle('프로젝트 관리',{exact:true})).toContainText(project.name);await page.getByRole('navigation',{name:'Workflow Stages'}).getByRole('button').nth(0).click();await expect.poll(async()=>(await api('/api/project/current')).source_dataset_dir,{timeout:10_000}).toBe(s.adoption.source_dataset_path);await page.getByRole('button',{name:'파생 편집 · 검수한 학습 데이터 버전',exact:true}).click();await expect(article).toBeVisible();expect(await api('/api/data-workbench/derived-adoptions/'+s.adoption.version_id)).toEqual(s.adoption);const adoptedMetadata=await api('/api/dataset/metadata/image?image_path='+encodeURIComponent(path.join(s.adoption.source_dataset_path,adopted.relative_path)));expect(adoptedMetadata).toMatchObject({workflow_state:'needs_review',usage_state:'not_used'});s.reopen={project:await api('/api/project/current'),version_id:s.adoption.version_id,saved_source:s.adoption.source_dataset_path,choice_response_sha256:sha(chosenBytes),actual_PUT200:true,actual_reload:true,adoptedMetadata};await e.screenshot(page,'derived-'+tag+'-saved-new-training-source-reopen');const returnImportWire=page.waitForResponse(r=>r.request().frame()===page.mainFrame()&&new URL(r.url()).origin===origin&&new URL(r.url()).pathname==='/api/dataset/import'&&r.request().method()==='POST'&&r.request().postDataJSON()?.folder_path===s.source,{timeout:10_000});const returnWire=page.waitForResponse(r=>r.request().frame()===page.mainFrame()&&new URL(r.url()).origin===origin&&new URL(r.url()).pathname==='/api/project/update'&&r.request().method()==='PUT'&&r.request().postDataJSON()?.source_dataset_dir===s.source,{timeout:10_000});await article.getByRole('button',{name:'검증한 편집 전 원본으로 돌아가기',exact:true}).click();const returned=await returnWire;expect(returned.request().postDataJSON()).toEqual({source_dataset_dir:s.source});expect(returned.status()).toBe(200);expect((await returned.json()).source_dataset_dir).toBe(s.source);expect(await returned.finished()).toBeNull();await expect.poll(async()=>(await api('/api/project/current')).source_dataset_dir,{timeout:10_000}).toBe(s.source);const returnImported=await returnImportWire;expect(returnImported.status()).toBe(200);expect(returnImported.request().postDataJSON()).toEqual({folder_path:s.source,task:'classification',validate_images:true});expect(await returnImported.finished()).toBeNull();if(await versions.isVisible())await versions.getByRole('button',{name:'닫기',exact:true}).click();s.project=await api('/api/project/current');await originalIntact(s);
   const recordControl=JSON.parse(execFileSync(harness.resolvePython(),['-c',derivedHandoffRecords,JSON.stringify({original:s.original,source:s.source,aligned:s.aligned,bright:s.bright,adoption:s.adoption})],{encoding:'utf8',timeout:15_000}));expect(recordControl.aligned.decoded_rgb_sha256).toBe(pixels.expected.align.decoded_rgb_sha256);expect(recordControl.bright.decoded_rgb_sha256).toBe(pixels.expected.brightness.decoded_rgb_sha256);controls.push({tag,...recordControl});for(const file of [path.join(s.aligned.dataset_path,'version.json'),path.join(s.bright.dataset_path,'version.json'),path.join(s.bright.dataset_path,'review.json'),path.join(path.dirname(s.adoption.source_dataset_path),'record.json'),s.aligned.file_path,s.bright.file_path,...[s.aligned,s.bright].flatMap(version=>Object.keys(version.annotation_files_sha256).map(relative=>path.join(version.dataset_path,relative))),path.join(s.adoption.source_dataset_path,adopted.relative_path)])e.addFile(file);
  }
  expect(scopeRows[0].pixels.source_sha256).not.toBe(scopeRows[1].pixels.source_sha256);expect(scopeRows[0].aligned.derived_sha256).not.toBe(scopeRows[1].aligned.derived_sha256);expect(scopeRows[0].bright.derived_sha256).not.toBe(scopeRows[1].bright.derived_sha256);expect(scopeRows[0].adoption.version_id).not.toBe(scopeRows[1].adoption.version_id);
  // Complete both real mounting/read materializations before the immutable read phase.
  for(const s of scopeRows){opens.push(await derivedHandoff.handoffProject(page,s,origin));await enter(s);await panel().getByLabel('파생 편집 기준 버전',{exact:true}).selectOption(s.bright.id);await expect(panel().getByText('채택 후보 · '+s.actor,{exact:false})).toBeVisible();states[s.tag]=await savedState(s);}
  for(const s of scopeRows){snapshots[s.tag]=derivedHandoffSnapshot(s);expect(snapshots[s.tag].failures).toEqual([]);}derivedHandoffSave(e,w,'derived-handoff-all-declared-roots-before',Buffer.from(JSON.stringify({snapshots,states},null,2)));readonly=true;const openBase=opens.length;
  for(const tag of ['A','B','A'] as const){const s=scopeRows.find(v=>v.tag===tag)!,other=scopeRows.find(v=>v.tag!==tag)!;opens.push(await derivedHandoff.handoffProject(page,s,origin));await enter(s);const history=(await api('/api/data-workbench/derived?image_path='+encodeURIComponent(s.original))).versions;expect(history.map((r:any)=>r.id).sort()).toEqual([s.aligned.id,s.bright.id].sort());expect(history.find((r:any)=>r.id===s.bright.id)).toEqual(s.bright);const choice=panel().getByLabel('파생 편집 기준 버전',{exact:true});await expect(choice.locator('option')).toHaveCount(3);await expect(choice.locator('option[value="'+other.bright.id+'"]')).toHaveCount(0);
   for(const version of [s.aligned,s.bright]){await choice.selectOption(version.id);await expect(choice).toHaveValue(version.id);await expect(panel().getByRole('img',{name:'편집 원본과 변환 라벨 미리보기',exact:true})).toHaveAttribute('viewBox','0 0 '+version.size.join(' '));const provenance=panel().locator('details').filter({has:page.locator('summary').filter({hasText:'버전 출처와 보존 해시'})});if(await provenance.getAttribute('open')===null)await provenance.locator('summary').click();expect(JSON.parse((await provenance.locator('pre').innerText()))).toEqual({version:version.id,parent:version.parent_id,actor:version.actor,operation:version.operation,original_sha256:version.source_sha256,derived_sha256:version.derived_sha256,dataset_path:version.dataset_path});expect(derivedHandoffFile(version.file_path).pin.sha256).toBe(version.derived_sha256);}
   await expect(panel().getByText('채택 후보 · '+s.actor,{exact:false})).toBeVisible();await page.getByRole('navigation',{name:'Workflow Stages'}).getByRole('button').nth(0).click();await page.getByRole('button',{name:'파생 편집 · 검수한 학습 데이터 버전',exact:true}).click();const versions=page.getByRole('region',{name:'파생 편집 데이터 버전',exact:true});await expect(versions.getByRole('article',{name:s.adoption.name,exact:true})).toBeVisible();await expect(versions.getByRole('article',{name:other.adoption.name,exact:true})).toHaveCount(0);const listed=(await api('/api/data-workbench/derived-adoptions')).versions;expect(listed).toEqual([s.adoption]);expect(await api('/api/data-workbench/derived-adoptions/'+s.adoption.version_id)).toEqual(s.adoption);expect((await api('/api/project/current')).source_dataset_dir).toBe(s.source);await e.screenshot(page,'derived-saved-owning-'+tag+'-'+(tag==='A'&&readbacks.length===2?'return':'entry'));await versions.getByRole('button',{name:'닫기',exact:true}).click();await originalIntact(s);expect(await savedState(s)).toEqual(states[s.tag]);for(const row of scopeRows){const current=derivedHandoffSnapshot(row);expect(current.failures).toEqual([]);expect(current).toEqual(snapshots[row.tag]);}expect(readOnlyWrites).toEqual([]);readbacks.push({tag,project_id:s.project.id,source:s.source,version_ids:history.map((r:any)=>r.id),aligned_sha256:s.aligned.derived_sha256,bright_sha256:s.bright.derived_sha256,review:s.bright.review,adoption_record_sha256:s.adoption.record_sha256,owning_adoption:s.adoption.version_id,actual_version_selection:true,other_project_versions_absent:true});
  }
  expect(opens.length-openBase).toBe(3);expect(uiWrites.filter(r=>r.path==='/api/data-workbench/derived'&&r.method==='POST')).toHaveLength(4);expect(wireProofs.filter(r=>r.path.endsWith('/review'))).toHaveLength(2);expect(wireProofs.filter(r=>r.path==='/api/data-workbench/derived-adoptions')).toHaveLength(2);expect(wireProofs).toHaveLength(8);expect(readOnlyWrites).toEqual([]);
 }catch(error){primary=error;}
 finally{
  try{page.off('request',observe);}catch(error){if(primary===undefined)primary=error;}
  for(const s of scopeRows){try{after[s.tag]=derivedHandoffSnapshot(s);expect(after[s.tag].failures).toEqual([]);if(snapshots[s.tag]!==undefined)expect(after[s.tag]).toEqual(snapshots[s.tag]);}catch(error){if(primary===undefined)primary=error;}}
  try{derivedHandoffSave(e,w,'derived-handoff-all-declared-roots-after',Buffer.from(JSON.stringify(after,null,2)));}catch(error){if(primary===undefined)primary=error;}
  try{e.note('derived_saved_project_handoff',{scopeRows,wireProofs,uiWrites,readOnlyWrites,opens,controls,readbacks,saved_state_before:states,all_postroles_attempted:true,original_images_and_fixed_splits_unchanged:true,saved_training_source_reopened_without_training:true,read_phase_has_no_business_writes:true,full_declared_roots_guard:Object.keys(snapshots).length===2&&primary===undefined,scope:'source/annotations/dataset/reports/labelsets/branch/version record full namespace regular bytes and raw stat; runtime SQLite/models/whole project top-level are not in this GUI tree guard',new_cases:1,prospective_cells:['U014.align-version-save.handoff','U014.brightness-version-save.handoff','U014.derived-reviewed-adoption.handoff','U014.derived-new-training-source.reopen'],no_quality_human_training_or_activation_acceptance:true,primary:primary===undefined?null:String(primary)});}catch(error){if(primary===undefined)primary=error;}
 }
 if(primary!==undefined)throw primary;
}
test('saved derived alignment brightness review and training-source reopen retain their owning projects',async({page,renderer,workspace,evidence})=>{test.setTimeout(240_000);await installDesktopHostShim(page,renderer.port);const api=derivedHandoff.handoffApi(page,renderer.origin,false);await derivedSavedProjectHandoff(page,workspace,evidence,api,renderer.origin,renderer.url);});
