import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {execFileSync} from 'node:child_process';
import type {Page,Route} from '@playwright/test';
import {test,expect,type Workspace,type Evidence} from './fixtures/test';
import {installDesktopHostShim} from './fixtures/desktop-host-shim';
const harness=require('./fixtures/harness.cjs');
type Api=(route:string,body?:any,method?:string)=>Promise<any>;
const sha=(file:string)=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
test.use({actionTimeout:10_000});

async function exercise(page:Page,workspace:Workspace,evidence:Evidence,api:Api,url?:string){
 const name='Derived source safety controls';
 const seed=(project?:any)=>JSON.parse(execFileSync(harness.resolvePython(),[path.join(harness.REPO_ROOT,'scripts/e2e/fixtures/derived_workflow_data.py'),workspace.root,...(project?[JSON.stringify(project)]:[])],{encoding:'utf8',timeout:15_000}));
 const fixture=seed();await api('/api/project/create',{name,task:'classification'});const project=await api('/api/project/update',{source_dataset_dir:fixture.source},'PUT');await api('/api/dataset/import',{folder_path:fixture.source,task:'classification'});const split=seed(project);
 const navigate=async()=>{if(url)await page.goto(url);else await page.reload();await expect(page.getByTitle('프로젝트 관리',{exact:true})).toContainText(name);await page.getByRole('navigation',{name:'Workflow Stages'}).getByRole('button').nth(0).click();};
 const panel=page.getByRole('region',{name:'파생 편집 데이터 버전'}),toggle=()=>page.getByRole('button',{name:'파생 편집 · 검수한 학습 데이터 버전',exact:true}).click();
 const use=panel.getByRole('button',{name:'검수한 파생 버전을 데이터 원본으로 선택',exact:true}),back=panel.getByRole('button',{name:'검증한 편집 전 원본으로 돌아가기',exact:true});
 await navigate();await toggle();await expect(panel.getByText('검수한 파생 학습 버전이 없습니다. 2단계의 원본 보존 이미지 편집에서 생성하세요.',{exact:true})).toBeVisible();await expect(use).toHaveCount(0);await expect(back).toHaveCount(0);expect((await api('/api/project/current')).source_dataset_dir).toBe(fixture.source);
 const image=fixture.images.find((r:any)=>r.relative_path==='train/NG/train_NG_00.png');await api('/api/annotations/save',{image_id:path.basename(image.path,'.png'),image_path:image.path,image_width:64,image_height:64,actor:'fixture-derived-editor',annotations:[{id:'preserved-bbox',type:'bbox',label:'NG',category_id:1,bbox:[8,10,40,44]}]});const originalLabels=await api('/api/annotations/'+path.basename(image.path,'.png')+'?file_path='+encodeURIComponent(image.path));const row=await api('/api/dataset/metadata/image?image_path='+encodeURIComponent(image.path));
 const derived=await api('/api/data-workbench/derived',{image_path:image.path,expected_sha256:image.sha256,expected_revision:row.revision,actor:'fixture-derived-editor',operation:{kind:'brightness',factor:.7}});
 await api(`/api/data-workbench/derived/${derived.id}/review`,{expected_revision:derived.review_revision||0,actor:'fixture-derived-reviewer',decision:'approve',note:'Generated pixels for source-selection controls only; not process quality acceptance'});
 const version=await api('/api/data-workbench/derived-adoptions',{version_ids:[derived.id],actor:'fixture-derived-reviewer',name:'Owned reviewed derivative'});expect(version.activated).toBe(false);expect(version.adopted).toHaveLength(1);
 await panel.getByRole('button',{name:'파생 학습 버전 새로 확인',exact:true}).click();await expect(use).toBeEnabled();await expect(back).toBeDisabled();
 const branch=path.join(version.source_dataset_path,version.adopted[0].relative_path),record=path.join(path.dirname(version.source_dataset_path),'record.json');
 const protectedFiles=[...fixture.images.map((r:any)=>r.path),branch,record,split.split_path,originalLabels.mask_file,derived.file_path,path.join(derived.dataset_path,'review.json')],originalHashes=Object.fromEntries(protectedFiles.map(file=>[file,sha(file)]));
 let projectWrites=0,trainingPosts=0;page.on('request',r=>{const u=new URL(r.url());if(r.method()==='PUT'&&u.pathname==='/api/project/update')projectWrites++;if(r.method()==='POST'&&u.pathname==='/api/training/start')trainingPosts++;});
 // Closing before choosing submits no source selection. It is not a claim
 // that an already submitted operation is cancelled by closing the panel.
 await panel.getByRole('button',{name:'닫기',exact:true}).click();expect(projectWrites).toBe(0);expect((await api('/api/project/current')).source_dataset_dir).toBe(fixture.source);await toggle();await expect(use).toBeEnabled();
 const verifyProtected=()=>{for(const [file,digest]of Object.entries(originalHashes))expect(sha(file),file).toBe(digest);};verifyProtected();
 const route=`**/api/data-workbench/derived-adoptions/${version.version_id}`;
 let entered!:()=>void,release!:()=>void;const accepted=new Promise<void>(resolve=>entered=resolve),hold=new Promise<void>(resolve=>release=resolve);
 const delayedFailure=async(r:Route)=>{entered();await hold;await r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({detail:'Controlled derived selection unavailable'})});};
 await page.route(route,delayedFailure);await use.click();await accepted;await expect(use).toBeDisabled();await expect(back).toBeDisabled();await expect(panel.getByRole('button',{name:'파생 학습 버전 새로 확인',exact:true})).toBeDisabled();expect(projectWrites).toBe(0);release();await expect(panel.getByRole('alert')).toContainText('Controlled derived selection unavailable');await page.unroute(route,delayedFailure);verifyProtected();expect((await api('/api/project/current')).source_dataset_dir).toBe(fixture.source);await evidence.screenshot(page,'derived-selection-controlled-error-no-write');
 const branchOriginal=fs.readFileSync(branch);let invalidSelect='';
 try{fs.writeFileSync(branch,Buffer.from('owned changed derived-source fixture'));const event=page.waitForResponse(r=>new URL(r.url()).pathname===`/api/data-workbench/derived-adoptions/${version.version_id}`);await use.click();const r=await event;expect(r.status()).toBe(422);invalidSelect=await panel.getByRole('alert').innerText();expect(invalidSelect).toMatch(/changed|differs/i);expect((await api('/api/project/current')).source_dataset_dir).toBe(fixture.source);expect(projectWrites).toBe(0);await evidence.screenshot(page,'changed-derived-source-actual-refusal');}finally{fs.writeFileSync(branch,branchOriginal);}
 verifyProtected();await use.click();await expect.poll(async()=>(await api('/api/project/current')).source_dataset_dir).toBe(version.source_dataset_path);await expect(use).toBeDisabled();await expect(back).toBeEnabled();
 await navigate();await toggle();await expect(back).toBeEnabled();await expect(use).toBeDisabled();verifyProtected();const writesBeforeCancel=projectWrites;await panel.getByRole('button',{name:'닫기',exact:true}).click();expect(projectWrites).toBe(writesBeforeCancel);expect((await api('/api/project/current')).source_dataset_dir).toBe(version.source_dataset_path);await toggle();await expect(back).toBeEnabled();
 const parentRoute=route+'/parent',fail=async(r:Route)=>r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({detail:'Controlled original return unavailable'})});await page.route(parentRoute,fail);await back.click();await expect(panel.getByRole('alert')).toContainText('Controlled original return unavailable');await page.unroute(parentRoute,fail);verifyProtected();expect(projectWrites).toBe(writesBeforeCancel);expect((await api('/api/project/current')).source_dataset_dir).toBe(version.source_dataset_path);
 const parentOriginal=fs.readFileSync(image.path);let invalidParent='';
 try{fs.writeFileSync(image.path,Buffer.from('owned changed parent-source fixture'));const event=page.waitForResponse(r=>new URL(r.url()).pathname===`/api/data-workbench/derived-adoptions/${version.version_id}/parent`);await back.click();const r=await event;expect(r.status()).toBe(422);invalidParent=await panel.getByRole('alert').innerText();expect(invalidParent).toMatch(/changed|differs/i);expect((await api('/api/project/current')).source_dataset_dir).toBe(version.source_dataset_path);expect(projectWrites).toBe(writesBeforeCancel);await evidence.screenshot(page,'changed-parent-source-actual-return-refusal');}finally{fs.writeFileSync(image.path,parentOriginal);}
 verifyProtected();await back.click();await expect.poll(async()=>(await api('/api/project/current')).source_dataset_dir).toBe(fixture.source);await navigate();await toggle();await expect(use).toBeEnabled();await expect(back).toBeDisabled();await evidence.screenshot(page,'exact-parent-restored-explicit-return-reopened');verifyProtected();
 expect(trainingPosts).toBe(0);expect((await api('/api/annotations/'+path.basename(image.path,'.png')+'?file_path='+encodeURIComponent(image.path))).annotations).toEqual(originalLabels.annotations);for(const file of protectedFiles)evidence.addFile(file);evidence.note('derived_source_controls',{actual_ui_and_backend:true,fixture,project,split,originalLabels,derived,version,originalHashes,empty_registry_no_selection_controls:true,inactive_return_disabled:true,unsubmitted_close_no_source_write:true,controlled_503_no_write_and_busy_lock:true,changed_branch_actual_422:invalidSelect,changed_parent_actual_422:invalidParent,exact_bytes_restored_before_retry:true,explicit_source_switch_and_return:true,actual_reload_saved_source_and_controls:true,protected_files_preserved:true,trainingPosts,synthetic_not_quality_approval:true,independent_acceptance:false});
}
test('derived source selection and verified return preserve bytes through empty invalid error cancel and reopen',async({page,request,renderer,workspace,evidence})=>{test.setTimeout(180_000);await installDesktopHostShim(page,renderer.port);const api:Api=async(route,body,method)=>{const r=await request.fetch(renderer.origin+route,{method:method||(body===undefined?'GET':'POST'),...(body===undefined?{}:{data:body})});expect(r.ok(),await r.text()).toBe(true);return r.json();};await exercise(page,workspace,evidence,api,renderer.url);});
test('native derived source selection and verified return preserve bytes through empty invalid error cancel and reopen',{tag:'@electron'},async({electronSession,workspace,evidence})=>{test.setTimeout(180_000);const {window}=electronSession,status=await electronSession.waitForBackend();const api:Api=(route,body,method)=>window.evaluate(async({port,route,body,method})=>{const r=await fetch(`http://127.0.0.1:${port}${route}`,{method:method||(body===undefined?'GET':'POST'),...(body===undefined?{}:{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})});if(!r.ok)throw Error(`Owned derivative control HTTP ${r.status}: ${await r.text()}`);return r.json();},{port:status.port,route,body,method});await exercise(window,workspace,evidence,api);});
