import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {execFileSync} from 'node:child_process';
import type {Page} from '@playwright/test';import {test,expect,type Workspace,type Evidence} from './fixtures/test';
const harness=require('./fixtures/harness.cjs');type Api=(route:string,body?:any)=>Promise<any>;test.use({actionTimeout:10_000});
async function exercise(page:Page,workspace:Workspace,evidence:Evidence,api:Api,url?:string){
 const helper=path.join(harness.REPO_ROOT,'scripts/e2e/fixtures/dino_segmentation_data.py');const fixture=JSON.parse(execFileSync(harness.resolvePython(),[helper,workspace.root],{encoding:'utf8',timeout:15_000}));
 await api('/api/project/create',{name:'Authentic DINO dense masks and original tiles',task:'segmentation'});await api('/api/project/update',{source_dataset_dir:fixture.source});const project=await api('/api/project/current');await api('/api/dataset/import',{folder_path:fixture.source,task:'segmentation'});
 const split=JSON.parse(execFileSync(harness.resolvePython(),[helper,workspace.root,JSON.stringify(project)],{encoding:'utf8',timeout:15_000}));expect(split.paired_flip_exact).toBe(true);
 if(url)await page.goto(url);else await page.reload();await expect(page.getByTitle('프로젝트 관리',{exact:true})).toContainText(project.name);const stage=(i:number)=>page.getByRole('navigation',{name:'Workflow Stages'}).getByRole('button').nth(i).click();await stage(2);
 await expect(page.getByRole('combobox',{name:'학습 모델 구조',exact:true})).toHaveValue('dinov3_vits16');await page.getByLabel('수동 학습 횟수',{exact:true}).fill('2');await page.getByLabel('수동 학습 입력 크기',{exact:true}).fill('64');
 await page.locator('summary').filter({hasText:'사전학습 파일 가져오기 · 상세 설정'}).click();await page.getByLabel('사전학습 가중치 파일',{exact:true}).fill(fixture.weights);await page.locator('summary').filter({hasText:'다음 학습 배치·로컬 장치 설정'}).click();await page.getByLabel('다음 학습 배치 크기',{exact:true}).fill('2');await page.getByLabel('다음 학습 로컬 장치',{exact:true}).selectOption('cpu');
 let waiting=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/training-workspace/readiness'&&r.request().method()==='POST');await page.getByRole('button',{name:'로컬 준비 검사',exact:true}).click();let response=await waiting;expect(response.ok()).toBe(true);const ready=await response.json();expect(ready.ready).toBe(true);expect(ready.weights.sha256).toBe(fixture.weights_sha256);
 await page.locator('summary').filter({hasText:'학습 실행 예산·대기열'}).click();await page.getByLabel('학습 시간 제한 (분)',{exact:true}).fill('2');waiting=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/training/start'&&r.request().method()==='POST');await page.getByRole('button',{name:'선택 설정으로 학습 시작',exact:true}).click();response=await waiting;expect(response.ok(),await response.text()).toBe(true);const posted=response.request().postDataJSON(),accepted=await response.json(),jobId=accepted.job_id;expect(posted).toMatchObject({task:'segmentation',device:'cpu',config_overrides:{model_name:'dinov3_vits16',train_mode:'head_only',epochs:2,image_size:64,batch_size:2,pretrained_checkpoint:fixture.weights}});
 let terminal:any;await expect.poll(async()=>{terminal=await api('/api/training/status?job_id='+jobId);if(['failed','cancelled','aborted'].includes(terminal.status))throw Error(JSON.stringify(terminal));return terminal.status;},{timeout:125_000}).toBe('completed');await expect(page.getByRole('region',{name:'학습 로그'})).toContainText('완료',{timeout:20_000});
 const metadata=JSON.parse(fs.readFileSync(path.join(project.models_dir,jobId,'model_meta.json'),'utf8'));expect(metadata.pretrained_sha256).toBe(fixture.weights_sha256);expect(metadata.classes).toEqual(['background','scratch','stain']);expect(metadata.augmentation_contract).toMatchObject({version:1,target_sync:true,mask_interpolation:'nearest'});
 waiting=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/evaluation/results'&&r.request().method()==='GET');await stage(3);response=await waiting;expect(response.ok(),await response.text()).toBe(true);const evaluated=await response.json();expect(evaluated.job_id).toBe(jobId);expect(evaluated.metrics.evaluated_split).toBe('test');expect(evaluated.test_predictions).toHaveLength(2);
 for(const metric of ['miou','mdice','pixel_accuracy','foreground_iou'])expect(Number.isFinite(evaluated.metrics[metric])).toBe(true);for(const row of evaluated.test_predictions){expect(row.pixel_evidence).toMatchObject({coordinate_space:'model_input',shape:[64,64],mapping:{kind:'full_image_resize',source_size:[128,96]}});expect(row.pixel_evidence.prediction_mask).toMatch(/^data:image\/png;base64,/);expect(row.pixel_evidence.truth_mask).toMatch(/^data:image\/png;base64,/);expect(Object.keys(row.class_scores)).toEqual(metadata.classes);}
 await evidence.screenshot(page,'authentic-dino-heldout-pixel-metrics');await page.reload();await stage(3);await expect(page.getByText('시험 분할 (Test)',{exact:false})).toBeVisible();await stage(4);
 const inspector=page.getByRole('group',{name:'원본 타일 결함 분할 노드 · 선택 안됨',exact:true});await inspector.click();await page.getByRole('combobox',{name:'완료된 학습 모델',exact:true}).selectOption(jobId);await page.getByLabel('결함 판정 임계치',{exact:true}).fill('0.2');
 await page.locator('summary').filter({hasText:'빠른 노드 추가·연결·실행 자원'}).click();await page.getByRole('button',{name:'Blob 측정',exact:true}).click();const selectedBlob=page.locator('[data-flow-node-id]').filter({has:page.getByRole('group',{name:'Blob 측정 1 노드 · 선택됨',exact:true})});await expect(selectedBlob).toHaveCount(1);const blobId=await selectedBlob.getAttribute('data-flow-node-id'),blob=page.locator(`[data-flow-node-id="${blobId}"]`);await page.getByLabel('최소 Blob 면적 (px²)',{exact:true}).fill('2');await page.getByLabel('NG 기준 Blob 개수',{exact:true}).fill('1');
 const originalNode=page.locator('[data-flow-node-id="node_inspect"]');await originalNode.getByRole('button',{name:/RESULT OUT$/}).click();await blob.getByRole('button',{name:/RESULT IN$/}).click();await blob.getByRole('button',{name:/RESULT OUT$/}).click();await page.locator('[data-flow-node-id="node_decision"]').getByRole('button',{name:/RESULT IN$/}).click();
 await page.getByRole('button',{name:'플로우 저장',exact:true}).click();const dialog=page.getByRole('dialog',{name:'검사 규칙 변경 저장',exact:true});await expect(dialog).toBeVisible();waiting=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/flowchart/pipeline'&&r.request().method()==='POST');await dialog.getByRole('button',{name:'변경 저장',exact:true}).click();response=await waiting;expect(response.ok(),await response.text()).toBe(true);const saved=await response.json();await evidence.screenshot(page,'authentic-dino-original-tile-blob-recipe');
 const reopened=await api('/api/flowchart/pipeline/active?source_dataset_path='+encodeURIComponent(fixture.source)),pipeline=reopened.pipeline||reopened;expect(pipeline.nodes.find((n:any)=>n.data.node_type==='inspection').data).toMatchObject({model_job_id:jobId,threshold:0.2});expect(pipeline.nodes.find((n:any)=>n.data.node_type==='blob_measure').data.params).toMatchObject({min_blob_area_px:2,min_blob_count_for_ng:1});const selected=fixture.files.find((f:any)=>f.split==='test'&&f.defect).path;
 const flow=await api('/api/flowchart/run',{image_path:selected,pipeline,execution_target:'local',device:'cpu'});expect(['OK','NG']).toContain(flow.final_verdict);const crop=flow.crops.find((c:any)=>c.blob_count!==null);expect(crop).toMatchObject({bbox:[0,0,128,96],tiles_processed:6});expect(crop.segmentation_classes).toHaveLength(3);for(const row of crop.segmentation_classes){expect(row.mask.shape).toEqual([96,128]);expect(row.probability.shape).toEqual([96,128]);expect(row.bbox).toEqual([0,0,128,96]);}
 const offline=JSON.parse(execFileSync(harness.resolvePython(),[path.join(harness.REPO_ROOT,'scripts/e2e/fixtures/patch_recipe_package_readback.py'),JSON.stringify({project_dir:project.project_dir,job_id:jobId,mode:'segmentation',pipeline,flow_result:flow,source:selected})],{encoding:'utf8',timeout:55_000}));expect(offline.comparison.status).toBe('passed');
 for(const file of fixture.files){for(const [name,key] of [['path','sha256'],['annotation','annotation_sha256']]){expect(crypto.createHash('sha256').update(fs.readFileSync(file[name])).digest('hex')).toBe(file[key]);evidence.addFile(file[name]);}}evidence.addFile(split.split_path);
 evidence.note('dino_segmentation_qualification',{fixture,project,split,ready,posted,terminal,metadata,evaluated,saved,reopened,pipeline,flow,offline,actual_app_button_training:true,actual_official_pretrained:true,actual_cpu:true,actual_paired_mask_augmentation:true,actual_pixel_metrics:true,actual_original_tiling:true,actual_blob_recipe:true,actual_reopen:true,actual_fresh_candidate_package:true,no_original_mutation:true,gpu_verified:false,quality_approval:false});
}
test('authentic DINO dense masks pixel metrics original tiles Blob and offline candidate',{tag:'@owned-model'},async({page,request,renderer,workspace,evidence})=>{test.setTimeout(240_000);const api:Api=async(route,body)=>{const r=body===undefined?await request.get(renderer.origin+route):route.endsWith('/update')?await request.put(renderer.origin+route,{data:body}):await request.post(renderer.origin+route,{data:body});expect(r.ok(),await r.text()).toBe(true);return r.json();};await exercise(page,workspace,evidence,api,renderer.url);});
test('native authentic DINO dense masks train evaluate tile Blob reopen and export',{tag:['@electron','@owned-model']},async({electronSession,workspace,evidence})=>{test.setTimeout(240_000);const {window}=electronSession;const backend=await electronSession.waitForBackend();const api:Api=(route,body)=>window.evaluate(async({port,route,body})=>{const r=await fetch(`http://127.0.0.1:${port}${route}`,{...(body===undefined?{}:{method:route.endsWith('/update')?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})});if(!r.ok)throw Error(`Owned API ${r.status}: ${await r.text()}`);return r.json();},{port:backend.port,route,body});await exercise(window,workspace,evidence,api);});
