import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {execFileSync} from 'node:child_process';
import type {Page} from '@playwright/test';import {test,expect,type Workspace,type Evidence} from './fixtures/test';
const harness=require('./fixtures/harness.cjs');type Api=(route:string,body?:any)=>Promise<any>;test.use({actionTimeout:10_000});
async function exercise(page:Page,workspace:Workspace,evidence:Evidence,api:Api,url?:string){
 const fixture=JSON.parse(execFileSync(harness.resolvePython(),[path.join(harness.REPO_ROOT,'scripts/e2e/fixtures/dino_patch_data.py'),workspace.root,process.env.MV_E2E_DINO_CHECKPOINT||''],{encoding:'utf8',timeout:15_000}));
 await api('/api/project/create',{name:'Authentic DINOv3 patch recipe',task:'segmentation'});await api('/api/project/update',{source_dataset_dir:fixture.source});const project=await api('/api/project/current');
 await api('/api/dataset/import',{folder_path:fixture.source,task:'segmentation'});if(url)await page.goto(url);else await page.reload();await expect(page.getByTitle('프로젝트 관리',{exact:true})).toContainText(project.name);
 const enter=async()=>{await page.getByRole('navigation',{name:'Workflow Stages'}).getByRole('button').nth(2).click();await page.getByRole('region',{name:'모델 학습 허브'}).getByRole('button',{name:/^패치 분류/}).click();};await enter();
 await page.getByLabel('원본 패치 크기',{exact:true}).fill('16');await page.getByLabel('패치 간격',{exact:true}).fill('16');
 let waiting=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/patch-classification/prepare'&&r.request().method()==='POST');await page.getByRole('button',{name:'영역 라벨에서 패치 준비',exact:true}).click();let response=await waiting;expect(response.ok()).toBe(true);const prepared=await response.json();expect(prepared.patch_count).toBe(36);
 const panel=page.getByRole('region',{name:'원본 패치 정답·판정 미리보기'});await expect(panel.getByAltText('검수 정답 패치')).toBeVisible();expect((await panel.getByAltText('검수 정답 패치').boundingBox())!.width).toBeGreaterThan(100);await expect(panel.getByRole('img',{name:'패치 정답의 원본 위치'})).toHaveAttribute('viewBox','0 0 35 29');
 await page.getByLabel('Epoch',{exact:true}).fill('2');await page.getByLabel('배치 크기',{exact:true}).fill('4');await page.getByLabel('모델 입력 크기',{exact:true}).fill('32');
 await page.locator('summary').filter({hasText:'사전학습 파일 지정'}).click();await page.getByLabel('패치 DINOv3 사전학습 파일').fill(fixture.weights);await page.locator('summary').filter({hasText:'학습 실행 예산·대기열'}).click();await page.getByLabel('학습 시간 제한 (분)',{exact:true}).fill('2');
 waiting=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/patch-classification/train'&&r.request().method()==='POST');await page.getByRole('button',{name:'패치 분류 후보 학습',exact:true}).click();response=await waiting;expect(response.ok(),await response.text()).toBe(true);const posted=response.request().postDataJSON(),accepted=await response.json(),jobId=accepted.job_id;expect(posted).toMatchObject({device:'cpu',epochs:2,image_size:32,backbone:'dinov3_vits16',max_runtime_s:120,pretrained_checkpoint:fixture.weights});
 let terminal:any;await expect.poll(async()=>{terminal=await api('/api/training/status?job_id='+jobId);if(['failed','cancelled','aborted'].includes(terminal.status))throw Error(JSON.stringify(terminal));return terminal.status;},{timeout:125_000}).toBe('completed');await expect(page.getByRole('combobox',{name:'완료 패치 분류 후보',exact:true})).toHaveValue(jobId,{timeout:20_000});
 const model=(await api('/api/evaluation/model-comparisons/models?source_dataset_path='+encodeURIComponent(fixture.source)+'&task=patch_classification')).models.find((r:any)=>r.job_id===jobId);expect(model).toBeTruthy();model.metadata=JSON.parse(fs.readFileSync(path.join(project.models_dir,jobId,'model_meta.json'),'utf8'));expect(model.metadata.pretrained_sha256).toBe(fixture.weights_sha256);expect(model.metadata.encoder_architecture).toBe('vit_small_patch16_dinov3.lvd1689m');
 waiting=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/patch-classification/evaluate'&&r.request().method()==='POST');await page.getByRole('button',{name:'시험 평가',exact:true}).click();response=await waiting;expect(response.ok(),await response.text()).toBe(true);const evaluated=await response.json();
 const testIndex=JSON.parse(fs.readFileSync(path.join(prepared.dataset_path,'patches.json'),'utf8')).patches.findIndex((r:any)=>r.split==='test');expect(testIndex).toBeGreaterThanOrEqual(0);await panel.getByLabel('정답 패치 번호',{exact:true}).fill(String(testIndex));await expect(panel).toContainText('test');const sample=await api('/api/patch-classification/sample?dataset_path='+encodeURIComponent(prepared.dataset_path)+'&sample_index='+testIndex);const selected=path.join(fixture.source,sample.source_relative_path);
 await panel.getByLabel('패치 결함 임계치',{exact:true}).fill('.37');await panel.getByLabel('NG 투표 비율',{exact:true}).fill('.75');await panel.getByLabel('최소 NG 패치 수',{exact:true}).fill('3');
 const runs:any[]=[];for(const mode of ['max','vote','ng_count']){
  await panel.getByRole('combobox',{name:'패치 전체 판정 방식',exact:true}).selectOption(mode);waiting=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/patch-classification/predict'&&r.request().method()==='POST');await panel.getByRole('button',{name:'선택 원본 패치 검사',exact:true}).click();response=await waiting;expect(response.ok(),await response.text()).toBe(true);const prediction=await response.json();expect(prediction.source_size).toEqual([35,29]);expect(prediction.patch_count).toBe(6);expect(prediction.recipe).toMatchObject({mode,threshold:.37,vote_fraction:.75,minimum_ng_count:3});
  await expect(panel.getByAltText('패치 결함 확률 지도 (미리보기)')).toBeVisible();expect((await panel.getByAltText('패치 결함 확률 지도 (미리보기)').boundingBox())!.height).toBeGreaterThan(100);expect(await panel.getByRole('img',{name:'원본 좌표 패치 검사 결과'}).locator('rect').count()).toBe(6);
  const pipeline=await api('/api/patch-classification/recipe-flow',{job_id:jobId,recipe:prediction.recipe});const flow=await api('/api/flowchart/run',{image_path:selected,pipeline,execution_target:'local',device:'cpu'});expect(flow.final_verdict).toBe(prediction.decision==='FAIL'?'NG':'OK');expect(flow.crops.map((r:any)=>r.bbox)).toEqual(prediction.patches.map((r:any)=>r.box));
  const offline=JSON.parse(execFileSync(harness.resolvePython(),[path.join(harness.REPO_ROOT,'scripts/e2e/fixtures/patch_recipe_package_readback.py'),JSON.stringify({project_dir:project.project_dir,job_id:jobId,mode,pipeline,flow_result:flow,source:selected})],{encoding:'utf8',timeout:55_000}));expect(offline.comparison.status).toBe('passed');runs.push({mode,prediction,pipeline,flow,offline});
 }
 await panel.scrollIntoViewIfNeeded();await evidence.screenshot(page,'authentic-dino-patch-original-boxes-probability-recipe');await page.reload();await enter();await expect(page.getByRole('combobox',{name:'완료 패치 분류 후보',exact:true})).toHaveValue(jobId);await expect(panel.getByRole('combobox',{name:'패치 전체 판정 방식',exact:true})).toHaveValue('ng_count');await expect(panel.getByLabel('패치 결함 임계치',{exact:true})).toHaveValue('0.37');
 waiting=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/flowchart/pipeline'&&r.request().method()==='POST');await panel.getByRole('button',{name:'패치 판정 플로우 저장',exact:true}).click();response=await waiting;expect(response.ok(),await response.text()).toBe(true);const saved=await response.json();const reopened=await api('/api/flowchart/pipeline/active?source_dataset_path='+encodeURIComponent(fixture.source));expect(reopened.nodes.find((n:any)=>n.data.node_type==='decision').data.params.patch_recipe).toEqual(runs.at(-1).prediction.recipe);await evidence.screenshot(page,'saved-dino-patch-recipe-flow');
 for(const file of fixture.files){expect(crypto.createHash('sha256').update(fs.readFileSync(file.path)).digest('hex')).toBe(file.sha256);evidence.addFile(file.path);}expect(crypto.createHash('sha256').update(fs.readFileSync(fixture.weights)).digest('hex')).toBe(fixture.weights_sha256);evidence.addFile(path.join(prepared.dataset_path,'patches.json'));
 evidence.note('dino_patch_recipe_qualification',{fixture,project,prepared,posted,terminal,model,evaluated,sample,runs,saved,reopened,actual_authentic_dino_training:true,actual_preview_and_heatmap:true,actual_three_recipe_flow_package_parity:true,actual_reopen:true,no_original_mutation:true,quality_approval:false});
}
test('authentic DINOv3 patch CPU candidate previews three decision recipes and portable flow parity',async({page,request,renderer,workspace,evidence})=>{test.setTimeout(300_000);const api:Api=async(route,body)=>{const r=body===undefined?await request.get(renderer.origin+route):route.endsWith('/update')?await request.put(renderer.origin+route,{data:body}):await request.post(renderer.origin+route,{data:body});expect(r.ok(),await r.text()).toBe(true);return r.json();};await exercise(page,workspace,evidence,api,renderer.url);});
test('native authentic DINOv3 patch preserves original coordinates recipes reopen and offline parity',{tag:'@electron'},async({electronSession,workspace,evidence})=>{test.setTimeout(300_000);const {window}=electronSession;const backend=await electronSession.waitForBackend();const api:Api=(route,body)=>window.evaluate(async({port,route,body})=>{const r=await fetch(`http://127.0.0.1:${port}${route}`,{...(body===undefined?{}:{method:route.endsWith('/update')?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})});if(!r.ok)throw Error(`Owned API ${r.status}: ${await r.text()}`);return r.json();},{port:backend.port,route,body});await exercise(window,workspace,evidence,api);});
