import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {execFileSync} from 'node:child_process';
import type {Page} from '@playwright/test';import {test,expect,type Workspace,type Evidence} from './fixtures/test';
const harness=require('./fixtures/harness.cjs');type Api=(route:string,body?:any)=>Promise<any>;
test.use({actionTimeout:10_000});
async function exercise(page:Page,workspace:Workspace,evidence:Evidence,api:Api,url?:string){
 const fixture=JSON.parse(execFileSync(harness.resolvePython(),[path.join(harness.REPO_ROOT,'scripts/e2e/fixtures/enhancement_pair_data.py'),workspace.root],{encoding:'utf8',timeout:15_000}));
 await api('/api/project/create',{name:'Explicit enhancement qualification',task:'classification'});await api('/api/project/update',{source_dataset_dir:fixture.source});const project=await api('/api/project/current');
 await api('/api/dataset/import',{folder_path:fixture.source,task:'classification'});
 const split=JSON.parse(execFileSync(harness.resolvePython(),[path.join(harness.REPO_ROOT,'scripts/e2e/fixtures/enhancement_pair_data.py'),workspace.root,JSON.stringify(project)],{encoding:'utf8',timeout:15_000}));
 if(url)await page.goto(url);else await page.reload();await expect(page.getByTitle('프로젝트 관리',{exact:true})).toContainText(project.name);
 const enter=async()=>{await page.getByRole('navigation',{name:'Workflow Stages'}).getByRole('button').nth(2).click();await page.getByRole('region',{name:'모델 학습 허브'}).getByRole('button',{name:/^이미지 개선/}).click();};await enter();
 await page.locator('summary').filter({hasText:'실제 입력·정답 쌍 가져오기'}).click();
 await page.getByLabel('이미지 개선 정답 이미지 폴더').fill(fixture.targets);
 const text=(rows:any[])=>rows.map(r=>`${r.input}\t${r.target}\t${r.split}`).join('\n');
 const bad=fixture.rows.map((r:any,i:number)=>i===1?{...r,target:'missing.png'}:r);
 await page.getByLabel('이미지 개선 실제 쌍 표').fill(text(bad));
 let waiting=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/enhancement/pairs/import'&&r.request().method()==='POST');await page.getByRole('button',{name:'실제 정답 쌍 가져오기',exact:true}).click();let wire=await waiting;expect(wire.status()).toBe(422);const refusal=await wire.json();await expect(page.getByRole('alert').filter({hasText:'missing'})).toBeVisible();
 await page.getByLabel('이미지 개선 실제 쌍 표').fill(text(fixture.rows));waiting=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/enhancement/pairs/import'&&r.request().method()==='POST');await page.getByRole('button',{name:'실제 정답 쌍 가져오기',exact:true}).click();wire=await waiting;expect(wire.ok()).toBe(true);const prepared=await wire.json();expect(prepared.mode).toBe('explicit_pairs');expect(prepared.records).toHaveLength(6);
 const viewer=page.getByRole('region',{name:'이미지 개선 원본·정답·출력 비교'});await expect(viewer.getByAltText('이미지 개선 입력 원본')).toBeVisible();await expect(viewer.getByAltText('이미지 개선 대응 정답')).toBeVisible();await expect(viewer).toContainText('직접 검토');
 await page.getByLabel('이미지 개선 학습 epoch').fill('3');await page.locator('summary').filter({hasText:'학습 시간 제한'}).click();await page.getByLabel('학습 시간 제한 (분)',{exact:true}).fill('1');
 waiting=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/enhancement/train'&&r.request().method()==='POST');await page.getByRole('button',{name:'이미지 개선 후보 학습',exact:true}).click();wire=await waiting;expect(wire.ok()).toBe(true);const posted=wire.request().postDataJSON(),accepted=await wire.json(),jobId=accepted.job_id;expect(posted).toMatchObject({device:'cpu',epochs:3,max_runtime_s:60});
 await expect.poll(async()=>(await api(`/api/enhancement/jobs/${jobId}`)).status,{timeout:65_000}).toBe('completed');await expect(page.getByRole('combobox',{name:'완료 후보 모델',exact:true})).toHaveValue(jobId,{timeout:20_000});
 const terminal=await api(`/api/enhancement/jobs/${jobId}`),model=(await api('/api/enhancement/models')).models.find((r:any)=>r.job_id===jobId);expect(model.metadata.epochs_completed).toBe(3);expect(model.metadata.mode).toBe('explicit_pairs');
 waiting=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/enhancement/evaluate'&&r.request().method()==='POST');await page.getByRole('button',{name:'시험 분할 평가',exact:true}).click();wire=await waiting;expect(wire.ok()).toBe(true);const evaluated=await wire.json();expect(evaluated.sample_count).toBe(2);expect(evaluated.evaluation_geometry.resize).toBe(false);expect(evaluated.defect_preservation_status).toBe('unreviewed');expect(Number.isFinite(evaluated.input_ssim)&&Number.isFinite(evaluated.output_ssim)).toBe(true);await expect(page.getByText(/SSIM \(RGB, 7×7\)/)).toBeVisible();
 await page.getByLabel('이미지 개선 비교 쌍').selectOption('4');await expect(viewer.getByAltText('이미지 개선 입력 원본')).toBeVisible();waiting=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/enhancement/predict'&&r.request().method()==='POST');await viewer.getByRole('button',{name:'원본·개선본 비교',exact:true}).click();wire=await waiting;expect(wire.ok()).toBe(true);const prediction=await wire.json();await expect(viewer.getByAltText('선택 후보 이미지 개선 출력')).toBeVisible();await viewer.scrollIntoViewIfNeeded();await evidence.screenshot(page,'explicit-enhancement-original-target-candidate-comparison');
 const selected=path.join(fixture.source,fixture.rows[4].input);
 await page.reload();await enter();await expect(page.getByRole('combobox',{name:'완료 후보 모델',exact:true})).toHaveValue(jobId);await expect(page.getByLabel('이미지 개선 비교 쌍')).toHaveCount(1);await expect(viewer.getByAltText('이미지 개선 입력 원본')).toBeVisible();
 // A real no-pretrained classifier provides a downstream consumer; no mock
 // inference weights or completed-job receipts are substituted.
 const downstream=await api('/api/training/start',{task:'classification',preset:'fast',dataset_path:fixture.source,device:'cpu',queue:false,max_runtime_s:90,config_overrides:{backbone:'resnet18',pretrained:false,epochs:2,image_size:64,batch_size:2,num_workers:0,learning_rate:.001}});
 let downstreamTerminal:any;await expect.poll(async()=>{downstreamTerminal=await api('/api/training/status?job_id='+downstream.job_id);if(['failed','cancelled'].includes(downstreamTerminal.status))throw Error(JSON.stringify(downstreamTerminal));return downstreamTerminal.status;},{timeout:95_000}).toBe('completed');
 await page.getByRole('button',{name:'검사 플로우·배포 패키지',exact:true}).click();const binding=page.getByRole('region',{name:'선택 모델 플로우 연결'});await expect(binding).toBeVisible();await binding.getByRole('button',{name:'선택 모델 연결',exact:true}).click();await evidence.screenshot(page,'enhancement-selected-model-flow-binding');
 const pipeline=await api('/api/flowchart/templates/single-segmentation?inspection_task=classification&job_id='+downstream.job_id);
 const input=pipeline.nodes.find((n:any)=>n.data.node_type==='input'),inspect=pipeline.nodes.find((n:any)=>n.data.node_type==='inspection');
 pipeline.nodes.push({id:'enhancement',position:{x:200,y:100},data:{label:'Actual enhancement',node_type:'preprocess',model_job_id:jobId,params:{operation:'enhancement'}}});
 pipeline.edges.find((edge:any)=>edge.source===input.id&&edge.target===inspect.id).target='enhancement';pipeline.edges.push({id:'enhancement-classifier',source:'enhancement',target:inspect.id});inspect.data.crop_padding=0;
 const flow=await api('/api/flowchart/run',{image_path:selected,pipeline,execution_target:'local',device:'cpu'});expect(flow.execution_steps.find((s:any)=>s.node_id==='enhancement').status).toBe('passed');
 const offline=JSON.parse(execFileSync(harness.resolvePython(),[path.join(harness.REPO_ROOT,'scripts/e2e/fixtures/enhancement_package_readback.py'),JSON.stringify({project_dir:project.project_dir,job_id:jobId,downstream_job_id:downstream.job_id,pipeline,flow_result:flow,source:selected,prediction})],{encoding:'utf8',timeout:55_000}));expect(offline.pixel_parity).toBe(true);expect(offline.comparison.status).toBe('passed');expect(offline.candidate_only).toBe(true);
 for(const file of fixture.files){expect(crypto.createHash('sha256').update(fs.readFileSync(file.path)).digest('hex')).toBe(file.sha256);evidence.addFile(file.path);}
 evidence.addFile(path.join(prepared.dataset_path,'pairs.json'));evidence.addFile(split.split_path);
 evidence.note('enhancement_pair_qualification',{fixture,project,split,refusal,prepared,posted,terminal,model,evaluated,prediction,downstream,downstreamTerminal,pipeline,flow,offline,actual_explicit_import:true,actual_cpu_training:true,actual_source_resolution_evaluation:true,actual_ui_comparison_and_reopen:true,actual_model_flow_binding:true,actual_candidate_package_process:true,no_original_mutation:true,quality_approval:false,defect_preservation_approval:false});
}
test('explicit paired enhancement validates imports trains measures compares reopens and exports actual flow',async({page,request,renderer,workspace,evidence})=>{test.setTimeout(240_000);const api:Api=async(route,body)=>{const r=body===undefined?await request.get(renderer.origin+route):route.endsWith('/update')?await request.put(renderer.origin+route,{data:body}):await request.post(renderer.origin+route,{data:body});expect(r.ok(),await r.text()).toBe(true);return r.json();};await exercise(page,workspace,evidence,api,renderer.url);});
test('native paired enhancement executes actual CPU candidate and portable whole-flow parity',{tag:'@electron'},async({electronSession,workspace,evidence})=>{test.setTimeout(240_000);const {window}=electronSession;const backend=await electronSession.waitForBackend();const api:Api=(route,body)=>window.evaluate(async({port,route,body})=>{const r=await fetch(`http://127.0.0.1:${port}${route}`,{...(body===undefined?{}:{method:route.endsWith('/update')?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})});if(!r.ok)throw Error(`Owned API ${r.status}: ${await r.text()}`);return r.json();},{port:backend.port,route,body});await exercise(window,workspace,evidence,api);});
