import fs from 'node:fs';
import path from 'node:path';
import {randomBytes} from 'node:crypto';
import {createServer} from 'node:net';
import {execFileSync,spawn,type ChildProcess} from 'node:child_process';
import type {Page} from '@playwright/test';
import {test,expect,type Workspace,type Evidence} from './fixtures/test';
import {installDesktopHostShim} from './fixtures/desktop-host-shim';
const harness=require('./fixtures/harness.cjs');
type Api=(route:string,body?:unknown)=>Promise<any>;
async function port(){const s=createServer();await new Promise<void>(r=>s.listen(0,'127.0.0.1',r));const p=(s.address() as {port:number}).port;await new Promise<void>(r=>s.close(()=>r()));return p;}
async function exercise(page:Page,workspace:Workspace,evidence:Evidence,api:Api,native:boolean,url?:string){
 const tool=path.join(harness.REPO_ROOT,'scripts/e2e/fixtures/fleet_runtime.py'),env={...process.env,VISION_AI_STUDIO_USER_DATA_DIR:workspace.userData};
 const fixture=JSON.parse(execFileSync(harness.resolvePython(),[tool,workspace.root],{cwd:harness.REPO_ROOT,env,encoding:'utf8',timeout:120_000}).trim());evidence.note('fixture',fixture);
 const agents:Array<{root:string;port:number;token:string;child:ChildProcess|null;pids:number[];log:fs.WriteStream}>=[];
 const remote=async(index:number,route:string,body?:unknown)=>{const a=agents[index],r=await fetch(`http://127.0.0.1:${a.port}${route}`,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+a.token,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});if(!r.ok)throw Error(`Owned agent ${r.status}: ${await r.text()}`);return r.json();};
 const start=async(index:number)=>{const a=agents[index];a.child=spawn(harness.resolvePython(),['-m','backend.engine.fleet_agent','--state-dir',a.root,'--port',String(a.port)],{cwd:harness.REPO_ROOT,env:{...env,VISION_FIELD_AGENT_TOKEN:a.token},stdio:['ignore','pipe','pipe']});a.pids.push(a.child.pid!);a.child.stdout!.pipe(a.log,{end:false});a.child.stderr!.pipe(a.log,{end:false});await expect.poll(async()=>{try{return (await remote(index,'/agent/v1/runtime')).status;}catch{return 'starting';}},{timeout:30_000}).not.toBe('starting');};
 const disconnect=async(index:number)=>{const a=agents[index],child=a.child;if(!child)return;const ended=new Promise<void>(r=>child.once('exit',()=>r()));child.kill('SIGTERM');await ended;a.child=null;};
 const inspect=async(index:number,viaAgent:boolean)=>{const a=agents[index],config=JSON.parse(fs.readFileSync(path.join(a.root,'service.json'),'utf8'));evidence.redact(config.token);const origin=`http://127.0.0.1:${viaAgent?a.port:config.port}`,headers:Record<string,string>=viaAgent?{Authorization:'Bearer '+a.token}:{'X-Vision-Token':config.token};
  const submitted=await fetch(origin+(viaAgent?'/agent/v1/jobs/upload':'/v1/jobs/upload'),{method:'POST',headers,body:fs.readFileSync(Object.keys(fixture.images)[0])});expect(submitted.status).toBe(viaAgent?200:202);const id=(await submitted.json() as any).job_id;
  let result:any;await expect.poll(async()=>{const r=await fetch(origin+(viaAgent?'/agent/v1/jobs/':'/v1/jobs/')+id,{headers});result=await r.json();return result.state;},{timeout:40_000}).toBe('completed');expect(result.model_verdict).toBe('OK');return result;
 };
 const jobs:any[]=[];const plans:any[]=[];
 try{
  for(let i=0;i<2;i++){const root=path.join(workspace.root,'owned-field-'+i);fs.mkdirSync(root);const token=randomBytes(24).toString('hex');evidence.redact(token);const log=fs.createWriteStream(path.join(root,'agent.log'));agents.push({root,port:await port(),token,child:null,pids:[],log});await start(i);}
  await api('/api/project/open',{project_dir:fixture.project.project_dir});if(url)await page.goto(url);else await page.reload();await page.getByRole('button',{name:'패키지·장치·진단',exact:true}).click();await page.getByText('중앙 · 현장 장비 모델 관리',{exact:true}).click();await page.getByText('현장 장비 추가',{exact:true}).click();
  for(let i=0;i<2;i++){await page.getByLabel('현장 장비 이름',{exact:true}).fill('Owned CPU '+i);await page.getByLabel('현장 Agent 주소',{exact:true}).fill(`http://127.0.0.1:${agents[i].port}`);await page.getByLabel('현장 Agent 인증값',{exact:true}).fill(agents[i].token);await page.getByRole('button',{name:'연결 설정 저장',exact:true}).click();await expect(page.getByLabel('현장 Agent 인증값',{exact:true})).toHaveValue('');}
  const targets=(await api('/api/fleet/targets')).targets;expect(targets).toHaveLength(2);expect(targets.every((t:any)=>!('token' in t))).toBe(true);
  await page.getByText('중앙 · 현장 장비 모델 관리',{exact:true}).locator('..').getByText('고급 · 패키지 폴더 직접 입력',{exact:true}).click();await page.getByLabel('현장 배포 승인 패키지',{exact:true}).fill(fixture.package.package_path);await page.getByLabel('현장 배포 검토자',{exact:true}).fill('synthetic-contract-reviewer');
  for(const target of targets){await page.getByLabel('현장 장비 선택',{exact:true}).selectOption(target.target_id);await page.getByRole('button',{name:'패키지 전송·적용 응답 확인',exact:true}).click();await expect(page.getByText('중앙 적용 기록과 일치',{exact:false})).toBeVisible({timeout:60_000});const state=await api('/api/fleet/targets/'+target.target_id);expect(state.runtime.manifest_sha256).toBe(fixture.first_release.manifest_sha256);expect(state.matches_active).toBe(true);}
  jobs.push(await inspect(0,true));await page.getByLabel('현장 배포 승인 패키지',{exact:true}).fill(fixture.candidate_package.package_path);
  const panel=page.getByRole('region',{name:'단계적 현장 배포'});for(const target of targets)await panel.getByRole('checkbox',{name:target.name,exact:true}).check();await panel.getByLabel('카나리 장비',{exact:true}).selectOption(targets[0].target_id);await panel.getByLabel('배치 장비 수',{exact:true}).fill('1');await panel.getByRole('button',{name:'배포 계획 저장',exact:true}).click();await expect(panel.getByRole('status')).toContainText('planned');let plan=(await api('/api/fleet/rollouts')).rollouts[0];plans.push(plan);
  await disconnect(0);await panel.getByRole('button',{name:'카나리 적용·응답 확인',exact:true}).click();await expect(panel.getByRole('status')).toContainText('paused');plan=await api('/api/fleet/rollouts/'+plan.plan_id);expect(plan.targets[0].status).toBe('offline');expect(plan.targets.every((t:any)=>!t.deployment_id)).toBe(true);plans.push(plan);
  jobs.push(await inspect(0,false));await start(0);await panel.getByRole('button',{name:'실제 응답 재확인·재개 준비',exact:true}).click();await expect(panel.getByRole('status')).toContainText('planned');await panel.getByRole('button',{name:'카나리 적용·응답 확인',exact:true}).click();await expect(panel.getByRole('status')).toContainText('waiting_canary_confirmation',{timeout:60_000});
  plan=await api('/api/fleet/rollouts/'+plan.plan_id);expect(plan.targets[0].readback.runtime.manifest_sha256).toBe(fixture.candidate_release.manifest_sha256);expect((await remote(1,'/agent/v1/runtime')).manifest_sha256).toBe(fixture.first_release.manifest_sha256);plans.push(plan);
  await panel.getByLabel('순차 배포 중단 사유',{exact:true}).fill('Owned canary review pause');await panel.getByRole('button',{name:'계획 중단',exact:true}).click();await expect(panel.getByRole('status')).toContainText('paused');await panel.getByRole('button',{name:'실제 응답 재확인·재개 준비',exact:true}).click();await expect(panel.getByRole('status')).toContainText('waiting_canary_confirmation');await panel.getByRole('button',{name:'카나리 응답 확인 · 다음 배치 승인',exact:true}).click();await expect(panel.getByRole('status')).toContainText('completed',{timeout:60_000});plan=await api('/api/fleet/rollouts/'+plan.plan_id);expect(plan.targets.every((t:any)=>t.status==='applied'&&t.readback.matches_active)).toBe(true);plans.push(plan);jobs.push(await inspect(1,true));
  await page.reload();await page.getByRole('button',{name:'패키지·장치·진단',exact:true}).click();await page.getByText('중앙 · 현장 장비 모델 관리',{exact:true}).click();const reopened=page.getByRole('region',{name:'단계적 현장 배포'});await reopened.getByLabel('순차 배포 계획',{exact:true}).selectOption(plan.plan_id);await expect(reopened.getByRole('status')).toContainText('completed');await page.getByLabel('현장 배포 검토자',{exact:true}).fill('synthetic-contract-reviewer');
  await reopened.getByRole('button',{name:'적용 장비의 이전 이력으로 롤백',exact:true}).click();await expect(reopened.getByRole('status')).toContainText('rolling_back',{timeout:60_000});await reopened.getByRole('button',{name:'다음 롤백 배치·응답 확인',exact:true}).click();await expect(reopened.getByRole('status')).toContainText('rolled_back',{timeout:60_000});plan=await api('/api/fleet/rollouts/'+plan.plan_id);expect(plan.targets.every((t:any)=>t.status==='rolled_back'&&t.readback.runtime.manifest_sha256===fixture.first_release.manifest_sha256)).toBe(true);plans.push(plan);jobs.push(await inspect(0,true));
  await reopened.scrollIntoViewIfNeeded();await evidence.screenshot(page,`${native?'native':'browser'}-actual-fleet-rollback`);evidence.note('actual_fleet',{fixture,targets,plans,jobs,agents:agents.map(({root,port,pids})=>({root,port,pids})),actual_os_agents:true,actual_cpu_inference:true,physical_field_devices:false,synthetic_approval_not_quality_acceptance:true,windows_excluded:true});
 }finally{
  const clean=[];for(let i=0;i<agents.length;i++){if(!agents[i].child)await start(i);clean.push({root:agents[i].root,port:agents[i].port,pids:agents[i].pids,result:await remote(i,'/agent/v1/stop',{})});await disconnect(i);agents[i].log.end();}evidence.note('owned_agents_cleanup',clean);
 }
}
test('actual authenticated CPU fleet canary, disconnect continuity and rollback',async({page,renderer,workspace,evidence})=>{const api:Api=async(route,body)=>{const r=await page.request.fetch(renderer.origin+route,{method:body?'POST':'GET',data:body});expect(r.ok(),await r.text()).toBe(true);return r.json();};await installDesktopHostShim(page,renderer.port);await exercise(page,workspace,evidence,api,false,renderer.url);});
test('native actual CPU fleet deploy, reopen and rollback',{tag:'@electron'},async({electronSession,workspace,evidence})=>{const status=await electronSession.waitForBackend(),page=electronSession.window;const api:Api=(route,body)=>page.evaluate(async({port,route,body})=>{const r=await fetch(`http://127.0.0.1:${port}${route}`,{method:body?'POST':'GET',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});if(!r.ok)throw Error(`Owned fleet HTTP ${r.status}: ${await r.text()}`);return r.json();},{port:status.port,route,body});await exercise(page,workspace,evidence,api,true);});
