import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {execFileSync} from 'node:child_process';
import type {Page} from '@playwright/test';import {test,expect,type Workspace,type Evidence} from './fixtures/test';
const harness=require('./fixtures/harness.cjs');type Api=(route:string,body?:any)=>Promise<any>;
test.use({actionTimeout:15_000});
async function exercise(page:Page,workspace:Workspace,evidence:Evidence,api:Api,url?:string){
 const python=(file:string,args:string[])=>JSON.parse(execFileSync(harness.resolvePython(),[path.join(harness.REPO_ROOT,'scripts/e2e/fixtures',file),...args],{encoding:'utf8',timeout:30_000}));
 const fixture=python('flow_comparison_control.py',[workspace.root]);
 const prepare=async(name:string,target=false)=>{await api('/api/project/create',{name,task:'classification'});await api('/api/project/update',{source_dataset_dir:fixture.source});await api('/api/dataset/import',{folder_path:fixture.source,task:'classification'});const project=await api('/api/project/current');python('comparison_models.py',[fixture.source,project.models_dir]);const graph=python('flow_template_control.py',[JSON.stringify(project),...(target?['target']:[])]);return {project,graph};};
 const open=async(project:any,version:string)=>{if(url)await page.goto(url);else await page.reload();await expect(page.getByTitle('프로젝트 관리',{exact:true})).toContainText(project.name);await page.getByRole('navigation',{name:'Workflow Stages'}).getByRole('button').nth(4).click();await page.getByRole('tab',{name:'편집',exact:true}).click();await page.getByLabel('저장 버전',{exact:true}).selectOption(version);};
 const details=()=>page.locator('details').filter({has:page.getByText('내 템플릿 · 모델·클래스 매핑',{exact:true})}).first();
 const source=await prepare('Cross-project template source');await open(source.project,source.graph.version);
 if(await details().getAttribute('open')===null)await details().locator('summary').first().click();
 await page.getByLabel('템플릿 이름',{exact:true}).fill('Reviewed source class NG');
 const saved=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/flow-workspace/templates'&&r.request().method()==='POST');
 await page.getByRole('button',{name:'전체 흐름 저장',exact:true}).click();const wire=await saved;expect(wire.ok(),await wire.text()).toBe(true);const template=await wire.json();
 expect(template.classes.names).toContain('NG');
 const selectedNodes=source.graph.pipeline.nodes.filter((n:any)=>['fixed_roi','inspection'].includes(n.data.node_type));
 const subset=page.getByText('부분 흐름으로 저장할 노드 선택',{exact:true}).locator('..');
 await subset.locator('summary').click();for(const node of selectedNodes)await subset.getByRole('checkbox',{name:node.data.label,exact:true}).check();
 await page.getByLabel('템플릿 이름',{exact:true}).fill('Selected ROI and model');
 const partialSaved=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/flow-workspace/templates'&&r.request().method()==='POST');
 await page.getByRole('button',{name:'선택 노드 저장',exact:true}).click();const partialWire=await partialSaved;expect(partialWire.ok(),await partialWire.text()).toBe(true);const partialTemplate=await partialWire.json();
 expect(partialWire.request().postDataJSON().node_ids.sort()).toEqual(selectedNodes.map((n:any)=>n.id).sort());
 expect(partialTemplate.kind).toBe('subgraph');expect(partialTemplate.pipeline.nodes.map((n:any)=>n.id).sort()).toEqual(selectedNodes.map((n:any)=>n.id).sort());
 expect(partialTemplate.ports.inputs).toHaveLength(1);expect(partialTemplate.ports.outputs).toHaveLength(1);
 for(const node of selectedNodes)await subset.getByRole('checkbox',{name:node.data.label,exact:true}).uncheck();
 const sourceCheckpoint=path.join(source.project.models_dir,source.graph.job_id,'best_model.pt'),sourceHash=crypto.createHash('sha256').update(fs.readFileSync(sourceCheckpoint)).digest('hex');
 const target=await prepare('Cross-project target scratch',true);await open(target.project,target.graph.version);
 if(await details().getAttribute('open')===null)await details().locator('summary').first().click();
 await page.getByLabel('내 템플릿 선택',{exact:true}).selectOption(partialTemplate.template_id);
 await page.getByLabel('ROI 결함 검사 템플릿 모델 매핑',{exact:true}).selectOption(target.graph.job_id);
 const partialMapped=page.waitForResponse(r=>new URL(r.url()).pathname.endsWith('/'+partialTemplate.template_id+'/map')&&r.request().method()==='POST');
 await page.getByRole('button',{name:'모델·클래스 매핑 후 초안으로 열기',exact:true}).click();const partialResult=await partialMapped;
 expect(partialResult.ok(),await partialResult.text()).toBe(true);expect((await partialResult.json()).kind).toBe('subgraph');
 await expect(page.getByText('부분 흐름을 추가했습니다. 입력 1개·출력 1개 경계 포트를 기존 노드와 연결하세요.',{exact:true})).toBeVisible();
 expect((await api('/api/flowchart/pipelines')).pipelines.some((v:any)=>v.version===target.graph.version||v.version_id===target.graph.version)).toBe(true);
 await evidence.screenshot(page,'actual-selected-subgraph-explicit-model-reuse-needs-boundary-wiring');
 // Persist the inserted graph before asking to replace it. The application
 // correctly refuses replacement if this graph's autosave starts mid-mapping.
 const partialDraftSaved=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/flowchart/draft'&&r.request().method()==='PUT');
 await page.getByRole('button',{name:'초안 저장',exact:true}).click();
 expect((await partialDraftSaved).ok()).toBe(true);
 await expect(page.getByRole('status').filter({hasText:'✓ 편집 초안이 저장되었습니다.'})).toBeVisible();
 await page.getByLabel('내 템플릿 선택',{exact:true}).selectOption(template.template_id);
 await page.getByLabel('ROI 결함 검사 템플릿 모델 매핑',{exact:true}).selectOption(target.graph.job_id);
 const apply=page.getByRole('button',{name:'모델·클래스 매핑 후 초안으로 열기',exact:true});
 page.on('dialog',dialog=>dialog.accept());
 let waiting=page.waitForResponse(r=>new URL(r.url()).pathname.endsWith('/'+template.template_id+'/map')&&r.request().method()==='POST');
 await apply.click();let mapped=await waiting;expect(mapped.status()).toBe(422);
 await expect(page.getByRole('alert').filter({hasText:'class mapping'})).toBeVisible();
 await page.getByLabel('ROI 결함 검사 · 이름 NG 매핑',{exact:true}).fill('scratch');
 waiting=page.waitForResponse(r=>new URL(r.url()).pathname.endsWith('/'+template.template_id+'/map')&&r.request().method()==='POST');
 await apply.click();mapped=await waiting;expect(mapped.ok(),await mapped.text()).toBe(true);const mappedBody=await mapped.json();
 expect(mapped.request().postDataJSON()).toMatchObject({project_id:target.project.id,models:{[source.graph.model_id]:target.graph.job_id},classes:{[source.graph.model_id+':name:NG']:'scratch'}});
 expect(mappedBody.pipeline.edges.find((e:any)=>e.predicate).predicate.class_name).toBe('scratch');
 await expect(page.getByText('모델·클래스를 매핑한 초안으로 열었습니다. 연결을 확인하고 저장하세요.',{exact:true})).toBeVisible();
 const search=page.getByLabel('플로우 노드 검색',{exact:true});await search.fill(source.graph.model_id);await page.getByRole('list',{name:'노드 검색 결과'}).getByRole('button').click();
 const label=page.getByRole('textbox',{name:'노드 명칭',exact:true});const original=await label.inputValue();await label.fill('Mapped draft recovered');
 await page.getByRole('button',{name:'플로우 실행 취소',exact:true}).click();await expect(label).toHaveValue(original);
 await page.getByRole('button',{name:'플로우 다시 실행',exact:true}).click();await expect(label).toHaveValue('Mapped draft recovered');
 await page.getByRole('button',{name:'초안 저장',exact:true}).click();
 await expect.poll(async()=>{const d=await api('/api/flowchart/draft');return d.pipeline.nodes.find((n:any)=>n.id===source.graph.model_id).data.label;}).toBe('Mapped draft recovered');
 const draft=await api('/api/flowchart/draft');await evidence.screenshot(page,'actual-cross-project-explicit-model-class-mapping-and-undo-redo');
 await page.reload();await expect(page.getByTitle('프로젝트 관리',{exact:true})).toContainText(target.project.name);await page.getByRole('navigation',{name:'Workflow Stages'}).getByRole('button').nth(4).click();await page.getByRole('tab',{name:'편집',exact:true}).click();await search.fill(source.graph.model_id);await page.getByRole('list',{name:'노드 검색 결과'}).getByRole('button').click();await expect(label).toHaveValue('Mapped draft recovered');
 expect((await api('/api/flowchart/draft')).draft_sha256).toBe(draft.draft_sha256);expect(fs.existsSync(path.join(target.project.project_dir,'flowcharts/active.json'))).toBe(false);
 expect(crypto.createHash('sha256').update(fs.readFileSync(sourceCheckpoint)).digest('hex')).toBe(sourceHash);
 for(const row of fixture.files)expect(crypto.createHash('sha256').update(fs.readFileSync(row.path)).digest('hex')).toBe(row.sha256);

 const input=fixture.files.find((r:any)=>r.split==='test').path;
 await page.getByRole('button',{name:/이미지 변경/}).click();await page.getByRole('button',{name:path.basename(input)+' 검사 이미지 선택',exact:true}).click();await page.getByRole('button',{name:'선택 확정',exact:true}).click();
 const roi=source.graph.pipeline.nodes.find((n:any)=>n.data.node_type==='fixed_roi').id;
 await search.fill(roi);await page.getByRole('list',{name:'노드 검색 결과'}).getByRole('button').click();
 const width=page.getByRole('spinbutton',{name:'너비 (px)',exact:true});await width.fill('80');await width.press('Enter');
 await expect(page.getByRole('status').filter({hasText:'원본 48×48 픽셀 경계'}).first()).toBeVisible();
 await evidence.screenshot(page,'actual-original-image-roi-bound-error');
 await page.getByRole('button',{name:'플로우 실행 취소',exact:true}).click();await expect(width).toHaveValue('36');
 await expect(page.getByRole('status').filter({hasText:'원본 48×48 픽셀 경계'})).toHaveCount(0);
 const decision=source.graph.pipeline.nodes.find((n:any)=>n.data.node_type==='decision').id;
 await search.fill(decision);await page.getByRole('list',{name:'노드 검색 결과'}).getByRole('button').click();
 const incomplete=page.getByLabel('UNKNOWN·미실행·오류 처리',{exact:true});await expect(incomplete).toHaveValue('review');
 await incomplete.selectOption('ng');await page.getByRole('button',{name:'초안 저장',exact:true}).click();
 await expect.poll(async()=>{const d=await api('/api/flowchart/draft');return d.pipeline.nodes.find((n:any)=>n.id===decision).data.params.incomplete_policy;}).toBe('ng');
 await page.reload();await page.getByRole('navigation',{name:'Workflow Stages'}).getByRole('button').nth(4).click();await page.getByRole('tab',{name:'편집',exact:true}).click();
 await search.fill(decision);await page.getByRole('list',{name:'노드 검색 결과'}).getByRole('button').click();await expect(incomplete).toHaveValue('ng');
 await incomplete.selectOption('review');await page.getByRole('button',{name:'초안 저장',exact:true}).click();
 await evidence.screenshot(page,'actual-incomplete-result-policy-persistence');
 await evidence.screenshot(page,'actual-cross-project-draft-recovery-reopen');evidence.note('template_draft',{source,target,template,partialTemplate,draft,selected_subgraph_reused:true,actual_gui_buttons:true,source_images_unchanged:true,source_checkpoint_unchanged:true,active_version_unchanged:true,trained:false,quality_approved:false});
}
test('cross-project model class mapping preserves source and recovers draft',async({page,request,renderer,workspace,evidence})=>{const api:Api=async(route,body)=>{const r=body===undefined?await request.get(renderer.origin+route):route.endsWith('/update')?await request.put(renderer.origin+route,{data:body}):await request.post(renderer.origin+route,{data:body});expect(r.ok(),await r.text()).toBe(true);return r.json();};await exercise(page,workspace,evidence,api,renderer.url);});
test('native cross-project mapping undo redo and persistent draft recovery',{tag:'@electron'},async({electronSession,workspace,evidence})=>{const {window}=electronSession;const backend=await electronSession.waitForBackend();const api:Api=(route,body)=>window.evaluate(async({port,route,body})=>{const r=await fetch(`http://127.0.0.1:${port}${route}`,{...(body===undefined?{}:{method:route.endsWith('/update')?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})});if(!r.ok)throw Error(`Owned API ${r.status}: ${await r.text()}`);return r.json();},{port:backend.port,route,body});await exercise(window,workspace,evidence,api);});
