import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {execFileSync} from 'node:child_process';
import type {Page} from '@playwright/test';import {test,expect,type Workspace,type Evidence} from './fixtures/test';
const harness=require('./fixtures/harness.cjs');type Api=(route:string,body?:any)=>Promise<any>;test.use({actionTimeout:15_000});
async function exercise(page:Page,workspace:Workspace,evidence:Evidence,api:Api,url?:string){
 const fixtureScript=path.join(harness.REPO_ROOT,'scripts/e2e/fixtures/flow_comparison_control.py');
 const fixture=JSON.parse(execFileSync(harness.resolvePython(),[fixtureScript,workspace.root],{encoding:'utf8',timeout:15_000}));
 await api('/api/project/create',{name:'A B comparison integrity controls',task:'classification'});await api('/api/project/update',{source_dataset_dir:fixture.source});const project=await api('/api/project/current');await api('/api/dataset/import',{folder_path:fixture.source,task:'classification'});
 const versions=JSON.parse(execFileSync(harness.resolvePython(),[fixtureScript,workspace.root,JSON.stringify(project)],{encoding:'utf8',timeout:15_000}));
 const result=await api('/api/flow-workspace/comparisons',{project_id:project.id,version_a:versions.version_a,version_b:versions.version_b,image_paths:[fixture.files.find((r:any)=>r.split==='test').path],stop_node_id:versions.stop_node_id,device:'cpu',execution_target:'local'});
 expect(result).toMatchObject({status:'completed',comparison_scope:'debug_partial',schema_version:2,integrity:'verified',quality_approved:false});for(const side of ['result_a','result_b'])expect(result.rows[0][side]).toMatchObject({status:'partial',final_verdict:'REVIEW',is_ok:false,stop_node_id:versions.stop_node_id});expect(result.record_sha256).toMatch(/^[a-f0-9]{64}$/);
 const file=path.join(project.project_dir,'flowcharts/comparisons',result.comparison_id+'.json');const original=fs.readFileSync(file);const preserved=path.join(workspace.root,'comparison-before-tamper.json');fs.writeFileSync(preserved,original);evidence.addFile(preserved);
 const legacy={...JSON.parse(original.toString()),comparison_id:'legacy-control',created_at:'2000-01-01T00:00:00Z'};delete legacy.schema_version;delete legacy.record_sha256;delete legacy.quality_approved;fs.writeFileSync(path.join(project.project_dir,'flowcharts/comparisons/legacy-control.json'),JSON.stringify(legacy));
 const show=async()=>{if(url)await page.goto(url);else await page.reload();await expect(page.getByTitle('프로젝트 관리',{exact:true})).toContainText(project.name);await page.getByRole('navigation',{name:'Workflow Stages'}).getByRole('button').nth(4).click();await page.getByRole('tab',{name:'일괄 평가',exact:true}).click();const details=page.locator('details').filter({has:page.getByText('고정 테스트 세트 · 플로우 버전 A/B 비교',{exact:true})}).first();if(await details.getAttribute('open')===null)await details.locator('summary').first().click();};
 await show();const selector=page.getByLabel('저장 비교 결과',{exact:true});await selector.selectOption(result.comparison_id);await expect(page.getByRole('status').filter({hasText:'저장 근거 무결성 확인'})).toContainText(result.record_sha256);await evidence.screenshot(page,'actual-comparison-envelope-reopen');
 await selector.selectOption('legacy-control');await expect(page.getByRole('status').filter({hasText:'이전 비교 기록'})).toContainText('해시 미기록');await evidence.screenshot(page,'legacy-comparison-unverified');
 const changed=JSON.parse(original.toString());changed.status='completed';changed.rows=[];fs.writeFileSync(file,JSON.stringify(changed));const after=await api('/api/flow-workspace/comparisons');expect(after.comparisons.map((r:any)=>r.comparison_id)).toEqual(['legacy-control']);expect(after.invalid).toContainEqual({comparison_id:result.comparison_id,reason:'record_hash_changed'});
 await show();await expect(page.getByRole('alert').filter({hasText:'무결성을 확인할 수 없는 저장 비교 1개'})).toBeVisible();await expect(selector.locator('option[value="'+result.comparison_id+'"]')).toHaveCount(0);await selector.selectOption('legacy-control');await evidence.screenshot(page,'changed-comparison-quarantined');
 for(const row of fixture.files)expect(crypto.createHash('sha256').update(fs.readFileSync(row.path)).digest('hex')).toBe(row.sha256);
 expect(fs.existsSync(path.join(project.project_dir,'flowcharts/active.json'))).toBe(false);
 evidence.note('flow_comparison_integrity',{project,fixture,versions,result,after,original_path:preserved,original_sha256:crypto.createHash('sha256').update(original).digest('hex'),actual_partial_roi_execution:true,actual_model_execution:false,quality_approved:false,source_unchanged:true,active_flow_unchanged:true});
}
test('actual A B partial ROI history reopens and quarantines changed envelopes',async({page,request,renderer,workspace,evidence})=>{test.setTimeout(120_000);const api:Api=async(route,body)=>{const r=body===undefined?await request.get(renderer.origin+route):route.endsWith('/update')?await request.put(renderer.origin+route,{data:body}):await request.post(renderer.origin+route,{data:body});expect(r.ok(),await r.text()).toBe(true);return r.json();};await exercise(page,workspace,evidence,api,renderer.url);});
test('native A B history shows legacy limits and refuses altered envelopes',{tag:'@electron'},async({electronSession,workspace,evidence})=>{test.setTimeout(120_000);const {window}=electronSession;const backend=await electronSession.waitForBackend();const api:Api=(route,body)=>window.evaluate(async({port,route,body})=>{const r=await fetch(`http://127.0.0.1:${port}${route}`,{...(body===undefined?{}:{method:route.endsWith('/update')?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})});if(!r.ok)throw Error(`Owned API ${r.status}: ${await r.text()}`);return r.json();},{port:backend.port,route,body});await exercise(window,workspace,evidence,api);});
