import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {execFileSync} from 'node:child_process';
import type {Page} from '@playwright/test';import {test,expect,type Workspace,type Evidence} from './fixtures/test';
const harness=require('./fixtures/harness.cjs');type Api=(route:string,body?:any)=>Promise<any>;
test.use({actionTimeout:15_000});
async function exercise(page:Page,workspace:Workspace,evidence:Evidence,api:Api,url?:string){
 const fixtureScript=path.join(harness.REPO_ROOT,'scripts/e2e/fixtures/flow_comparison_control.py');
 const fixture=JSON.parse(execFileSync(harness.resolvePython(),[fixtureScript,workspace.root],{encoding:'utf8',timeout:15_000}));
 await api('/api/project/create',{name:'CPU flow identity controls',task:'classification'});await api('/api/project/update',{source_dataset_dir:fixture.source});await api('/api/dataset/import',{folder_path:fixture.source,task:'classification'});const project=await api('/api/project/current');
 const weights=JSON.parse(execFileSync(harness.resolvePython(),[path.join(harness.REPO_ROOT,'scripts/e2e/fixtures/comparison_models.py'),fixture.source,project.models_dir],{encoding:'utf8',timeout:30_000}));
 const versions=JSON.parse(execFileSync(harness.resolvePython(),[path.join(harness.REPO_ROOT,'scripts/e2e/fixtures/flow_debug_model_control.py'),JSON.stringify(project)],{encoding:'utf8',timeout:15_000}));
 const input=fixture.files.find((row:any)=>row.split==='test').path;
 const body={project_id:project.id,pipeline:versions.pipeline,image_path:input,execution_target:'local',device:'cpu',stop_node_id:versions.stop_node_id};
 const first=await api('/api/flowchart/run',body),repeat=await api('/api/flowchart/run',body);
 expect(first).toMatchObject({status:'partial',final_verdict:'REVIEW',is_ok:false,debug_cache:{status:'miss'}});expect(repeat).toMatchObject({status:'partial',final_verdict:'REVIEW',is_ok:false,debug_cache:{status:'hit'}});expect(repeat.debug_cache.identity_sha256).toBe(first.debug_cache.identity_sha256);expect(repeat.crops).toEqual(first.crops);expect(repeat.execution_steps.every((s:any)=>s.latency_ms===0)).toBe(true);
 const changed=structuredClone(body);changed.pipeline.nodes.find((n:any)=>n.data.node_type==='fixed_roi').data.params.roi_bbox=[8,8,40,40];const changedResult=await api('/api/flowchart/run',changed);expect(changedResult.debug_cache.status).toBe('miss');expect(changedResult.debug_cache.identity_sha256).not.toBe(first.debug_cache.identity_sha256);
 const record=await api('/api/flow-workspace/comparisons',{project_id:project.id,version_a:versions.version_a,version_b:versions.version_b,image_paths:[input],execution_target:'local',device:'cpu'});
 expect(record).toMatchObject({status:'completed',comparison_scope:'whole_flow',quality_approved:false,integrity:'verified'});expect(record.rows[0].difference).toMatchObject({verdict_changed:true,verdict_a:'OK',verdict_b:'NG'});expect(record.cohort_sha256).toMatch(/^[a-f0-9]{64}$/);
 for(const side of ['a','b']){const binding=record.model_bindings[side][0];expect(binding.checkpoint_sha256).toBe(versions.models[binding.job_id]);}
 if(url)await page.goto(url);else await page.reload();await expect(page.getByTitle('프로젝트 관리',{exact:true})).toContainText(project.name);await page.getByRole('navigation',{name:'Workflow Stages'}).getByRole('button').nth(4).click();await page.getByRole('tab',{name:'일괄 평가',exact:true}).click();const details=page.locator('details').filter({has:page.getByText('고정 테스트 세트 · 플로우 버전 A/B 비교',{exact:true})}).first();if(await details.getAttribute('open')===null)await details.locator('summary').first().click();await page.getByLabel('저장 비교 결과',{exact:true}).selectOption(record.comparison_id);await page.getByText('고정 모델·입력 근거',{exact:true}).click();await expect(page.getByText('입력 목록 해시:',{exact:false})).toContainText(record.cohort_sha256);await expect(page.getByText(versions.models.job_fixture_incumbent,{exact:false})).toBeVisible();await expect(page.getByText(versions.models.job_fixture_candidate,{exact:false})).toBeVisible();await evidence.screenshot(page,'actual-cpu-model-ab-identity-reopen');
 await page.getByRole('tab',{name:'편집',exact:true}).click();await page.getByLabel('저장 버전',{exact:true}).selectOption(versions.version_a);
 await page.getByRole('button',{name:/이미지 변경/}).click();await page.getByRole('button',{name:path.basename(input)+' 검사 이미지 선택',exact:true}).click();await page.getByRole('button',{name:'선택 확정',exact:true}).click();
 await page.getByLabel('플로우 노드 검색',{exact:true}).fill(versions.stop_node_id);await page.getByRole('list',{name:'노드 검색 결과'}).getByRole('button').first().click();
 const guiRuns=[];for(let i=0;i<2;i++){await page.getByRole('tab',{name:'테스트',exact:true}).click();if(i===0)await page.getByLabel('플로우 실행 위치',{exact:true}).selectOption('local_cpu');const response=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/flowchart/run'&&r.request().method()==='POST');await page.getByRole('button',{name:'선택 노드까지 실행',exact:true}).click();const wire=await response;expect(wire.ok(),await wire.text()).toBe(true);guiRuns.push(await wire.json());}
 expect(guiRuns[0].debug_cache.status).toBe('miss');expect(guiRuns[1].debug_cache.status).toBe('hit');await expect(page.getByRole('status').filter({hasText:'동일한 부분 실행 근거 재사용'})).toBeVisible();await evidence.screenshot(page,'actual-gui-debug-cache-hit');
 evidence.note('gui_debug_runs',{runs:guiRuns,actual_buttons:true,partial_never_final_ok:guiRuns.every(r=>r.status==='partial'&&r.final_verdict==='REVIEW'&&r.is_ok===false)});
 expect((await api('/api/flow-workspace/comparisons')).comparisons[0]).toEqual(record);
 for(const row of fixture.files)expect(crypto.createHash('sha256').update(fs.readFileSync(row.path)).digest('hex')).toBe(row.sha256);
 expect(fs.existsSync(path.join(project.project_dir,'flowcharts/active.json'))).toBe(false);
 evidence.note('flow_debug_model_freeze',{project,fixture,weights,versions,first,repeat,changedResult,record,actual_cpu_inference:true,trained:false,quality_approved:false,source_unchanged:true,active_flow_unchanged:true});
}
test('actual CPU debug cache and frozen model A B survive history reopen',async({page,request,renderer,workspace,evidence})=>{test.setTimeout(180_000);const api:Api=async(route,body)=>{const r=body===undefined?await request.get(renderer.origin+route):route.endsWith('/update')?await request.put(renderer.origin+route,{data:body}):await request.post(renderer.origin+route,{data:body});expect(r.ok(),await r.text()).toBe(true);return r.json();};await exercise(page,workspace,evidence,api,renderer.url);});
test('native CPU debug cache and model hash history reopen',{tag:'@electron'},async({electronSession,workspace,evidence})=>{test.setTimeout(180_000);const {window}=electronSession;const backend=await electronSession.waitForBackend();const api:Api=(route,body)=>window.evaluate(async({port,route,body})=>{const r=await fetch(`http://127.0.0.1:${port}${route}`,{...(body===undefined?{}:{method:route.endsWith('/update')?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})});if(!r.ok)throw Error(`Owned API ${r.status}: ${await r.text()}`);return r.json();},{port:backend.port,route,body});await exercise(window,workspace,evidence,api);});
