import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {execFileSync} from 'node:child_process';
import type {Page} from '@playwright/test';import {test,expect,type Workspace,type Evidence} from './fixtures/test';import {installDesktopHostShim} from './fixtures/desktop-host-shim';import {png} from './qa/appFlow';
const harness=require('./fixtures/harness.cjs');type Api=(route:string,body?:unknown)=>Promise<any>;const sha=(b:Buffer)=>crypto.createHash('sha256').update(b).digest('hex');test.use({actionTimeout:10_000});
async function exercise(page:Page,workspace:Workspace,evidence:Evidence,api:Api,native:boolean,url?:string){
 const source=path.join(workspace.root,'flow-origin-source'),originals:Record<string,string>={};
 for(const [split,label,name,shift]of [['train','good','one',0],['train','good','two',10],['train','good','three',20],['val','good','val',5],['test','anomaly','owned-part',150]] as const){const dir=path.join(source,split,label);fs.mkdirSync(dir,{recursive:true});const file=path.join(dir,name+'.png');fs.writeFileSync(file,png(64,3,(x,y)=>[Math.min(255,30+shift+x),30+y,50]));originals[file]=sha(fs.readFileSync(file));}
 const project=await api('/api/project/create',{name:'Flow raster origin fixture',task:'anomaly'});await api('/api/project/update',{source_dataset_dir:source});await api('/api/dataset/import',{folder_path:source,task:'anomaly'});
 const fixture=JSON.parse(execFileSync(harness.resolvePython(),[path.join(harness.REPO_ROOT,'scripts/e2e/fixtures/raster_models.py'),source,project.models_dir],{cwd:harness.REPO_ROOT,env:{...process.env,VISION_AI_STUDIO_USER_DATA_DIR:workspace.userData},encoding:'utf8',timeout:60_000}));
 await api('/api/flowchart/models/verify',{source_dataset_path:source,models:[{job_id:'job_fixture_raster',task:'anomaly'}]});const pipeline=await api('/api/flowchart/templates/single-segmentation?inspection_task=anomaly&job_id=job_fixture_raster');
 const savePath=`/api/flowchart/pipeline?source_dataset_path=${encodeURIComponent(source)}`;const a=await api(savePath,{...pipeline,name:'Raster origin A'}),b=await api(savePath,{...pipeline,name:'Raster origin B'});const input=Object.keys(originals).find(f=>f.endsWith('owned-part.png'))!;
 const compare=await api('/api/flow-workspace/comparisons',{project_id:project.id,version_a:a.version_id,version_b:b.version_id,image_paths:[input],device:'cpu',execution_target:'local'});expect(compare).toMatchObject({status:'completed',schema_version:2,integrity:'verified',quality_approved:false});for(const key of ['result_a','result_b'])expect(compare.rows[0][key].execution_device).toBe('cpu');
 const protectedHistory=await api('/api/flow-workspace/comparisons'),historyHash=sha(Buffer.from(JSON.stringify(protectedHistory)));const comparisonFile=path.join(project.project_dir,'flowcharts/comparisons',compare.comparison_id+'.json'),fileHash=sha(fs.readFileSync(comparisonFile));
 const foreign='https://flow-external.invalid/image.png',requests:string[]=[];page.on('request',r=>{if(r.url().startsWith('https://flow-external.invalid/'))requests.push(r.url());});await page.route('https://flow-external.invalid/**',r=>r.abort());
 if(url)await page.goto(url);else await page.reload();await expect(page.getByTitle('프로젝트 관리',{exact:true})).toContainText(project.name);await page.getByRole('navigation',{name:'Workflow Stages'}).getByRole('button').nth(4).click();await page.getByRole('button',{name:/이미지 변경/}).click();await page.getByRole('button',{name:'owned-part.png 검사 이미지 선택',exact:true}).click();await page.getByRole('button',{name:'선택 확정',exact:true}).click();await page.getByRole('tab',{name:'테스트',exact:true}).click();await page.getByLabel('플로우 실행 위치').selectOption('local_cpu');
 const runButton=page.getByRole('button',{name:/선택 이미지 검사/}),runPath='**/api/flowchart/run',runResponse=()=>page.waitForResponse(r=>new URL(r.url()).pathname==='/api/flowchart/run'&&r.request().method()==='POST');let waiting=runResponse();await runButton.click();let response=await waiting;expect(response.status()).toBe(200);const flow=await response.json();expect(flow.execution_device).toBe('cpu');expect(flow.crops).toHaveLength(1);await expect(page.getByAltText('실제 검사 결과',{exact:true})).toHaveAttribute('src',flow.annotated_image);
 let bad=true,flowHits=0;await page.route(runPath,r=>{flowHits++;const body=structuredClone(flow);if(bad){body.annotated_image=foreign;body.crops=body.crops.map((c:any)=>({...c,crop_thumbnail:foreign}));}return r.fulfill({status:200,json:body});});waiting=runResponse();await runButton.click();expect((await waiting).status()).toBe(200);await expect(page.getByAltText('실제 검사 결과',{exact:true})).toHaveCount(0);await expect(page.getByText('결과 이미지를 읽을 수 없습니다.',{exact:true})).toBeVisible();await expect(page.getByText('ROI 이미지를 읽을 수 없습니다.',{exact:true})).toBeVisible();await evidence.screenshot(page,`${native?'native':'browser'}-flow-refuses-external-master-and-roi`);
 bad=false;waiting=runResponse();await runButton.click();expect((await waiting).status()).toBe(200);await expect(page.getByAltText('실제 검사 결과',{exact:true})).toHaveAttribute('src',flow.annotated_image);await expect(page.getByAltText(flow.crops[0].label,{exact:true})).toHaveAttribute('src',flow.crops[0].crop_thumbnail);await expect(page.getByText('결과 이미지를 읽을 수 없습니다.',{exact:true})).toHaveCount(0);await evidence.screenshot(page,`${native?'native':'browser'}-flow-exact-captured-rasters-recovered`);await page.unroute(runPath);
 let compareBad=true,compareHits=0;await page.route('**/api/flow-workspace/comparisons',r=>{if(r.request().method()!=='GET')return r.fallback();compareHits++;const body=structuredClone(protectedHistory);if(compareBad)for(const row of body.comparisons[0].rows)for(const key of ['result_a','result_b'])row[key].annotated_image=foreign;return r.fulfill({status:200,json:body});});
 const show=async()=>{await page.reload();await expect(page.getByTitle('프로젝트 관리',{exact:true})).toContainText(project.name);await page.getByRole('navigation',{name:'Workflow Stages'}).getByRole('button').nth(4).click();await page.getByRole('tab',{name:'일괄 평가',exact:true}).click();const details=page.locator('details').filter({has:page.getByText('고정 테스트 세트 · 플로우 버전 A/B 비교',{exact:true})}).first();await details.locator('summary').first().click();await page.getByLabel('저장 비교 결과',{exact:true}).selectOption(compare.comparison_id);await page.getByText('중간 이미지와 원본 해시',{exact:true}).click();await expect(page.getByRole('status').filter({hasText:'저장 근거 무결성 확인'})).toContainText(compare.record_sha256);};
 await show();await expect(page.getByAltText('버전 A 검사 결과',{exact:true})).toHaveCount(0);await expect(page.getByAltText('버전 B 검사 결과',{exact:true})).toHaveCount(0);await expect(page.getByText('결과 이미지를 읽을 수 없습니다.',{exact:true})).toHaveCount(2);await evidence.screenshot(page,`${native?'native':'browser'}-comparison-refuses-external-previews`);
 compareBad=false;await show();for(const [side,key]of [['A','result_a'],['B','result_b']])await expect(page.getByAltText(`버전 ${side} 검사 결과`,{exact:true})).toHaveAttribute('src',compare.rows[0][key].annotated_image);await evidence.screenshot(page,`${native?'native':'browser'}-comparison-exact-stored-previews-reopened`);await page.unroute('**/api/flow-workspace/comparisons');
 expect(flowHits).toBe(2);expect(compareHits).toBeGreaterThanOrEqual(2);expect(requests).toEqual([]);expect(await api('/api/flow-workspace/comparisons')).toEqual(protectedHistory);expect(sha(fs.readFileSync(comparisonFile))).toBe(fileHash);for(const [file,hash]of Object.entries(originals))expect(sha(fs.readFileSync(file))).toBe(hash);
 evidence.note('flow_raster_origin',{project_id:project.id,fixture,version_a:a.version_id,version_b:b.version_id,comparison_id:compare.comparison_id,comparison_record_sha256:compare.record_sha256,history_sha256:historyHash,comparison_file_sha256:fileHash,originals,flow,actual_cpu_flow_execution:true,actual_cpu_comparison_two_versions:true,controlled_response_only:true,flow_response_fixture_hits:flowHits,comparison_response_fixture_hits:compareHits,foreign_requests:requests,exact_saved_history_unchanged:true,originals_unchanged:true,actual_external_refusal_and_valid_reopen:true,app_training:false,model_quality_approval:false});
}
test('flow result and stored A B comparison refuse persisted external raster addresses',async({page,request,renderer,workspace,evidence})=>{await installDesktopHostShim(page,renderer.port);const api:Api=async(route,body)=>{const r=body===undefined?await request.get(renderer.origin+route):route.endsWith('/update')?await request.put(renderer.origin+route,{data:body}):await request.post(renderer.origin+route,{data:body});expect(r.ok(),await r.text()).toBe(true);return r.json();};await exercise(page,workspace,evidence,api,false,renderer.url);});
test('native flow and A B stored preview origin boundaries preserve exact saved reports',{tag:'@electron'},async({electronSession,workspace,evidence})=>{const {window}=electronSession,backend=await electronSession.waitForBackend();const api:Api=(route,body)=>window.evaluate(async({port,route,body})=>{const r=await fetch(`http://127.0.0.1:${port}${route}`,body===undefined?{}:{method:route.endsWith('/update')?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw Error(`Owned flow-origin API ${r.status}`);return r.json();},{port:backend.port,route,body});await exercise(window,workspace,evidence,api,true);});
