import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {execFileSync} from 'node:child_process';
import type {Page} from '@playwright/test';import {test,expect,type Workspace,type Evidence} from './fixtures/test';
const harness=require('./fixtures/harness.cjs');type Api=(route:string,body?:any)=>Promise<any>;test.use({actionTimeout:10_000});
async function exercise(page:Page,workspace:Workspace,evidence:Evidence,api:Api,url?:string){
 const fixtureScript=path.join(harness.REPO_ROOT,'scripts/e2e/fixtures/gan_adoption_data.py');
 const fixture=JSON.parse(execFileSync(harness.resolvePython(),[fixtureScript,workspace.root],{encoding:'utf8',timeout:15_000}));
 await api('/api/project/create',{name:'GAN adoption original test cohort',task:'classification'});await api('/api/project/update',{source_dataset_dir:fixture.source});let project=await api('/api/project/current');await api('/api/dataset/import',{folder_path:fixture.source,task:'classification'});
 const split=JSON.parse(execFileSync(harness.resolvePython(),[fixtureScript,workspace.root,JSON.stringify(project)],{encoding:'utf8',timeout:15_000}));
 if(url)await page.goto(url);else await page.reload();await expect(page.getByTitle('프로젝트 관리',{exact:true})).toContainText(project.name);
 const stage=async(index:number)=>page.getByRole('navigation',{name:'Workflow Stages'}).getByRole('button').nth(index).click();await stage(2);
 const family=async(name:string)=>page.getByRole('region',{name:'모델 학습 허브'}).getByRole('button',{name:new RegExp('^'+name)}).click();
 async function trainClassifier(){
  await family('이미지 분류');await page.getByRole('combobox',{name:'학습 모델 구조',exact:true}).selectOption('efficientnet_b0');await page.getByLabel('수동 학습 횟수',{exact:true}).fill('1');await page.getByLabel('수동 학습 입력 크기',{exact:true}).fill('64');
  const device=page.getByLabel('다음 학습 로컬 장치',{exact:true});if(!await device.isVisible())await page.locator('summary').filter({hasText:'다음 학습 배치·로컬 장치 설정'}).click();await page.getByLabel('다음 학습 배치 크기',{exact:true}).fill('2');await device.selectOption('cpu');
  const budget=page.getByLabel('학습 시간 제한 (분)',{exact:true});if(!await budget.isVisible())await page.locator('summary').filter({hasText:'학습 실행 예산·대기열'}).click();await budget.fill('2');
  const waiting=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/training/start'&&r.request().method()==='POST');await page.getByRole('button',{name:'선택 설정으로 학습 시작',exact:true}).click();const response=await waiting;expect(response.ok(),await response.text()).toBe(true);const posted=response.request().postDataJSON(),accepted=await response.json();expect(posted).toMatchObject({task:'classification',device:'cpu',config_overrides:{backbone:'efficientnet_b0',epochs:1,image_size:64,batch_size:2}});
  let terminal:any;await expect.poll(async()=>{terminal=await api('/api/training/status?job_id='+accepted.job_id);if(['failed','cancelled','aborted'].includes(terminal.status))throw Error(JSON.stringify(terminal));return terminal.status;},{timeout:125_000}).toBe('completed');await expect(page.getByRole('region',{name:'학습 로그'})).toContainText('완료',{timeout:20_000});
  const metadata=JSON.parse(fs.readFileSync(path.join(project.models_dir,accepted.job_id,'model_meta.json'),'utf8'));return {job_id:accepted.job_id,posted,terminal,metadata};
 }
 const before=await trainClassifier();await family('결함 이미지 생성');const workbench=page.locator('details').filter({has:page.locator('summary').filter({hasText:'결함 이미지 생성 실험'})});await workbench.locator('summary').first().click();
 await workbench.getByRole('textbox',{name:/결함 영역 표/}).fill(fixture.rows.map((r:any)=>`${r.image}\t${r.bbox.join(',')}\t${r.split}\t${r.label}`).join('\n'));
 let waiting=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/defect-gan/prepare'&&r.request().method()==='POST');await workbench.getByRole('button',{name:'원본을 보존하고 학습 복사본 준비',exact:true}).click();let response=await waiting;expect(response.ok(),await response.text()).toBe(true);const prepared=await response.json();expect(prepared.split_counts).toEqual({train:4,val:2,test:2});
 await workbench.getByLabel('학습 epoch',{exact:true}).fill('2');await workbench.locator('summary').filter({hasText:'학습 시간 제한·대기열'}).click();await workbench.getByLabel('학습 시간 제한 (분)',{exact:true}).fill('2');
 waiting=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/defect-gan/train'&&r.request().method()==='POST');await workbench.getByRole('button',{name:'생성 모델 학습',exact:true}).click();response=await waiting;expect(response.ok(),await response.text()).toBe(true);const ganPosted=response.request().postDataJSON(),gan=await response.json();let ganTerminal:any;
 await expect.poll(async()=>{ganTerminal=await api('/api/defect-gan/jobs/'+gan.job_id);if(['failed','cancelled','aborted'].includes(ganTerminal.status))throw Error(JSON.stringify(ganTerminal));return ganTerminal.status;},{timeout:125_000}).toBe('completed');await expect(workbench.getByRole('combobox',{name:'완료된 GAN 생성 모델',exact:true})).toHaveValue(gan.job_id,{timeout:20_000});
 await workbench.getByLabel('생성 장수',{exact:true}).fill('2');await workbench.getByLabel('생성 시드',{exact:true}).fill('41');waiting=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/model-execution/recipes'&&r.request().method()==='POST'&&r.request().postDataJSON()?.task==='defect_gan'&&r.request().postDataJSON()?.stage==='generate');await workbench.getByRole('button',{name:'후보 생성',exact:true}).click();response=await waiting;expect(response.ok(),await response.text()).toBe(true);const plain=await response.json();expect(response.request().postDataJSON()).toMatchObject({task:'defect_gan',stage:'generate',execution_target:'local',device:'cpu',params:{job_id:gan.job_id,count:2,seed:41}});expect(plain.execution.evidence_sha256).toMatch(/^[a-f0-9]{64}$/);expect(plain.candidates.map((r:any)=>r.status)).toEqual(['synthetic_unreviewed','synthetic_unreviewed']);expect(fs.readdirSync(project.dataset_dir)).not.toContain('synthetic_adoptions');
 waiting=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/defect-gan/export'&&r.request().method()==='POST');await workbench.getByRole('button',{name:'생성·검토 작업 패키지 내보내기',exact:true}).click();response=await waiting;expect(response.ok(),await response.text()).toBe(true);const exported=await response.json();const offline=JSON.parse(execFileSync(harness.resolvePython(),[path.join(harness.REPO_ROOT,'scripts/e2e/fixtures/gan_generation_package_readback.py'),JSON.stringify({...exported,project_dir:project.project_dir,expected:plain.candidates})],{encoding:'utf8',timeout:65_000}));expect(offline.exact_pixel_parity).toBe(true);
 await workbench.getByLabel('원본 영역에 결함 후보 합성',{exact:true}).check();const background=fixture.files.find((r:any)=>r.split==='train'&&r.label==='OK');await workbench.getByRole('combobox',{name:'GAN 합성 원본',exact:true}).selectOption(background.path);await expect(workbench.getByRole('img',{name:'GAN 원본 합성 영역 그리기',exact:true})).toBeVisible();
 const boxes=[[4,4,24,24],[34,22,58,42]];for(let i=0;i<2;i++){await workbench.getByRole('button',{name:'좌표로 영역 추가',exact:true}).click();for(let axis=0;axis<4;axis++)await workbench.getByLabel(['X₁ (px)','Y₁ (px)','X₂ (px)','Y₂ (px)'][axis],{exact:true}).nth(i).fill(String(boxes[i][axis]));}
 await workbench.getByLabel('불투명도',{exact:true}).nth(1).fill('0.5');await workbench.getByLabel('경계 혼합 (px)',{exact:true}).nth(1).fill('2');await workbench.getByLabel('합성 영역 2 외곽선',{exact:true}).fill('34,22;58,22;46,42');await workbench.getByLabel('생성 시드',{exact:true}).fill('43');
 waiting=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/model-execution/recipes'&&r.request().method()==='POST'&&r.request().postDataJSON()?.task==='defect_gan'&&r.request().postDataJSON()?.stage==='generate');await workbench.getByRole('button',{name:'후보 생성',exact:true}).click();response=await waiting;expect(response.ok(),await response.text()).toBe(true);const generationRequest=response.request().postDataJSON(),compositionPosted=generationRequest.params,composed=await response.json();expect(generationRequest).toMatchObject({task:'defect_gan',stage:'generate',execution_target:'local',device:'cpu'});expect(composed.execution.evidence_sha256).toMatch(/^[a-f0-9]{64}$/);expect(compositionPosted.regions[1].mask_polygon).toEqual([[34,22],[58,22],[46,42]]);expect(composed.source_image_sha256).toBe(background.sha256);expect(composed.candidates).toHaveLength(2);
 await evidence.screenshot(page,'actual-gan-original-two-region-masked-candidates');await page.reload();await stage(2);await family('결함 이미지 생성');await workbench.locator('summary').first().click();await workbench.getByRole('combobox',{name:'완료된 GAN 생성 모델',exact:true}).selectOption(gan.job_id);await workbench.getByRole('button',{name:'저장된 생성 후보 열기',exact:true}).click();await expect(workbench.getByRole('img',{name:'결함 생성 후보 '+composed.candidates[0].id,exact:true})).toBeVisible();
 await workbench.getByLabel('검토자',{exact:true}).fill('Codex synthetic software qualification');await workbench.getByLabel('채택 결함 클래스',{exact:true}).fill('scratch');await workbench.getByLabel('채택 검토 이유',{exact:true}).fill('Synthetic control transition only; no human or model-quality approval');
 await workbench.getByRole('combobox',{name:'후보 '+composed.candidates[0].id+' 검토',exact:true}).selectOption('adopt');await workbench.getByRole('combobox',{name:'후보 '+composed.candidates[1].id+' 검토',exact:true}).selectOption('reject');waiting=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/defect-gan/adopt'&&r.request().method()==='POST');await workbench.getByRole('button',{name:'검토 저장·학습 데이터 준비',exact:true}).click();response=await waiting;expect(response.ok(),await response.text()).toBe(true);const adopted=await response.json();expect(adopted).toMatchObject({adopted_count:1,real_image_count:12,task:'classification'});
 await workbench.getByRole('button',{name:'채택 데이터로 학습 준비',exact:true}).click();await expect.poll(async()=> (await api('/api/project/current')).source_dataset_dir).toBe(adopted.dataset_path);project=await api('/api/project/current');const after=await trainClassifier();
 await family('결함 이미지 생성');await workbench.locator('summary').first().click();const comparison=workbench.getByRole('region',{name:'GAN 채택 전후 검사 비교',exact:true});await comparison.getByRole('combobox',{name:'채택 전 검사 모델',exact:true}).selectOption(before.job_id);await comparison.getByRole('combobox',{name:'채택 후 검사 모델',exact:true}).selectOption(after.job_id);
 waiting=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/defect-gan/downstream-comparison'&&r.request().method()==='POST');await comparison.getByRole('button',{name:'같은 원본 시험 데이터로 비교·저장',exact:true}).click();response=await waiting;expect(response.ok(),await response.text()).toBe(true);const compared=await response.json();expect(compared).toMatchObject({heldout_count:3,synthetic_train_count:1,same_original_test_cohort:true,full_test:true,quality_approved:false});await expect(comparison.getByLabel('저장된 GAN 채택 전후 비교',{exact:true})).toContainText(compared.comparison_id);await evidence.screenshot(page,'actual-gan-downstream-same-original-heldout-comparison');
 await page.reload();await stage(2);await family('결함 이미지 생성');await workbench.locator('summary').first().click();await expect(workbench.getByLabel('저장된 GAN 채택 전후 비교',{exact:true})).toContainText(compared.comparison_id);expect((await api('/api/defect-gan/downstream-comparison')).comparison.evidence_sha256).toBe(compared.evidence_sha256);
 for(const file of fixture.files){expect(crypto.createHash('sha256').update(fs.readFileSync(file.path)).digest('hex')).toBe(file.sha256);evidence.addFile(file.path);}evidence.addFile(split.split_path);
 evidence.note('gan_adoption_qualification',{fixture,project,split,before,after,prepared,ganPosted,ganTerminal,plain,exported,offline,compositionPosted,composed,adopted,compared,actual_cpu:true,actual_app_training_buttons:true,actual_same_original_test_cohort:true,actual_review_state_reopen:true,actual_fresh_generation_package:true,originals_unchanged:true,human_review_approval:false,quality_approved:false});
}
test('actual GAN generation source masks review train-only adoption classifier A/B and offline candidate',{tag:'@owned-model'},async({page,request,renderer,workspace,evidence})=>{test.setTimeout(300_000);const api:Api=async(route,body)=>{const r=body===undefined?await request.get(renderer.origin+route):route.endsWith('/update')?await request.put(renderer.origin+route,{data:body}):await request.post(renderer.origin+route,{data:body});expect(r.ok(),await r.text()).toBe(true);return r.json();};await exercise(page,workspace,evidence,api,renderer.url);});
test('native actual GAN generates masked candidates adopts only train and reopens full heldout A/B',{tag:['@electron','@owned-model']},async({electronSession,workspace,evidence})=>{test.setTimeout(300_000);const {window}=electronSession;const backend=await electronSession.waitForBackend();const api:Api=(route,body)=>window.evaluate(async({port,route,body})=>{const r=await fetch(`http://127.0.0.1:${port}${route}`,{...(body===undefined?{}:{method:route.endsWith('/update')?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})});if(!r.ok)throw Error(`Owned API ${r.status}: ${await r.text()}`);return r.json();},{port:backend.port,route,body});await exercise(window,workspace,evidence,api);});
