import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { execFileSync } from 'node:child_process';
import type { Page } from '@playwright/test';
import { test, expect, type Workspace, type Evidence } from './fixtures/test';
import { installDesktopHostShim } from './fixtures/desktop-host-shim';
const harness = require('./fixtures/harness.cjs');
type Api = (route: string, body?: any) => Promise<any>;
async function key(page: Page, target: any, value = 'Enter') { await target.focus(); await page.keyboard.press(value); }
const ids = (page: Page) => page.locator('[data-flow-node-id]').evaluateAll(nodes => nodes.map(n => n.getAttribute('data-flow-node-id')!));
async function exercise(page: Page, workspace: Workspace, evidence: Evidence, api: Api, resize: (width: number, height: number) => Promise<void>, url?: string) {
    const fixture = JSON.parse(execFileSync(harness.resolvePython(), [path.join(harness.REPO_ROOT, 'scripts/e2e/fixtures/canvas_source.py'), workspace.root], { encoding: 'utf8' }));
    await api('/api/project/create', { name: 'Keyboard canvas projection', task: 'anomaly' });
    await api('/api/project/update', { source_dataset_dir: fixture.source });
    const project = await api('/api/project/current');
    await api('/api/dataset/import', { folder_path: fixture.source, task: 'anomaly' });
    if (url)
        await page.goto(url);
    else
        await page.reload();
    await expect(page.getByTitle('프로젝트 관리', { exact: true })).toContainText(project.name);
    await page.getByRole('navigation', { name: 'Workflow Stages' }).getByRole('button').nth(4).click();
    await expect(page.getByRole('heading', { name: '검사 플로우 편집기', exact: true })).toBeVisible();
    await expect(page.locator('[data-flow-node-id]')).not.toHaveCount(0);
    const enterQuick = async () => { const summary = page.locator('summary').filter({ hasText: '빠른 노드 추가·연결·실행 자원' }); if (!await summary.evaluate(e => (e.parentElement as HTMLDetailsElement).open))
        await key(page, summary); };
    await enterQuick();
    const before = await ids(page), edges = await page.locator('[data-flow-edge]').count();
    await key(page, page.locator('details').filter({ has: page.locator('summary').filter({ hasText: '빠른 노드 추가·연결·실행 자원' }) }).getByRole('button', { name: '검사 모델', exact: true }));
    await expect.poll(async () => (await ids(page)).length).toBe(before.length + 1);
    const added = (await ids(page)).find(id => !before.includes(id))!;
    const node = page.locator(`[data-flow-node-id="${added}"]`), focus = node.locator('[data-flow-node-focus]');
    await expect(focus).toBeFocused();
    await page.keyboard.press('Space');
    await expect(focus).toHaveAttribute('aria-label', /선택됨/);
    await page.keyboard.press('Tab');
    await expect(node.getByRole('button', { name: /IMAGE\/ROI IN$/ })).toBeFocused();
    const existing = page.locator('[data-flow-node-id]').filter({ has: page.getByRole('button', { name: /RESULT OUT$/ }) }).filter({ hasNot: focus }).first();
    await key(page, existing.getByRole('button', { name: /RESULT OUT$/ }));
    await key(page, node.getByRole('button', { name: /IMAGE\/ROI IN$/ }));
    await expect(page.getByText(/이 입력은 이미지·ROI만 받습니다/)).toBeVisible();
    await key(page, existing.getByRole('button', { name: /IMAGE\/ROI OUT$/ }));
    await key(page, node.getByRole('button', { name: /IMAGE\/ROI IN$/ }));
    await expect.poll(() => page.locator('[data-flow-edge]').count()).toBe(edges + 1);
    await expect(node.getByRole('button').first()).toBeEnabled();
    await key(page, focus, 'Delete');
    await expect(node).toHaveCount(0);
    await expect(page.locator('[data-flow-node-focus]:focus')).toHaveCount(1);
    await expect(page.getByRole('button', { name: '플로우 실행 취소', exact: true })).toBeEnabled();
    await page.keyboard.press('Control+z');
    await expect(node).toHaveCount(1);
    await expect.poll(() => page.locator('[data-flow-edge]').count()).toBe(edges + 1);
    await expect(page.getByRole('button', { name: '플로우 다시 실행', exact: true })).toBeEnabled();
    await page.keyboard.press('Control+Shift+z');
    await expect(node).toHaveCount(0);
    await expect(page.getByRole('button', { name: '플로우 실행 취소', exact: true })).toBeEnabled();
    await page.keyboard.press('Control+z');
    await expect(node).toHaveCount(1);
    const opener = page.getByRole('button', { name: '이미지 변경...', exact: true });
    await key(page, opener);
    const dialog = page.getByRole('dialog', { name: '검사 대상 이미지 선택', exact: true });
    await expect(dialog).toBeVisible();
    const close = dialog.getByRole('button', { name: '닫기 (Esc)', exact: true });
    await expect(close).toBeFocused();
    await page.keyboard.press('Shift+Tab');
    await expect(dialog.getByRole('button', { name: '취소', exact: true })).toBeFocused();
    await page.keyboard.press('Tab');
    await expect(close).toBeFocused();
    await page.keyboard.press('Escape');
    await expect(dialog).not.toBeVisible();
    await expect(opener).toBeFocused();
    await page.keyboard.press('Enter');
    await expect(dialog).toBeVisible();
    await key(page, dialog.getByRole('button', { name: '로컬 파일', exact: true }));
    await dialog.getByPlaceholder('예: /path/to/inspection-image.png').fill(fixture.path);
    await key(page, dialog.getByRole('button', { name: '선택 확정', exact: true }));
    await expect(dialog).not.toBeVisible();
    await expect(opener).toBeFocused();
    await enterQuick();
    const prior = await ids(page);
    await key(page, page.locator('details').filter({ has: page.locator('summary').filter({ hasText: '빠른 노드 추가·연결·실행 자원' }) }).getByRole('button', { name: '고정 ROI', exact: true }));
    await expect.poll(async () => (await ids(page)).length).toBe(prior.length + 1);
    const roiId = (await ids(page)).find(id => !prior.includes(id))!, roiNode = page.locator(`[data-flow-node-id="${roiId}"]`);
    await expect(roiNode.locator('[data-flow-node-focus]')).toBeFocused();
    const roi = page.getByRole('application', { name: '원본 이미지 ROI 편집', exact: true });
    await expect(roi).toHaveAttribute('viewBox', '0 0 512 256');
    const scales: any[] = [];
    for (const size of [[1366, 768], [1920, 1080]]) {
        await resize(size[0], size[1]);
        for (const scale of [1, 1.25, 1.5, 2]) {
            await page.evaluate(s => document.documentElement.style.zoom = String(s), scale);
            await roi.scrollIntoViewIfNeeded();
            await roi.focus();
            expect(await roi.evaluate(e => getComputedStyle(e).outlineStyle)).not.toBe('none');
            const points = await roi.evaluate(e => { const matrix = (e as SVGSVGElement).getScreenCTM()!; return [[64.25, 32.25], [256.25, 160.25]].map(([x, y]) => { const p = new DOMPoint(x, y).matrixTransform(matrix); return { x: p.x, y: p.y }; }); });
            await page.mouse.move(points[0].x, points[0].y);
            await page.mouse.down();
            await page.mouse.move(points[1].x, points[1].y, { steps: 4 });
            await page.mouse.up();
            const rect = roi.locator('rect');
            await expect(rect).toHaveAttribute('x', '64');
            await expect(rect).toHaveAttribute('y', '32');
            await expect(rect).toHaveAttribute('width', '193');
            await expect(rect).toHaveAttribute('height', '129');
            await roi.focus();
            await page.keyboard.press('ArrowRight');
            await expect(rect).toHaveAttribute('x', '65');
            await page.keyboard.press('Shift+ArrowDown');
            await expect(rect).toHaveAttribute('height', '130');
            await roiNode.scrollIntoViewIfNeeded();
            const start = await roiNode.evaluate(e => ({ x: parseFloat((e as HTMLElement).style.left), y: parseFloat((e as HTMLElement).style.top) }));
            const box = (await roiNode.boundingBox())!, factor = box.width / 272;
            const a = { x: box.x + box.width * .5, y: box.y + 12 * factor };
            await page.mouse.move(a.x, a.y);
            await page.mouse.down();
            await page.mouse.move(a.x + 40 * factor, a.y + 30 * factor, { steps: 4 });
            await page.mouse.up();
            await expect.poll(() => roiNode.evaluate(e => ({ x: parseFloat((e as HTMLElement).style.left), y: parseFloat((e as HTMLElement).style.top) }))).toEqual({ x: start.x + 40, y: start.y + 30 });
            scales.push({ size, scale, roi: [65, 32, 258, 162], node_delta: [40, 30] });
        }
    }
    await page.evaluate(() => document.documentElement.style.zoom = '1');
    await key(page, page.getByRole('button', { name: '초안 저장', exact: true }));
    await expect.poll(async () => (await api('/api/flowchart/draft')).pipeline.nodes.find((n: any) => n.id === roiId)?.data.params.roi_bbox).toEqual([65, 32, 258, 162]);
    const draft = await api('/api/flowchart/draft');
    await evidence.screenshot(page, 'keyboard-nodes-original-roi-scale');
    await page.reload();
    await expect(page.getByTitle('프로젝트 관리', { exact: true })).toContainText(project.name);
    await page.getByRole('navigation', { name: 'Workflow Stages' }).getByRole('button').nth(4).click();
    await expect(roiNode).toHaveCount(1);
    await key(page, roiNode.locator('[data-flow-node-focus]'));
    await expect(page.getByText('원본 기준 [65, 32, 258, 162]', { exact: false })).toBeVisible();
    const reopened = await api('/api/flowchart/draft');
    expect(reopened.draft_sha256).toBe(draft.draft_sha256);
    expect(crypto.createHash('sha256').update(fs.readFileSync(fixture.path)).digest('hex')).toBe(fixture.sha256);
    evidence.addFile(fixture.path);
    evidence.note('keyboard_canvas_qualification', { fixture, project, draft, reopened, roi_id: roiId, scales, actual_keyboard_edits: true, actual_dialog_focus_restore: true, actual_original_coordinate_drag: true, actual_draft_reopen: true, windows_native_dpi: false, training_or_quality_approval: false });
}
test('keyboard graph and original ROI survive window and display scale changes', async ({ page, request, renderer, workspace, evidence }) => { test.setTimeout(240000); await installDesktopHostShim(page, renderer.port); const api: Api = async (route, body) => { const r = body === undefined ? await request.get(renderer.origin + route) : route.endsWith('/update') ? await request.put(renderer.origin + route, { data: body }) : await request.post(renderer.origin + route, { data: body }); expect(r.ok(), await r.text()).toBe(true); return r.json(); }; await exercise(page, workspace, evidence, api, async (w, h) => page.setViewportSize({ width: w, height: h }), renderer.url); });
test('native keyboard graph and original ROI preserve draft and focus', { tag: '@electron' }, async ({ electronSession, workspace, evidence }) => { test.setTimeout(240000); const { window, app } = electronSession; const backend = await electronSession.waitForBackend(); const api: Api = (route, body) => window.evaluate(async ({ port, route, body }) => { const r = await fetch(`http://127.0.0.1:${port}${route}`, body === undefined ? {} : { method: route.endsWith('/update') ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); if (!r.ok)
    throw Error(`Owned API ${r.status}: ${await r.text()}`); return r.json(); }, { port: backend.port, route, body }); await exercise(window, workspace, evidence, api, async (w, h) => { await app.evaluate(({ BrowserWindow }, { w, h }) => BrowserWindow.getAllWindows()[0].setContentSize(w, h), { w, h }); }); });
