import crypto from 'node:crypto';
import fs from 'node:fs';
import type {Page} from '@playwright/test';
import {test,expect,type Workspace,type Evidence} from './fixtures/test';
import {installDesktopHostShim} from './fixtures/desktop-host-shim';

type Api=(route:string,body?:unknown,method?:string)=>Promise<any>;
const sha=(bytes:Buffer)=>crypto.createHash('sha256').update(bytes).digest('hex');
async function exercise(page:Page,workspace:Workspace,evidence:Evidence,api:Api,native:boolean,url?:string){
 const prefix=native?'native':'browser',name='Metadata and truth fixture';
 const project=await api('/api/project/create',{name,task:'classification'});
 await api('/api/project/update',{source_dataset_dir:workspace.dataset},'PUT');await api('/api/dataset/import',{folder_path:workspace.dataset,task:'classification'});
 const image=workspace.images.find(i=>i.label==='ng')!,truthRoute='/api/image-truth?'+new URLSearchParams({image_path:image.path,task:'classification'})+'&classes=ok&classes=ng';
 const before=await api(truthRoute);expect(before.verdict).toBe('UNKNOWN');
 const navigate=async(stage:number)=>{if(url)await page.goto(url);else await page.reload();await expect(page.getByTitle('프로젝트 관리',{exact:true})).toContainText(name);await page.getByRole('navigation',{name:'Workflow Stages'}).getByRole('button').nth(stage).click();};
 await navigate(1);await page.getByRole('button',{name:'이미지 정보·검토',exact:true}).click();const review=page.getByRole('region',{name:'이미지 정보와 검토 기록'});
 await expect(review.getByLabel('작업자·검토자 이름')).toBeVisible();await review.getByLabel('작업자·검토자 이름').fill('fixture-reviewer');await review.getByLabel('자유 태그 (쉼표 구분)').fill('inspection-ready');await review.getByLabel('제품',{exact:true}).fill('Fixture board');await review.getByLabel('로트',{exact:true}).fill('Lot-7');await review.getByRole('button',{name:'정보 저장',exact:true}).click();
 await review.getByRole('button',{name:'검토 요청',exact:true}).click();await expect(page.getByText('검토 필요',{exact:true}).first()).toBeVisible();await review.getByRole('button',{name:'라벨 승인',exact:true}).click();await expect(page.getByText('승인됨',{exact:true}).first()).toBeVisible();
 const rows=await api('/api/dataset/metadata?limit=10'),approved=rows.items.find((r:any)=>r.workflow_state==='approved');expect(approved).toBeTruthy();expect(approved.reviewer).toBe('fixture-reviewer');expect(approved.tags).toEqual(['inspection-ready']);expect(approved.audit.filter((r:any)=>r.actor==='fixture-reviewer').map((r:any)=>r.action)).toEqual(['metadata_edited','review','review']);
 const approvedTruthRoute='/api/image-truth?'+new URLSearchParams({image_path:approved.file_path,task:'classification'})+'&classes=ok&classes=ng';const afterApproval=await api(approvedTruthRoute);expect(afterApproval.verdict).toBe('UNKNOWN');
 await evidence.screenshot(page,`${prefix}-review-audit-empty-annotation-not-normal`);
 await navigate(0);await page.getByRole('button',{name:'태그 색상·플래그',exact:true}).click();let prefs=page.getByRole('region',{name:'프로젝트 태그 색상과 모델 플래그'});
 await prefs.getByLabel('색상을 지정할 태그').fill('inspection-ready');await prefs.getByLabel('태그 색상',{exact:true}).fill('#24a7cb');await prefs.getByRole('button',{name:'저장',exact:true}).nth(0).click();await expect(prefs.getByRole('button',{name:'inspection-ready',exact:true})).toBeVisible();await prefs.getByLabel('라벨 세트 플래그').fill('baseline');await prefs.getByRole('button',{name:'저장',exact:true}).nth(1).click();
 await expect.poll(async()=>(await api('/api/project/preferences')).labelset_flags.default).toEqual(['baseline']);const first=await api('/api/project/preferences');expect(first.tag_colors['inspection-ready']).toBe('#24a7cb');expect(first.labelset_flags.default).toEqual(['baseline']);await evidence.screenshot(page,`${prefix}-default-labelset-flags-color`);
 await page.getByRole('navigation',{name:'Workflow Stages'}).getByRole('button').nth(1).click();await page.getByLabel('새 레이블셋 이름').fill('Second review');await page.getByRole('button',{name:'현재 라벨 복제',exact:true}).click();await expect(page.getByLabel('활성 레이블셋')).not.toHaveValue('default');const second=await api('/api/project/current');expect(second.active_labelset_id).not.toBe('default');
 await navigate(0);await page.getByRole('button',{name:'태그 색상·플래그',exact:true}).click();prefs=page.getByRole('region',{name:'프로젝트 태그 색상과 모델 플래그'});await prefs.getByLabel('라벨 세트 플래그').fill('second-pass');await prefs.getByRole('button',{name:'저장',exact:true}).nth(1).click();
 await expect.poll(async()=>(await api('/api/project/preferences')).labelset_flags[second.active_labelset_id]).toEqual(['second-pass']);const both=await api('/api/project/preferences');expect(both.labelset_flags.default).toEqual(['baseline']);expect(both.labelset_flags[second.active_labelset_id]).toEqual(['second-pass']);
 await navigate(1);await expect(page.getByLabel('활성 레이블셋')).toHaveValue(second.active_labelset_id);await page.getByRole('navigation',{name:'Workflow Stages'}).getByRole('button').nth(0).click();await page.getByRole('button',{name:'태그 색상·플래그',exact:true}).click();prefs=page.getByRole('region',{name:'프로젝트 태그 색상과 모델 플래그'});await expect(prefs.getByLabel('라벨 세트 플래그')).toHaveValue('second-pass');await expect(prefs.getByRole('button',{name:'inspection-ready',exact:true})).toBeVisible();await evidence.screenshot(page,`${prefix}-named-labelset-preferences-reopened`);await page.getByRole('button',{name:'태그 색상·플래그',exact:true}).click();
 const statistics=await api('/api/dataset/metadata/statistics');expect(statistics.total).toBe(2);expect(statistics.labelset_id).toBe(second.active_labelset_id);expect(statistics.classes.ng.count).toBe(1);expect(statistics.assignments.not_split.count).toBe(2);
 const queries:string[]=[];page.on('request',r=>{const u=new URL(r.url());if(u.pathname==='/api/dataset/images'&&u.searchParams.get('class_name')==='ng')queries.push(u.search);});const stats=page.getByRole('region',{name:'활성 라벨 세트 데이터 통계'});await expect(stats).toContainText('전체 이미지 2개');await stats.locator('summary',{hasText:'클래스별 이미지'}).click();await stats.getByRole('button',{name:/^ng/}).click();await expect.poll(()=>queries.length).toBeGreaterThan(0);await evidence.screenshot(page,`${prefix}-class-statistic-opens-gallery-filter`);
 for(const original of workspace.images){expect(sha(fs.readFileSync(original.path))).toBe(original.sha256);evidence.addFile(original.path);}
 evidence.note('metadata_truth_closure',{project_id:project.id,before,approved,afterApproval,preferences:both,active_labelset:second.active_labelset_id,statistics,class_filter_queries:queries,original:workspace.images,actual_ui_and_backend:true,label_approval_did_not_declare_normal_truth:true,named_flags_reopened:true,fixture_review_not_model_or_operational_quality_approval:true});
}
test('review metadata named flags colors and statistics reopen without declaring empty labels normal',async({page,request,renderer,workspace,evidence})=>{
 await installDesktopHostShim(page,renderer.port);const api:Api=async(route,body,method)=>{const r=await request.fetch(renderer.origin+route,{method:method||(body===undefined?'GET':'POST'),...(body===undefined?{}:{data:body})});expect(r.ok(),`Owned metadata fixture HTTP ${r.status()}`).toBe(true);return r.json();};await exercise(page,workspace,evidence,api,false,renderer.url);
});
test('native review metadata named flags colors and statistics reopen without declaring empty labels normal',{tag:'@electron'},async({electronSession,workspace,evidence})=>{
 const {window}=electronSession,status=await electronSession.waitForBackend();const api:Api=(route,body,method)=>window.evaluate(async({port,route,body,method})=>{const r=await fetch(`http://127.0.0.1:${port}${route}`,{method:method||(body===undefined?'GET':'POST'),...(body===undefined?{}:{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})});if(!r.ok)throw Error(`Owned metadata fixture HTTP ${r.status}`);return r.json();},{port:status.port,route,body,method});await exercise(window,workspace,evidence,api,true);
});
