import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {execFileSync} from 'node:child_process';
import type {Page} from '@playwright/test';import {test,expect,type Workspace,type Evidence} from './fixtures/test';
const harness=require('./fixtures/harness.cjs');
type Api=(route:string,body?:any)=>Promise<any>;
test.use({actionTimeout:10_000});
async function exercise(page:Page,workspace:Workspace,evidence:Evidence,api:Api,url?:string){
 const fixture=JSON.parse(execFileSync(harness.resolvePython(),[path.join(harness.REPO_ROOT,'scripts/e2e/fixtures/rotation_direction_data.py'),workspace.root],{encoding:'utf8',timeout:15_000}));
 const project=await api('/api/project/create',{name:'Explicit model execution target',task:'classification'});await api('/api/project/update',{source_dataset_dir:fixture.source});
 if(url)await page.goto(url);else await page.reload();
 await expect(page.getByTitle('프로젝트 관리',{exact:true})).toContainText(project.name);
 const enter=async()=>{await page.getByRole('navigation',{name:'Workflow Stages'}).getByRole('button').nth(2).click();await page.getByRole('region',{name:'모델 학습 허브'}).getByRole('button',{name:/^정방향 보정/}).click();};await enter();
 await page.locator('summary').filter({hasText:'각도 정답 표·가져오기 상세'}).click();await page.getByLabel('각도 정답 표 · 상대 이미지 경로 ↹ 보정각 ↹ train/val/test').fill(fixture.rows.map((r:any)=>`${r.image}\t${r.correction_deg}\t${r.split}`).join('\n'));
 const preparation=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/rotation/prepare'&&r.request().method()==='POST');await page.getByRole('button',{name:'원본과 보정각 준비',exact:true}).click();expect((await preparation).ok()).toBe(true);
 await page.getByLabel('Epoch',{exact:true}).fill('1');await page.getByLabel('모델 입력 크기',{exact:true}).fill('32');await page.getByLabel('학습 평가 장치',{exact:true}).first().selectOption('cpu');
 const training=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/rotation/train'&&r.request().method()==='POST');await page.getByRole('button',{name:'정방향 모델 후보 학습',exact:true}).click();const accepted=await training;expect(accepted.ok(),await accepted.text()).toBe(true);const job=(await accepted.json()).job_id;
 await expect.poll(async()=>(await api(`/api/rotation/jobs/${job}`)).status,{timeout:60_000}).toBe('completed');await expect(page.getByLabel('완료 정방향 후보 모델')).toHaveValue(job);
 const image=path.join(fixture.source,'test_90_0.png');await page.getByLabel('프로젝트 이미지 선택',{exact:true}).selectOption(image);
 const localPrediction=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/rotation/predict'&&r.request().method()==='POST');await page.getByRole('button',{name:'선택 이미지 정렬',exact:true}).click();const prediction=await localPrediction;expect(prediction.ok()).toBe(true);await expect(page.getByAltText('모델이 예측한 정방향 정렬 결과')).toBeVisible();
 // The production recipe endpoint executes the completed CPU model and writes
 // its immutable receipt. No browser request or prediction response is mocked.
 const recipe=await api('/api/model-execution/recipes',{task:'rotation',stage:'predict',execution_target:'local',device:'cpu',params:{job_id:job,image_path:image,include_aligned:true}});
 expect(recipe.aligned_image_base64).toBe((await prediction.json()).aligned_image_base64);const receipt=await api('/api/model-execution/recipes/'+recipe.execution.receipt_id);
 await page.getByRole('button',{name:'실행 기록 새로 읽기',exact:true}).click();const history=page.getByRole('region',{name:'저장된 실행 위치 기록'});await expect(history).toContainText(receipt.evidence_sha256);await evidence.screenshot(page,'actual-cpu-execution-receipt');
 const profile={id:'unreachable-owned-loopback',name:'Unavailable owned loopback',ssh_target:'127.0.0.1',ssh_port:1,remote_root:path.join(workspace.root,'unreachable-worker'),runtime_kind:'python',runtime_value:'python3'};await api('/api/compute/profiles',profile);
 await page.reload();await enter();await expect(history).toContainText(receipt.evidence_sha256);await page.getByLabel('모델 학습 실행 위치',{exact:true}).first().selectOption(profile.id);await expect(page.getByLabel('모델 학습 실행 위치',{exact:true}).first()).toHaveValue(profile.id);await expect(page.getByLabel('학습 평가 장치',{exact:true}).first()).toHaveValue('cpu');expect(await page.getByLabel('학습 평가 장치',{exact:true}).first().locator('option[value="mps"]').count()).toBe(0);
 await page.getByLabel('완료 정방향 후보 모델').selectOption(job);await page.getByLabel('프로젝트 이미지 선택',{exact:true}).selectOption(image);
 const posts:string[]=[];const observe=(req:any)=>{if(req.method()==='POST')posts.push(new URL(req.url()).pathname);};page.on('request',observe);
 const failed=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/model-execution/recipes'&&r.request().method()==='POST');await page.getByRole('button',{name:'선택 이미지 정렬',exact:true}).click();const wire=await failed;expect(wire.status()).toBe(503);expect(wire.request().postDataJSON()).toMatchObject({execution_target:'selected_compute',compute_profile_id:profile.id,device:'cpu',params:{job_id:job,image_path:image}});
 await expect(page.getByRole('alert').last()).toBeVisible();page.off('request',observe);expect(posts).not.toContain('/api/rotation/predict');await evidence.screenshot(page,'selected-server-failure-no-local-fallback');
 const independent=JSON.parse(execFileSync(harness.resolvePython(),['-c',"import hashlib,json,sys;from pathlib import Path;p=Path(sys.argv[1]);v=json.loads(p.read_bytes());expected=v.pop('evidence_sha256');actual=hashlib.sha256(json.dumps(v,ensure_ascii=False,sort_keys=True,separators=(',',':'),allow_nan=False).encode()).hexdigest();print(json.dumps({'expected':expected,'actual':actual}))",path.join(project.reports_dir,'execution_recipes',receipt.receipt_id+'.json')],{encoding:'utf8'}));expect(independent.actual).toBe(receipt.evidence_sha256);expect(independent.expected).toBe(receipt.evidence_sha256);
 for(const row of fixture.rows)expect(crypto.createHash('sha256').update(fs.readFileSync(path.join(fixture.source,row.image))).digest('hex')).toBe(row.source_sha256);
 evidence.note('execution_target_qualification',{project,fixture,job_id:job,receipt,failed_status:wire.status(),failed_body:await wire.json(),observed_posts:posts,actual_cpu_model:true,actual_saved_receipt:true,real_ssh_gpu_success:false,source_unchanged:true});
}
test('browser native action preserves CPU receipt and fails selected server without local fallback',async({page,request,renderer,workspace,evidence})=>{test.setTimeout(180_000);const api:Api=async(route,body)=>{const r=body===undefined?await request.get(renderer.origin+route):route.endsWith('/update')?await request.put(renderer.origin+route,{data:body}):await request.post(renderer.origin+route,{data:body});expect(r.ok(),await r.text()).toBe(true);return r.json();};await exercise(page,workspace,evidence,api,renderer.url);});
test('native application preserves CPU receipt and fails selected server without local fallback',{tag:'@electron'},async({electronSession,workspace,evidence})=>{test.setTimeout(180_000);const {window}=electronSession;const backend=await electronSession.waitForBackend();const api:Api=(route,body)=>window.evaluate(async({port,route,body})=>{const r=await fetch(`http://127.0.0.1:${port}${route}`,{...(body===undefined?{}:{method:route.endsWith('/update')?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})});if(!r.ok)throw Error(`Owned API ${r.status}: ${await r.text()}`);return r.json();},{port:backend.port,route,body});await exercise(window,workspace,evidence,api);});
