import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {execFileSync} from 'node:child_process';
import type {Page} from '@playwright/test';
import {test,expect,type Workspace,type Evidence} from './fixtures/test';
import {installDesktopHostShim} from './fixtures/desktop-host-shim';
import {png} from './qa/appFlow';
test.use({actionTimeout:10_000});
type Api=(route:string,body?:unknown,method?:string)=>Promise<any>;
type Download=(action:()=>Promise<void>,name:string)=>Promise<string>;
const sha=(file:string)=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
const python=(code:string,args:string[])=>execFileSync(process.env.MV_E2E_PYTHON||'python3',['-c',code,...args]);
async function exercise(page:Page,workspace:Workspace,evidence:Evidence,api:Api,chooseFolder:(dir:string)=>Promise<void>,download:Download,native:boolean,url?:string){
 const source=path.join(workspace.root,'pixel-source'),bundle=path.join(workspace.root,'pixel-bundle');fs.mkdirSync(bundle);
 const paths=['batch-a/part.png','batch-b/part.png'].map((name,i)=>{const file=path.join(source,name);fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,png(256,3,(x,y)=>[x,y,60+i*60]));return file;});
 const original=paths.map(file=>({path:file,sha256:sha(file)}));
 python("import sys,pathlib,json,hashlib,numpy as np\nfrom PIL import Image\nr=pathlib.Path(sys.argv[1]);s=pathlib.Path(sys.argv[2]);images=[]\nfor i,name in enumerate(['batch-a/part.png','batch-b/part.png']):\n p=np.zeros((256,256),np.uint8);dy=i*10;p[20+dy:100+dy,20:110]=7;p[40+dy:70+dy,45:80]=0;p[130+dy:200+dy,130:210]=23;p[155+dy:175+dy,155:185]=0\n mask='masks/'+name+'.png';f=r/mask;f.parent.mkdir(parents=True,exist_ok=True);Image.fromarray(p).save(f)\n images.append({'file_name':name,'mask_file':mask,'width':256,'height':256,'source_sha256':hashlib.sha256((s/name).read_bytes()).hexdigest()})\nclasses=[{'id':0,'name':'background','color':'#000000'},{'id':7,'name':'Scratch','color':'#f59e0b'},{'id':23,'name':'Crack','color':'#ef4444'},{'id':31,'name':'Void','color':'#a855f7'}]\n(r/'mask_manifest.json').write_text(json.dumps({'schema_version':1,'classes':classes,'images':images}),encoding='utf-8')",[bundle,source]);
 const manifest=JSON.parse(fs.readFileSync(path.join(bundle,'mask_manifest.json'),'utf8'));
 const project=await api('/api/project/create',{name:'Pixel mask roundtrip fixture',task:'segmentation'});await api('/api/project/update',{source_dataset_dir:source},'PUT');await api('/api/dataset/import',{folder_path:source,task:'segmentation'});
 if(url)await page.goto(url);else await page.reload();await expect(page.getByTitle('프로젝트 관리',{exact:true})).toContainText('Pixel mask roundtrip fixture');
 const stages=page.getByRole('navigation',{name:'Workflow Stages'}),toggle=page.getByRole('button',{name:'이미지 검토·그룹 분할·라벨 교환',exact:true});
 const open=async()=>{await stages.getByRole('button').nth(0).click();if(await toggle.getAttribute('aria-expanded')==='false')await toggle.click();const panel=page.getByRole('region',{name:'데이터 검토와 라벨 교환',exact:true});await expect(panel).toContainText('검색 결과 2개');await panel.getByLabel('데이터 작업자 이름',{exact:true}).fill('pixel-owner');const section=panel.getByLabel('외부 multiclass mask 교환',{exact:true});if(await section.getAttribute('open')===null)await section.locator('summary').click();return {panel,section};};
 let {panel,section}=await open();
 const select=async(dir:string)=>{await chooseFolder(dir);await section.getByRole('button',{name:'mask 폴더 선택',exact:true}).click();await expect(section.getByText(dir,{exact:true})).toBeVisible();};
 const request=async(name:string)=>{const response=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/dataset/masks/import'&&r.request().method()==='POST');await section.getByRole('button',{name,exact:true}).click();return response;};
 await select(bundle);const previewReply=await request('mask 미리보기');expect(previewReply.status()).toBe(200);const preview=await previewReply.json();
 expect(preview.preview.map((r:any)=>r.file_name)).toEqual(['batch-a/part.png','batch-b/part.png']);expect(preview.preview.every((r:any)=>r.incoming_count===2)).toBe(true);await expect(section.getByText('31=Void',{exact:false})).toHaveCount(2);
 await evidence.screenshot(page,`${native?'native':'browser'}-pixel-preview`);
 const changedMask=path.join(bundle,manifest.images[0].mask_file),originalMask=fs.readFileSync(changedMask);
 python("import sys,numpy as np\nfrom PIL import Image\nf=sys.argv[1];p=np.asarray(Image.open(f)).copy();p[0,0]=7;Image.fromarray(p).save(f)",[changedMask]);
 const refused=await request('검토한 mask 라벨 적용');expect(refused.status()).toBe(409);await expect(section.getByRole('alert')).toContainText('Mask files changed since preview');
 for(const file of paths){const row=await api(`/api/annotations/part?file_path=${encodeURIComponent(file)}`);expect(row.annotations).toEqual([]);expect(row.metadata.revision).toBe(1);}
 fs.writeFileSync(changedMask,originalMask);expect(sha(changedMask)).toBe(crypto.createHash('sha256').update(originalMask).digest('hex'));
 expect((await request('mask 미리보기')).status()).toBe(200);await section.getByLabel('외부 mask 충돌 처리',{exact:true}).selectOption('replace');const firstApplyReply=await request('검토한 mask 라벨 적용');expect(firstApplyReply.status()).toBe(200);const firstApply=await firstApplyReply.json();expect(firstApply.backup_version_id).toBeTruthy();await expect(section.getByRole('status').filter({hasText:'이전 버전'})).toBeVisible();
 const beforeMerge=await Promise.all(paths.map(async file=>{const current=await api(`/api/annotations/part?file_path=${encodeURIComponent(file)}`);return {annotations:current.annotations,revision:current.metadata.revision,mask_sha256:sha(current.mask_file),classes:current.mask_classes};}));
 const versionsBeforeMerge=fs.readdirSync(path.join(project.project_dir,'versions')).sort();
 const conflict=path.join(workspace.root,'pixel-conflict');fs.cpSync(bundle,conflict,{recursive:true});
 python("import sys,pathlib,json,numpy as np\nfrom PIL import Image\nr=pathlib.Path(sys.argv[1]);f=r/'mask_manifest.json';d=json.loads(f.read_text());next(c for c in d['classes'] if c['id']==7)['id']=8\nfor row in d['images']:\n p=np.asarray(Image.open(r/row['mask_file'])).copy();p[p==7]=8;Image.fromarray(p).save(r/row['mask_file'])\nf.write_text(json.dumps(d),encoding='utf-8')",[conflict]);
 await select(conflict);expect((await request('mask 미리보기')).status()).toBe(200);await section.getByLabel('외부 mask 충돌 처리',{exact:true}).selectOption('merge');const mergeRefused=await request('검토한 mask 라벨 적용');expect(mergeRefused.status()).toBe(422);await expect(section.getByRole('alert')).toContainText('Merge class name conflicts');
 const formatConflict=path.join(workspace.root,'format-conflict');fs.mkdirSync(formatConflict);fs.writeFileSync(path.join(formatConflict,'annotations.json'),JSON.stringify({images:['batch-a/part.png','batch-b/part.png'].map((file_name,i)=>({id:i+1,file_name,width:256,height:256})),categories:[{id:1,name:'Scratch'}],annotations:[1,2].map(image_id=>({id:image_id,image_id,category_id:1,bbox:[20,20,30,30],segmentation:[]})),studio_classes:[{label:'Scratch',category_id:8,color:'#f59e0b'}]}));
 const formatSummary=panel.getByText('LabelMe · COCO · YOLO 라벨 가져오기/내보내기',{exact:true});if(await formatSummary.locator('..').getAttribute('open')===null)await formatSummary.click();await panel.getByLabel('라벨 교환 형식',{exact:true}).selectOption('coco');await chooseFolder(formatConflict);await panel.getByRole('button',{name:'라벨 폴더 선택',exact:true}).click();await panel.getByLabel('기존 라벨 충돌 처리',{exact:true}).selectOption('merge');
 const formatPreview=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/dataset/formats/import'&&r.request().method()==='POST');await panel.getByRole('button',{name:'가져오기 미리보기',exact:true}).click();expect((await formatPreview).status()).toBe(200);const formatApply=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/dataset/formats/import'&&r.request().method()==='POST');await panel.getByRole('button',{name:'검토한 라벨 적용',exact:true}).click();expect((await formatApply).status()).toBe(422);await expect(panel.getByRole('alert').filter({hasText:'Merge class name conflicts'})).toHaveCount(2);
 for(let i=0;i<paths.length;i++){const current=await api(`/api/annotations/part?file_path=${encodeURIComponent(paths[i])}`);expect({annotations:current.annotations,revision:current.metadata.revision,mask_sha256:sha(current.mask_file),classes:current.mask_classes}).toEqual(beforeMerge[i]);}
 expect(fs.readdirSync(path.join(project.project_dir,'versions')).sort()).toEqual(versionsBeforeMerge);await evidence.screenshot(page,`${native?'native':'browser'}-merge-class-conflicts-refused`);
 const exports:any[]=[];const snapshots:any[]=[];
 const collect=async(label:string)=>{for(let i=0;i<paths.length;i++){
  const current=await api(`/api/annotations/part?file_path=${encodeURIComponent(paths[i])}`);expect(current.annotations.map((a:any)=>[a.type,a.label,a.category_id,a.color])).toEqual([['brush_mask','Scratch',7,'#f59e0b'],['brush_mask','Crack',23,'#ef4444']]);expect(current.mask_classes).toEqual(manifest.classes);expect(sha(paths[i])).toBe(original[i].sha256);
  const disk=path.join(path.dirname(path.dirname(current.mask_file)),'part.json');expect(JSON.parse(fs.readFileSync(disk,'utf8')).annotations).toEqual(current.annotations);const json=path.join(workspace.logs,`${label}-${i}-annotation.json`),mask=path.join(workspace.logs,`${label}-${i}-mask.png`);fs.copyFileSync(disk,json);fs.copyFileSync(current.mask_file,mask);evidence.addFile(json);evidence.addFile(mask);snapshots.push({label,image_path:paths[i],expected_mask:path.join(bundle,manifest.images[i].mask_file),snapshot_json:json,snapshot_mask:mask,current});
  ({panel,section}=await open());await panel.getByRole('row').filter({hasText:`batch-${i===0?'a':'b'}/part.png`}).getByRole('button',{name:'2단계 검토',exact:true}).click();await expect(page.getByRole('button',{name:/^Scratch 1$/})).toBeVisible();await expect(page.getByRole('button',{name:/^Crack 1$/})).toBeVisible();await expect(page.getByRole('button',{name:'Void',exact:true})).toBeVisible();await page.getByRole('button',{name:'집중 편집',exact:true}).click();await page.getByTitle('100% Zoom (1:1)',{exact:true}).click();await evidence.screenshot(page,`${native?'native':'browser'}-${label}-batch-${i===0?'a':'b'}-holes-reopened`);
 }};
 await collect('imported');({panel,section}=await open());
 const exportBundle=async(originals:boolean,name:string)=>{const checkbox=section.getByRole('checkbox',{name:'원본 이미지 함께 내보내기',exact:true});await checkbox.setChecked(originals);const response=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/dataset/masks/export'&&r.request().method()==='POST');const zip=await download(()=>section.getByRole('button',{name:'pixel mask 내보내기',exact:true}).click(),name);const receipt=await (await response).json();expect(receipt).toMatchObject({image_count:2,annotation_count:4,include_originals:originals});const sourceZip=path.join(project.project_dir,'exports',path.basename(receipt.download_url)+'.zip');expect(sha(zip)).toBe(sha(sourceZip));evidence.addFile(zip);exports.push({originals,zip,sha256:sha(zip),source_zip:sourceZip,receipt});return zip;};
 const exported=await exportBundle(false,'labels-only');const roundtrip=path.join(workspace.root,'pixel-roundtrip');fs.mkdirSync(roundtrip);python("import sys,pathlib,zipfile\nr=pathlib.Path(sys.argv[2]).resolve()\nwith zipfile.ZipFile(sys.argv[1]) as z:\n for name in z.namelist():assert (r/name).resolve().is_relative_to(r) and not name.startswith('/')\n z.extractall(r)",[exported,roundtrip]);
 await select(roundtrip);const repreviewReply=await request('mask 미리보기');expect(repreviewReply.status()).toBe(200);const repreview=await repreviewReply.json();expect(repreview.preview.every((r:any)=>r.conflict)).toBe(true);await section.getByLabel('외부 mask 충돌 처리',{exact:true}).selectOption('replace');const secondApplyReply=await request('검토한 mask 라벨 적용');expect(secondApplyReply.status()).toBe(200);const secondApply=await secondApplyReply.json();expect(secondApply.backup_version_id).not.toBe(firstApply.backup_version_id);await expect(section.getByRole('status').filter({hasText:'이전 버전'})).toBeVisible();
 await collect('roundtrip');({panel,section}=await open());await exportBundle(true,'with-originals');
 evidence.note('pixel_roundtrip',{project,source,bundle,manifest,original,snapshots,exports,first_preview:preview,first_apply:firstApply,second_preview:repreview,second_apply:secondApply,
  changed_preview_refused_without_mutation:true,mask_and_coco_merge_refused_without_mutation_or_backup:true,premerge_snapshots:beforeMerge,versions_before_merge:versionsBeforeMerge,actual_export_import_reopen:true,folder_dialog_stubbed:true,unused_class_retained:31,internal_holes_retained:true,representative_annotation_quality:false,new_gpu_training:false});
}
test('app pixel-mask bundles retain holes palette and exact image identities',async({page,request,renderer,workspace,evidence})=>{
 await installDesktopHostShim(page,renderer.port);const api:Api=async(route,body,method)=>{const r=await request.fetch(renderer.origin+route,{method:method||(body===undefined?'GET':'POST'),...(body===undefined?{}:{data:body})});expect(r.ok(),await r.text()).toBe(true);return r.json();};const folder=(dir:string)=>page.evaluate(value=>{(window as any).api.selectFolder=async()=>value;},dir);const download:Download=async(action,name)=>{const event=page.waitForEvent('download');await action();const item=await event,target=path.join(workspace.logs,`${name}.zip`);await item.saveAs(target);expect(await item.failure()).toBeNull();return target;};await exercise(page,workspace,evidence,api,folder,download,false,renderer.url);
});
test('native pixel-mask bundles retain holes palette and exact image identities',{tag:'@electron'},async({electronSession,workspace,evidence})=>{
 const {window,app}=electronSession,backend=await electronSession.waitForBackend();const api:Api=(route,body,method)=>window.evaluate(async({port,route,body,method})=>{const r=await fetch(`http://127.0.0.1:${port}${route}`,{method:method||(body===undefined?'GET':'POST'),...(body===undefined?{}:{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})});if(!r.ok)throw Error(`Owned pixel fixture HTTP ${r.status}: ${await r.text()}`);return r.json();},{port:backend.port,route,body,method});const folder=(dir:string)=>app.evaluate(({dialog},value)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[value]});},dir);const download:Download=async(action,name)=>{const target=path.join(workspace.logs,`${name}.zip`);await app.evaluate(({session},file)=>{(globalThis as any).__pixelDownload=null;session.defaultSession.once('will-download',(_event,item)=>{item.setSavePath(file);item.once('done',(_ev,state)=>{(globalThis as any).__pixelDownload=state;});});},target);await action();await expect.poll(()=>app.evaluate(()=> (globalThis as any).__pixelDownload)).toBe('completed');return target;};await exercise(window,workspace,evidence,api,folder,download,true);
});
