import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import type {Page} from '@playwright/test';
import {test, expect, type Workspace, type Evidence} from './fixtures/test';
const harness = require('./fixtures/harness.cjs');
type Api = (route:string, body?:unknown, method?:string)=>Promise<any>;
const sha = (file:string)=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
test.use({actionTimeout:10_000});

// One epoch is an actual CPU artifact for lifecycle parity, not model quality.
async function exercise(page:Page, workspace:Workspace, evidence:Evidence, api:Api, url?:string){
  const fixture = JSON.parse(execFileSync(harness.resolvePython(), [path.join(harness.REPO_ROOT,'scripts/e2e/fixtures/ocr_korean_data.py'),workspace.root], {encoding:'utf8',timeout:15_000}));
  await api('/api/project/create', {name:'Portable lifecycle fixture', task:'segmentation', active_preset:'precision'});
  const project = await api('/api/project/update',{source_dataset_dir:fixture.source},'PUT');
  await api('/api/dataset/import',{folder_path:fixture.source,task:'segmentation'});
  const image = path.join(fixture.source,fixture.rows[0].image);
  const annotation = {id:'lifecycle-box',type:'bbox',label:'controlled-review',category_id:1,bbox:[1,1,8,8]};
  const dimensions = JSON.parse(execFileSync(harness.resolvePython(),['-c','from PIL import Image;import json,sys;print(json.dumps(Image.open(sys.argv[1]).size))',image],{encoding:'utf8',timeout:10_000}));
  await api('/api/annotations/save',{image_id:path.basename(image,'.png'),image_path:image,image_width:dimensions[0],image_height:dimensions[1],annotations:[annotation],actor:'lifecycle-fixture'});
  let row = await api('/api/dataset/metadata/image?image_path='+encodeURIComponent(image));
  row = await api('/api/dataset/metadata/'+row.image_uuid,{expected_revision:row.revision,actor:'controlled-reviewer',changes:{workflow_state:'approved'}},'PATCH');
  const version = await api('/api/dataset/versions',{name:'Before relocation',note:'Owned synthetic lifecycle evidence'});
  await api('/api/project/preferences',{expected_revision:0,actor:'lifecycle-fixture',changes:{tag_colors:{'검수':'#123456'}}},'PATCH');
  await api('/api/project/retention/policy',{retention_days:15,trash_days:7,quota_bytes:1000000},'PUT');
  const prepared = await api('/api/ocr/prepare',{source_dataset_path:fixture.source,samples:fixture.rows.map(({image,text,split}:any)=>({image,text,split}))});
  const training = await api('/api/ocr/train',{dataset_path:prepared.dataset_path,epochs:1,batch_size:2,image_width:32,learning_rate:.003,device:'cpu',max_runtime_s:60,recipe:{mode:'detect_recognize',charset:'가나12'}});
  await expect.poll(async()=>(await api('/api/ocr/jobs/'+training.job_id)).status,{timeout:65_000}).toBe('completed');
  const model = (await api('/api/ocr/models')).models.find((candidate:any)=>candidate.job_id===training.job_id);
  const evaluated = await api('/api/ocr/evaluate',{job_id:training.job_id,dataset_path:prepared.dataset_path,split:'test'});
  const pipeline = await api('/api/flowchart/templates/single-segmentation?inspection_task=ocr&job_id='+training.job_id);
  const flowVersion = await api('/api/flowchart/pipeline?source_dataset_path='+encodeURIComponent(fixture.source),pipeline);
  const originalResult = await api('/api/flowchart/run',{image_path:path.join(fixture.source,'multiline.png'),pipeline,execution_target:'local',device:'cpu'});
  const items = (await api('/api/dataset/images?folder_path='+encodeURIComponent(fixture.source)+'&task=segmentation')).items;
  const run = await api('/api/inspections/runs',{source_folder:fixture.source,task:'segmentation',scope:'all',pipeline,images:items.slice(0,1),project_id:project.id,execution_target:'local',device:'cpu'});
  await api('/api/inspections/runs/'+run.run_id+'/execute',{image_path:items[0].file_path});
  await api('/api/inspections/runs/'+run.run_id+'/finish',{status:'completed'},'PUT');
  const beforeRun = await api('/api/inspections/runs/'+run.run_id);
  if(url) await page.goto(url); else await page.reload();
  await expect(page.getByTitle('프로젝트 관리',{exact:true})).toContainText(project.name);
  const manage = async()=>{await page.getByTitle('프로젝트 관리',{exact:true}).click();return page.getByRole('dialog',{name:'프로젝트 관리',exact:true});};
  let dialog = await manage();
  await dialog.getByRole('button',{name:'프로젝트 설정 템플릿',exact:true}).click();
  await dialog.getByRole('button',{name:'현재 설정을 템플릿으로 읽기',exact:true}).click();
  const templateField = dialog.getByLabel('프로젝트 설정 템플릿 JSON',{exact:true});
  await expect(templateField).toHaveValue(/modu-project-template-v1/);
  const template = JSON.parse(await templateField.inputValue());
  expect(template.tag_colors).toEqual({'검수':'#123456'});
  expect(JSON.stringify(template)).not.toContain(project.id);
  await evidence.screenshot(page,'lifecycle-allowlisted-setup-template');
  // Invalid pasted JSON/template must preserve the selected project and original files.
  await templateField.fill(JSON.stringify({...template,source_dataset_dir:fixture.source}));
  await dialog.getByLabel('템플릿 새 프로젝트 이름').fill('Refused setup');
  const invalidTarget = path.join(workspace.root,'invalid-template');
  await dialog.getByLabel('템플릿 새 프로젝트 폴더').fill(invalidTarget);
  let response = page.waitForResponse(r=>new URL(r.url()).pathname==='/api/project/create'&&r.request().method()==='POST');
  await dialog.getByRole('button',{name:'템플릿으로 새 프로젝트 만들기',exact:true}).click();
  expect((await response).status()).toBe(422); expect(fs.existsSync(invalidTarget)).toBe(false);
  await expect(dialog.getByRole('alert')).toContainText('template');
  await templateField.fill(JSON.stringify(template));
  const templateTarget = path.join(workspace.projects,'fresh-template');
  await dialog.getByLabel('템플릿 새 프로젝트 이름').fill('Fresh setup from template');
  await dialog.getByLabel('템플릿 새 프로젝트 폴더').fill(templateTarget);
  response = page.waitForResponse(r=>new URL(r.url()).pathname==='/api/project/create'&&r.request().method()==='POST');
  await dialog.getByRole('button',{name:'템플릿으로 새 프로젝트 만들기',exact:true}).click();
  const freshReply = await response;expect(freshReply.status()).toBe(200);const fresh = await freshReply.json();
  await expect(dialog).toHaveCount(0); expect(fresh.id).not.toBe(project.id); expect(fresh.source_dataset_dir).toBeNull();
  expect(fs.readdirSync(fresh.models_dir)).toEqual([]);expect((await api('/api/project/preferences')).tag_colors).toEqual(template.tag_colors);
  expect((await api('/api/project/retention')).policy).toEqual(template.retention_policy);
  await page.reload();await expect(page.getByTitle('프로젝트 관리',{exact:true})).toContainText(fresh.name);
  await api('/api/project/open',{project_dir:project.project_dir});await page.reload();
  dialog = await manage();await dialog.getByRole('button',{name:'프로젝트 백업',exact:true}).click();
  await dialog.getByPlaceholder('백업 ZIP을 저장할 폴더').fill(path.join(workspace.root,'backups'));
  response = page.waitForResponse(r=>new URL(r.url()).pathname==='/api/project/backup'&&r.request().method()==='POST');
  await dialog.getByRole('button',{name:'프로젝트 백업 만들기',exact:true}).click();
  const backupReply = await response; expect(backupReply.status()).toBe(200);const backup = await backupReply.json();
  await expect(dialog.getByRole('status')).toContainText('백업 완료');await evidence.screenshot(page,'lifecycle-archive-verified');
  const target = path.join(workspace.projects,'relocated-project');
  await dialog.getByRole('button',{name:'백업에서 복원',exact:true}).click();
  await dialog.getByPlaceholder('.mvision.zip 파일 경로').fill(backup.archive_path);
  await dialog.getByPlaceholder('아직 존재하지 않는 새 폴더 경로').fill(target);
  response = page.waitForResponse(r=>new URL(r.url()).pathname==='/api/project/restore'&&r.request().method()==='POST');
  await dialog.getByRole('button',{name:'새 프로젝트로 복원',exact:true}).click();
  const restoreReply = await response;expect(restoreReply.status()).toBe(200);const restored = await restoreReply.json();await expect(dialog).toHaveCount(0);
  expect(restored.id).toBe(project.id);expect(restored.project_dir).toBe(target);
  const restoredModel = (await api('/api/ocr/models')).models.find((candidate:any)=>candidate.job_id===training.job_id);
  expect(restoredModel.model_sha256).toBe(model.model_sha256);
  const activePipeline = await api('/api/flowchart/pipeline/active');expect(activePipeline.id).toBe(pipeline.id);
  const restoredResult = await api('/api/flowchart/run',{image_path:path.join(restored.source_dataset_dir,'multiline.png'),pipeline:activePipeline,execution_target:'local',device:'cpu'});
  expect(restoredResult.final_verdict).toBe(originalResult.final_verdict);
  expect(restoredResult.crops.map((crop:any)=>({text:crop.recognized_text,regions:crop.ocr_regions.map(({confidence,...region}:any)=>region),rules:crop.ocr_rule_result}))).toEqual(originalResult.crops.map((crop:any)=>({text:crop.recognized_text,regions:crop.ocr_regions.map(({confidence,...region}:any)=>region),rules:crop.ocr_rule_result})));
  const restoredImage = path.join(restored.source_dataset_dir,fixture.rows[0].image);
  expect((await api('/api/annotations/'+path.basename(restoredImage,'.png')+'?file_path='+encodeURIComponent(restoredImage))).annotations).toMatchObject([annotation]);
  const restoredList = await api('/api/inspections/runs');
  expect(restoredList.runs).toHaveLength(1);
  const restoredRun = await api('/api/inspections/runs/'+restoredList.runs[0].run_id);
  expect(restoredRun.run_id).not.toBe(beforeRun.run_id);
  expect(restoredRun.status).toBe('completed');expect(restoredRun.rows[0].image_sha256).toBe(beforeRun.rows[0].image_sha256);
  expect(restoredRun.rows[0].state).toBe(beforeRun.rows[0].state);
  expect(restoredRun.rows[0].result.crops[0].recognized_text).toBe(beforeRun.rows[0].result.crops[0].recognized_text);
  const restoredVersions = await api('/api/dataset/versions');expect(restoredVersions.versions.map((entry:any)=>entry.id)).toContain(version.id);
  await page.reload();await expect(page.getByTitle('프로젝트 관리',{exact:true})).toContainText(project.name);
  await page.getByRole('navigation',{name:'Workflow Stages'}).getByRole('button').nth(2).click();
  await page.getByRole('region',{name:'모델 학습 허브'}).getByRole('button',{name:/^문자 인식/}).click();
  await expect(page.getByRole('combobox',{name:'완료 후보 모델',exact:true})).toHaveValue(training.job_id);
  await expect(page.getByLabel('프로젝트에 저장된 문자 정답')).toHaveValue(restoredModel.metadata.dataset_path);
  await evidence.screenshot(page,'lifecycle-relocated-completed-candidate-reopened');
  dialog = await manage();await dialog.getByRole('button',{name:'백업에서 복원',exact:true}).click();
  await dialog.getByPlaceholder('.mvision.zip 파일 경로').fill(backup.archive_path);await dialog.getByPlaceholder('아직 존재하지 않는 새 폴더 경로').fill(target);
  response = page.waitForResponse(r=>new URL(r.url()).pathname==='/api/project/restore'&&r.request().method()==='POST');await dialog.getByRole('button',{name:'새 프로젝트로 복원',exact:true}).click();expect((await response).status()).toBe(409);
  await expect(dialog.getByRole('alert')).toContainText('already exists');await evidence.screenshot(page,'lifecycle-existing-target-refusal');
  for(const image of fixture.images){expect(sha(path.join(fixture.source,image.image))).toBe(image.source_sha256);expect(sha(path.join(restored.source_dataset_dir,image.image))).toBe(image.source_sha256);}
  evidence.note('project_lifecycle',{fixture,project,template,fresh,prepared,training,model,evaluated,version,flow_version:flowVersion,original_result:originalResult,run,before_run:beforeRun,backup,restored,restored_model:restoredModel,restored_result:restoredResult,restored_run:restoredRun,restored_versions:restoredVersions,annotation,review:row,actual_cpu_training:true,actual_app_template_backup_restore:true,original_unchanged:true,quality_approval:false});
}

test('actual app template and fresh archive relocation preserve model source versions and review history',async({page,request,renderer,workspace,evidence})=>{
  test.setTimeout(200_000);
  const api:Api=async(route,body,method)=>{const r=await request.fetch(renderer.origin+route,{method:method||(body===undefined?'GET':'POST'),...(body===undefined?{}:{data:body})});expect(r.ok(),await r.text()).toBe(true);return r.json();};
  await exercise(page,workspace,evidence,api,renderer.url);
});
test('native lifecycle creates clean setup and reopens relocated actual CPU candidate',{tag:'@electron'},async({electronSession,workspace,evidence})=>{
  test.setTimeout(200_000);const {window}=electronSession,backend=await electronSession.waitForBackend();
  const api:Api=(route,body,method)=>window.evaluate(async({port,route,body,method})=>{const r=await fetch(`http://127.0.0.1:${port}${route}`,{method:method||(body===undefined?'GET':'POST'),...(body===undefined?{}:{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})});if(!r.ok)throw Error(`Owned lifecycle HTTP ${r.status}: ${await r.text()}`);return r.json();},{port:backend.port,route,body,method});
  await exercise(window,workspace,evidence,api);
});
