import path from 'node:path';
import {test,expect} from './fixtures/test';
import {installDesktopHostShim} from './fixtures/desktop-host-shim';

test('optimization renderer refuses cached source and foreign poll responses before review',async({page,renderer,workspace,evidence})=>{
 await installDesktopHostShim(page,renderer.port);
 const created=await page.request.post(renderer.origin+'/api/project/create',{data:{name:'Optimization source binding control',task:'classification'}});expect(created.ok(),await created.text()).toBe(true);
 const project=await created.json();
 const updated=await page.request.put(renderer.origin+'/api/project/update',{data:{source_dataset_dir:workspace.dataset}});expect(updated.ok(),await updated.text()).toBe(true);
 const packagePath=path.join(project.project_dir,'exports/flows/controlled-source');
 const row={package_id:'controlled-source',name:'Controlled input package record',package_path:packagePath,integrity:'verified',scope_matches:true,approval_present:false,models:[],parity:{status:'not_run'},optimization_jobs:[]};
 const options={package_dir:packagePath,input_receipt:{source_dataset_path:workspace.dataset}};
 const cached={job_id:'cached',status:'failed',package_path:'',options:{...options,input_receipt:{source_dataset_path:path.join(workspace.root,'previous-source')}},error:'previous source run',result:null};
 const own={job_id:'owned',status:'running',package_path:'',options,error:null,result:null};
 let foreign=true,reviewRequests=0;const submissions:any[]=[];
 const answer=(route:any,value:unknown)=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(value)});
 await page.route('**/api/product-delivery/packages',r=>answer(r,{packages:[row],selected_package_id:null,scope:{project_id:project.id,source_dataset_path:workspace.dataset,task:'classification'}}));
 await page.route('**/api/product-delivery/packages/controlled-source/select',r=>answer(r,row));
 await page.route('**/api/export/runtime-capabilities',r=>answer(r,{torch_devices:['cpu'],openvino:{available:true,devices:['CPU']},native_sdk:{languages:[],transport:'controlled'}}));
 await page.route('**/api/dataset/images?**',r=>{const split=new URL(r.request().url()).searchParams.get('split');const input=workspace.images[split==='train'?0:1];return answer(r,{total:1,limit:128,offset:0,items:[{file_path:input.path,file_name:path.basename(input.path),width:32,height:32,split:split||'test'}]});});
 await page.route('**/api/export/flow/optimize',r=>{submissions.push(r.request().postDataJSON());return answer(r,own);});
 await page.route('**/api/export/flow/optimization-jobs/*',r=>answer(r,new URL(r.request().url()).pathname.endsWith('/cached')?cached:foreign?{...own,job_id:'foreign',status:'completed'}:{...own,status:'failed',error:'controlled conversion stopped'}));
 await page.route('**/api/export/flow/optimization-jobs/*/approval-prerequisites',r=>{reviewRequests++;return answer(r,{approval_revision_ids:{}});});
 await page.route('**/api/export/flow/optimization-jobs/*/heldout-results/*',r=>{reviewRequests++;return answer(r,null);});
 const key='runtime-optimization:'+JSON.stringify([project.project_dir,packagePath,workspace.dataset,'classification']);
 await page.addInitScript(key=>localStorage.setItem(key,'cached'),key);
 await page.goto(renderer.url);
 await page.getByRole('button',{name:'패키지·장치·진단',exact:true}).click();
 await page.getByRole('button',{name:'최적화로 이동',exact:true}).click();
 const panel=page.getByRole('region',{name:'Runtime 최적화와 양자화'});
 await expect(panel.getByRole('alert')).toContainText('패키지·원본 소스');
 await expect(panel.getByLabel('선택한 최적화 작업',{exact:true})).toHaveCount(0);
 expect(reviewRequests).toBe(0);
 await panel.getByLabel('정밀도',{exact:false}).selectOption('int8');
 await panel.getByRole('button',{name:'독립 후보 패키지 생성',exact:true}).click();
 await expect(panel.getByLabel('선택한 최적화 작업',{exact:true})).toContainText('owned');
 await expect(panel.getByRole('alert')).toContainText('ID');
 await expect(panel.getByLabel('선택한 최적화 작업',{exact:true})).not.toContainText('foreign');
 await expect(panel.getByRole('button',{name:'검토 후 새 승인 패키지 생성',exact:true})).toHaveCount(0);
 expect(reviewRequests).toBe(0);expect(submissions).toHaveLength(1);
 expect(submissions[0]).toMatchObject({package_dir:packagePath,source_dataset_path:workspace.dataset,precision:'int8',calibration_images:[workspace.images[0].path],validation_images:[workspace.images[1].path]});
 await panel.getByRole('alert').scrollIntoViewIfNeeded();await evidence.screenshot(page,'optimization-foreign-source-and-job-refusal');
 foreign=false;await expect(panel.getByRole('status')).toContainText('controlled conversion stopped');
 await expect(panel.getByRole('alert')).toHaveCount(0);
 expect(await page.evaluate(key=>localStorage.getItem(key),key)).toBe('owned');
 await panel.getByRole('status').scrollIntoViewIfNeeded();await evidence.screenshot(page,'optimization-owned-poll-recovery');
 evidence.note('optimization_binding',{actual_renderer:true,owned_project_backend:true,optimization_transport:'controlled responses; no model conversion or quality approval',cached_other_source_refused:true,foreign_poll_job_refused:true,foreign_review_requests:reviewRequests,matching_poll_resumed:true,distinct_calibration_validation_paths:true,actual_int8_execution:false,native_electron:false});
});

test('optimization lifecycle refuses missing input and failed submission, cancels exact job and reopens',async({page,renderer,workspace,evidence})=>{
 await installDesktopHostShim(page,renderer.port);
 const created=await page.request.post(renderer.origin+'/api/project/create',{data:{name:'Optimization lifecycle control',task:'classification'}});expect(created.ok(),await created.text()).toBe(true);
 const project=await created.json();
 expect((await page.request.put(renderer.origin+'/api/project/update',{data:{source_dataset_dir:workspace.dataset}})).ok()).toBe(true);
 const packagePath=path.join(project.project_dir,'exports/flows/controlled-lifecycle');
 const row={package_id:'controlled-lifecycle',name:'Controlled lifecycle input package',package_path:packagePath,integrity:'verified',scope_matches:true,approval_present:false,models:[],parity:{status:'not_run'},optimization_jobs:[]};
 const options={package_dir:packagePath,input_receipt:{source_dataset_path:workspace.dataset}};
 let empty=true,unavailable=true,submitFailure=true,foreignCancel=true,reviewRequests=0;
 let owned={job_id:'owned-lifecycle',status:'running',package_path:'',options,error:null,result:null};
 const submissions:any[]=[],cancels:string[]=[];
 const answer=(route:any,value:unknown,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(value)});
 await page.route('**/api/product-delivery/packages',r=>answer(r,{packages:[row],selected_package_id:null,scope:{project_id:project.id,source_dataset_path:workspace.dataset,task:'classification'}}));
 await page.route('**/api/product-delivery/packages/controlled-lifecycle/select',r=>answer(r,row));
 await page.route('**/api/export/runtime-capabilities',r=>answer(r,{torch_devices:['cpu'],openvino:{available:!unavailable,devices:unavailable?[]:['CPU'],error:unavailable?'controlled optional runtime absent':undefined},native_sdk:{languages:[],transport:'controlled'}}));
 await page.route('**/api/dataset/images?**',r=>{
  const split=new URL(r.request().url()).searchParams.get('split'),input=workspace.images[split==='train'?0:1];
  return answer(r,{total:empty?0:1,limit:128,offset:0,items:empty?[]:[{file_path:input.path,file_name:path.basename(input.path),width:32,height:32,split:split||'test'}]});
 });
 await page.route('**/api/export/flow/optimize',r=>{submissions.push(r.request().postDataJSON());return submitFailure?answer(r,{detail:'controlled pack input refused'},422):answer(r,owned);});
 await page.route('**/api/export/flow/optimization-jobs/*',r=>answer(r,owned));
 await page.route('**/api/export/flow/optimization-jobs/*/cancel',r=>{
  cancels.push(new URL(r.request().url()).pathname);
  if(foreignCancel)return answer(r,{...owned,job_id:'foreign-cancel',status:'cancelled'});
  owned={...owned,status:'cancelled'};return answer(r,owned);
 });
 await page.route('**/api/export/flow/optimization-jobs/*/approval-prerequisites',r=>{reviewRequests++;return answer(r,{approval_revision_ids:{}});});
 await page.route('**/api/export/flow/optimization-jobs/*/heldout-results/*',r=>{reviewRequests++;return answer(r,null);});
 const open=async()=>{
  await page.getByRole('button',{name:'패키지·장치·진단',exact:true}).click();
  await page.getByRole('button',{name:'최적화로 이동',exact:true}).click();
  return page.getByRole('region',{name:'Runtime 최적화와 양자화'});
 };
 await page.goto(renderer.url);let panel=await open();
 await expect(panel.getByRole('alert')).toContainText('controlled optional runtime absent');
 await expect(panel.getByRole('button',{name:'독립 후보 패키지 생성',exact:true})).toBeDisabled();
 await expect(panel.getByRole('group',{name:'변환 오차 검증 · test / val'}).getByText('명시된 split의 이미지가 없습니다.',{exact:true})).toBeVisible();
 expect(submissions).toHaveLength(0);await panel.scrollIntoViewIfNeeded();await evidence.screenshot(page,'optimization-empty-and-unavailable-refused');
 empty=false;unavailable=false;await page.reload();panel=await open();
 await panel.getByLabel('정밀도',{exact:false}).selectOption('int8');
 const submit=panel.getByRole('button',{name:'독립 후보 패키지 생성',exact:true});
 const calibration=panel.getByRole('group',{name:'보정 이미지 · train'}).getByRole('checkbox');
 const validation=panel.getByRole('group',{name:'변환 오차 검증 · test / val'}).getByRole('checkbox');
 await calibration.uncheck();await expect(submit).toBeDisabled();await calibration.check();
 await validation.uncheck();await expect(submit).toBeDisabled();await validation.check();
 await submit.click();await expect(panel.getByRole('alert')).toContainText('controlled pack input refused');
 await expect(panel.getByLabel('선택한 최적화 작업',{exact:true})).toHaveCount(0);
 await expect(submit).toBeEnabled();await expect(calibration).toBeChecked();await expect(validation).toBeChecked();
 await panel.getByRole('alert').scrollIntoViewIfNeeded();await evidence.screenshot(page,'optimization-submission-error-keeps-input');
 submitFailure=false;await submit.click();await expect(panel.getByRole('status')).toContainText('running');
 const cancel=panel.getByRole('button',{name:'변환 중단',exact:true});
 await cancel.click();await expect(panel.getByRole('alert')).toContainText('ID');
 await expect(panel.getByRole('status')).toContainText('running');
 await expect(panel.getByLabel('선택한 최적화 작업',{exact:true})).not.toContainText('foreign-cancel');
 foreignCancel=false;await cancel.click();await expect(panel.getByRole('status')).toContainText('cancelled');
 await expect(panel.getByRole('alert')).toHaveCount(0);
 await expect(cancel).toHaveCount(0);expect(cancels).toEqual(Array(2).fill('/api/export/flow/optimization-jobs/owned-lifecycle/cancel'));
 await page.reload();panel=await open();
 await expect(panel.getByLabel('선택한 최적화 작업',{exact:true})).toContainText('owned-lifecycle');
 await expect(panel.getByRole('status')).toContainText('cancelled');
 await expect(panel.getByRole('button',{name:'검토 후 새 승인 패키지 생성',exact:true})).toHaveCount(0);
 expect(reviewRequests).toBe(0);expect(submissions).toHaveLength(2);
 expect(submissions[1]).toMatchObject({package_dir:packagePath,source_dataset_path:workspace.dataset,precision:'int8',calibration_images:[workspace.images[0].path],validation_images:[workspace.images[1].path]});
 await panel.getByRole('status').scrollIntoViewIfNeeded();await evidence.screenshot(page,'optimization-exact-cancel-reopened');
 evidence.note('optimization_lifecycle',{actual_renderer:true,owned_project_backend:true,optimization_transport:'controlled HTTP; no model execution or actual worker cancellation',empty_and_unavailable_blocked:true,unselected_calibration_or_validation_blocked:true,failed_submission_kept_selection:true,foreign_cancel_refused:true,cancel_requested_job:'owned-lifecycle',matching_cancel_reopened:true,foreign_review_requests:reviewRequests,actual_conversion:false,native_electron:false,quality_accepted:false});
});
