import path from 'node:path';
import {test,expect} from './fixtures/test';
import {installDesktopHostShim} from './fixtures/desktop-host-shim';

test('optimization renderer refuses cached source and foreign poll responses before review',async({page,renderer,workspace,evidence})=>{
 await installDesktopHostShim(page,renderer.port);
 const created=await page.request.post(renderer.origin+'/api/project/create',{data:{name:'Optimization source binding control',task:'classification'}});expect(created.ok(),await created.text()).toBe(true);
 const project=await created.json();
 const updated=await page.request.put(renderer.origin+'/api/project/update',{data:{source_dataset_dir:workspace.dataset}});expect(updated.ok(),await updated.text()).toBe(true);
 const packagePath=path.join(project.project_dir,'exports/flows/controlled-source');
 const row={package_id:'controlled-source',name:'Controlled input package record',package_path:packagePath,integrity:'verified',scope_matches:true,approval_present:false,models:[],parity:{status:'not_run'},optimization_jobs:[]};
 const options={package_dir:packagePath,input_receipt:{source_dataset_path:workspace.dataset}};
 const cached={job_id:'cached',status:'failed',package_path:'',options:{...options,input_receipt:{source_dataset_path:path.join(workspace.root,'previous-source')}},error:'previous source run',result:null};
 const own={job_id:'owned',status:'running',package_path:'',options,error:null,result:null};
 let foreign=true,reviewRequests=0;const submissions:any[]=[];
 const answer=(route:any,value:unknown)=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(value)});
 await page.route('**/api/product-delivery/packages',r=>answer(r,{packages:[row],selected_package_id:null,scope:{project_id:project.id,source_dataset_path:workspace.dataset,task:'classification'}}));
 await page.route('**/api/product-delivery/packages/controlled-source/select',r=>answer(r,row));
 await page.route('**/api/export/runtime-capabilities',r=>answer(r,{torch_devices:['cpu'],openvino:{available:true,devices:['CPU']},native_sdk:{languages:[],transport:'controlled'}}));
 await page.route('**/api/dataset/images?**',r=>{const split=new URL(r.request().url()).searchParams.get('split');const input=workspace.images[split==='train'?0:1];return answer(r,{total:1,limit:128,offset:0,items:[{file_path:input.path,file_name:path.basename(input.path),width:32,height:32,split:split||'test'}]});});
 await page.route('**/api/export/flow/optimize',r=>{submissions.push(r.request().postDataJSON());return answer(r,own);});
 await page.route('**/api/export/flow/optimization-jobs/*',r=>answer(r,new URL(r.request().url()).pathname.endsWith('/cached')?cached:foreign?{...own,job_id:'foreign',status:'completed'}:{...own,status:'failed',error:'controlled conversion stopped'}));
 await page.route('**/api/export/flow/optimization-jobs/*/approval-prerequisites',r=>{reviewRequests++;return answer(r,{approval_revision_ids:{}});});
 await page.route('**/api/export/flow/optimization-jobs/*/heldout-results/*',r=>{reviewRequests++;return answer(r,null);});
 const key='runtime-optimization:'+JSON.stringify([project.project_dir,packagePath,workspace.dataset,'classification']);
 await page.addInitScript(key=>localStorage.setItem(key,'cached'),key);
 await page.goto(renderer.url);
 await page.getByRole('button',{name:'패키지·장치·진단',exact:true}).click();
 await page.getByRole('button',{name:'최적화로 이동',exact:true}).click();
 const panel=page.getByRole('region',{name:'Runtime 최적화와 양자화'});
 await expect(panel.getByRole('alert')).toContainText('패키지·원본 소스');
 await expect(panel.getByLabel('선택한 최적화 작업',{exact:true})).toHaveCount(0);
 expect(reviewRequests).toBe(0);
 await panel.getByLabel('정밀도',{exact:false}).selectOption('int8');
 await panel.getByRole('button',{name:'독립 후보 패키지 생성',exact:true}).click();
 await expect(panel.getByLabel('선택한 최적화 작업',{exact:true})).toContainText('owned');
 await expect(panel.getByRole('alert')).toContainText('ID');
 await expect(panel.getByLabel('선택한 최적화 작업',{exact:true})).not.toContainText('foreign');
 await expect(panel.getByRole('button',{name:'검토 후 새 승인 패키지 생성',exact:true})).toHaveCount(0);
 expect(reviewRequests).toBe(0);expect(submissions).toHaveLength(1);
 expect(submissions[0]).toMatchObject({package_dir:packagePath,source_dataset_path:workspace.dataset,precision:'int8',calibration_images:[workspace.images[0].path],validation_images:[workspace.images[1].path]});
 await panel.getByRole('alert').scrollIntoViewIfNeeded();await evidence.screenshot(page,'optimization-foreign-source-and-job-refusal');
 foreign=false;await expect(panel.getByRole('status')).toContainText('controlled conversion stopped');
 expect(await page.evaluate(key=>localStorage.getItem(key),key)).toBe('owned');
 await panel.getByRole('status').scrollIntoViewIfNeeded();await evidence.screenshot(page,'optimization-owned-poll-recovery');
 evidence.note('optimization_binding',{actual_renderer:true,owned_project_backend:true,optimization_transport:'controlled responses; no model conversion or quality approval',cached_other_source_refused:true,foreign_poll_job_refused:true,foreign_review_requests:reviewRequests,matching_poll_resumed:true,distinct_calibration_validation_paths:true,actual_int8_execution:false,native_electron:false});
});
