import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {execFileSync} from 'node:child_process';
import type {Page} from '@playwright/test';import {test,expect,type Workspace,type Evidence} from './fixtures/test';
import {confirmFlowSave} from './fixtures/flowChange';
const harness=require('./fixtures/harness.cjs');type Api=(route:string,body?:any)=>Promise<any>;test.use({actionTimeout:10_000});
async function exercise(page:Page,workspace:Workspace,evidence:Evidence,api:Api,url?:string){
 const failures:any[]=[];page.on('requestfailed',request=>{failures.push({url:request.url(),failure:request.failure()});evidence.note('request_failures',failures);});
 const fixtureScript=path.join(harness.REPO_ROOT,'scripts/e2e/fixtures/gan_adoption_data.py');
 const fixture=JSON.parse(execFileSync(harness.resolvePython(),[fixtureScript,workspace.root],{encoding:'utf8',timeout:15_000}));
 await api('/api/project/create',{name:'Core model explicit target trials',task:'classification'});await api('/api/project/update',{source_dataset_dir:fixture.source});let project=await api('/api/project/current');await api('/api/dataset/import',{folder_path:fixture.source,task:'classification'});
 const split=JSON.parse(execFileSync(harness.resolvePython(),[fixtureScript,workspace.root,JSON.stringify(project)],{encoding:'utf8',timeout:15_000}));
 if(url)await page.goto(url);else await page.reload();await expect(page.getByTitle('프로젝트 관리',{exact:true})).toContainText(project.name);
 const stage=async(index:number)=>page.getByRole('navigation',{name:'Workflow Stages'}).getByRole('button').nth(index).click();await stage(2);
 const family=async(name:string)=>page.getByRole('region',{name:'모델 학습 허브'}).getByRole('button',{name:new RegExp('^'+name)}).click();
 async function trainClassifier(){
  await family('이미지 분류');await page.getByRole('combobox',{name:'학습 모델 구조',exact:true}).selectOption('efficientnet_b0');await page.getByLabel('수동 학습 횟수',{exact:true}).fill('1');await page.getByLabel('수동 학습 입력 크기',{exact:true}).fill('64');
  const device=page.getByLabel('다음 학습 로컬 장치',{exact:true});if(!await device.isVisible())await page.locator('summary').filter({hasText:'다음 학습 배치·로컬 장치 설정'}).click();await page.getByLabel('다음 학습 배치 크기',{exact:true}).fill('2');await device.selectOption('cpu');
  const budget=page.getByLabel('학습 시간 제한 (분)',{exact:true});if(!await budget.isVisible())await page.locator('summary').filter({hasText:'학습 실행 예산·대기열'}).click();await budget.fill('2');
  const waiting=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/training/start'&&r.request().method()==='POST');await page.getByRole('button',{name:'선택 설정으로 학습 시작',exact:true}).click();const response=await waiting;expect(response.ok(),await response.text()).toBe(true);const posted=response.request().postDataJSON(),accepted=await response.json();expect(posted).toMatchObject({task:'classification',device:'cpu',config_overrides:{backbone:'efficientnet_b0',epochs:1,image_size:64,batch_size:2}});
  let terminal:any;await expect.poll(async()=>{terminal=await api('/api/training/status?job_id='+accepted.job_id);if(['failed','cancelled','aborted'].includes(terminal.status))throw Error(JSON.stringify(terminal));return terminal.status;},{timeout:125_000}).toBe('completed');await expect(page.getByRole('region',{name:'학습 로그'})).toContainText('완료',{timeout:20_000});
  const metadata=JSON.parse(fs.readFileSync(path.join(project.models_dir,accepted.job_id,'model_meta.json'),'utf8'));return {job_id:accepted.job_id,posted,terminal,metadata};
 }
 const trained=await trainClassifier();await stage(4);await page.getByRole('list',{name:'목적 레시피'}).getByRole('button',{name:/^고정 ROI 검사/}).click();
 const recipe=page.getByRole('dialog',{name:'레시피 미리보기·모델 매핑'});await recipe.getByLabel('검사 모델 레시피 모델',{exact:true}).selectOption(trained.job_id);await recipe.getByLabel('검사 모델 클래스 적용 범위').selectOption('all');await recipe.getByRole('button',{name:'매핑 확인·새 초안으로 채택'}).click();
 await page.getByRole('button',{name:'플로우 저장',exact:true}).click();await confirmFlowSave(page,'Owned trained classifier preflight target qualification');const version=await page.getByLabel('저장 버전',{exact:true}).inputValue();expect(version).not.toBe('');await page.getByRole('tab',{name:'배포',exact:true}).click();
 const panel=page.getByRole('region',{name:'배포 전 의존성 점검'});let waiting=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/export/flow/preflight'&&r.request().method()==='POST');await panel.getByRole('button',{name:'점검 실행',exact:true}).click();let response=await waiting;expect(response.ok(),await response.text()).toBe(true);const local=await response.json();expect(local.target_identity).toEqual({kind:'this_computer',device:'cpu'});expect(local.recipe_release.version_id).toBe(version);expect(local.requirements.find((r:any)=>r.kind==='model')).toMatchObject({state:'ready',artifact_ref:'classification:'+trained.job_id});await expect(panel.getByRole('status')).toBeVisible();await evidence.screenshot(page,'trained-classifier-local-preflight');
 await page.reload();await stage(4);await page.getByRole('tab',{name:'배포',exact:true}).click();await expect(panel).toContainText(local.report_id.slice(0,8));
 const profile={id:'unreachable-preflight-loopback',name:'Unavailable owned preflight target',ssh_target:'127.0.0.1',ssh_port:1,remote_root:path.join(workspace.root,'unreachable-preflight'),runtime_kind:'python',runtime_value:'python3'};await api('/api/compute/profiles',profile);await page.reload();await stage(4);await page.getByRole('tab',{name:'배포',exact:true}).click();await page.getByRole('combobox').filter({has:page.locator('option[value="unreachable-preflight-loopback"]')}).first().selectOption(profile.id);await expect(panel.getByLabel('점검 대상')).toHaveValue('selected-cpu');await expect(panel.getByRole('status')).toHaveCount(0);
 const posts:string[]=[];const observe=(req:any)=>{if(req.method()==='POST')posts.push(new URL(req.url()).pathname);};page.on('request',observe);waiting=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/export/flow/preflight'&&r.request().method()==='POST');await panel.getByRole('button',{name:'점검 실행',exact:true}).click();response=await waiting;expect(response.status()).toBe(503);expect(response.request().postDataJSON()).toMatchObject({version_id:version,recipe_task:'classification',target:{kind:'selected_compute',compute_profile_id:profile.id,device:'cpu'}});await expect(panel.getByRole('alert')).toContainText('no local fallback');page.off('request',observe);expect(posts.filter(route=>route.startsWith('/api/export/flow/'))).toEqual(['/api/export/flow/preflight']);await evidence.screenshot(page,'selected-preflight-failure-no-host-fallback');
 for(const row of fixture.files)expect(crypto.createHash('sha256').update(fs.readFileSync(row.path)).digest('hex')).toBe(row.sha256);
 evidence.note('selected_preflight_qualification',{project,fixture,split,trained,version,local,failed_status:response.status(),failed_body:await response.json(),posts,actual_gui_cpu_training:true,actual_backend_preflight:true,automatic_target:true,reopen:true,source_unchanged:true,selected_success_in_this_app_case:false,physical_gpu_verified:false});
}

test('actual trained classifier preflight reopens and refuses unavailable selected target',{tag:'@owned-model'},async({page,request,renderer,workspace,evidence})=>{test.setTimeout(300_000);const api:Api=async(route,body)=>{const r=body===undefined?await request.get(renderer.origin+route):route.endsWith('/update')?await request.put(renderer.origin+route,{data:body}):await request.post(renderer.origin+route,{data:body});expect(r.ok(),await r.text()).toBe(true);return r.json();};await exercise(page,workspace,evidence,api,renderer.url);});
test('native saved flow preflight uses selected target and refuses fallback',{tag:['@electron','@owned-model']},async({electronSession,workspace,evidence})=>{test.setTimeout(300_000);const {window}=electronSession;const backend=await electronSession.waitForBackend();const api:Api=(route,body)=>window.evaluate(async({port,route,body})=>{const r=await fetch(`http://127.0.0.1:${port}${route}`,{...(body===undefined?{}:{method:route.endsWith('/update')?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})});if(!r.ok)throw Error(`Owned API ${r.status}: ${await r.text()}`);return r.json();},{port:backend.port,route,body});await exercise(window,workspace,evidence,api);});
