import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {execFileSync} from 'node:child_process';
import type {Page} from '@playwright/test';import {test,expect,type Workspace,type Evidence} from './fixtures/test';
const harness=require('./fixtures/harness.cjs');type Api=(route:string,body?:any)=>Promise<any>;type Download=(action:()=>Promise<unknown>,label:string)=>Promise<string>;test.use({actionTimeout:10_000});
async function exercise(page:Page,workspace:Workspace,evidence:Evidence,api:Api,download:Download,url?:string){
 await api('/api/project/create',{name:'Owned support privacy qualification',task:'classification'});const project=await api('/api/project/current');
 const fixture=JSON.parse(execFileSync(harness.resolvePython(),[path.join(harness.REPO_ROOT,'scripts/e2e/fixtures/support_bundle_error.py'),workspace.root,JSON.stringify(project)],{encoding:'utf8',timeout:15_000}));
 await api('/api/project/update',{source_dataset_dir:fixture.source});if(url)await page.goto(url);else await page.reload();
 const enter=async()=>{await page.getByRole('button',{name:'패키지·장치·진단',exact:true}).click();await page.getByRole('navigation',{name:'배포 운영 화면'}).getByRole('button',{name:'설치·진단',exact:true}).click();};await enter();
 const panel=page.getByRole('group',{name:'문제 보고 자료',exact:true});const names=['버전·의존성','패키지','장치 실행','검사·오류'];for(const name of names)await panel.getByRole('checkbox',{name,exact:true}).uncheck();await expect(panel.getByRole('button',{name:'진단 자료 저장',exact:true})).toBeDisabled();
 const receipts:any[]=[];for(const [name,section,key] of [['검사·오류','operator_errors','operator_results'],['버전·의존성','installation','installation']]){
  for(const other of names)await panel.getByRole('checkbox',{name:other,exact:true}).uncheck();await panel.getByRole('checkbox',{name,exact:true}).check();
  const response=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/product-delivery/diagnostics'&&r.request().method()==='POST');const downloaded=await download(()=>panel.getByRole('button',{name:'진단 자료 저장',exact:true}).click(),section);const wire=await response;expect(wire.ok(),await wire.text()).toBe(true);expect(wire.request().postDataJSON()).toEqual({sections:[section]});const accepted=await wire.json();
  expect(accepted.redacted).toBe(true);expect(accepted.includes_source_images).toBe(false);const file=JSON.parse(fs.readFileSync(downloaded,'utf8')),persisted=JSON.parse(fs.readFileSync(path.join(project.project_dir,'delivery','diagnostics.json'),'utf8'));expect(file).toEqual(accepted.bundle);expect(persisted).toEqual(file);expect(Object.keys(file).sort()).toEqual(['schema_version','created_at','project_id','sections',key].sort());expect(file.sections).toEqual([section]);
  const text=JSON.stringify(file);for(const forbidden of fixture.forbidden)expect(text).not.toContain(forbidden);expect(text).not.toContain(fixture.image);expect(text).not.toContain(fixture.image_sha256);if(section==='operator_errors'){expect(file.operator_results).toHaveLength(1);expect(file.operator_results[0]).toMatchObject({state:'failed',model_verdict:null});expect(file.operator_results[0].error).toContain('[REDACTED]');expect(file.operator_results[0].error).toContain('[URL]');}
  await expect(page.getByText('비식별 진단 JSON 저장 요청 완료',{exact:true})).toBeVisible();evidence.addFile(downloaded);receipts.push({section,downloaded,sha256:crypto.createHash('sha256').update(fs.readFileSync(downloaded)).digest('hex'),bundle:file});
 }
 await evidence.screenshot(page,'actual-selected-support-bundle-download');await page.reload();await enter();await expect(page.getByText(/프로젝트 schema/)).toBeVisible();expect(crypto.createHash('sha256').update(fs.readFileSync(fixture.image)).digest('hex')).toBe(fixture.image_sha256);evidence.addFile(fixture.image);evidence.addFile(path.join(project.project_dir,'delivery','diagnostics.json'));
 evidence.note('support_bundle_qualification',{project,fixture,receipts,actual_app_button_download:true,actual_persisted_response_parity:true,actual_section_selection:true,actual_empty_selection_refusal:true,actual_redaction:true,actual_reopen:true,no_original_mutation:true,external_upload:false,real_inspection:false,release_approval:false});
}
test('actual selected support downloads redact controlled failure and match persisted response',async({page,request,renderer,workspace,evidence})=>{const api:Api=async(route,body)=>{const r=body===undefined?await request.get(renderer.origin+route):route.endsWith('/update')?await request.put(renderer.origin+route,{data:body}):await request.post(renderer.origin+route,{data:body});expect(r.ok(),await r.text()).toBe(true);return r.json();};const download:Download=async(action,label)=>{const event=page.waitForEvent('download');await action();const item=await event;const target=path.join(workspace.logs,label+'.json');await item.saveAs(target);expect(await item.failure()).toBeNull();return target;};await exercise(page,workspace,evidence,api,download,renderer.url);});
test('native support button downloads exact selected sanitized persisted bundles',{tag:'@electron'},async({electronSession,workspace,evidence})=>{const {window,app}=electronSession;const backend=await electronSession.waitForBackend();const api:Api=(route,body)=>window.evaluate(async({port,route,body})=>{const r=await fetch(`http://127.0.0.1:${port}${route}`,{...(body===undefined?{}:{method:route.endsWith('/update')?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})});if(!r.ok)throw Error(`Owned API ${r.status}: ${await r.text()}`);return r.json();},{port:backend.port,route,body});const download:Download=async(action,label)=>{const target=path.join(workspace.logs,label+'.json');await app.evaluate(({session},file)=>{(globalThis as any).__supportDownload=null;session.defaultSession.once('will-download',(_event,item)=>{item.setSavePath(file);item.once('done',(_ev,state)=>{(globalThis as any).__supportDownload=state;});});},target);await action();await expect.poll(()=>app.evaluate(()=>(globalThis as any).__supportDownload)).toBe('completed');return target;};await exercise(window,workspace,evidence,api,download);});
