import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import type {Page} from '@playwright/test';
import {test,expect,type Workspace,type Evidence} from './fixtures/test';import {installDesktopHostShim} from './fixtures/desktop-host-shim';import {png} from './qa/appFlow';
test.use({actionTimeout:10_000});
type Api=(route:string,body?:unknown,method?:string)=>Promise<any>;const sha=(data:Buffer)=>crypto.createHash('sha256').update(data).digest('hex');
async function exercise(page:Page,w:Workspace,e:Evidence,api:Api,native:boolean,url?:string){
 const source=path.join(w.root,'team-source');fs.mkdirSync(source);const image=path.join(source,'part.png');fs.writeFileSync(image,png(256,3,(x,y)=>[x,y,100]));const original=sha(fs.readFileSync(image));
 const project=await api('/api/project/create',{name:'Team reconnect fixture',task:'segmentation'});await api('/api/project/update',{source_dataset_dir:source},'PUT');await api('/api/dataset/import',{folder_path:source,task:'segmentation'});
 await api('/api/team-data/books',{expected_version:0,actor:'fixture-owner',title:'Controlled book v1',categories:[{id:0,name:'OK',color:'#10b981'},{id:2,name:'Scratch',color:'#f59e0b',definition:'Controlled scratch'}]});
 await api('/api/team-data/settings',{expected_revision:1,actor:'fixture-owner',changes:{review_enabled:true,required_reviews:2,prevent_self_review:true,approved_only_training:true}},'PUT');
 const query='/api/annotations/part?file_path='+encodeURIComponent(image),saved=await api('/api/annotations/save',{image_id:'part',image_path:image,image_width:256,image_height:256,actor:'labeler-a',annotations:[{id:'initial',type:'bbox',label:'Scratch',category_id:2,bbox:[2,3,20,21]}]});
 const uuid=saved.metadata.image_uuid,route='/api/team-data/images/'+uuid,latest=async()=>(await api(query)).metadata;
 if(url)await page.goto(url);else await page.reload();await page.getByRole('navigation',{name:'Workflow Stages'}).getByRole('button').nth(1).click();await page.getByRole('button',{name:'집중 편집',exact:true}).click();
 const openTeam=async()=>{await page.getByRole('button',{name:'팀 작업 · 라벨 기준·검수',exact:true}).click();return page.getByRole('dialog',{name:'팀 데이터 작업',exact:true});};
 let team=await openTeam();await team.getByLabel('팀 작업자 이름',{exact:true}).fill('labeler-a');await team.getByRole('tab',{name:'검수 정책',exact:true}).click();await team.getByLabel('공동 편집 잠금 사용',{exact:true}).click();await expect.poll(async()=>(await api('/api/team-data')).settings.editing_enabled).toBe(true);await team.getByRole('tab',{name:'작업·검수',exact:true}).click();
 await team.getByLabel('이미지 담당자',{exact:true}).fill('labeler-b');await team.getByLabel('작업 우선순위',{exact:true}).fill('90');await team.getByRole('button',{name:'작업 배정',exact:true}).click();await expect.poll(async()=>(await latest()).team.assignment.assignee).toBe('labeler-b');await team.getByRole('button',{name:'팀 데이터 작업 닫기',exact:true}).click();
 const deniedReply=page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname===route+'/lease/acquire');await page.getByRole('button',{name:'편집 시작',exact:true}).click();expect((await deniedReply).status()).toBe(422);await expect(page.getByRole('alert')).toContainText('다른 담당자');team=await openTeam();await team.getByLabel('이미지 담당자',{exact:true}).fill('labeler-a');await team.getByRole('button',{name:'작업 배정',exact:true}).click();await expect.poll(async()=>(await latest()).team.assignment.assignee).toBe('labeler-a');await team.getByRole('button',{name:'팀 데이터 작업 닫기',exact:true}).click();
 const leaseReply=page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname===route+'/lease/acquire');await page.getByRole('button',{name:'편집 시작',exact:true}).click();const leased=await leaseReply;expect(leased.status()).toBe(200);const lease=await leased.json();e.redact(lease.lease_token);expect(lease.image.team.edit_lease.owner).toBe('labeler-a');
 await expect.poll(async()=>Number((await page.getByTestId('canvas-hud').innerText()).match(/scale\s*([\d.]+)\s*%/)?.[1]||0)).toBeGreaterThan(100);await page.getByTitle('100% Zoom (1:1)',{exact:true}).click();await page.getByRole('button',{name:/^Scratch(?: \d+)?$/}).click();await page.getByTitle('바운딩 박스 (BBox - 2)',{exact:true}).click();
 const box=(await page.locator('[data-canvas-container]').boundingBox())!;const pt=(x:number,y:number)=>({x:box.x+(box.width-256)/2+x,y:box.y+(box.height-256)/2+y});const a=pt(40,40),b=pt(80,80);await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(b.x,b.y,{steps:6});await page.mouse.up();
 await expect(page.getByRole('region',{name:'라벨 연결 복구'})).toContainText('이 컴퓨터에 초안 보존됨');
 const drafts=()=>page.evaluate(()=>Object.entries(localStorage).filter(([key])=>key.startsWith('modu-annotation-draft:v1:')).map(([,raw])=>JSON.parse(raw)));
 const local=await drafts();expect(local).toHaveLength(1);expect(local[0].annotations).toHaveLength(2);expect(local[0].annotations[1].bbox).toEqual([40,40,80,80]);e.note('local_draft_before_reconnect',local[0]);
 const blocked='**/api/annotations/save';await page.route(blocked,r=>r.abort('failed'));await page.getByTestId('annotation-save-button').click();await expect(page.getByText(/^Failed:/)).toBeVisible();await page.unroute(blocked);expect((await api(query)).annotations).toHaveLength(1);
 // A separate real API client releases its own lease and another fixture actor saves newer labels.
 await api(route+'/lease/release',{expected_revision:(await latest()).revision,actor:'labeler-a',lease_token:lease.lease_token});await api(route+'/assign',{expected_revision:(await latest()).revision,actor:'fixture-owner',assignee:'labeler-b',priority:90});const foreignLease=await api(route+'/lease/acquire',{expected_revision:(await latest()).revision,actor:'labeler-b'});e.redact(foreignLease.lease_token);
 const other=await api('/api/annotations/save',{image_id:'part',image_path:image,image_width:256,image_height:256,actor:'labeler-b',lease_token:foreignLease.lease_token,expected_revision:foreignLease.image.revision,annotations:[{id:'foreign',type:'bbox',label:'Scratch',category_id:2,bbox:[100,100,130,140]}]});await api(route+'/lease/release',{expected_revision:other.metadata.revision,actor:'labeler-b',lease_token:foreignLease.lease_token});
 await api(route+'/assign',{expected_revision:(await latest()).revision,actor:'fixture-owner',assignee:'labeler-a',priority:90});const otherLabels=(await api(query)).annotations;const stale=page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname==='/api/annotations/save');await page.getByTestId('annotation-save-button').click();expect((await stale).status()).toBeGreaterThanOrEqual(400);expect((await api(query)).annotations).toEqual(otherLabels);
 await page.reload();await expect(page.getByRole('button',{name:'저장 전 초안 비교·복구',exact:true})).toBeVisible();expect((await drafts())[0].annotations).toEqual(local[0].annotations);
 await page.getByRole('button',{name:'저장 전 초안 비교·복구',exact:true}).click();let compare=page.getByRole('dialog',{name:'서버 라벨과 로컬 초안 비교',exact:true});await expect(compare).toContainText('충돌: 서버 변경 있음');const apply=()=>compare.getByRole('button',{name:'비교한 초안을 명시적으로 적용',exact:true});await expect(apply()).toBeDisabled();await compare.getByRole('checkbox').check();
 // A metadata revision moves after comparison; the apply readback must refuse it.
 const moved=await latest();await api('/api/dataset/metadata/'+uuid,{expected_revision:moved.revision,actor:'fixture-reviewer',changes:{tags:['changed-after-comparison']}},'PATCH');await apply().click();await expect(compare.getByRole('alert')).toContainText('비교 이후 바뀌었습니다');expect((await api(query)).annotations[0].id).toBe('foreign');await compare.getByRole('button',{name:'서버 라벨과 로컬 초안 비교 닫기',exact:true}).click();
 await page.getByRole('button',{name:'저장 전 초안 비교·복구',exact:true}).click();compare=page.getByRole('dialog',{name:'서버 라벨과 로컬 초안 비교',exact:true});await expect(compare).toContainText('충돌: 서버 변경 있음');await e.screenshot(page,`${native?'native':'browser'}-draft-conflict-comparison`);await compare.getByRole('checkbox').check();await apply().click();await expect(compare).toHaveCount(0);expect((await api(query)).annotations[0].id).toBe('foreign');
 await page.getByRole('button',{name:'편집 시작',exact:true}).click();const accepted=page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname==='/api/annotations/save');await page.getByTestId('annotation-save-button').click();expect((await accepted).status()).toBe(200);const restored=await api(query);const canonical=(rows:any[])=>rows.map(row=>Object.fromEntries(Object.entries(row).filter(([,v])=>v!==null&&v!==undefined)));expect(canonical(restored.annotations)).toEqual(canonical(local[0].annotations));await expect.poll(drafts).toHaveLength(0);await page.getByRole('button',{name:'편집 종료',exact:true}).click();
 team=await openTeam();await team.getByLabel('팀 작업자 이름',{exact:true}).fill('reviewer-b');await team.getByRole('button',{name:'승인 표 제출',exact:true}).click();await expect.poll(async()=>(await latest()).team.reviews.length).toBe(1);await team.getByLabel('팀 작업자 이름',{exact:true}).fill('reviewer-c');await team.getByLabel('검수 이유',{exact:true}).fill('Controlled disagreement');await team.getByRole('button',{name:'반려 표 제출',exact:true}).click();await expect.poll(async()=>(await latest()).team.review_status).toBe('disputed');const disputed=await latest();expect(disputed.team.reviews.map((r:any)=>r.actor)).toEqual(['reviewer-b','reviewer-c']);
 await team.getByLabel('팀 작업자 이름',{exact:true}).fill('reviewer-d');await team.getByLabel('검수 이유',{exact:true}).fill('Controlled adjudication after comparison');await team.getByRole('button',{name:'최종 승인 조정',exact:true}).click();await expect.poll(async()=>(await latest()).team.review_status).toBe('approved');const approved=await latest();await e.screenshot(page,`${native?'native':'browser'}-two-reviewers-adjudicated`);
 await team.getByRole('tab',{name:'라벨 기준서',exact:true}).click();await team.getByLabel('라벨 기준서 제목',{exact:true}).fill('Controlled book v2');await team.getByLabel('클래스 정의',{exact:true}).fill('Updated controlled definition');await team.getByRole('button',{name:'새 기준 버전 발행',exact:true}).click();await expect.poll(async()=>(await api('/api/team-data')).book.version).toBe(2);await team.getByRole('tab',{name:'작업·검수',exact:true}).click();await team.getByRole('button',{name:'새로고침',exact:true}).click();await expect.poll(async()=>(await latest()).team.reviews.length).toBe(0);const invalidated=await latest();expect(invalidated.workflow_state).toBe('needs_review');
 await team.getByRole('button',{name:'팀 데이터 작업 닫기',exact:true}).click();await page.reload();team=await openTeam();await expect(team.getByLabel('이미지 담당자',{exact:true})).toHaveValue('labeler-a');await expect(team.getByLabel('작업 우선순위',{exact:true})).toHaveValue('90');await team.getByLabel('작업 목록 담당 필터',{exact:true}).fill('labeler-a');await expect(team.getByRole('region',{name:'팀 작업 목록'})).toContainText('part.png');await e.screenshot(page,`${native?'native':'browser'}-team-queue-reopened`);
 expect(sha(fs.readFileSync(image))).toBe(original);const workspace=await api('/api/team-data');expect(workspace.book_history[0].title).toBe('Controlled book v1');e.note('team_edit_closure',{project_id:project.id,image_path:image,image_sha256:original,disputed,approved,invalidated,workspace,annotation:await api(query),actual_ui_and_backend:true,controlled_reviewers:true,quality_approved:false,local_draft_removed_after_actual_save:true});
}
test('team edit reconnect compares drafts and preserves two-person review and assignment',async({page,renderer,workspace,evidence})=>{await installDesktopHostShim(page,renderer.port);const api:Api=async(route,body,method)=>{const r=await page.request.fetch(renderer.origin+route,{method:method||(body?'POST':'GET'),data:body});expect(r.ok(),await r.text()).toBe(true);return r.json();};await exercise(page,workspace,evidence,api,false,renderer.url);});
test('native team edit reconnect preserves conflict decisions review policy and queue',{tag:'@electron'},async({electronSession,workspace,evidence})=>{const page=electronSession.window,status=await electronSession.waitForBackend();const api:Api=(route,body,method)=>page.evaluate(async({port,route,body,method})=>{const r=await fetch(`http://127.0.0.1:${port}${route}`,{method:method||(body?'POST':'GET'),headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});if(!r.ok)throw Error(`Owned team fixture HTTP ${r.status}`);return r.json();},{port:status.port,route,body,method});await exercise(page,workspace,evidence,api,true);});
