import {modelRecipeResponse} from './fixtures/modelRecipe';
import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {execFileSync} from 'node:child_process';
import type {Page} from '@playwright/test';import {test,expect,type Workspace,type Evidence} from './fixtures/test';
const harness=require('./fixtures/harness.cjs');type Api=(route:string,body?:any)=>Promise<any>;test.use({actionTimeout:10_000});
async function exercise(page:Page,workspace:Workspace,evidence:Evidence,api:Api,url?:string){
 const fixture=JSON.parse(execFileSync(harness.resolvePython(),[path.join(harness.REPO_ROOT,'scripts/e2e/fixtures/yolo_obb_data.py'),workspace.root],{encoding:'utf8',timeout:15_000}));
 await api('/api/project/create',{name:'Actual oriented geometry and fitted ROI qualification',task:'detection'});await api('/api/project/update',{source_dataset_dir:fixture.source});const project=await api('/api/project/current');
 if(url)await page.goto(url);else await page.reload();await expect(page.getByTitle('프로젝트 관리',{exact:true})).toContainText(project.name);
 const stage=(i:number)=>page.getByRole('navigation',{name:'Workflow Stages'}).getByRole('button').nth(i).click();const enter=async()=>{await stage(2);await page.getByRole('region',{name:'모델 학습 허브'}).getByRole('button',{name:/^회전 객체 검출/}).click();};await enter();
 await expect(page.getByLabel('회전 검출 구현',{exact:true})).toHaveValue('fixed_slot_cnn');await page.getByLabel('회전 검출 구현',{exact:true}).selectOption('ultralytics_yolo_obb');
 await page.getByLabel('로컬 OBB 모델 .pt 절대 경로',{exact:true}).fill(fixture.weights);await expect(page.getByRole('button',{name:'후보 학습',exact:true})).toBeDisabled();await page.getByLabel('선택한 로컬 모델의 출처와 네이티브 로딩을 신뢰합니다.',{exact:true}).check();
 await page.getByLabel(/정답 표 · 이미지 상대 경로/).fill(fixture.tsv);let waiting=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/rotated-detection/manifest'&&r.request().method()==='POST');await page.getByRole('button',{name:'정답·이미지 해시 저장',exact:true}).click();let response=await waiting;expect(response.ok(),await response.text()).toBe(true);const prepared=await response.json();expect(prepared.provenance.source_image_count).toBe(6);expect(prepared.samples.filter((r:any)=>!r.objects.length)).toHaveLength(3);expect(prepared.samples.find((r:any)=>r.split==='train'&&r.objects.length).objects).toHaveLength(35);
 await page.getByLabel('학습 epoch',{exact:true}).fill('2');await page.locator('summary').filter({hasText:'학습 시간 제한'}).click();await page.getByLabel('학습 시간 제한 (분)',{exact:true}).fill('2');
 waiting=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/rotated-detection/train'&&r.request().method()==='POST');await page.getByRole('button',{name:'후보 학습',exact:true}).click();response=await waiting;expect(response.ok(),await response.text()).toBe(true);const posted=response.request().postDataJSON(),accepted=await response.json(),jobId=accepted.job_id;expect(posted).toMatchObject({epochs:2,device:'cpu',recipe:{adapter:'ultralytics_yolo_obb',model_path:fixture.weights,trust_native_weights:true}});
 let terminal:any;await expect.poll(async()=>{terminal=await api('/api/rotated-detection/jobs/'+jobId);if(['failed','aborted','stopped'].includes(terminal.status))throw Error(JSON.stringify(terminal));return terminal.status;},{timeout:130_000}).toBe('completed');expect(terminal.epochs_completed).toBe(2);await expect(page.getByLabel('완료 후보 모델',{exact:true})).toHaveValue(jobId,{timeout:20_000});
 const metadata=JSON.parse(fs.readFileSync(path.join(project.models_dir,'rotated_detection',jobId,'model_meta.json'),'utf8'));expect(metadata.initial_model_sha256).toBe(fixture.weights_sha256);expect(metadata.epochs_completed).toBe(2);expect(metadata.license.distribution_status).toBe('pending_review');expect(metadata.direction_enabled).toBe(false);
 waiting=modelRecipeResponse(page,'rotated_detection','evaluate',jobId);await page.getByRole('button',{name:'시험 분할 평가',exact:true}).click();response=await waiting;expect(response.ok(),await response.text()).toBe(true);const evaluated=await response.json();expect(evaluated.execution.evidence_sha256).toMatch(/^[a-f0-9]{64}$/);expect(evaluated.sample_count).toBe(2);expect(evaluated.ground_truth_objects).toBe(2);expect(evaluated.direction_supported).toBe(false);expect(Number.isFinite(evaluated.mAP_50)).toBe(true);await expect(page.getByText(/회전 box mAP@50/)).toBeVisible();await evidence.screenshot(page,'actual-obb-fixed-heldout-metrics');
 const source=fixture.files.find((r:any)=>r.split==='test'&&!r.background).path;await page.getByLabel('한 장 시험 이미지 경로',{exact:true}).fill(source);waiting=modelRecipeResponse(page,'rotated_detection','predict',jobId);await page.getByRole('button',{name:'회전 박스 예측',exact:true}).click();response=await waiting;expect(response.ok(),await response.text()).toBe(true);const predicted=await response.json();expect(predicted.execution.evidence_sha256).toMatch(/^[a-f0-9]{64}$/);expect(predicted.angle_convention).toBe('clockwise_degrees_axial_180');await expect(page.getByAltText('원본 이미지 위에 예측된 회전 박스를 그린 미리보기',{exact:true})).toBeVisible();
 await page.reload();await enter();await expect(page.getByLabel('완료 후보 모델',{exact:true})).toHaveValue(jobId);await expect(page.getByLabel('프로젝트에 저장된 회전 박스 정답',{exact:true})).toHaveValue(prepared.dataset_path);await page.getByRole('button',{name:'검사 플로우·배포 패키지',exact:true}).click();await expect(page.getByRole('region',{name:'선택 모델 플로우 연결'})).toBeVisible();
 await page.getByRole('button',{name:'회전 ROI 정렬 검사 회전 검출 다각형 → 맞춤 정렬 → 검사 모델',exact:true}).click();const dialog=page.getByRole('dialog',{name:'레시피 미리보기·모델 매핑',exact:true});await expect(dialog).toBeVisible();await dialog.getByLabel('회전 영역 검출 레시피 모델',{exact:true}).selectOption(jobId);await dialog.getByLabel('회전 영역 검출 클래스 적용 범위',{exact:true}).selectOption('all');await dialog.getByLabel('검사 모델 레시피 작업',{exact:true}).selectOption('rotated_detection');await dialog.getByLabel('검사 모델 레시피 모델',{exact:true}).selectOption(jobId);await dialog.getByLabel('검사 모델 클래스 적용 범위',{exact:true}).selectOption('all');await dialog.getByRole('button',{name:'매핑 확인·새 초안으로 채택',exact:true}).click();await expect(dialog).toHaveCount(0);
 const helper=path.join(harness.REPO_ROOT,'scripts/e2e/fixtures/yolo_obb_package_readback.py');const diagnose=JSON.parse(execFileSync(harness.resolvePython(),[helper],{input:JSON.stringify({action:'inspect',project_dir:project.project_dir,job_id:jobId,source}),encoding:'utf8',timeout:35_000,maxBuffer:8*1024*1024}));
 await page.getByRole('group',{name:/^회전 영역 검출 노드 · 선택/}).click();await expect(page.getByLabel('완료된 학습 모델',{exact:true})).toHaveValue(jobId);await page.getByLabel('결함 판정 임계치',{exact:true}).fill(String(diagnose.diagnostic_roi_threshold));await page.getByRole('group',{name:/^검사 모델 노드 · 선택/}).click();await page.getByLabel('결함 판정 임계치',{exact:true}).fill('0.001');
 await page.getByRole('button',{name:'플로우 저장',exact:true}).click();const save=page.getByRole('dialog',{name:'검사 규칙 변경 저장',exact:true});await expect(save).toBeVisible();await save.getByLabel('변경 사유',{exact:true}).fill('Owned OBB polygon fitted ROI and offline candidate qualification');waiting=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/flowchart/pipeline'&&r.request().method()==='POST');await save.getByRole('button',{name:'변경 저장',exact:true}).click();response=await waiting;expect(response.ok(),await response.text()).toBe(true);const saved=await response.json();await page.reload();await stage(4);await expect(page.getByText('모델 2/2 연결',{exact:true})).toBeVisible();await evidence.screenshot(page,'actual-obb-fitted-roi-recipe-reopened');
 const reopened=await api('/api/flowchart/pipeline/active?source_dataset_path='+encodeURIComponent(fixture.source)),pipeline=reopened.pipeline||reopened;expect(pipeline.nodes.find((n:any)=>n.id==='node_align').data.params.operation).toBe('fitted_roi');const flow=await api('/api/flowchart/run',{image_path:source,pipeline,execution_target:'local',device:'cpu'});const aligned=flow.execution_steps.find((r:any)=>r.node_id==='node_align');expect(aligned.input_count).toBe(diagnose.selected_rois);expect(aligned.output_count).toBe(diagnose.selected_rois);expect(aligned.status).toBe('passed');expect(flow.execution_steps.find((r:any)=>r.node_id==='node_inspect').input_count).toBe(diagnose.selected_rois);
 const offline=JSON.parse(execFileSync(harness.resolvePython(),[helper],{input:JSON.stringify({project_dir:project.project_dir,job_id:jobId,source,pipeline,flow_result:flow}),encoding:'utf8',timeout:95_000,maxBuffer:12*1024*1024}));expect(offline.comparison.status).toBe('passed');for(const file of fixture.files){expect(crypto.createHash('sha256').update(fs.readFileSync(file.path)).digest('hex')).toBe(file.sha256);evidence.addFile(file.path);expect(crypto.createHash('sha256').update(fs.readFileSync(file.annotation)).digest('hex')).toBe(file.annotation_sha256);evidence.addFile(file.annotation);}
 evidence.note('obb_qualification',{fixture,project,prepared,posted,jobId,terminal,metadata,evaluated,predicted,diagnose,saved,reopened,pipeline,source,flow,offline,actual_app_cpu_training:true,actual_official_weights:true,actual_fitted_roi:true,actual_reopen:true,actual_fresh_package:true,source_unchanged:true,gpu_verified:false,quality_approval:false,license_approval:false});
}
test('authentic OBB actual empty crowded multiclass fit heldout polygon metrics and aligned offline recipe',{tag:'@owned-model'},async({page,request,renderer,workspace,evidence})=>{test.setTimeout(360_000);const api:Api=async(route,body)=>{const r=body===undefined?await request.get(renderer.origin+route):route.endsWith('/update')?await request.put(renderer.origin+route,{data:body}):await request.post(renderer.origin+route,{data:body});expect(r.ok(),await r.text()).toBe(true);return r.json();};await exercise(page,workspace,evidence,api,renderer.url);});
test('native authentic OBB actual axial detection and fitted original geometry survive offline recipe',{tag:['@electron','@owned-model']},async({electronSession,workspace,evidence})=>{test.setTimeout(360_000);const {window}=electronSession;const backend=await electronSession.waitForBackend();const api:Api=(route,body)=>window.evaluate(async({port,route,body})=>{const r=await fetch(`http://127.0.0.1:${port}${route}`,{...(body===undefined?{}:{method:route.endsWith('/update')?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})});if(!r.ok)throw Error(`Owned API ${r.status}: ${await r.text()}`);return r.json();},{port:backend.port,route,body});await exercise(window,workspace,evidence,api);});
