import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {execFileSync} from 'node:child_process';
import type {Page} from '@playwright/test';import {test,expect,type Workspace,type Evidence} from './fixtures/test';
const harness=require('./fixtures/harness.cjs');type Api=(route:string,body?:any)=>Promise<any>;test.use({actionTimeout:10_000});
async function exercise(page:Page,workspace:Workspace,evidence:Evidence,api:Api,url?:string){
 const helper=path.join(harness.REPO_ROOT,'scripts/e2e/fixtures/yolo_detection_data.py');const fixture=JSON.parse(execFileSync(harness.resolvePython(),[helper,workspace.root],{encoding:'utf8',timeout:15_000}));
 await api('/api/project/create',{name:'Authentic YOLO detector and dense ROI recipe',task:'detection'});await api('/api/project/update',{source_dataset_dir:fixture.source});const project=await api('/api/project/current');await api('/api/dataset/import',{folder_path:fixture.source,task:'detection'});
 const split=JSON.parse(execFileSync(harness.resolvePython(),[helper,workspace.root,JSON.stringify(project)],{encoding:'utf8',timeout:15_000}));expect(split.empty_target_valid).toBe(true);expect(split.multiple_box_class_ids).toEqual([1,2]);
 if(url)await page.goto(url);else await page.reload();await expect(page.getByTitle('프로젝트 관리',{exact:true})).toContainText(project.name);
 const stage=(i:number)=>page.getByRole('navigation',{name:'Workflow Stages'}).getByRole('button').nth(i).click();
 async function train(task:'detection'|'segmentation',weights:string,hash:string){
  await stage(2);const backbone=task==='detection'?'yolo26n':'dinov3_vits16';await expect(page.getByRole('combobox',{name:'학습 모델 구조',exact:true})).toHaveValue(backbone);await page.getByLabel('수동 학습 횟수',{exact:true}).fill('2');await page.getByLabel('수동 학습 입력 크기',{exact:true}).fill('64');
  await page.locator('summary').filter({hasText:'사전학습 파일 가져오기 · 상세 설정'}).click();await page.getByLabel('사전학습 가중치 파일',{exact:true}).fill(weights);await page.locator('summary').filter({hasText:'다음 학습 배치·로컬 장치 설정'}).click();await page.getByLabel('다음 학습 배치 크기',{exact:true}).fill('2');await page.getByLabel('다음 학습 로컬 장치',{exact:true}).selectOption('cpu');
  let waiting=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/training-workspace/readiness'&&r.request().method()==='POST');await page.getByRole('button',{name:'로컬 준비 검사',exact:true}).click();let response=await waiting;expect(response.ok()).toBe(true);const ready=await response.json();expect(ready.ready).toBe(true);expect(ready.weights.sha256).toBe(hash);
  await page.locator('summary').filter({hasText:'학습 실행 예산·대기열'}).click();await page.getByLabel('학습 시간 제한 (분)',{exact:true}).fill('2');waiting=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/training/start'&&r.request().method()==='POST');await page.getByRole('button',{name:'선택 설정으로 학습 시작',exact:true}).click();response=await waiting;expect(response.ok(),await response.text()).toBe(true);const posted=response.request().postDataJSON(),accepted=await response.json(),jobId=accepted.job_id;expect(posted).toMatchObject({task,device:'cpu',config_overrides:{epochs:2,image_size:64,batch_size:2,pretrained_checkpoint:weights}});expect(posted.config_overrides[task==='detection'?'backbone':'model_name']).toBe(backbone);
  let terminal:any;await expect.poll(async()=>{terminal=await api('/api/training/status?job_id='+jobId);if(['failed','cancelled','aborted'].includes(terminal.status))throw Error(JSON.stringify(terminal));return terminal.status;},{timeout:125_000}).toBe('completed');await expect(page.getByRole('region',{name:'학습 로그'})).toContainText('완료',{timeout:20_000});
  const metadata=JSON.parse(fs.readFileSync(path.join(project.models_dir,jobId,'model_meta.json'),'utf8'));expect(metadata.pretrained_sha256).toBe(hash);expect(metadata.augmentation_contract).toMatchObject({version:1,target_sync:true});
  return {ready,posted,terminal,metadata,jobId};
 }
 const detector=await train('detection',fixture.yolo_weights,fixture.yolo_sha256);expect(detector.metadata.classes).toEqual(['scratch','stain']);expect(detector.metadata.checkpoint_selection).toEqual({metric:'val_loss',direction:'min',split:'val',epoch:detector.metadata.best_epoch});const losses=detector.terminal.loss_history.map((r:any)=>r.val_loss);expect(detector.metadata.best_metric).toBeCloseTo(Math.min(...losses),5);expect(losses[detector.metadata.best_epoch]).toBeCloseTo(detector.metadata.best_metric,5);
 let waiting=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/evaluation/results'&&r.request().method()==='GET');await stage(3);let response=await waiting;expect(response.ok(),await response.text()).toBe(true);const evaluated=await response.json();expect(evaluated.job_id).toBe(detector.jobId);expect(evaluated.metrics.evaluated_split).toBe('test');expect(evaluated.test_predictions).toHaveLength(2);expect(evaluated.confusion_matrix.classes).toEqual(['background','scratch','stain']);for(const key of ['mAP_50','mAP_50_95'])expect(Number.isFinite(evaluated.metrics[key])).toBe(true);
 for(const row of evaluated.test_predictions){expect(row.object_evidence).toMatchObject({coordinate_space:'original_image',source_size:[128,96],grain:'object'});expect(row.object_evidence.truth).toHaveLength(row.file_path.includes('defect.png')?2:0);}
 const panel=page.locator('details').filter({has:page.locator('summary').filter({hasText:'객체·픽셀·문자 오류와 분포 분석'})}).first();await panel.locator('summary').first().click();await panel.getByLabel('평가 증거 클래스',{exact:true}).selectOption('scratch');await panel.getByLabel('평가 증거 오류',{exact:true}).selectOption('fn');const missingScratch=evaluated.test_predictions.filter((r:any)=>r.object_evidence.missing_truth_indices.some((i:number)=>r.object_evidence.truth[i].label==='scratch')).length;await expect(panel.getByRole('button',{name:/defect.png · FN/})).toHaveCount(missingScratch);await panel.getByRole('button',{name:'필터 초기화',exact:true}).click();await panel.getByRole('button',{name:/defect.png · FN/}).click();await expect(panel.getByLabel('정답과 예측 객체 위치',{exact:true})).toHaveAttribute('viewBox','0 0 128 96');await expect(panel.getByLabel('정답과 예측 객체 위치',{exact:true}).locator('polygon[stroke="#4ade80"]')).toHaveCount(2);await evidence.screenshot(page,'authentic-yolo-heldout-object-errors');
 const countRecipe=JSON.parse(execFileSync(harness.resolvePython(),[path.join(harness.REPO_ROOT,'scripts/e2e/fixtures/detection_count_control.py'),JSON.stringify(project),detector.jobId],{encoding:'utf8',timeout:15_000}));
 await stage(4);await page.getByRole('tab',{name:'편집',exact:true}).click();await page.getByLabel('저장 버전',{exact:true}).selectOption(countRecipe.version);
 await page.getByLabel('플로우 노드 검색',{exact:true}).fill(countRecipe.model_id);await page.getByRole('list',{name:'노드 검색 결과'}).getByRole('button').click();
 await page.getByLabel('검출 판정 방식',{exact:true}).selectOption('count');await page.getByLabel('객체 클래스 1',{exact:true}).selectOption('scratch');await page.getByLabel('객체 최소 개수 1',{exact:true}).fill('0');await page.getByLabel('객체 최대 개수 1',{exact:true}).fill('1000');
 await page.getByRole('button',{name:'초안 저장',exact:true}).click();
 let countDraft=await api('/api/flowchart/draft');expect(countDraft.pipeline.nodes.find((n:any)=>n.id===countRecipe.model_id).data.params.object_requirements).toEqual([{class_name:'scratch',min_count:0,max_count:1000}]);
 const countInput=fixture.files.find((f:any)=>f.split==='test'&&!f.defect).path;
 const countedOK=await api('/api/flowchart/run',{image_path:countInput,pipeline:countDraft.pipeline,execution_target:'local',device:'cpu'});expect(countedOK.final_verdict).toBe('OK');
 await page.getByLabel('객체 최소 개수 1',{exact:true}).fill('1000');await page.getByRole('button',{name:'초안 저장',exact:true}).click();countDraft=await api('/api/flowchart/draft');
 const countedNG=await api('/api/flowchart/run',{image_path:countInput,pipeline:countDraft.pipeline,execution_target:'local',device:'cpu'});expect(countedNG.final_verdict).toBe('NG');expect(countedNG.rejection_reason).toContain('required 1000');
 const countStep=countedNG.execution_steps.find((step:any)=>step.node_id===countRecipe.model_id);expect(countStep.count_rule_results[0]).toMatchObject({class_name:'scratch',min_count:1000,verdict:'NG'});expect(countedNG.crops.length).toBe(countStep.output_count);
 await page.reload();await stage(4);await page.getByRole('tab',{name:'편집',exact:true}).click();await page.getByLabel('플로우 노드 검색',{exact:true}).fill(countRecipe.model_id);await page.getByRole('list',{name:'노드 검색 결과'}).getByRole('button').click();await expect(page.getByLabel('객체 최소 개수 1',{exact:true})).toHaveValue('1000');
 await evidence.screenshot(page,'actual-trained-detector-required-count-persistent-rule');evidence.note('required_object_counts',{countRecipe,countedOK,countedNG,actual_trained_detector:true,actual_gui_editor:true,no_fabricated_crops:true,quality_approved:false});
 await api('/api/project/update',{task:'segmentation'});await page.reload();const dense=await train('segmentation',fixture.weights,fixture.weights_sha256);expect(dense.metadata.classes).toEqual(['background','scratch','stain']);await stage(4);
 await page.locator('summary').filter({hasText:'새 플로우'}).click();await page.getByRole('button',{name:'검출 ROI 검사',exact:true}).click();const dialog=page.getByRole('dialog',{name:'레시피 미리보기·모델 매핑',exact:true});await expect(dialog).toBeVisible();await dialog.getByLabel('관심 영역 검출 레시피 모델',{exact:true}).selectOption(detector.jobId);await dialog.getByLabel('관심 영역 검출 클래스 적용 범위',{exact:true}).selectOption('all');await dialog.getByLabel('검사 모델 레시피 모델',{exact:true}).selectOption(dense.jobId);await dialog.getByLabel('검사 모델 클래스 적용 범위',{exact:true}).selectOption('all');await dialog.getByRole('button',{name:'매핑 확인·새 초안으로 채택',exact:true}).click();await expect(dialog).toHaveCount(0);
 await page.getByRole('group',{name:/^관심 영역 검출 노드 · 선택/}).click();await page.getByLabel('결함 판정 임계치',{exact:true}).fill('0.001');await page.getByRole('group',{name:/^검사 모델 노드 · 선택/}).click();await page.getByLabel('결함 판정 임계치',{exact:true}).fill('0.2');
 await page.getByRole('button',{name:'플로우 저장',exact:true}).click();const save=page.getByRole('dialog',{name:'검사 규칙 변경 저장',exact:true});await expect(save).toBeVisible();waiting=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/flowchart/pipeline'&&r.request().method()==='POST');await save.getByRole('button',{name:'변경 저장',exact:true}).click();response=await waiting;expect(response.ok(),await response.text()).toBe(true);const saved=await response.json();await page.reload();await stage(4);await expect(page.getByText('모델 2/2 연결',{exact:true})).toBeVisible();await expect(page.getByRole('group',{name:/^관심 영역 검출 노드 · 선택/})).toBeVisible();await expect(page.getByRole('group',{name:/^검사 모델 노드 · 선택/})).toBeVisible();await evidence.screenshot(page,'authentic-yolo-dense-roi-reopened');
 const reopened=await api('/api/flowchart/pipeline/active?source_dataset_path='+encodeURIComponent(fixture.source)),pipeline=reopened.pipeline||reopened;expect(pipeline.nodes.find((n:any)=>n.data.node_type==='detection_crop').data).toMatchObject({model_job_id:detector.jobId,threshold:0.001});expect(pipeline.nodes.find((n:any)=>n.data.node_type==='inspection').data).toMatchObject({model_job_id:dense.jobId,threshold:0.2});const source=fixture.files.find((f:any)=>f.split==='test'&&f.defect).path;
 const flow=await api('/api/flowchart/run',{image_path:source,pipeline,execution_target:'local',device:'cpu'});expect(['OK','NG']).toContain(flow.final_verdict);expect(flow.roi_count).toBeGreaterThan(0);expect(flow.crops.length).toBeGreaterThan(0);const inspect=flow.execution_steps.find((r:any)=>r.node_id==='node_inspect');expect(['passed','flagged_ng']).toContain(inspect.status);expect(inspect.input_count).toBeGreaterThan(0);for(const crop of flow.crops){expect(crop.source_node_id).toBe('node_inspect');expect(crop.segmentation_classes).toHaveLength(3);expect(crop.bbox[0]).toBeGreaterThanOrEqual(0);expect(crop.bbox[2]).toBeLessThanOrEqual(128);expect(crop.bbox[3]).toBeLessThanOrEqual(96);}
 const offline=JSON.parse(execFileSync(harness.resolvePython(),[path.join(harness.REPO_ROOT,'scripts/e2e/fixtures/yolo_flow_package_readback.py')],{input:JSON.stringify({project_dir:project.project_dir,job_ids:[detector.jobId,dense.jobId],pipeline,flow_result:flow,source}),encoding:'utf8',timeout:70_000,maxBuffer:8*1024*1024}));expect(offline.comparison.status).toBe('passed');
 for(const file of fixture.files){for(const [name,key] of [['path','sha256'],['annotation','annotation_sha256']]){expect(crypto.createHash('sha256').update(fs.readFileSync(file[name])).digest('hex')).toBe(file[key]);evidence.addFile(file[name]);}}evidence.addFile(split.split_path);
 evidence.note('yolo_detection_qualification',{fixture,project,split,detector,dense,evaluated,saved,reopened,pipeline,flow,offline,source,actual_app_button_training:true,actual_official_pretrained:true,actual_cpu:true,actual_heldout_object_metrics:true,actual_error_viewer:true,actual_roi_followup_model:true,actual_reopen:true,actual_fresh_candidate_package:true,no_original_mutation:true,gpu_verified:false,quality_approval:false});
}
test('authentic YOLO empty multi-box small-object mAP errors dense ROI and offline candidate',{tag:'@owned-model'},async({page,request,renderer,workspace,evidence})=>{test.setTimeout(360_000);const api:Api=async(route,body)=>{const r=body===undefined?await request.get(renderer.origin+route):route.endsWith('/update')?await request.put(renderer.origin+route,{data:body}):await request.post(renderer.origin+route,{data:body});expect(r.ok(),await r.text()).toBe(true);return r.json();};await exercise(page,workspace,evidence,api,renderer.url);});
test('native authentic YOLO trains evaluates object errors and reopens dense ROI export',{tag:['@electron','@owned-model']},async({electronSession,workspace,evidence})=>{test.setTimeout(360_000);const {window}=electronSession;const backend=await electronSession.waitForBackend();const api:Api=(route,body)=>window.evaluate(async({port,route,body})=>{const r=await fetch(`http://127.0.0.1:${port}${route}`,{...(body===undefined?{}:{method:route.endsWith('/update')?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})});if(!r.ok)throw Error(`Owned API ${r.status}: ${await r.text()}`);return r.json();},{port:backend.port,route,body});await exercise(window,workspace,evidence,api);});
