import {useEffect,useState} from 'react';
import {ganWorkflow,type GANPreview,type GANRegion} from '../../services/ganWorkflow';
import {useDatasetStore} from '../../stores/useDatasetStore';
import {programInput,programButton} from './ProgramWorkbenchControls';
import {parseGANMask} from './ganComposition';
export function GANCompositionEditor({source,scope,imagePath,onImageChange,regions,onRegionsChange,onPreview,disabled}:{source:string;scope:string;imagePath:string;onImageChange:(path:string)=>void;regions:GANRegion[];onRegionsChange:(regions:GANRegion[])=>void;onPreview:(preview:GANPreview|null)=>void;disabled:boolean}) {
  const images=useDatasetStore(state=>state.images);const [preview,setPreview]=useState<GANPreview|null>(null),[error,setError]=useState(''),[start,setStart]=useState<[number,number]|null>(null);
  useEffect(()=>{let active=true;setPreview(null);onPreview(null);setError('');setStart(null);if(imagePath)ganWorkflow.preview(imagePath).then(row=>{if(active){setPreview(row);onPreview(row);}}).catch(cause=>{if(active)setError(cause.message||String(cause));});return()=>{active=false;};},[imagePath,scope]);
  const add=(bbox:[number,number,number,number])=>{let index=regions.length+1;while(regions.some(row=>row.id===`영역 ${index}`))index++;onRegionsChange([...regions,{id:`영역 ${index}`,bbox,opacity:1,feather_px:0}]);};
  return <section className="space-y-3 rounded border border-violet-700 bg-[#0E1722] p-3"><h4 className="font-semibold text-violet-200">원본 이미지의 한 영역·여러 영역 합성</h4><label>합성 원본<select aria-label="GAN 합성 원본" disabled={disabled} value={imagePath} onChange={e=>{onImageChange(e.target.value);onRegionsChange([]);}} className={programInput}><option value="">현재 원본 이미지 선택</option>{images.filter(image=>image.file_path.startsWith(`${source.replace(/\/+$/,'')}/`)).map(image=><option key={image.image_id} value={image.file_path}>{image.file_name}</option>)}</select></label><p className="text-slate-400">미리보기에서 사각형의 두 모서리를 클릭하세요. 생성 후보는 원본 크기로 저장하며 선택 영역 밖의 픽셀은 보존합니다.</p>
    {preview&&<><p className="text-violet-200">원본 {preview.source_size.join(' × ')} px · SHA {preview.source_sha256.slice(0,12)} · 영역 {regions.length}개</p><svg role="img" aria-label="GAN 원본 합성 영역 그리기" viewBox={`0 0 ${preview.source_size.join(' ')}`} className="max-h-96 w-full cursor-crosshair rounded bg-black" onClick={event=>{
      if(disabled||regions.length>=32)return;const rect=event.currentTarget.getBoundingClientRect();const [width,height]=preview.source_size,scale=Math.min(rect.width/width,rect.height/height);
      const point:[number,number]=[Math.round((event.clientX-rect.left-(rect.width-width*scale)/2)/scale),Math.round((event.clientY-rect.top-(rect.height-height*scale)/2)/scale)];
      if(point[0]<0||point[1]<0||point[0]>width||point[1]>height)return;
      if(!start)setStart(point);else{const bbox:[number,number,number,number]=[Math.min(start[0],point[0]),Math.min(start[1],point[1]),Math.max(start[0],point[0]),Math.max(start[1],point[1])];if(bbox[2]>bbox[0]&&bbox[3]>bbox[1])add(bbox);setStart(null);}
    }}><image href={preview.preview_data_url} width={preview.source_size[0]} height={preview.source_size[1]}/>{regions.map(row=><rect key={row.id} x={row.bbox[0]} y={row.bbox[1]} width={row.bbox[2]-row.bbox[0]} height={row.bbox[3]-row.bbox[1]} fill="#a78bfa30" stroke="#c4b5fd" strokeWidth={2} vectorEffect="non-scaling-stroke"/>)}{start&&<circle cx={start[0]} cy={start[1]} r={Math.max(...preview.source_size)/150} fill="#fbbf24"/>}</svg><button type="button" disabled={disabled||regions.length>=32} onClick={()=>add([0,0,Math.min(32,preview.source_size[0]),Math.min(32,preview.source_size[1])])} className={programButton}>좌표로 영역 추가</button></>}
    {regions.map((row,index)=><div key={index} className="space-y-2 border-t border-slate-700 pt-2"><div className="flex gap-2"><input aria-label={`합성 영역 ${index+1} 이름`} disabled={disabled} value={row.id} onChange={e=>onRegionsChange(regions.map((r,i)=>i===index?{...r,id:e.target.value}:r))} className={programInput}/><button type="button" disabled={disabled} onClick={()=>onRegionsChange(regions.filter((_,i)=>i!==index))} className={programButton}>삭제</button></div><div className="grid grid-cols-4 gap-2">{row.bbox.map((value,axis)=><label key={axis}>{['X₁','Y₁','X₂','Y₂'][axis]} (px)<input disabled={disabled} type="number" min="0" step="1" value={value} onChange={e=>onRegionsChange(regions.map((r,i)=>{if(i!==index)return r;const bbox=[...r.bbox] as GANRegion['bbox'];bbox[axis]=Number(e.target.value);return {...r,bbox};}))} className={programInput}/></label>)}</div><div className="grid grid-cols-2 gap-2"><label>불투명도<input disabled={disabled} type="number" min="0.01" max="1" step="0.05" value={row.opacity} onChange={e=>onRegionsChange(regions.map((r,i)=>i===index?{...r,opacity:Number(e.target.value)}:r))} className={programInput}/></label><label>경계 혼합 (px)<input disabled={disabled} type="number" min="0" max="1024" step="1" value={row.feather_px} onChange={e=>onRegionsChange(regions.map((r,i)=>i===index?{...r,feather_px:Number(e.target.value)}:r))} className={programInput}/></label></div><label className="block">영역 외곽선 · 원본 x,y; x,y; x,y (선택)<input aria-label={`합성 영역 ${index+1} 외곽선`} disabled={disabled} type="text" defaultValue={row.mask_polygon?.map(point=>point.join(',')).join(';')||''} placeholder="비우면 사각형 전체" onChange={event=>onRegionsChange(regions.map((r,i)=>i===index?{...r,mask_polygon:parseGANMask(event.target.value)}:r))} className={programInput}/></label></div>)}
    <p className="text-[10px] text-slate-400">원본 해시·영역·시드·혼합 조건을 후보와 함께 저장합니다. 검토자가 채택하기 전에는 정답 라벨이나 학습 데이터로 쓰이지 않습니다.</p>{error&&<p role="alert" className="text-rose-300">{error}</p>}
  </section>;
}
