const assert=require('node:assert/strict'),test=require('node:test'),fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),ts=require('typescript');
test('saved execution receipts reopen and stale project replies never appear in the new project',async()=>{
 let cursor=0;const slots=[],effects=[],pending=[];let project={projectDir:'/one',project:{id:'one',source_dataset_dir:'/source-one',active_labelset_id:'default'}};
 const react={useState:initial=>{const i=cursor++;if(!(i in slots))slots[i]=initial;return[slots[i],value=>slots[i]=value];},useRef:initial=>{const i=cursor++;return slots[i]||(slots[i]={current:initial});},useEffect:(fn,deps)=>{const i=cursor++;if(!slots[i]||deps.some((v,j)=>v!==slots[i][j])){slots[i]=deps;effects.push(fn);}}};
 const jsx=(type,props)=>({type,props:props||{}});const file=path.join(__dirname,'ModelExecutionEvidence.tsx'),m=new Module(file,module);m.filename=file;m.paths=Module._nodeModulePaths(__dirname);
 m.require=k=>({'react':react,'react/jsx-runtime':{jsx,jsxs:jsx},'../../stores/useProjectStore':{useProjectStore:()=>project},'../../stores/useComputeStore':{useComputeStore:()=>({transportRevision:0})},'../../services/api':{request:url=>new Promise(resolve=>pending.push({url,resolve})),getApiPersistenceIdentity:()=> 'local',getProjectContextGeneration:()=>0}}[k]);
 m._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2022}}).outputText,file);
 const render=()=>{cursor=0;const tree=m.exports.ModelExecutionEvidence({task:'rotation',jobId:'model'});effects.splice(0).forEach(fn=>fn());return tree;};
 const row=id=>({receipt_id:id,evidence_sha256:'hash-'+id,device:'cpu',stage:'predict',runtime:{device_name:'CPU',process_id:123,torch_version:'verified'},checkpoint_sha256:'model-hash',input_binding_sha256:'input-hash'});
 render();assert.match(pending[0].url,/task=rotation&job_id=model/);project={projectDir:'/two',project:{id:'two',source_dataset_dir:'/source-two',active_labelset_id:'default'}};render();pending[0].resolve({receipts:[row('stale')]});await new Promise(setImmediate);assert.doesNotMatch(JSON.stringify(render()),/hash-stale/);
 pending[1].resolve({receipts:[row('current')]});await new Promise(setImmediate);const tree=render();assert.match(JSON.stringify(tree),/hash-current/);assert.match(JSON.stringify(tree),/model-hash/);assert.match(JSON.stringify(tree),/input-hash/);
 const nodes=n=>[n,...[n?.props?.children].flat().filter(v=>v&&typeof v==='object').flatMap(nodes)];nodes(tree).find(n=>n.type==='button').props.onClick();assert.equal(pending.length,3);pending[2].resolve({receipts:[row('reopened')]});await new Promise(setImmediate);assert.match(JSON.stringify(render()),/hash-reopened/);
});
