const test=require('node:test');const assert=require('node:assert/strict');
const fs=require('node:fs');const ts=require('typescript');const vm=require('node:vm');
function load(file='modelAdapterRecipes.ts'){const path=require('node:path').join(__dirname,file);assert.ok(fs.existsSync(path),'Model adapter payload helpers are missing');const exports={};const code=ts.transpileModule(fs.readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;vm.runInNewContext(code,{exports,require:name=>name.startsWith('.')?load(name+'.ts'):require(name),Error,JSON,Set});return exports;}
test('OCR recipe keeps Unicode charset and explicit multiline mode in outgoing payload',()=>{const m=load();const recipe=m.ocrRecipePayload('detect_recognize','가A1','nfkc_strip','가A[0-9]');assert.equal(recipe.mode,'detect_recognize');assert.equal(recipe.charset,'가A1');assert.equal(recipe.text_rules.regex,'가A[0-9]');assert.throws(()=>m.ocrRecipePayload('crop','AA','none',''),/중복/);});
test('OCR length and exact allowed values share the saved train and inference recipe',()=>{const m=load();const row=m.ocrRecipePayload('detect_recognize','가나12','none','[가나12]+',{minLength:'1',maxLength:'10',allowedValues:'가1\n나2\n가1\n'});assert.equal(row.text_rules.min_length,1);assert.equal(row.text_rules.max_length,10);assert.equal(JSON.stringify(row.text_rules.allowed_values),JSON.stringify(['가1','나2']));assert.throws(()=>m.ocrRecipePayload('crop','','none','',{minLength:'3',maxLength:'2'}),/최소/);assert.throws(()=>m.ocrRecipePayload('crop','','none','',{minLength:'1.5'}),/정수/);});
test('absent and invalid OCR error rates cannot look like zero errors',()=>{const m=load();for(const v of [undefined,null,NaN,Infinity,-1,'0'])assert.equal(m.formatOCRRate(v),'측정되지 않음');assert.equal(m.formatOCRRate(0),'0.0%');assert.equal(m.formatOCRRate(1.2),'120.0%');});
test('OBB payload requires an explicit local model and native trust acknowledgement',()=>{const m=load();assert.equal(m.obbRecipePayload('fixed_slot_cnn','').adapter,'fixed_slot_cnn');assert.throws(()=>m.obbRecipePayload('ultralytics_yolo_obb','yolo11n-obb.pt'),/절대 경로/);assert.throws(()=>m.obbRecipePayload('ultralytics_yolo_obb','C:\\models\\local-obb.pt'),/신뢰/);const recipe=m.obbRecipePayload('ultralytics_yolo_obb','C:\\models\\local-obb.pt',true);assert.equal(recipe.model_path,'C:\\models\\local-obb.pt');assert.equal(recipe.direction_schema,'none');assert.equal(recipe.trust_native_weights,true);});
test('empty background TSV rows survive a UI load/save round trip beside object rows',()=>{const m=load();const rows=m.parseOBBRows('background.png\t\t\tval\npart.png\t가 defect\t30,30,12,8,-20\ttrain');assert.equal(rows[0].objects.length,0);assert.equal(rows[1].objects[0].label,'가 defect');assert.equal(m.parseOBBRows(m.formatOBBRows(rows))[0].objects.length,0);assert.throws(()=>m.parseOBBRows('x.png\t\t30,30,12,8,0\ttrain'),/빈 정상/);});
test('reopening an OCR candidate restores the exact saved recognition rules',()=>{const m=load();const saved={mode:'detect_recognize',charset:'가나12',normalizer:'nfkc_strip',text_rules:{regex:'[가나12]+',min_length:1,max_length:10,allowed_values:['가1',' 나2 ']}};const draft=m.ocrRecipeDraft(saved);assert.deepEqual(JSON.parse(JSON.stringify(m.ocrRecipePayload(draft.mode,draft.charset,draft.normalizer,draft.regex,draft))),{...saved,orientation:'horizontal'});});
test('OCR input width batch and learning rate reach the bounded training request',()=>{const m=load();assert.deepEqual(JSON.parse(JSON.stringify(m.ocrTrainingOptions(120,'2','32','0.003'))),{epochs:120,batch_size:2,image_width:32,learning_rate:.003});for(const args of [[501,'2','32','.003'],[120,'0','32','.003'],[120,'2','7','.003'],[120,'2','32','NaN']])assert.throws(()=>m.ocrTrainingOptions(...args));});
