import {useEffect,useRef,useState} from 'react';
import {api} from '../../services/api';
import {modelTrainingProgram,type LocalTrainingDevice,type PatchSample,type PatchPrediction} from '../../services/modelTrainingProgram';
import {defaultPatchRecipe,readPatchRecipe,type PatchRecipe} from '../flowchart/flowchartGraph';
import {useProjectStore} from '../../stores/useProjectStore';
import {ProgramField,programInput,programButton} from './ProgramWorkbenchControls';

export function PatchRecipePreview({scope,source,datasetPath,patchCount,modelId,device,disabled,isCurrent,action,setNotice,setError}:{scope:string;source:string;datasetPath:string;patchCount:number;modelId:string;device:LocalTrainingDevice;disabled:boolean;isCurrent:()=>boolean;action:(name:string,run:()=>Promise<void>)=>Promise<void>;setNotice:(value:string)=>void;setError:(value:string)=>void}){
 const [index,setIndex]=useState(0),[sample,setSample]=useState<PatchSample|null>(null),[prediction,setPrediction]=useState<PatchPrediction|null>(null);
 const [recipe,setRecipe]=useState<PatchRecipe>({...defaultPatchRecipe}),[restoredKey,setRestoredKey]=useState('');
 const key=`vision-patch-recipe-v1:${scope}:${modelId}`;
 const selection=`${scope}\n${datasetPath}\n${index}\n${modelId}\n${device}\n${JSON.stringify(recipe)}`;const current=useRef(selection);current.current=selection;
 useEffect(()=>{setIndex(0);setSample(null);setPrediction(null);},[scope,datasetPath]);
 useEffect(()=>{let loaded={...defaultPatchRecipe};try{const saved=localStorage.getItem(key);if(saved)loaded=readPatchRecipe(JSON.parse(saved));}catch{setError('저장된 패치 설정을 읽지 못했습니다. 새 설정을 확인하세요.');}setRecipe(loaded);setRestoredKey(key);},[key]);
 useEffect(()=>{if(restoredKey===key&&modelId){try{localStorage.setItem(key,JSON.stringify(readPatchRecipe(recipe)));}catch{/* Invalid edits remain visible until corrected. */}}},[key,recipe,restoredKey,modelId]);
 useEffect(()=>{let active=true;setSample(null);setPrediction(null);if(datasetPath)void modelTrainingProgram.patch.sample(datasetPath,index).then(row=>{if(active&&isCurrent())setSample(row);}).catch(cause=>{if(active&&isCurrent())setError(String(cause));});return()=>{active=false;};},[scope,datasetPath,index]);
 useEffect(()=>{setPrediction(null);},[selection]);
 let recipeError='';try{readPatchRecipe(recipe);}catch(cause){recipeError=String(cause);}
 const infer=()=>action('원본 패치 검사',async()=>{if(!sample)return;const expected=selection;const row=await modelTrainingProgram.patch.predict(modelId,source.replace(/[/\\]+$/,'')+'/'+sample.source_relative_path,device,readPatchRecipe(recipe));if(isCurrent()&&current.current===expected)setPrediction(row);});
 const save=()=>action('패치 판정 플로우 저장',async()=>{const expected=selection;const version=await api.flowchart.activeVersionId();if(!isCurrent()||current.current!==expected)return;const pipeline=await modelTrainingProgram.patch.recipeFlow(modelId,readPatchRecipe(recipe));if(!isCurrent()||current.current!==expected)return;const result=await api.flowchart.savePipeline(pipeline,'patch_classification',source,{changeReason:'선택 패치 후보와 명시적 전체 판정 설정',expectedVersionId:version.version_id});if(isCurrent()&&current.current===expected){setNotice(`패치 판정 플로우 버전 ${result.version_id} 저장`);await useProjectStore.getState().setStep(5);}});
 return <section aria-label="원본 패치 정답·판정 미리보기" className="mt-4 rounded border border-[#344255] p-3">
  <h3 className="font-semibold text-cyan-200">원본 패치 정답과 전체 판정</h3>
  <ProgramField label="정답 패치 번호"><input aria-label="정답 패치 번호" type="number" min={0} max={Math.max(0,patchCount-1)} value={index} onChange={e=>setIndex(Number(e.target.value))} className={programInput}/></ProgramField>
  {sample&&<><p className="mt-2">{sample.source_relative_path} · {sample.split} · 정답 {sample.label} · 원본 좌표 [{sample.box.join(', ')}] · {sample.patch_size}px / 간격 {sample.stride}px</p><div className="mt-2 grid gap-3 sm:grid-cols-2"><svg role="img" aria-label="패치 정답의 원본 위치" viewBox={`0 0 ${sample.source_size.join(' ')}`} className="max-h-64 w-full"><image href={'data:image/png;base64,'+sample.original_base64} width={sample.source_size[0]} height={sample.source_size[1]}/><rect x={sample.box[0]} y={sample.box[1]} width={sample.box[2]-sample.box[0]} height={sample.box[3]-sample.box[1]} fill="none" stroke="cyan" strokeWidth={1}/></svg><img alt="검수 정답 패치" src={'data:image/png;base64,'+sample.patch_base64} className="max-h-64 w-full object-contain"/></div><p className="break-all text-slate-500">원본 SHA-256 {sample.source_sha256}</p></>}
  <div className="mt-3 grid gap-3 sm:grid-cols-4"><ProgramField label="패치 전체 판정 방식"><select value={recipe.mode} onChange={e=>setRecipe({...recipe,mode:e.target.value as PatchRecipe['mode']})} className={programInput}><option value="max">최대 결함 점수</option><option value="vote">NG 비율 투표</option><option value="ng_count">최소 NG 패치 수</option></select></ProgramField>
  <ProgramField label="패치 결함 임계치"><input type="number" min={0} max={1} step={.01} value={recipe.threshold} onChange={e=>setRecipe({...recipe,threshold:Number(e.target.value)})} className={programInput}/></ProgramField>
  <ProgramField label="NG 투표 비율"><input type="number" min={.01} max={1} step={.01} value={recipe.vote_fraction} onChange={e=>setRecipe({...recipe,vote_fraction:Number(e.target.value)})} className={programInput}/></ProgramField>
  <ProgramField label="최소 NG 패치 수"><input type="number" min={1} max={100000} value={recipe.minimum_ng_count} onChange={e=>setRecipe({...recipe,minimum_ng_count:Number(e.target.value)})} className={programInput}/></ProgramField></div>
  <p className="mt-2 text-slate-400">점수 ≥ 임계치인 패치가 NG입니다. 투표는 NG 비율 ≥ 지정 비율일 때 NG로 판정합니다. 겹친 패치를 각각 세며, 결함 객체 수와 다릅니다. 점수 지도는 겹친 패치의 최대 확률을 표시하며 분할 정답이 아닙니다.</p>
  {recipeError&&<p role="alert" className="text-rose-300">{recipeError}</p>}
  <div className="mt-3 flex gap-3"><button type="button" disabled={disabled||!modelId||!sample||!!recipeError} onClick={()=>void infer()} className={programButton}>선택 원본 패치 검사</button><button type="button" disabled={disabled||!modelId||!!recipeError} onClick={()=>void save()} className={programButton}>패치 판정 플로우 저장</button></div>
  {prediction&&<div className="mt-3" aria-label="패치 전체 검사 결과"><p>전체 판정 {prediction.decision==='FAIL'?'NG':'OK'} · NG {prediction.ng_count}/{prediction.patch_count} · 최대 점수 {prediction.max_defect_score.toFixed(4)}</p><div className="mt-2 grid gap-3 sm:grid-cols-2"><svg role="img" aria-label="원본 좌표 패치 검사 결과" viewBox={`0 0 ${prediction.source_size.join(' ')}`} className="max-h-72 w-full"><image href={'data:image/png;base64,'+prediction.original_base64} width={prediction.source_size[0]} height={prediction.source_size[1]}/>{prediction.patches.slice(0,1000).map((row,i)=><rect key={i} x={row.box[0]} y={row.box[1]} width={row.box[2]-row.box[0]} height={row.box[3]-row.box[1]} fill="none" stroke={row.decision==='FAIL'?'red':'lime'} strokeWidth={1}><title>{row.predicted_class} · {row.defect_score.toFixed(4)}</title></rect>)}</svg><img alt="패치 결함 확률 지도 (미리보기)" src={'data:image/png;base64,'+prediction.score_map_base64} className="max-h-72 w-full object-contain"/></div><p className="mt-2 text-slate-400">{prediction.score_map_definition}</p>{prediction.patches.length>1000&&<p className="text-slate-400">원본 위치는 처음 1000개 표시 · 판정은 전체 {prediction.patch_count}개 사용</p>}<p className="break-all text-slate-500">모델 SHA-256 {prediction.model_sha256}</p><div className="mt-2 max-h-40 overflow-auto">{prediction.patches.slice(0,100).map((row,i)=><p key={i}>[{row.box.join(', ')}] {row.predicted_class} · {row.defect_score.toFixed(4)} · {row.decision}</p>)}{prediction.patches.length>100&&<p>처음 100개 표시 · 전체 {prediction.patches.length}개</p>}</div></div>}
 </section>;
}
