const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),ts=require('typescript');
function load(file,mocks={}){const name=path.resolve(__dirname,file),m=new Module(name,module);m.filename=name;m.paths=Module._nodeModulePaths(path.dirname(name));const req=m.require.bind(m);m.require=key=>key in mocks?mocks[key]:req(key);m._compile(ts.transpileModule(fs.readFileSync(name,'utf8'),{fileName:name,compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText,name);return m.exports;}
const jsx=(type,props)=>({type,props:props||{}});const nodes=tree=>[tree,...[tree?.props?.children].flat().filter(x=>x&&typeof x==='object').flatMap(nodes)];
function fixture(remote=false){const values=[],calls=[],jobs=[];let cursor=0;const settings=load('TrainingSchedulingSettings.tsx',{'react/jsx-runtime':{jsx,jsxs:jsx}});const state={scope:'owned-project',source:'/source',dataset:{dataset_path:'/patch'},datasets:[],parents:[],models:[],modelId:'',job:null,active:false,busy:'',action:async(_,fn)=>fn(),isCurrent:()=>true,setJob:job=>jobs.push(job)};
 const m=load('PatchClassificationWorkbench.tsx',{'react':{useState:initial=>{const i=cursor++;if(!(i in values))values[i]=initial;return[values[i],value=>values[i]=value];},useEffect:()=>{}},'react/jsx-runtime':{jsx,jsxs:jsx},'lucide-react':{},'./parentCandidate':{},'./ProgramWorkbenchControls':{},'./useProgramWorkbench':{useProgramWorkbench:()=>state},'./TrainingSchedulingSettings':settings,'../../stores/useComputeStore':{useComputeStore:()=>({selectedProfileId:remote?'server':null})},'../../services/modelTrainingProgram':{modelTrainingProgram:{patch:{train:async body=>{calls.push(body);return{job_id:'owned-patch',status:'queued'};}}}},'./JobProgressView':{},'./AutoDLWorkbench':{},'./TrainingPreparationPanel':{},'./PatchRecipePreview':{},'./ModelExecutionEvidence':{ModelExecutionEvidence:()=>null}});
 const render=()=>{cursor=0;return nodes(m.PatchClassificationWorkbench());};const controls=tree=>{const view=tree.find(x=>x.type===settings.TrainingSchedulingSettings);assert.ok(view,'Patch scheduling controls are mounted');return view.props;};const button=tree=>tree.find(x=>x.type==='button'&&x.props.children==='패치 분류 후보 학습');return{render,controls,button,calls,jobs};}
test('patch workbench submits validated minutes queue and priority while retaining its prepared input',async()=>{const f=fixture();let tree=f.render();f.controls(tree).onChange({runtimeMinutes:'1.5',queue:false,priority:'0'});tree=f.render();assert.equal(f.button(tree).props.disabled,false);await f.button(tree).props.onClick();assert.equal(f.calls.length,1);assert.equal(f.calls[0].dataset_path,'/patch');assert.equal(f.calls[0].max_runtime_s,90);assert.equal(f.calls[0].queue,false);assert.equal(f.calls[0].priority,0);assert.equal(f.jobs[0].status,'queued');});
test('invalid patch runtime cannot submit even through the captured start callback',async()=>{const f=fixture();let tree=f.render();f.controls(tree).onChange({runtimeMinutes:'-1',queue:true,priority:'0'});tree=f.render();assert.match(f.controls(tree).error,/시간 제한/);assert.equal(f.button(tree).props.disabled,true);await f.button(tree).props.onClick();assert.equal(f.calls.length,0);});
test('remote patch controls retain a budget but use existing FIFO scheduling',async()=>{const f=fixture(true);let tree=f.render();assert.equal(f.controls(tree).remote,true);f.controls(tree).onChange({runtimeMinutes:'1',queue:false,priority:'5'});tree=f.render();await f.button(tree).props.onClick();assert.equal(f.calls[0].max_runtime_s,60);assert.equal(f.calls[0].queue,true);assert.equal(f.calls[0].priority,0);});
