const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),ts=require('typescript');
const tick=()=>new Promise(setImmediate);
function harness(){
 let cursor=0,generation=0,identity='local';const slots=[],effects=[],pending=[],calls=[];
 const state={projectDir:'/project',project:{id:'p',source_dataset_dir:'/source',active_labelset_id:'default'}},compute={transportRevision:0,selectedProfileId:null};
 const handoff={jobId:'exact',executionJobId:'exact',family:'classification',transport:'local',status:'interrupted',selectionId:'selection-1'};
 const react={useState:initial=>{const i=cursor++;if(!(i in slots))slots[i]=typeof initial==='function'?initial():initial;return[slots[i],v=>slots[i]=typeof v==='function'?v(slots[i]):v];},useRef:initial=>{const i=cursor++;if(!(i in slots))slots[i]={current:initial};return slots[i];},useEffect:(fn,deps)=>{const i=cursor++;if(!slots[i]||deps.some((v,j)=>v!==slots[i].deps[j])){slots[i]?.cleanup?.();slots[i]={deps};effects.push(()=>slots[i].cleanup=fn());}}};
 const mocks={'react':react,'../../services/api':{request:async route=>{calls.push(route);return new Promise(resolve=>pending.push(resolve));},getProjectContextGeneration:()=>generation,getApiPersistenceIdentity:()=>identity,subscribeProjectContext:()=>()=>{}},'../../stores/useProjectStore':{useProjectStore:Object.assign(()=>state,{getState:()=>state})},'../../stores/useComputeStore':{useComputeStore:Object.assign(()=>compute,{getState:()=>compute})},'./useTaskHandoff':{useTaskHandoff:()=>handoff}};
 function load(name){const file=path.join(__dirname,name),m=new Module(file,module);m.filename=file;m.paths=Module._nodeModulePaths(__dirname);m.require=ref=>mocks[ref]||load(ref+'.ts');m._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,file);return m.exports;}
 const mod=load('useSelectedCoreJob.ts');const render=(active=null)=>{cursor=0;const result=mod.useSelectedCoreJob(active);effects.splice(0).forEach(fn=>fn());return result;};
 const exact={job_id:'exact',task:'classification',status:'interrupted',source_dataset_path:'/source',training_provenance:{labelset_id:'default'}};
 return{render,pending,calls,exact,handoff,state,advance:()=>{generation++;identity='new-account';},dispose:()=>slots.forEach(row=>row?.cleanup?.())};
}
test('reopening the selected interrupted core job preserves exact record without launching a worker',async()=>{const h=harness();try{h.render();h.pending[0]({tasks:[{...h.exact,job_id:'newest'},h.exact]});await tick();assert.deepEqual(h.render().job,h.exact);assert.deepEqual(h.calls,['/api/training-workspace/tasks']);}finally{h.dispose();}});
for(const [field,value]of [['job_id','foreign'],['source_dataset_path','/other'],['training_provenance',{labelset_id:'other'}],['compute_profile_id','other-server']])test(`saved core job cannot reopen mismatched ${field}`,async()=>{const h=harness();try{h.render();h.pending[0]({tasks:[{...h.exact,[field]:value}]});await tick();const result=h.render();assert.equal(result.job,null);assert.match(result.error,/찾지 못/);}finally{h.dispose();}});
test('a reply under an old project authority cannot populate a reopened core job',async()=>{const h=harness();try{h.render();h.advance();h.pending[0]({tasks:[h.exact]});await tick();assert.equal(h.render().job,null);}finally{h.dispose();}});
test('a previous selection reply cannot replace the newly selected job',async()=>{const h=harness();try{h.render();h.handoff.jobId='new';h.handoff.executionJobId='new';h.handoff.selectionId='selection-2';h.render();h.pending[0]({tasks:[h.exact]});h.pending[1]({tasks:[{...h.exact,job_id:'new'}]});await tick();assert.equal(h.render().job.job_id,'new');}finally{h.dispose();}});
test('current active job stays owned by the training store and is not duplicated as a saved job',()=>{const h=harness();try{assert.equal(h.render('exact').job,null);assert.deepEqual(h.calls,[]);}finally{h.dispose();}});
