const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const Module=require('node:module');const test=require('node:test');const ts=require('typescript');
function load(file,mocks={}){const name=path.resolve(__dirname,file);assert.ok(fs.existsSync(name),'Task handoff implementation exists');const m=new Module(name,module);m.filename=name;m.paths=Module._nodeModulePaths(__dirname);const req=m.require.bind(m);m.require=key=>mocks[key]||req(key);m._compile(ts.transpileModule(fs.readFileSync(name,'utf8'),{compilerOptions:{jsx:ts.JsxEmit.ReactJSX,module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,name);return m.exports;}
const memory=()=>{const values=new Map();return{getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)};};
const scope={projectDir:'/project',project:{id:'p',source_dataset_dir:'/source',active_labelset_id:'default'}};
const task=(family,kind='training')=>({key:`${kind}:local:exact`,id:'exact',kind,task:family,status:'completed',source:'/source',labelset:'default',transport:'local',raw:{dataset_path:'/project/dataset/exact'}});
test('all ten families route completed candidates to their actual evaluation workspaces',()=>{const {taskDestination}=load('taskHandoff.ts');for(const family of ['classification','segmentation','detection','anomaly'])assert.equal(taskDestination(task(family)).step,4);for(const family of ['patch_classification','ocr','rotated_detection','rotation','defect_gan','enhancement']){const result=taskDestination(task(family));assert.equal(result.step,3);assert.equal(result.family,family);}assert.equal(taskDestination(task('detection','inspection')).step,6);assert.equal(taskDestination(task('detection','export')).step,6);assert.equal(taskDestination(task('labeling','labeling-batch')).step,2);});
test('exact job and family are scoped across reopen; missing target never selects newest model',()=>{const api=load('taskHandoff.ts');const storage=memory();api.saveTaskHandoff(storage,scope,task('ocr','ocr'));assert.equal(api.readTaskHandoff(storage,scope,'ocr').jobId,'exact');assert.equal(api.readTaskHandoff(storage,{...scope,project:{...scope.project,source_dataset_dir:'/other'}},'ocr'),null);assert.equal(api.readTaskHandoff(storage,scope,'rotation'),null);assert.equal(api.selectHandoffRecord([{job_id:'newest'},{job_id:'exact'}],api.readTaskHandoff(storage,scope,'ocr')).job_id,'exact');assert.throws(()=>api.selectHandoffRecord([{job_id:'newest'}],api.readTaskHandoff(storage,scope,'ocr')),/찾지 못/);});
test('actual completed OCR action invokes overlay callback and preserves exact downstream handoff',async()=>{
 let cursor=0;const slots=[],effects=[],calls=[],storage=memory();const state={...scope,task:'detection',setStep:async step=>calls.push(['step',step]),setTask:async family=>calls.push(['task',family])};const useProjectStore=sel=>sel?sel(state):state;useProjectStore.getState=()=>state;
 const react={useState:initial=>{const i=cursor++;if(!(i in slots))slots[i]=typeof initial==='function'?initial():initial;return[slots[i],v=>slots[i]=typeof v==='function'?v(slots[i]):v];},useRef:initial=>{const i=cursor++;if(!(i in slots))slots[i]={current:initial};return slots[i];},useEffect:(fn,deps)=>{const i=cursor++;if(!slots[i]||deps.some((v,j)=>v!==slots[i][j])){slots[i]=deps;effects.push(fn);}}};const jsx=(type,props)=>({type,props:props||{},children:[props?.children].flat().filter(Boolean)});
 const m=load('TaskCenter.tsx',{'react':react,'react/jsx-runtime':{jsx,jsxs:jsx},'lucide-react':{},'../../services/api':{getApiPersistenceIdentity:()=> 'local',request:async()=>({tasks:[{kind:'ocr',job_id:'exact',task:'ocr',status:'completed',source_dataset_path:'/source',training_provenance:{labelset_id:'default'},dataset_path:'/project/dataset/exact'}],reservations:[],errors:[],source_dataset_path:'/source',labelset_id:'default'})},'../../stores/useProjectStore':{useProjectStore},'../../stores/useComputeStore':{useComputeStore:Object.assign(sel=>sel({transportRevision:0,profiles:[],selectedProfileId:null}),{getState:()=>({transportRevision:0,selectedProfileId:null})})},'./taskCenterModel':load('taskCenterModel.ts'),'./ProgramWorkbenchControls':{programInput:'',programButton:''},'./taskHandoff':fs.existsSync(path.resolve(__dirname,'taskHandoff.ts'))?load('taskHandoff.ts'):{} });
 const oldStorage=global.localStorage,oldInterval=global.setInterval;global.localStorage=storage;global.setInterval=()=>0;try{const render=()=>{cursor=0;const tree=m.TaskCenter({initialOpen:true,onNavigate:async step=>calls.push(['navigate',step])});effects.splice(0).forEach(fn=>fn());return tree;};render();await new Promise(setImmediate);const tree=render();const nodes=[];const walk=n=>{if(n&&typeof n==='object'){nodes.push(n);n.children?.flat().forEach(walk);}};walk(tree);const familySelector=nodes.find(n=>n.props['aria-label']==='작업 모델 종류');assert.equal(familySelector.children.flat().filter(n=>n?.type==='option').length,11);await nodes.find(n=>n.type==='button'&&n.children.includes('완료 후보 평가로 이동')).props.onClick();assert.deepEqual(calls,[['step',3],['navigate',3]]);const api=load('taskHandoff.ts');assert.equal(api.readTaskHandoff(storage,state,'ocr').jobId,'exact');}finally{global.localStorage=oldStorage;global.setInterval=oldInterval;}
});

test('basic handoff loads the requested evaluation job instead of transient newest completed job',async()=>{const calls=[];const training={isCurrentData:true,status:'completed',jobId:'newest'};const m=load('../../stores/useEvaluationStore.ts',{'./useTrainingStore':{useTrainingStore:{getState:()=>training}},'../services/api':{api:{evaluation:{getOverkillUnderkill:async()=>({}),getResults:async(id)=>{calls.push(id);return{job_id:id,metrics:{accuracy:1},test_predictions:[]};}}},getApiBaseUrl:()=>''}});m.useEvaluationStore.setState({allowLatestRecovery:false});await m.useEvaluationStore.getState().loadEvaluation('exact',{folderPath:'/source',task:'classification'});assert.deepEqual(calls,['exact']);assert.equal(m.useEvaluationStore.getState().jobId,'exact');});

function hookHarness(){let cursor=0;const slots=[],effects=[];const react={useState:initial=>{const i=cursor++;if(!(i in slots))slots[i]=typeof initial==='function'?initial():initial;return[slots[i],v=>slots[i]=typeof v==='function'?v(slots[i]):v];},useRef:initial=>{const i=cursor++;if(!(i in slots))slots[i]={current:initial};return slots[i];},useEffect:(fn,deps)=>{const i=cursor++;if(!slots[i]||deps.some((v,j)=>v!==slots[i].deps[j])){slots[i]?.cleanup?.();slots[i]={deps};effects.push(()=>{slots[i].cleanup=fn();});}},useCallback:fn=>fn};return{react,render:fn=>{cursor=0;const result=fn();effects.splice(0).forEach(fn=>fn());return result;}};}
test('specialized hook restores requested job rather than first completed journal',async()=>{const h=hookHarness(),state={...scope};const store=sel=>sel(state);store.getState=()=>state;const jobs=['newest','exact'].map(job_id=>({job_id,task:'ocr',status:'completed',source_dataset_path:'/source',training_provenance:{labelset_id:'default'}}));const completed=[];const m=load('useSpecializedTraining.ts',{'react':h.react,'../../stores/useProjectStore':{useProjectStore:store},'../../services/specializedApi':{specializedApi:{trainingJobs:async()=>({jobs})}},'./scopedTrainingJob':load('scopedTrainingJob.ts'),'./useTaskHandoff':{useTaskHandoff:()=>({jobId:'exact',family:'ocr'})},'./taskHandoff':load('taskHandoff.ts')});h.render(()=>m.useSpecializedTraining('ocr',row=>completed.push(row.job_id)));await new Promise(setImmediate);const result=h.render(()=>m.useSpecializedTraining('ocr',row=>completed.push(row.job_id)));assert.equal(result.job.job_id,'exact');assert.deepEqual(completed,['exact']);});
test('OCR model and prepared dataset selectors restore exact target despite newer defaults',async()=>{const h=hookHarness(),state={...scope};const store=sel=>sel(state);store.getState=()=>state;const jsx=(type,props)=>({type,props:props||{},children:[props?.children].flat().filter(Boolean)});const handoff={jobId:'exact',family:'ocr',datasetPath:'/project/dataset/exact'};const models=['newest','exact'].map(job_id=>({job_id,metadata:{dataset_path:`/project/dataset/${job_id}`}}));const m=load('OCRWorkbench.tsx',{'react':h.react,'react/jsx-runtime':{jsx,jsxs:jsx},'lucide-react':{},'../../stores/useProjectStore':{useProjectStore:store},'../../services/api':{api:{ocr:{models:async()=>({models})}},request:async()=>({datasets:[{dataset_path:'/project/dataset/exact',sample_count:3},{dataset_path:'/project/dataset/newest',sample_count:4}]})},'./useSpecializedTraining':{useSpecializedTraining:()=>({active:false})},'./useTaskHandoff':{useTaskHandoff:()=>handoff},'./taskHandoff':load('taskHandoff.ts'),'./SpecializedTrainingStatus':{},'./WarmStartSelector':{},'./AutoDLWorkbench':{},'./ProgramWorkbenchControls':{},'./ProjectImagePicker':{},'./preparedSampleRows':{}});h.render(()=>m.OCRWorkbench());await new Promise(setImmediate);const tree=h.render(()=>m.OCRWorkbench());const nodes=[];const walk=n=>{if(n&&typeof n==='object'){nodes.push(n);n.children?.flat().forEach(walk);}};walk(tree);const selectors=nodes.filter(n=>n.type==='select');assert.ok(selectors.some(n=>n.props.value==='exact'),'Exact OCR model is selected');assert.ok(selectors.some(n=>n.props.value==='/project/dataset/exact'),'Matching prepared dataset is selected');selectors.find(n=>n.props.value==='exact').props.onChange({target:{value:'newest'}});h.render(()=>m.OCRWorkbench());handoff.selectionId='select-same-task-again';h.render(()=>m.OCRWorkbench());await new Promise(setImmediate);const repeated=h.render(()=>m.OCRWorkbench());nodes.length=0;walk(repeated);assert.ok(nodes.some(n=>n.type==='select'&&n.props.value==='exact'),'Same-task re-click restores exact OCR model after manual selection changed');});

test('persisted handoff reopens across epochs while server identity and GPU profile remain isolated',()=>{const handoff=load('taskHandoff.ts');const storage=memory();const server={...scope,transportRevision:4,selectedProfileId:'server-a',apiTransportIdentity:'https://server-a/base'};handoff.saveTaskHandoff(storage,server,task('ocr','ocr'));assert.equal(handoff.readTaskHandoff(storage,{...server,transportRevision:0},'ocr').jobId,'exact');assert.equal(handoff.readTaskHandoff(storage,{...server,apiTransportIdentity:'https://server-b/base'},'ocr'),null);assert.equal(handoff.readTaskHandoff(storage,{...server,selectedProfileId:'server-b'},'ocr'),null);const {dataWorkbenchScope}=load('../../services/dataWorkbench.ts',{'./api':{request(){}}});assert.notEqual(dataWorkbenchScope(server),dataWorkbenchScope({...server,transportRevision:5}));assert.notEqual(dataWorkbenchScope(server),dataWorkbenchScope({...server,selectedProfileId:'server-b'}));});

test('diagnostic scope differs for same project after transport-only or selected-server change',()=>{const {dataWorkbenchScope}=load('../../services/dataWorkbench.ts',{'./api':{request(){}}});const state={...scope,transportRevision:4,selectedProfileId:'a'};assert.notEqual(dataWorkbenchScope(state),dataWorkbenchScope({...state,transportRevision:5}));assert.notEqual(dataWorkbenchScope(state),dataWorkbenchScope({...state,selectedProfileId:'b'}));});

test('reopening the same completed task creates a new selection identity',()=>{const api=load('taskHandoff.ts');const storage=memory();const first=api.saveTaskHandoff(storage,scope,task('ocr','ocr'));const next=api.saveTaskHandoff(storage,scope,task('ocr','ocr'));assert.equal(next.jobId,first.jobId);assert.ok(first.selectionId);assert.notEqual(next.selectionId,first.selectionId);});

test('API persistence identity omits credentials and transient parameters and keeps local restart identity stable',()=>{const api=load('../../services/api.ts');api.setCachedPort(8000);assert.equal(api.getApiPersistenceIdentity(),'local');api.setCachedPort(9123);assert.equal(api.getApiPersistenceIdentity(),'local');api.setSharedApiBase('https://user:password@api-a.example/base/?token=sentinel#private');assert.equal(api.getApiPersistenceIdentity(),'shared:https://api-a.example/base');api.setSharedApiBase('https://api-a.example/base');assert.equal(api.getApiPersistenceIdentity(),'shared:https://api-a.example/base');api.setSharedApiBase('https://api-b.example/base');assert.equal(api.getApiPersistenceIdentity(),'shared:https://api-b.example/base');api.setSharedApiBase(null);assert.equal(api.getApiPersistenceIdentity(),'local');});

test('review queue storage scope survives reconnect but isolates stable API identity',()=>{const {dataWorkbenchPersistenceScope,dataWorkbenchScope}=load('../../services/dataWorkbench.ts',{'./api':{request(){}}});const initial={...scope,transportRevision:9,selectedProfileId:'gpu-a',apiTransportIdentity:'shared:https://api-a/base'};assert.equal(dataWorkbenchPersistenceScope(initial),dataWorkbenchPersistenceScope({...initial,transportRevision:0}));assert.notEqual(dataWorkbenchScope(initial),dataWorkbenchScope({...initial,transportRevision:0}));assert.notEqual(dataWorkbenchPersistenceScope(initial),dataWorkbenchPersistenceScope({...initial,apiTransportIdentity:'shared:https://api-b/base'}));});
