const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),ts=require('typescript');
function load(file,mocks={}){const name=path.join(__dirname,file),m=new Module(name,module);m.filename=name;m.paths=Module._nodeModulePaths(__dirname);m.require=ref=>ref in mocks?mocks[ref]:['./jobProgress','./taskCenterModel','./taskHandoff'].includes(ref)?load(ref+'.ts'):require(ref);m._compile(ts.transpileModule(fs.readFileSync(name,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText,name);return m.exports;}
const flush=()=>new Promise(setImmediate);
function harness(){
 let cursor=0,tree;const slots=[],effects=[],cleanup=[],pending=[],timers=new Map(),listeners=new Set();let nextTimer=0;
 const state={projectDir:'/project',project:{id:'p',source_dataset_dir:'/source',active_labelset_id:'default'},isProjectBusy:false};
 const compute={transportRevision:0,profiles:[],selectedProfileId:null};
 const react={useState:initial=>{const i=cursor++;if(!(i in slots))slots[i]=typeof initial==='function'?initial():initial;return[slots[i],v=>slots[i]=typeof v==='function'?v(slots[i]):v];},useRef:initial=>{const i=cursor++;if(!(i in slots))slots[i]={current:initial};return slots[i];},useEffect:(fn,deps)=>{const i=cursor++;if(!slots[i]||deps.some((v,j)=>v!==slots[i][j])){slots[i]=deps;effects.push(()=>{cleanup[i]?.();cleanup[i]=fn();});}}};
 const jsx=(type,props)=>({type,props:props||{},children:[props?.children].flat()});
 const old={storage:global.localStorage,interval:global.setInterval,clear:global.clearInterval};global.localStorage={getItem:()=>null,setItem(){},removeItem(){}};global.setInterval=fn=>{const id=++nextTimer;timers.set(id,fn);return id;};global.clearInterval=id=>timers.delete(id);
 const m=load('TaskCenter.tsx',{react,'react/jsx-runtime':{jsx,jsxs:jsx},'lucide-react':{},'../../services/jobEventFeed':{onJobEventChanges:fn=>{listeners.add(fn);return()=>listeners.delete(fn);}},'../../services/api':{getApiPersistenceIdentity:()=>'local',request:()=>new Promise((resolve,reject)=>pending.push({resolve,reject}))},'../../stores/useProjectStore':{useProjectStore:Object.assign(()=>state,{getState:()=>state})},'../../stores/useComputeStore':{useComputeStore:Object.assign(sel=>sel(compute),{getState:()=>compute})},'./ProgramWorkbenchControls':{programInput:'',programButton:''}});
 function render(){cursor=0;tree=m.TaskCenter({initialOpen:true});effects.splice(0).forEach(fn=>fn());return tree;}
 function text(n){return typeof n==='string'||typeof n==='number'?String(n):n&&typeof n==='object'?(n.children||[]).flat().map(text).join(''):'';}
 function nodes(n){return n&&typeof n==='object'?[n,...(n.children||[]).flat().flatMap(nodes)]:[];}
 function reply(id='backup',source='/source'){return{tasks:[{kind:'project_backup',job_id:id,task:'project_backup',status:'completed',scope_kind:'project',source_dataset_path:source}],reservations:[],errors:[],source_dataset_path:source,labelset_id:'default'};}
 render();return{pending,state,render,text:()=>text(tree),buttons:()=>nodes(tree).filter(n=>n.type==='button').map(n=>({text:text(n),disabled:n.props.disabled})),reply,poll:()=>[...timers.values()].forEach(fn=>fn()),event:()=>[...listeners].forEach(fn=>fn()),manual:()=>nodes(tree).find(n=>n.type==='button'&&text(n).includes('같은 작업 확인')).props.onClick(),toggle:open=>tree.props.onToggle({currentTarget:{open}}),unmount:()=>cleanup.forEach(fn=>fn?.()),dispose:()=>{cleanup.forEach(fn=>fn?.());global.localStorage=old.storage;global.setInterval=old.interval;global.clearInterval=old.clear;}};
}
test('task center uses recorded pending cancel and permits re-observation without a second cancel',async()=>{
 const h=harness();try{const r=h.reply();r.tasks=[{kind:'training',task:'classification',job_id:'pending',status:'disconnected',compute_profile_id:'server',source_dataset_path:'/source',observation:{cause:'cancel_unconfirmed',next_action:'종료 확인이 필요합니다.',cancel:{stage:'requested',requested_at:1,complete:false}}}];h.pending[0].resolve(r);await flush();h.render();
 assert.equal(h.buttons().find(b=>b.text==='취소 요청'),undefined);assert.equal(h.buttons().find(b=>b.text==='종료 확인 중')?.disabled,true);assert.ok(h.buttons().find(b=>b.text==='같은 서버 작업 재연결'));
 }finally{h.dispose();}
});

test('slow responses render while polling continues and HTTP requests never overlap',async()=>{const h=harness();try{for(let i=0;i<4;i++)h.poll();assert.equal(h.pending.length,1,'poll ticks must not start concurrent reads');h.pending[0].resolve(h.reply());await flush();h.render();assert.match(h.text(),/현재 프로젝트 1개/);assert.match(h.text(),/마지막 응답 확인/);h.poll();assert.equal(h.pending.length,2,'a later poll refreshes after completion');}finally{h.dispose();}});
test('manual and catch-up bursts coalesce one follow-up without overlapping',async()=>{const h=harness();try{for(let i=0;i<3;i++){h.manual();h.event();}assert.equal(h.pending.length,1);h.pending[0].resolve(h.reply());await flush();assert.equal(h.pending.length,2);h.pending[1].resolve(h.reply());await flush();assert.equal(h.pending.length,2);}finally{h.dispose();}});
test('scope A to B to A rejects old completion and queues one current scope read',async()=>{const h=harness();try{h.state.project={...h.state.project,source_dataset_dir:'/other'};h.render();h.state.project={...h.state.project,source_dataset_dir:'/source'};h.render();assert.equal(h.pending.length,1);h.pending[0].resolve(h.reply('old'));await flush();h.render();assert.doesNotMatch(h.text(),/마지막 응답 확인/);assert.equal(h.pending.length,2);h.pending[1].resolve(h.reply('fresh'));await flush();h.render();assert.match(h.text(),/현재 프로젝트 1개/);}finally{h.dispose();}});
test('closing rejects old completion; reopen reads after old request releases',async()=>{const h=harness();try{h.toggle(false);h.render();h.pending[0].resolve(h.reply());await flush();h.render();assert.doesNotMatch(h.text(),/마지막 응답 확인/);assert.equal(h.pending.length,1);h.toggle(true);h.render();assert.equal(h.pending.length,2);}finally{h.dispose();}});
test('unmount drops queued refresh and stale completion',async()=>{const h=harness();try{h.event();h.unmount();h.pending[0].resolve(h.reply());await flush();assert.equal(h.pending.length,1);h.render();assert.doesNotMatch(h.text(),/마지막 응답 확인/);}finally{h.dispose();}});
test('failed read releases the gate, displays error and later poll recovers',async()=>{const h=harness();try{h.poll();assert.equal(h.pending.length,1);h.pending[0].reject(Error('fixture failed read'));await flush();h.render();assert.match(h.text(),/fixture failed read/);h.poll();assert.equal(h.pending.length,2);h.pending[1].resolve(h.reply());await flush();h.render();assert.match(h.text(),/현재 프로젝트 1개/);assert.doesNotMatch(h.text(),/fixture failed read/);}finally{h.dispose();}});
test('same open details toggle and stable scope rerenders do not restart polling',()=>{const h=harness();try{for(let i=0;i<4;i++){h.toggle(true);h.state.project={...h.state.project};h.render();}assert.equal(h.pending.length,1);}finally{h.dispose();}});
