const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),ts=require('typescript');
function load(file){const name=path.join(__dirname,file),m=new Module(name,module);m.filename=name;m.paths=Module._nodeModulePaths(__dirname);m.require=ref=>ref.startsWith('.')?load(ref+'.ts'):require(ref);m._compile(ts.transpileModule(fs.readFileSync(name,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,name);return m.exports;}
const model=()=>load('taskCenterModel.ts');
test('S1-04: each cancel step is done only with its own evidence, never because a later stage was reached',()=>{const m=model();
 const row=(observation)=>m.normalizeTask('training',{job_id:'j',status:'aborted',observation});
 assert.equal(m.observationSummary(row(undefined)),null);
 const localExit=m.observationSummary(row({cause:'cancelled',next_action:null,cancel:{stage:'exited',requested_at:1,acknowledged_at:null,signals:[],exit_confirmed:true,reservation_released:false}}));
 assert.deepEqual(localExit.steps.map(step=>step.done),[true,false,false,true,false],'no acknowledgement and no signal were recorded');
 const full=m.observationSummary(row({cause:'cancelled',next_action:null,cancel:{stage:'released',requested_at:1,acknowledged_at:2,signals:['cooperative'],exit_confirmed:true,reservation_released:true}}));
 assert.ok(full.steps.every(step=>step.done));
 const lost=m.observationSummary(row({cause:'cancel_unconfirmed',next_action:'연결을 복구하면 같은 작업을 다시 확인합니다.',cancel:{stage:'signalled',requested_at:1,acknowledged_at:null,signals:['cooperative'],exit_confirmed:false,reservation_released:null}}));
 assert.deepEqual(lost.steps.map(step=>step.done),[true,false,true,false,false]);assert.match(lost.nextAction,/다시 확인/);});
test('S1-04: only an uncertain reservation of a job that is no longer active can be settled by an operator',()=>{const m=model();
 const row=status=>m.normalizeTask('training',{job_id:'j',status});
 const uncertain=[{job_id:'j',uncertain:true,fence:4}],held=[{job_id:'j',uncertain:false,fence:4}];
 assert.deepEqual(m.releasableReservation(row('disconnected'),uncertain),uncertain[0]);
 assert.equal(m.releasableReservation(row('running'),uncertain),null,'an active job is cancelled, not released');
 assert.equal(m.releasableReservation(row('failed'),held),null,'a reservation returned on exit evidence is left alone');
 assert.equal(m.releasableReservation(row('failed'),null),null);
 assert.equal(m.releasableReservation(m.normalizeTask('optimization',{job_id:'j',status:'failed'}),uncertain),null);});
test('S1-04: a row without a cancel still states its recorded exit and reservation release',()=>{const m=model();
 const row=(status,cancel)=>m.normalizeTask('training',{job_id:'j',status,observation:{cause:null,next_action:null,cancel:{stage:'none',...cancel}}});
 assert.deepEqual(m.observationSummary(row('completed',{exit_confirmed:true,reservation_released:true})).facts,['실행 종료 확인','예약 반환']);
 assert.deepEqual(m.observationSummary(row('failed',{exit_confirmed:false,reservation_released:false})).facts,['실행 종료 미확인','예약 보유 중']);
 assert.deepEqual(m.observationSummary(row('running',{exit_confirmed:false,reservation_released:null})).facts,[],'a running job is not called unconfirmed');
 assert.deepEqual(m.observationSummary(row('aborted',{stage:'released',requested_at:1,acknowledged_at:2,signals:['cooperative'],exit_confirmed:true,reservation_released:true})).facts,[],'a cancelled row shows its steps instead');
 const prepared=m.normalizeTask('training',{job_id:'j',status:'failed',observation:{cause:null,next_action:null,worker_recorded:false,cancel:{stage:'none',exit_confirmed:false,reservation_released:true}}});
 assert.deepEqual(m.observationSummary(prepared).facts,['작업자 실행 기록 없음','예약 반환'],'a job that failed before any worker started has no exit to confirm');
 const preparing=m.normalizeTask('training',{job_id:'j',status:'preparing',observation:{cause:null,next_action:null,worker_recorded:false,cancel:{stage:'none',exit_confirmed:false,reservation_released:null}}});
 assert.deepEqual(m.observationSummary(preparing).facts,[],'an active job that has not launched its worker yet is not labelled');
 const unknown=m.normalizeTask('training',{job_id:'j',status:'failed',observation:{cause:null,next_action:null,worker_recorded:null,cancel:{stage:'none',exit_confirmed:false,reservation_released:false}}});
 assert.deepEqual(m.observationSummary(unknown).facts,['실행 종료 미확인','예약 보유 중'],'an unreadable journal is not called absent');});
