const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),ts=require('typescript');
const tick=()=>new Promise(setImmediate);
function harness(component){
 let cursor=0,epoch=0,identity='actor-a',tree;const slots=[],effects=[],cleanup=[],listeners=[],calls=[],pending=[];
 const project={projectDir:'/project',project:{id:'p',source_dataset_dir:'/source',active_labelset_id:'default'},isProjectBusy:false,setStep:async()=>{}};
 const compute={selectedProfileId:null,transportRevision:0,profiles:[]};
 const react={useState:initial=>{const i=cursor++;if(!(i in slots))slots[i]=typeof initial==='function'?initial():initial;return[slots[i],v=>slots[i]=typeof v==='function'?v(slots[i]):v];},useRef:initial=>{const i=cursor++;if(!(i in slots))slots[i]={current:initial};return slots[i];},useEffect:(fn,deps)=>{const i=cursor++;if(!slots[i]||deps.some((v,j)=>v!==slots[i][j])){slots[i]=deps;effects.push(()=>{cleanup[i]?.();cleanup[i]=fn();});}}};
 const jsx=(type,props)=>({type,props:props||{},children:[props?.children].flat()});
 const task={kind:'training',task:'patch_classification',job_id:'owned',status:'disconnected',source_dataset_path:'/source',training_provenance:{labelset_id:'default'}};
 const request=async(route,options)=>{calls.push({route,options});if(route==='/api/training-workspace/tasks')return {tasks:[task],reservations:[],errors:[],source_dataset_path:'/source',labelset_id:'default'};return new Promise(resolve=>pending.push({route,resolve}));};
 const mocks={'react':react,'react/jsx-runtime':{jsx,jsxs:jsx},'lucide-react':{},'../../services/api':{request,getApiPersistenceIdentity:()=>identity,getProjectContextGeneration:()=>epoch,subscribeProjectContext:fn=>{listeners.push(fn);return()=>{};}},'../../stores/useProjectStore':{useProjectStore:Object.assign(()=>project,{getState:()=>project})},'../../stores/useComputeStore':{useComputeStore:Object.assign(sel=>sel?sel(compute):compute,{getState:()=>compute})},'../../stores/useDatasetStore':{useDatasetStore:()=>({totalImages:2})},'../../services/hostAdapter':{host:{can:()=>true,shared:{connection:async()=>null},selectFile:async()=>new Promise(resolve=>pending.push({route:'picker',resolve}))}},'./ProgramWorkbenchControls':{programButton:'',programInput:''},'./TeamTrainingReadiness':{},'../../services/jobEventFeed':{onJobEventChanges:()=>()=>{}},'./trainingWorkflow':{familyPreparation:{classification:{label:'분류'}}}};
 function load(name){const file=path.join(__dirname,name),m=new Module(file,module);m.filename=file;m.paths=Module._nodeModulePaths(__dirname);m.require=ref=>ref in mocks?mocks[ref]:ref.startsWith('./')?load(ref+'.ts'):require(ref);const source=process.env.MV_TRAINING_SCOPE_BASE&&['TaskCenter.tsx','TrainingPreparationPanel.tsx'].includes(name)?require('node:child_process').execFileSync('git',['show',`HEAD:src/renderer/components/training/${name}`],{cwd:path.resolve(__dirname,'../../../..'),encoding:'utf8'}):fs.readFileSync(file,'utf8');m._compile(ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText,file);return m.exports;}
 const mod=load(component+'.tsx');const old={storage:global.localStorage,interval:global.setInterval,clear:global.clearInterval};global.localStorage={getItem:()=>null,setItem(){},removeItem(){}};global.setInterval=()=>0;global.clearInterval=()=>{};
 const text=n=>typeof n==='string'?n:n&&typeof n==='object'?(n.children||[]).flat().map(text).join(''):'';
 const nodes=n=>n&&typeof n==='object'?[n,...(n.children||[]).flat().flatMap(nodes)]:[];
 const render=(props={})=>{cursor=0;tree=component==='TaskCenter'?mod.TaskCenter({initialOpen:true}):mod.TrainingPreparationPanel({family:'classification',model:'resnet18',onCheckpointChange:()=>calls.push({route:'checkpoint-callback'}),...props});effects.splice(0).forEach(fn=>fn());return tree;};
 return{render,calls,pending,advance:()=>{epoch++;identity='actor-b';listeners.forEach(fn=>fn());},action:label=>nodes(tree).find(n=>n.type==='button'&&text(n)===label)?.props.onClick,text:()=>text(tree),dispose:()=>{cleanup.forEach(fn=>fn?.());Object.assign(global,{localStorage:old.storage,setInterval:old.interval,clearInterval:old.clear});}};
}
test('retained preparation action cannot submit a readiness check after authority changes',async()=>{const h=harness('TrainingPreparationPanel');try{h.render();const action=h.action('로컬 준비 검사');h.advance();action();await tick();assert.equal(h.calls.length,0);}finally{h.dispose();}});
test('catalog reply under an old authority cannot start a readiness request',async()=>{const h=harness('TrainingPreparationPanel');try{h.render({model:undefined});h.action('로컬 준비 검사')();await tick();assert.equal(h.pending[0].route,'/api/models/capabilities');h.advance();h.pending[0].resolve({families:[{task:'classification',default_architecture:'resnet18'}]});await tick();assert.equal(h.calls.length,1);}finally{h.dispose();}});
test('late preparation reply cannot fill current panel or choose its checkpoint',async()=>{const h=harness('TrainingPreparationPanel');try{h.render();h.action('로컬 준비 검사')();await tick();h.advance();h.pending[0].resolve({ready:true,model:'resnet18',runtime:{available:true,device:'cpu'},weights:{state:'file_available'},dependencies:{missing:[]},next_actions:[],selected_checkpoint_path:'/old/checkpoint'});await tick();h.render();assert.doesNotMatch(h.text(),/준비 항목 확인됨/);assert.ok(!h.calls.some(r=>r.route==='checkpoint-callback'));}finally{h.dispose();}});
test('file picker completion under changed authority cannot import weights',async()=>{const h=harness('TrainingPreparationPanel');try{h.render();h.action('사전학습 파일 선택·프로젝트에 가져오기')();await tick();h.advance();h.pending[0].resolve('/old/weights.pth');await tick();assert.equal(h.calls.length,0);}finally{h.dispose();}});
for(const action of ['취소 요청','같은 로컬 작업 재연결','검증된 프로젝트 백업 만들기'])test(`retained task-center ${action} cannot mutate a new authority`,async()=>{const h=harness('TaskCenter');try{h.render();await tick();h.render();const callback=h.action(action);assert.equal(typeof callback,'function');h.advance();callback();await tick();assert.equal(h.calls.filter(r=>r.options).length,0);}finally{h.dispose();}});
