const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),ts=require('typescript'),test=require('node:test');
const settle=()=>new Promise(setImmediate);
function fixture({fallback=false,identity=false,value=''}={}){
 let cursor=0;const slots=[],effects=[],timers=[],paths=[],identities=[],legacyChoices=[];
 const react={useState:initial=>{const i=cursor++;if(!(i in slots))slots[i]=initial;return [slots[i],v=>slots[i]=typeof v==='function'?v(slots[i]):v];},useRef:initial=>{const i=cursor++;return slots[i]??(slots[i]={current:initial});},useEffect:(fn,deps)=>{const i=cursor++;if(!slots[i]||deps.some((v,j)=>v!==slots[i].deps[j])){slots[i]?.cleanup?.();slots[i]={deps};effects.push(()=>slots[i].cleanup=fn());}}};
 const jsx=(type,props)=>({type,props:props||{}}),image={image_uuid:'a',sha256:'a'.repeat(64),relative_path:'ok/a.png',file_path:'/s/a.png',file_name:'a.png',valid:true},invalid={...image,image_uuid:'bad',file_path:'/s/bad.png',valid:false,error_code:'bad_image'};
 const api={library:{images:async()=>{if(fallback)throw Object.assign(new Error('no index'),{status:409});return {items:[image,invalid]};}},dataset:{getImages:async()=>({items:[{file_path:'/s/a.png',file_name:'a.png'}]})}};
 const file=path.resolve(__dirname,'ImageSearchSelect.tsx'),m=new Module(file,module);m.filename=file;m.paths=Module._nodeModulePaths(path.dirname(file));const requireOriginal=m.require.bind(m);m.require=ref=>ref==='react'?react:ref==='react/jsx-runtime'?{jsx,jsxs:jsx}:ref==='../../services/api'?{api}:requireOriginal(ref);m._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText,file);
 const originalWindow=global.window;global.window={setTimeout:fn=>{timers.push(fn);return timers.length;},clearTimeout:()=>{}};
 const props={label:'operator',value,onChange:path=>paths.push(path),folder:'/s',autoSelectFirst:false,...(identity?{onIdentityChange:row=>identities.push(row),onLegacyChange:path=>legacyChoices.push(path)}:{})};
 const nodes=tree=>!tree||typeof tree!=='object'?[]:[tree,...[tree.props.children].flat(Infinity).flatMap(nodes)];
 return {props,paths,identities,legacyChoices,image,render:()=>{cursor=0;const tree=m.exports.ImageSearchSelect(props);effects.splice(0).forEach(fn=>fn());return tree;},nodes,run:async()=>{timers.splice(0).forEach(fn=>fn());await settle();},close:()=>{if(originalWindow===undefined)delete global.window;else global.window=originalWindow;}};
}
test('operator receives full selected identity, explicit empty callback and invalid option stays blocked',async()=>{const f=fixture({identity:true});try{f.render();await f.run();let tree=f.render();const select=f.nodes(tree).find(n=>n.type==='select');select.props.onChange({target:{value:'/s/a.png'}});assert.equal(f.identities[0].image_uuid,'a');assert.equal(f.identities[0].sha256,'a'.repeat(64));assert.deepEqual(f.paths,[]);select.props.onChange({target:{value:''}});assert.equal(f.identities[1],null);assert.equal(f.nodes(tree).find(n=>n.type==='option'&&n.props.value==='/s/bad.png').props.disabled,true);}finally{f.close();}});
test('existing consumers keep path callbacks and automatic first valid selection',async()=>{const f=fixture();try{f.props.autoSelectFirst=true;f.render();await f.run();assert.deepEqual(f.paths,['/s/a.png']);const select=f.nodes(f.render()).find(n=>n.type==='select');select.props.onChange({target:{value:'/s/bad.png'}});assert.deepEqual(f.paths,['/s/a.png','/s/bad.png']);assert.deepEqual(f.identities,[]);}finally{f.close();}});
test('legacy operator choice remains visible outside the listing and uses explicit path callback',async()=>{const f=fixture({fallback:true,identity:true,value:'/s/old.png'});try{f.render();await f.run();const tree=f.render();assert.ok(f.nodes(tree).find(n=>n.type==='option'&&n.props.value==='/s/old.png'));f.nodes(tree).find(n=>n.type==='select').props.onChange({target:{value:'/s/a.png'}});assert.deepEqual(f.legacyChoices,['/s/a.png']);assert.deepEqual(f.paths,[]);assert.deepEqual(f.identities,[]);}finally{f.close();}});
test('explicit same-path reselect delivers the current listed UUID and content digest',async()=>{const f=fixture({identity:true,value:'/s/a.png'});try{f.image.image_uuid='current-a';f.image.sha256='b'.repeat(64);f.render();await f.run();const tree=f.render(),button=f.nodes(tree).find(n=>n.type==='button'&&n.props.children==='현재 이미지 다시 선택');assert.ok(button,'same-path explicit reselection must be possible');assert.equal(Boolean(button.props.disabled),false);button.props.onClick();assert.equal(f.identities[0].image_uuid,'current-a');assert.equal(f.identities[0].sha256,'b'.repeat(64));assert.equal(f.identities[0].file_path,'/s/a.png');assert.deepEqual(f.paths,[]);f.props.disabled=true;assert.equal(f.nodes(f.render()).find(n=>n.type==='button').props.disabled,true);}finally{f.close();}});
test('same-path reselect is only offered for identity consumers with a valid hashed current page image',async()=>{for(const options of [{value:'/s/a.png'},{identity:true,value:'/s/absent.png'},{identity:true,value:'/s/bad.png'},{identity:true,value:'/s/a.png',unhashed:true},{fallback:true,identity:true,value:'/s/a.png'}]){const f=fixture(options);try{if(options.unhashed)f.image.sha256=null;f.render();await f.run();assert.ok(!f.nodes(f.render()).some(n=>n.type==='button'&&n.props.children==='현재 이미지 다시 선택'));}finally{f.close();}}});
