const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),ts=require('typescript');
const settle=()=>new Promise(setImmediate);
function fixture(){
 let cursor=0,epoch=0,scope={key:'source-A'};const slots=[],effects=[],requests=[];
 const react={useState:initial=>{const i=cursor++;if(!(i in slots))slots[i]=typeof initial==='function'?initial():initial;return [slots[i],v=>slots[i]=typeof v==='function'?v(slots[i]):v];},useRef:initial=>{const i=cursor++;return slots[i]??(slots[i]={current:initial});},useSyncExternalStore:(_s,snapshot)=>{cursor++;return snapshot();},useEffect:(fn,deps)=>{const i=cursor++;if(!slots[i]||deps.some((v,j)=>v!==slots[i].deps[j])){slots[i]?.cleanup?.();slots[i]={deps};effects.push(()=>slots[i].cleanup=fn());}}};
 const jsx=(type,props)=>({type,props:props||{}}),project={id:'project',source_dataset_dir:'/source',active_labelset_id:'default',task:'classification'},pstore={project,projectDir:'/project',language:'ko'};
 const mocks={react,'react/jsx-runtime':{jsx,jsxs:jsx},'react-dom':{createPortal:x=>x},'lucide-react':new Proxy({},{get:()=>()=>null}),'../../stores/useDatasetStore':{useDatasetStore:s=>s({images:[{file_path:'/source/part.png',file_name:'part.png'}]})},'../../stores/useAnnotationStore':{useAnnotationStore:s=>s({currentImage:null})},'../../stores/useProjectStore':{useProjectStore:s=>s(pstore)},'../../services/api':{request:()=>new Promise((resolve,reject)=>requests.push({resolve,reject})),getProjectContextGeneration:()=>epoch,subscribeProjectContext:()=>()=>{}},'../runtime/useDeliveryScope':{useDeliveryScope:()=>({scope:{get current(){return scope;}},key:scope.key,project,projectDir:'/project'})},'./ImageSearchSelect':{ImageSearchSelect:()=>null},'./WorkflowImpactPanel':{WorkflowImpactPanel:()=>null}};
 const filename=path.resolve(__dirname,'ProvenancePanel.tsx'),m=new Module(filename,module);m.filename=filename;m.paths=Module._nodeModulePaths(path.dirname(filename));const original=m.require.bind(m);m.require=r=>mocks[r]??original(r);m._compile(ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX}}).outputText,filename);
 const oldWindow=global.window,oldDocument=global.document;global.window={addEventListener(){},removeEventListener(){}};global.document={body:{}};
 const record=name=>({project:{name,id:'project',active_labelset_id:'default'},image:{image_uuid:'image',content_hash:'a'.repeat(64),content_version:1},label:{sha256:'b'.repeat(64),revision:1,workflow_state:'approved',history:[]},split:{assignment:'train'},review_binding:{image_eligible:true,eligible_count:1,book_version:1,policy_revision:1,review_revision:1},dataset_versions:[],models:[],flows:[],inspections:[]});
 return {requests,record,render(){cursor=0;const tree=m.exports.ProvenancePanel({onClose(){}});effects.splice(0).forEach(fn=>fn());return tree;},sourceChange(){scope={key:'source-B'};},actorChange(){epoch++;},close(){global.window=oldWindow;global.document=oldDocument;}};
}
function text(n){if(Array.isArray(n))return n.map(text).join(' ');if(n==null||typeof n==='boolean')return '';if(typeof n!=='object')return String(n);return text(n.props?.children);}
for(const change of ['sourceChange','actorChange'])test(`provenance refuses old data on ${change} with the same project ID`,async()=>{
 const f=fixture();try{f.render();f.requests[0].resolve(f.record('OLD SOURCE'));await settle();assert.match(text(f.render()),/OLD SOURCE/);f[change]();assert.doesNotMatch(text(f.render()),/OLD SOURCE/);assert.equal(f.requests.length,2);f.requests[1].resolve(f.record('CURRENT SOURCE'));await settle();assert.match(text(f.render()),/CURRENT SOURCE/);}finally{f.close();}
});
test('provenance ignores a late response after the transport namespace changes',async()=>{
 const f=fixture();try{f.render();f.actorChange();f.render();assert.equal(f.requests.length,2);f.requests[1].resolve(f.record('CURRENT SOURCE'));await settle();f.requests[0].resolve(f.record('LATE SOURCE'));await settle();assert.match(text(f.render()),/CURRENT SOURCE/);assert.doesNotMatch(text(f.render()),/LATE SOURCE/);}finally{f.close();}
});
