const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),ts=require('typescript');
function load(){const file=path.join(__dirname,'browserSession.ts'),m=new Module(file,module);m.filename=file;m.paths=Module._nodeModulePaths(__dirname);m._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,file);return m.exports;}
const value={expires_at:2000000000,user:{id:'actor1',username:'viewer',administrator:false},csrf_token:'test_csrf_value_abcdefghijklmnopqrstuvwxyz'};
function fixture(){const calls=[];const session=new (load().BrowserSession)({origin:()=> 'https://studio.test',now:()=>1700000000,fetch:async(url,options)=>{calls.push({url,options});return new Response(JSON.stringify(value),{status:200,headers:{'Content-Type':'application/json'}});}});return {session,calls};}
test('browser host refuses other origins, credentials, paths and insecure addresses before sending a password',async()=>{const {session,calls}=fixture();for(const url of ['https://other.test','http://studio.test','https://fixture-user@studio.test','https://:fixture-password@studio.test','https://studio.test/api','https://studio.test?x=1','https://studio.test#x'])await assert.rejects(session.login({server_url:url,username:'viewer',password:'fixture password'}));assert.equal(calls.length,0);});
test('cookie login keeps bearer/password out of connection and supplies CSRF only to exact-origin API mutations',async()=>{const {session,calls}=fixture();const connection=await session.login({server_url:'https://studio.test/',username:'viewer',password:'fixture password'});assert.deepEqual(connection,{server_url:'https://studio.test',expires_at:value.expires_at,user:value.user});assert.equal(JSON.parse(calls[0].options.body).transport,'cookie');assert.equal(calls[0].options.credentials,'same-origin');assert.equal(calls[0].options.redirect,'error');assert.deepEqual(session.requestOptions('https://studio.test/api/project/create','POST'),{credentials:'same-origin',headers:{'X-Vision-CSRF':value.csrf_token}});assert.deepEqual(session.requestOptions('https://studio.test/api/project/current','GET'),{credentials:'same-origin',headers:{}});for(const url of ['https://other.test/api/project/create','https://studio.test.evil/api/project/create','https://studio.test/assets/file'])assert.deepEqual(session.requestOptions(url,'POST'),{});assert(!JSON.stringify(connection).includes('csrf'));assert(!JSON.stringify(connection).includes('password'));});
test('project selection returns isolated public values and logout retires memory',async()=>{const {session,calls}=fixture();await session.login({server_url:'https://studio.test',username:'viewer',password:'fixture password'});assert.equal(session.select('project1').project_id,'project1');const copy=session.connection();copy.user.id='tampered';assert.equal(session.connection().user.id,'actor1');await assert.rejects(async()=>session.select('../foreign'));await session.disconnect();assert.equal(session.connection(),null);assert.equal(calls[1].options.headers['X-Vision-CSRF'],value.csrf_token);assert.deepEqual(session.requestOptions('https://studio.test/api/project/create','POST'),{});});
test('clock advancement expires memory and cannot supply stale project or CSRF authority',async()=>{let now=1700000000;const session=new (load().BrowserSession)({origin:()=> 'https://studio.test',now:()=>now,fetch:async()=>new Response(JSON.stringify(value),{status:200})});await session.login({server_url:'https://studio.test',username:'viewer',password:'fixture password'});session.select('project1');now=value.expires_at;assert.equal(session.connection(),null);assert.deepEqual(session.requestOptions('https://studio.test/api/project/create','POST'),{});assert.throws(()=>session.select('project1'));});
test('expired, token-leaking and malformed server sessions are never adopted',async()=>{for(const response of [{...value,expires_at:1},{...value,token:'should stay HttpOnly'},{...value,csrf_token:''},{...value,user:{id:'',username:'viewer'}},{...value,expires_at:NaN}]){const session=new (load().BrowserSession)({origin:()=> 'https://studio.test',now:()=>1700000000,fetch:async()=>new Response(JSON.stringify(response),{status:200})});await assert.rejects(session.login({server_url:'https://studio.test',username:'viewer',password:'fixture password'}));assert.equal(session.connection(),null);}});
test('a login answer arriving after disconnect cannot restore the retired session',async()=>{let answer;const session=new (load().BrowserSession)({origin:()=> 'https://studio.test',now:()=>1700000000,fetch:()=>new Promise(resolve=>answer=resolve)});const pending=session.login({server_url:'https://studio.test',username:'viewer',password:'fixture password'});await session.disconnect();answer(new Response(JSON.stringify(value),{status:200}));await assert.rejects(pending,/바뀌/);assert.equal(session.connection(),null);});
