import {request} from './api';
export type SavedPackage={package_id:string;name:string;package_path:string;integrity:string;scope_matches:boolean;manifest_sha256?:string;pipeline_id?:string;version_id?:string;recipe_task?:string;created_at?:string;error?:string;approval_present?:boolean;runtime?:{device?:string};models?:Array<{job_id:string;task:string}>;parity:{status:string;device?:string;execution_target?:'local'|'selected_compute';compute_profile_id?:string|null;compute_profile_name?:string;compute_gpu_selector?:string|null};optimization_jobs:Array<{job_id:string;status:string}>};
export type PackageLibrary={packages:SavedPackage[];selected_package_id:string|null;scope:{project_id:string;source_dataset_path:string|null;task:string}};
export type HardwareState={device:string;kind:string;configured:boolean;live_verified:boolean;approved:boolean;evidence:Array<{observed_at:number;manifest_sha256:string;image_sha256:string;verdict:string}>};
export type RuntimePack={id:string;version:string;inventory_sha256:string;kind?:string;integrity:'verified'|'failed';installed:boolean;activated:false;signature_verified:false;execution_verified:false;target_compatible:boolean;compatibility_error?:string|null;error?:string;total_bytes?:number;estimated_staging_bytes?:number;source?:string;license?:string;driver_minimum?:string|null;observed_driver?:string|null;installation_relative_path:string;python_abi:{state:string;compatible:boolean;wheel_count:number}};
export type RuntimePackInventory={project_id:string;target:{platform:string;arch:string;python:string;python_abi:string|null;compatibility:{worker:number;runtime:number}};packs:RuntimePack[];activation_supported:false};
export type InstallationState={app_version:string|null;version_source:string;host:{os:string;architecture:string;python:string};project:{schema_version:number;compatible:boolean;migration_performed:boolean};runtime_dependencies:Record<string,boolean>;python_supported:boolean;sdk:Record<string,{ready:boolean;requires_embedded_python?:boolean;compiler_available?:boolean;python_headers_available?:boolean;dotnet_available?:boolean}>;install:{native_autostart_supported:boolean;signing_verified:boolean};update:{automatic_update_available:boolean;actions:string[]}};
export type MigrationPreview={compatible:boolean;schema_version:number|null;current_schema_version:1;migration_required:boolean;manifest_sha256:string;status:string;backup_relative_path?:string;can_apply?:boolean;blockers?:string[];source_snapshot?:{sha256:string};inventory?:{file_count:number;byte_count:number};receipt?:{migration_id:string;status:string};transactions?:Array<{migration_id:string;status:string;can_restore:boolean;backup_file_count:number;backup_sha256:string}>};
export const productDeliveryApi={
 packages:()=>request<PackageLibrary>('/api/product-delivery/packages'),
 select:(id:string)=>request<SavedPackage>(`/api/product-delivery/packages/${encodeURIComponent(id)}/select`,{method:'POST'}),
 verify:(id:string,image_path:string,device:string)=>request<{result:Record<string,unknown>;evidence:Record<string,unknown>}>(`/api/product-delivery/packages/${encodeURIComponent(id)}/verify`,{method:'POST',body:JSON.stringify({image_path,device})}),
 preflight:(id:string,image_path:string)=>request<{ready:boolean;training_started:false;probe:{checks?:Record<string,unknown>;message?:string};input?:{width:number;height:number;local_sha256:string;remote_sha256:string;execution:string};observed_at:number}>(`/api/product-delivery/servers/${encodeURIComponent(id)}/preflight`,{method:'POST',body:JSON.stringify({image_path})}),
 protocol:(protocol:'http'|'modbus',mode:'success'|'reject'|'timeout')=>request<{acknowledged:boolean;error?:string;scope:string;physical_equipment_verified:false}>('/api/product-delivery/protocol-test',{method:'POST',body:JSON.stringify({protocol,mode})}),
 installation:()=>request<InstallationState>('/api/product-delivery/installation'),
 runtimePacks:()=>request<RuntimePackInventory>('/api/product-delivery/runtime-packs'),
 installRuntimePack:(body:{source_dir:string;inventory_path:string;expected_sha256:string})=>request<RuntimePack>('/api/product-delivery/runtime-packs/install',{method:'POST',body:JSON.stringify(body)}),
 previewMigration:(project_dir:string)=>request<MigrationPreview>('/api/project/compatibility/preview',{method:'POST',body:JSON.stringify({project_dir})}),
 applyMigration:(project_dir:string,expected_manifest_sha256:string,expected_source_sha256?:string)=>request<MigrationPreview>('/api/project/compatibility/apply',{method:'POST',body:JSON.stringify({project_dir,expected_manifest_sha256,expected_source_sha256})}),
 recoverMigration:(project_dir:string,migration_id:string,action:"restore"|"finish")=>request<MigrationPreview>("/api/project/compatibility/recover",{method:"POST",body:JSON.stringify({project_dir,migration_id,action})}),
 globalMigration:()=>request<{status:string;can_apply:false;inventory:{file_count:number;byte_count:number};blockers:string[];ownership_policy:string}>("/api/project/compatibility/global-preview",{method:"POST"}),
 hardware:()=>request<{devices:HardwareState[]}>('/api/product-delivery/hardware'),
 diagnostics:(sections:Array<'installation'|'packages'|'hardware'|'operator_errors'>=['installation','packages','hardware','operator_errors'])=>request<{filename:string;bundle:Record<string,unknown>;redacted:true}>('/api/product-delivery/diagnostics',{method:'POST',body:JSON.stringify({sections})}),
};
