const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),ts=require('typescript');
function harness(outcome){
 let cursor=0,context={workspace_id:'w',project_id:'p',actor_id:'a',mode:'team'},transport='server';const slots=[],calls=[],results=[],closed=[];
 const project={project:{id:'p',source_dataset_dir:'/source',active_labelset_id:'default'},projectDir:'/p',task:'classification',isProjectBusy:false,updateTask:async value=>{calls.push(value);return typeof outcome==='function'?await outcome():outcome;}};
 const data={isLoading:false,isSplitting:false,totalImages:10,split:{train:6,val:2,test:2}},annotation={isDirty:false},flow={pipelineDirty:false};
 const store=value=>Object.assign(selector=>selector?selector(value):value,{getState:()=>value});
 const jsx=(type,props)=>({type,props:props||{}}),Dialog=()=>null,Action=()=>null;
 const filename=path.join(__dirname,'TaskChangeImpactDialog.tsx'),m=new Module(filename,module);
 const mocks={react:{useState:initial=>{const i=cursor++;if(!(i in slots))slots[i]=typeof initial==='function'?initial():initial;return [slots[i],v=>slots[i]=typeof v==='function'?v(slots[i]):v];},useEffect(){},useRef:value=>{const i=cursor++;return slots[i]??(slots[i]={current:value});}},'react/jsx-runtime':{jsx,jsxs:jsx},'../../services/api':{getProjectContext:()=>context,getApiPersistenceIdentity:()=>transport,subscribeProjectContext:()=>()=>{}},'../../stores/useProjectStore':{useProjectStore:store(project),taskChangeScope:p=>JSON.stringify([p.project.id,p.projectDir])},'../../stores/useDatasetStore':{useDatasetStore:store(data)},'../../stores/useAnnotationStore':{useAnnotationStore:store(annotation)},'../../stores/useFlowchartStore':{useFlowchartStore:store(flow)},'../common/WorkspaceDialog':{WorkspaceDialog:Dialog},'../common/AsyncAction':{AsyncAction:Action}};
 m.require=name=>mocks[name];m._compile(ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText,filename);
 const scope=m.exports.taskPreviewScope(),render=()=>{cursor=0;return m.exports.TaskChangeImpactDialog({scope,nextTask:'segmentation',onClose:()=>closed.push(true),onResult:result=>results.push(result)});};
 const nodes=n=>!n||typeof n!=='object'?[]:[n,...[n.props?.children].flat(Infinity).flatMap(nodes)];
 const action=label=>nodes(render()).find(n=>n.type===Action&&n.props.children===label);
 return {project,data,annotation,flow,calls,results,closed,confirm:()=>action('영향 확인 후 변경').props.onClick(),cancel:()=>action('취소').props.onClick(),blocker:()=>m.exports.taskPreviewBlocker(scope),changeContext:()=>{context={...context,actor_id:'b'};},changeTransport:()=>transport='other'};
}
test('cancel has no task mutation',()=>{const h=harness({ok:true,task:'segmentation'});h.cancel();assert.deepEqual(h.calls,[]);assert.equal(h.closed.length,1);});
for(const field of ['project','data','annotation','flow'])test(`confirmation rechecks live ${field} busy/dirty state`,async()=>{const h=harness({ok:true,task:'segmentation'});if(field==='project')h.project.isProjectBusy=true;if(field==='data')h.data.isSplitting=true;if(field==='annotation')h.annotation.isDirty=true;if(field==='flow')h.flow.pipelineDirty=true;assert.ok(h.blocker());await h.confirm();assert.deepEqual(h.calls,[]);});
for(const change of ['changeContext','changeTransport'])test(`confirmation rejects stale ${change}`,async()=>{const h=harness({ok:true,task:'segmentation'});h[change]();await h.confirm();assert.deepEqual(h.calls,[]);});
test('successful confirmation uses existing atomic outcome once',async()=>{const value={ok:true,task:'segmentation',changed:true};const h=harness(value);await h.confirm();assert.deepEqual(h.calls,['segmentation']);assert.deepEqual(h.results,[value]);});
for(const applied of [false,true])test(`refused outcome remains a refusal (applied=${applied})`,async()=>{const value={ok:false,task:applied?'segmentation':'classification',applied,error:'Import refused'},h=harness(value);await h.confirm();assert.deepEqual(h.results,[value]);});
test('duplicate confirmation and late response after scope change are suppressed',async()=>{let finish;const promise=new Promise(r=>finish=r),h=harness(()=>promise);const first=h.confirm();await h.confirm();assert.equal(h.calls.length,1);h.changeContext();finish({ok:true,task:'segmentation'});await first;assert.deepEqual(h.results,[]);});
