const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),ts=require('typescript');
function load(){const filename=path.join(__dirname,'workflowReadiness.ts');assert.ok(fs.existsSync(filename),'production readiness contract must exist');const m=new Module(filename,module);m._compile(ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,filename);return m.exports;}
const base={stage:1,projectReady:true,sourceReady:true,totalImages:12,train:8,val:4,busy:false,task:'classification',modelJobId:null,flowVersionId:null,flowDirty:false,evidence:{status:'ready',review:{ready:true,counts:{eligible:12}},impact:{models:[],model_evaluations:[],flows:[],flow_evaluations:[],approvals:[],packages:[]}}};
test('each stage has completed/missing inputs and exactly one recommended action',()=>{const {getNextAction}=load();for(let stage=1;stage<=6;stage++){const r=getNextAction({...base,stage,sourceReady:false,totalImages:0});assert.ok(r.missingInputs.length);assert.ok(Array.isArray(r.completedInputs));assert.equal(typeof r.nextAction.label,'string');assert.ok(r.nextAction.step>=1&&r.nextAction.step<=6);}});
test('a retained evaluation job does not count as a current model',()=>{const {getNextAction}=load();const r=getNextAction({...base,stage:4,modelJobId:'old'});assert.notEqual(r.status,'ready');assert.equal(r.nextAction.step,3);});
test('current model needs matched checkpoint and data evidence',()=>{const {getNextAction}=load();for(const state of ['changed','unverified','different_source'])assert.notEqual(getNextAction({...base,stage:4,modelJobId:'m',evidence:{...base.evidence,impact:{...base.evidence.impact,models:[{job_id:'m',task:'classification',checkpoint_state:'current',data_state:state,scope_matches:true}]}}}).status,'ready');});
test('empty reports never imply evaluated/approved/deployed readiness',()=>{const {getNextAction}=load();for(const stage of [4,5,6])assert.notEqual(getNextAction({...base,stage}).status,'ready');});
test('checking and failed evidence remain unknown with retry action',()=>{const {getNextAction}=load();for(const status of ['checking','error']){const r=getNextAction({...base,stage:4,evidence:{status,error:'offline'}});assert.equal(r.status,status==='checking'?'checking':'unknown');assert.equal(r.nextAction.kind,'refresh');}});
test('matching saved flow evidence is useful but never deployment authorization',()=>{const {getNextAction}=load();const r=getNextAction({...base,stage:6,flowVersionId:'v',evidence:{...base.evidence,impact:{...base.evidence.impact,flows:[{version_id:'v',state:'current',scope_matches:true}],approvals:[{revision_id:'r',state:'unverified'}],packages:[]}}});assert.notEqual(r.status,'ready');assert.ok(r.missingInputs.length);});
test('a verified active version cannot make a different displayed graph ready',()=>{const {getNextAction}=load();const r=getNextAction({...base,stage:5,flowVersionId:'active-a',flowMatchesSaved:false,evidence:{...base.evidence,impact:{...base.evidence.impact,flows:[{version_id:'active-a',state:'current',scope_matches:true}]}}});assert.notEqual(r.status,'ready');assert.equal(r.nextAction.step,5);});

async function hookFixture({wrongProject=false}={}){
 const filename=path.join(__dirname,'useWorkflowReadiness.ts'),m=new Module(filename,module),slots=[],effects=[],calls=[];let cursor=0;
 const context={workspace_id:'w',project_id:'p',actor_id:'a',mode:'local'};
 const project={project:{id:'p',source_dataset_dir:'/data',active_labelset_id:'default'},projectDir:'/p',task:'classification',activeStep:5,isProjectBusy:false};
 const data={folderPath:'/data',datasetKey:'/data\0classification',totalImages:10,split:{train:6,val:2,test:2},isLoading:false,isSplitting:false};
 const displayed={id:'graph',nodes:[{id:'rule',data:{threshold:0.8}}],edges:[]},saved={...displayed,nodes:[{id:'rule',data:{threshold:0.2}}]};
 const flow={pipeline:displayed,pipelineDirty:false,flowIdentity:{semantic_revision:0}};
 const store=value=>selector=>selector?selector(value):value;
 const mocks={react:{useEffect:fn=>effects.push(fn),useState:initial=>{const i=cursor++;if(!(i in slots))slots[i]=typeof initial==='function'?initial():initial;return[slots[i],v=>slots[i]=typeof v==='function'?v(slots[i]):v];},useRef:value=>{const i=cursor++;return slots[i]??(slots[i]={current:value});}},
 '../../services/api':{getProjectContext:()=>context,getApiPersistenceIdentity:()=>null,subscribeProjectContext:()=>()=>{},request:async endpoint=>endpoint.includes('team-data')?{ready:true,counts:{eligible:10}}:{project_id:wrongProject?'other':'p',source_dataset_path:'/data',labelset_id:'default',models:[],model_evaluations:[],flows:[{version_id:'a',scope_matches:true,state:'current'}],approvals:[],packages:[]},api:{flowchart:{listPipelines:async()=>({pipelines:[{version_id:'a',is_active:true}]}),getPipelineVersion:async id=>{calls.push(id);return saved;}}}},
 '../../stores/useProjectStore':{useProjectStore:store(project)},'../../stores/useComputeStore':{useComputeStore:store({transportRevision:0})},'../../stores/useDatasetStore':{useDatasetStore:store(data)},'../../stores/useTrainingStore':{useTrainingStore:store({status:'idle'})},'../../stores/useEvaluationStore':{useEvaluationStore:store({jobId:null})},'../../stores/useAnnotationStore':{useAnnotationStore:store({isDirty:false,metadata:null})},'../../stores/useFlowchartStore':{useFlowchartStore:store(flow),flowSemanticKey:value=>JSON.stringify(value)},'./workflowReadiness':load()};
 m.require=name=>mocks[name];m._compile(ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,filename);
 m.exports.useWorkflowReadiness();effects.forEach(fn=>fn());await new Promise(resolve=>setImmediate(resolve));cursor=0;const result=m.exports.useWorkflowReadiness();return{...result,calls};
}
test('production readiness hook reads the active saved graph before claiming displayed rules match',async()=>{const result=await hookFixture();assert.deepEqual(result.calls,['a']);assert.equal(result.readiness.status,'blocked');assert.match(result.readiness.missingInputs.join(' '),/규칙이 다릅니다/);});
test('production readiness hook rejects evidence from a different project',async()=>{const result=await hookFixture({wrongProject:true});assert.equal(result.readiness.status,'unknown');assert.match(result.readiness.missingInputs.join(' '),/현재 입력과 다릅니다/);assert.deepEqual(result.calls,[]);});
