const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const Module=require('node:module');const ts=require('typescript');
const tick=()=>new Promise(resolve=>setImmediate(resolve));
const helperFilename=path.resolve(__dirname,'flowWorkspace.ts');const helper=new Module(helperFilename,module);helper.paths=Module._nodeModulePaths(__dirname);helper._compile(ts.transpileModule(fs.readFileSync(helperFilename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,helperFilename);
function nodes(tree){if(!tree||typeof tree!=='object')return [];return [tree,...[].concat(tree.props?.children||[]).flatMap(nodes)];}
function renderPanel(options={}){const context={project:{id:'project',project_dir:'/project',active_labelset_id:'labels'},folderPath:'/fixture',task:'segmentation',transportRevision:options.epoch||0,selectedProfileId:'profile',generation:0};const values=[options.template?[options.template]:[],options.template?.template_id||'','Fixture flow',[],{}, {},[],['/fixture/input.png'],'a','b','local','cpu',null,[],null,false,'',''];let cursor=0;let complete;let sent;const effects=[];const changes=[];const flowState={pipeline:{id:'original',nodes:[],edges:[]},isRunning:false,replacePipeline:value=>changes.push(value)};const flowStore=()=>flowState;flowStore.getState=()=>flowState;
  const react={createElement:(type,props,...children)=>({type,props:{...props,children}}),useEffect:callback=>{effects.push(callback);},useState:initial=>{const index=cursor++;if(values[index]===undefined)values[index]=initial;return [values[index],value=>{values[index]=typeof value==='function'?value(values[index]):value;}];}};
  const projectStore=selector=>selector(context);projectStore.getState=()=>context;const datasetStore=selector=>selector(context);datasetStore.getState=()=>context;const computeStore=selector=>selector(context);computeStore.getState=()=>context;
  const filename=path.resolve(__dirname,'FlowWorkspacePanel.tsx');const m=new Module(filename,module);m.filename=filename;m.paths=Module._nodeModulePaths(__dirname);const orig=m.require.bind(m);const mocks={
    react:{__esModule:true,default:react,...react},
    '../../services/api':{api:{dataset:{getImages:async()=>({items:[{file_path:'/fixture/one.png',file_name:'one'},{file_path:'/fixture/two.png',file_name:'two'}]})}},getProjectContextGeneration:()=>context.generation,getApiPersistenceIdentity:()=>options.apiIdentity||'shared:https://server-a',resolveApiUrl:value=>value,request:async(endpoint,requestOptions)=>{if(!requestOptions)return endpoint.endsWith('templates')?{templates:[]}:{comparisons:[]};sent=JSON.parse(requestOptions.body);return new Promise(resolve=>{complete=resolve;});}},
    '../../stores/useProjectStore':{useProjectStore:projectStore},'../../stores/useDatasetStore':{useDatasetStore:datasetStore},'../../stores/useComputeStore':{useComputeStore:computeStore},
    '../../stores/useFlowchartStore':{useFlowchartStore:flowStore},'./flowWorkspace':helper.exports,'./modelFlowHandoff':{compatibleModelNode:()=>true,modelScoreBinding:model=>({model_job_id:model.job_id,threshold:model.score_spec?.threshold??.5,score_spec:model.score_spec})},
  };m.require=name=>name in mocks?mocks[name]:orig(name);m._compile(ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText,filename);
  function render(){cursor=0;effects.length=0;return m.exports.FlowWorkspacePanel({versions:[],models:[],onOpenImage:()=>{}});}
  const tree=render();const button=nodes(tree).find(n=>n.type==='button'&&[].concat(n.props.children||[]).some(c=>typeof c==='string'&&c.includes('비교 실행')));
  return {context,values,changes,flowState,render,apply:()=>nodes(render()).find(n=>n.type==='button'&&n.props.children==='모델·클래스 매핑 후 초안으로 열기').props.onClick(),start:()=>button.props.onClick(),sent:()=>sent,complete:value=>complete(value||{comparison_id:'cmp',device:'cpu',rows:[]}),load:async()=>{effects[0]();await tick();},saveSelections:()=>{const tree=render();for(const node of nodes(tree).filter(n=>n.type==='input'&&n.props.type==='checkbox'))node.props.onChange({target:{checked:true}});render();effects[1]();}};
}
test('A/B result attributes CPU execution to the connected backend, including shared transport',async()=>{const panel=renderPanel();panel.start();await tick();assert.equal(panel.sent().device,'cpu');panel.complete();await tick();assert.match(panel.values[17],/백엔드.*CPU/i);assert.doesNotMatch(panel.values[17],/이 컴퓨터 CPU/);assert.equal(panel.values[14].comparison_id,'cmp');});
test('A/B response from a previous transport cannot publish its result or execution-location notice',async()=>{const panel=renderPanel();panel.start();await tick();panel.context.transportRevision=1;panel.complete();await tick();assert.equal(panel.values[14],null);assert.equal(panel.values[17],'');});
test('two fixed test images restore in the real panel after the same shared API/profile reopens with a different epoch',async()=>{const storage=new Map();global.localStorage={getItem:key=>storage.get(key)||null,setItem:(key,value)=>storage.set(key,value)};const first=renderPanel({epoch:7});await first.load();first.saveSelections();const reopened=renderPanel({epoch:0});await reopened.load();assert.deepEqual(reopened.values[7],['/fixture/one.png','/fixture/two.png']);delete global.localStorage;});
test('the real panel isolates identical project paths and IDs on different API servers',async()=>{const storage=new Map();global.localStorage={getItem:key=>storage.get(key)||null,setItem:(key,value)=>storage.set(key,value)};const first=renderPanel({apiIdentity:'shared:https://server-a'});await first.load();first.saveSelections();const other=renderPanel({apiIdentity:'shared:https://server-b'});await other.load();assert.deepEqual(other.values[7],[]);delete global.localStorage;});
const template={template_id:'template',name:'Whole graph',kind:'flow',pipeline:{nodes:[],edges:[]},models:[],classes:{names:[],ids:[]},ports:{inputs:[],outputs:[]}};
test('a clean whole-flow template still requires explicit replacement confirmation',async()=>{const previous=global.window;let asked=0;global.window={confirm:()=>{asked++;return false;}};try{const panel=renderPanel({template});await panel.apply();assert.equal(asked,1);assert.equal(panel.sent(),undefined);assert.deepEqual(panel.changes,[]);}finally{global.window=previous;}});
for(const scenario of ['current','edited graph','namespace ABA','busy'])test(`mapped template adoption respects ${scenario}`,async()=>{const previous=global.window;global.window={confirm:()=>true};try{const panel=renderPanel({template}),pending=panel.apply();await tick();if(scenario==='edited graph')panel.flowState.pipeline={id:'newer',nodes:[],edges:[]};if(scenario==='namespace ABA')panel.context.generation+=2;if(scenario==='busy')panel.flowState.isRunning=true;panel.complete({kind:'flow',pipeline:{id:'mapped',nodes:[],edges:[]},ports:template.ports});await pending;assert.equal(panel.changes.length,scenario==='current'?1:0);const alert=nodes(panel.render()).find(n=>n.props?.role==='alert');if(['edited graph','busy'].includes(scenario))assert.match(String(alert?.props.children),/그래프가 바뀌었거나 실행 중/,'a dropped apply is said, not silent');else assert.equal(alert,undefined,'no message for the current apply or another project');}finally{global.window=previous;}});
const subgraph={template_id:'module',name:'ROI check module',kind:'subgraph',pipeline:{nodes:[],edges:[]},models:[],classes:{names:[],ids:[]},ports:{inputs:[],outputs:[]}};
test('a partial template is inserted into the current graph without whole-flow confirmation',async()=>{const previous=global.window;let asked=0;global.window={confirm:()=>{asked++;return true;}};try{
 const panel=renderPanel({template:subgraph}),pending=panel.apply();await tick();
 panel.complete({kind:'subgraph',pipeline:{id:'module',nodes:[{id:'check',position:{x:0,y:0},data:{node_type:'inspection',label:'Inserted check',task:'segmentation'}}],edges:[]},ports:subgraph.ports});await pending;
 assert.equal(asked,0,'insertion keeps the current graph, so it needs no replacement confirmation');assert.equal(panel.changes.length,1);
 const inserted=panel.changes[0];assert.ok(inserted.nodes.some(n=>n.data.label==='Inserted check'&&n.id.endsWith(':check')),'the module is added beside the existing nodes');}finally{global.window=previous;}});
