const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const Module=require('node:module');const ts=require('typescript');
const tick=()=>new Promise(resolve=>setImmediate(resolve));
const helperFilename=path.resolve(__dirname,'flowWorkspace.ts');const helper=new Module(helperFilename,module);helper.paths=Module._nodeModulePaths(__dirname);helper._compile(ts.transpileModule(fs.readFileSync(helperFilename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,helperFilename);
const testSetFilename=path.resolve(__dirname,'flowTestSet.ts');const testSetHelper=new Module(testSetFilename,module);testSetHelper.paths=Module._nodeModulePaths(__dirname);testSetHelper._compile(ts.transpileModule(fs.readFileSync(testSetFilename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,testSetFilename);
// State positions used below: 7 legacy path list, 14 comparison, 17 notice, 18 identity test set, 19 library availability.
const libraryImage=name=>({image_uuid:`uuid-${name}`,sha256:name.padEnd(64,'0').slice(0,64),relative_path:`${name}.png`,file_name:`${name}.png`,file_path:`/fixture/${name}.png`});
function nodes(tree){if(!tree||typeof tree!=='object')return [];return [tree,...[].concat(tree.props?.children||[]).flatMap(nodes)];}
function renderPanel(options={}){const context={project:{id:'project',project_dir:'/project',active_labelset_id:'labels'},folderPath:'/fixture',task:'segmentation',transportRevision:options.epoch||0,selectedProfileId:'profile',generation:0};const values=[options.template?[options.template]:[],options.template?.template_id||'','Fixture flow',[],{}, {},[],['/fixture/input.png'],'a','b','local','cpu',null,[],null,false,'',''];let cursor=0;let complete;let sent;const effects=[];const changes=[];const flowState={pipeline:{id:'original',nodes:[],edges:[]},isRunning:false,replacePipeline:value=>changes.push(value)};const flowStore=()=>flowState;flowStore.getState=()=>flowState;
  const react={createElement:(type,props,...children)=>({type,props:{...props,children}}),useEffect:callback=>{effects.push(callback);},useState:initial=>{const index=cursor++;if(values[index]===undefined)values[index]=initial;return [values[index],value=>{values[index]=typeof value==='function'?value(values[index]):value;}];}};
  const projectStore=selector=>selector(context);projectStore.getState=()=>context;const datasetStore=selector=>selector(context);datasetStore.getState=()=>context;const computeStore=selector=>selector(context);computeStore.getState=()=>context;
  const browserStub=()=>null;const resolve=async selections=>{if(options.noRevision)throw Object.assign(new Error('No validated dataset revision is active'),{status:409});
    if(options.failResolve)throw Object.assign(new Error('The server could not check the saved images'),{status:options.failResolve});
    return {revision_id:'r',active:true,results:selections.map(selection=>options.missing?.includes(selection.relative_path)?{...selection,status:'missing',current:null,candidates:[]}:options.changed?.includes(selection.relative_path)?{...selection,status:'changed',current:null,candidates:[]}:{...selection,status:'found',current:{...selection,valid:1,file_path:`/fixture/${selection.relative_path}`},candidates:[]})};};
  const filename=path.resolve(__dirname,'FlowWorkspacePanel.tsx');const m=new Module(filename,module);m.filename=filename;m.paths=Module._nodeModulePaths(__dirname);const orig=m.require.bind(m);const mocks={
    react:{__esModule:true,default:react,...react},
    '../common/ImageLibraryBrowser':{ImageLibraryBrowser:browserStub},'./flowTestSet':testSetHelper.exports,
    '../../services/api':{api:{library:{resolve},dataset:{getImages:async()=>{if(options.listingFails)throw new Error('The image listing failed');if(options.listingHeld)return new Promise(()=>{});return {items:[{file_path:'/fixture/one.png',file_name:'one'},{file_path:'/fixture/two.png',file_name:'two'}]};}}},getProjectContextGeneration:()=>context.generation,getApiPersistenceIdentity:()=>options.apiIdentity||'shared:https://server-a',resolveApiUrl:value=>value,request:async(endpoint,requestOptions)=>{if(!requestOptions)return endpoint.endsWith('templates')?{templates:[]}:{comparisons:[]};sent=JSON.parse(requestOptions.body);return new Promise(resolve=>{complete=resolve;});}},
    '../../stores/useProjectStore':{useProjectStore:projectStore},'../../stores/useDatasetStore':{useDatasetStore:datasetStore},'../../stores/useComputeStore':{useComputeStore:computeStore},
    '../../stores/useFlowchartStore':{useFlowchartStore:flowStore},'./flowWorkspace':helper.exports,'./modelFlowHandoff':{compatibleModelNode:()=>true,modelScoreBinding:model=>({model_job_id:model.job_id,threshold:model.score_spec?.threshold??.5,score_spec:model.score_spec})},
  };m.require=name=>name in mocks?mocks[name]:orig(name);m._compile(ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText,filename);
  function render(){cursor=0;effects.length=0;return m.exports.FlowWorkspacePanel({versions:[],models:[],onOpenImage:()=>{}});}
  const tree=render();const button=nodes(tree).find(n=>n.type==='button'&&[].concat(n.props.children||[]).some(c=>typeof c==='string'&&c.includes('비교 실행')));
  return {context,values,changes,flowState,render,apply:()=>nodes(render()).find(n=>n.type==='button'&&n.props.children==='모델·클래스 매핑 후 초안으로 열기').props.onClick(),start:()=>button.props.onClick(),sent:()=>sent,complete:value=>complete(value||{comparison_id:'cmp',device:'cpu',rows:[]}),load:async()=>{effects[0]();await tick();await tick();render();if(effects[2]){effects[2]();await tick();}render();},
    pick:names=>{for(const name of names){const browser=nodes(render()).find(n=>n.type===browserStub);browser.props.onPick(libraryImage(name));}render();effects[1]();},
    save:()=>{render();effects[1]();}};
}
test('A/B result attributes CPU execution to the connected backend, including shared transport',async()=>{const panel=renderPanel();panel.start();await tick();assert.equal(panel.sent().device,'cpu');panel.complete();await tick();assert.match(panel.values[17],/백엔드.*CPU/i);assert.doesNotMatch(panel.values[17],/이 컴퓨터 CPU/);assert.equal(panel.values[14].comparison_id,'cmp');});
test('A/B response from a previous transport cannot publish its result or execution-location notice',async()=>{const panel=renderPanel();panel.start();await tick();panel.context.transportRevision=1;panel.complete();await tick();assert.equal(panel.values[14],null);assert.equal(panel.values[17],'');});
test('two fixed test images restore by identity after the same shared API/profile reopens with a different epoch',async()=>{const storage=new Map();global.localStorage={getItem:key=>storage.get(key)||null,setItem:(key,value)=>storage.set(key,value)};const first=renderPanel({epoch:7});await first.load();first.pick(['one','two']);const reopened=renderPanel({epoch:0});await reopened.load();assert.deepEqual(reopened.values[18].map(image=>image.file_path),['/fixture/one.png','/fixture/two.png']);assert.equal(reopened.values[19],'available');delete global.localStorage;});
test('the real panel isolates identical project paths and IDs on different API servers',async()=>{const storage=new Map();global.localStorage={getItem:key=>storage.get(key)||null,setItem:(key,value)=>storage.set(key,value)};const first=renderPanel({apiIdentity:'shared:https://server-a'});await first.load();first.pick(['one','two']);const other=renderPanel({apiIdentity:'shared:https://server-b'});await other.load();assert.deepEqual(other.values[18],[]);delete global.localStorage;});
test('a saved image the revision no longer has is left out of comparisons but stays saved and listed',async()=>{const storage=new Map();global.localStorage={getItem:key=>storage.get(key)||null,setItem:(key,value)=>storage.set(key,value)};const first=renderPanel();await first.load();first.pick(['one','two']);const reopened=renderPanel({missing:['two.png']});await reopened.load();assert.deepEqual(reopened.values[18].map(image=>image.relative_path),['one.png']);assert.deepEqual(reopened.values[20].map(image=>[image.relative_path,image.status]),[['two.png','missing']]);assert.match(reopened.values[17],/찾을 수 없음 1장/);reopened.save();const again=renderPanel();await again.load();assert.deepEqual(again.values[18].map(image=>image.relative_path),['one.png','two.png'],'the entry survived the load that could not confirm it');delete global.localStorage;});
test('a load without an accepted revision never erases the saved identity set',async()=>{const storage=new Map();global.localStorage={getItem:key=>storage.get(key)||null,setItem:(key,value)=>storage.set(key,value)};const first=renderPanel();await first.load();first.pick(['one','two']);const offline=renderPanel({noRevision:true});await offline.load();assert.equal(offline.values[19],'unavailable');const key=[...storage.keys()].find(name=>!name.endsWith(':paths'));assert.deepEqual(JSON.parse(storage.get(key)).map(image=>image.relative_path),['one.png','two.png']);delete global.localStorage;});
test('picking again a changed test image keeps it once, confirmed, and frees its place',async()=>{const storage=new Map();global.localStorage={getItem:key=>storage.get(key)||null,setItem:(key,value)=>storage.set(key,value)};const first=renderPanel();await first.load();first.pick(['one','two']);const reopened=renderPanel({changed:['two.png']});await reopened.load();assert.deepEqual(reopened.values[20].map(image=>[image.relative_path,image.status]),[['two.png','changed']]);reopened.pick(['two']);assert.deepEqual(reopened.values[18].map(image=>image.relative_path),['one.png','two.png']);assert.deepEqual(reopened.values[20],[]);const key=[...storage.keys()].find(name=>!name.endsWith(':paths'));assert.deepEqual(JSON.parse(storage.get(key)).map(image=>image.relative_path),['one.png','two.png'],'saved once');delete global.localStorage;});
test('an older path-only set is kept for a later load without a revision when a revision exists now',async()=>{const storage=new Map();global.localStorage={getItem:key=>storage.get(key)||null,setItem:(key,value)=>storage.set(key,value)};const key=helper.exports.flowTestSetStorageKey({projectId:'project',projectDir:'/project',source:'/fixture',task:'segmentation',labelset:'labels',computeProfileId:'profile',apiIdentity:'shared:https://server-a'});storage.set(key,JSON.stringify(['/fixture/one.png','/fixture/two.png']));const current=renderPanel();await current.load();current.save();assert.match(current.values[17],/경로로만 저장된 2장/);assert.deepEqual(JSON.parse(storage.get(key)),[],'the identity key now holds identities only');const legacy=renderPanel({noRevision:true});await legacy.load();assert.equal(legacy.values[19],'unavailable','asked although only the legacy key holds paths');assert.deepEqual(legacy.values[7],['/fixture/one.png','/fixture/two.png'],'the copied paths are offered again');delete global.localStorage;});
test('when the library reports no revision the saved older paths are offered, not overwritten',async()=>{const storage=new Map();global.localStorage={getItem:key=>storage.get(key)||null,setItem:(key,value)=>storage.set(key,value)};const key=helper.exports.flowTestSetStorageKey({projectId:'project',projectDir:'/project',source:'/fixture',task:'segmentation',labelset:'labels',computeProfileId:'profile',apiIdentity:'shared:https://server-a'});storage.set(`${key}:paths`,JSON.stringify(['/fixture/one.png']));const panel=renderPanel();await panel.load();assert.equal(panel.values[19],'available');const browser=nodes(panel.render()).find(n=>n.props?.onUnavailable);browser.props.onUnavailable();panel.render();assert.equal(panel.values[19],'unavailable');assert.deepEqual(panel.values[7],['/fixture/one.png']);panel.save();assert.deepEqual(JSON.parse(storage.get(`${key}:paths`)),['/fixture/one.png']);delete global.localStorage;});
test('a failed check keeps saved identities untouched but lets a user with only older paths save new picks',async()=>{const storage=new Map();global.localStorage={getItem:key=>storage.get(key)||null,setItem:(key,value)=>storage.set(key,value)};const key=helper.exports.flowTestSetStorageKey({projectId:'project',projectDir:'/project',source:'/fixture',task:'segmentation',labelset:'labels',computeProfileId:'profile',apiIdentity:'shared:https://server-a'});
 storage.set(key,JSON.stringify(['/fixture/one.png']));const legacy=renderPanel({failResolve:500});await legacy.load();assert.match(legacy.values[16],/could not check/);
 assert.deepEqual(JSON.parse(storage.get(`${key}:paths`)),['/fixture/one.png'],'the older paths are kept under their own key');legacy.pick(['two']);
 assert.deepEqual(JSON.parse(storage.get(key)).map(image=>image.relative_path),['two.png'],'new picks are saved');
 const identity=JSON.stringify([libraryImage('one')]);storage.set(key,identity);const checked=renderPanel({failResolve:500});await checked.load();assert.match(checked.values[16],/could not check/);checked.pick(['two']);
 assert.equal(storage.get(key),identity,'saved identities that could not be checked are never overwritten');delete global.localStorage;});
test('without an accepted revision the older path list restores the paths saved by an older version',async()=>{const storage=new Map();global.localStorage={getItem:key=>storage.get(key)||null,setItem:(key,value)=>storage.set(key,value)};const probe=renderPanel();const key=helper.exports.flowTestSetStorageKey({projectId:'project',projectDir:'/project',source:'/fixture',task:'segmentation',labelset:'labels',computeProfileId:'profile',apiIdentity:'shared:https://server-a'});storage.set(key,JSON.stringify(['/fixture/one.png','/fixture/gone.png','/fixture/two.png']));const legacy=renderPanel({noRevision:true});await legacy.load();assert.equal(legacy.values[19],'unavailable');
 assert.deepEqual(legacy.values[7],['/fixture/one.png','/fixture/gone.png','/fixture/two.png'],'a saved path outside the listed images stays saved');
 legacy.save();assert.deepEqual(JSON.parse(storage.get(`${key}:paths`)),['/fixture/one.png','/fixture/gone.png','/fixture/two.png'],'and is not lost by saving');
 const compare=nodes(legacy.render()).find(n=>n.type==='button'&&[].concat(n.props.children||[]).some(c=>typeof c==='string'&&c.includes('비교 실행')));compare.props.onClick();await tick();
 assert.deepEqual(legacy.sent().image_paths,['/fixture/one.png','/fixture/two.png'],'only listed images are compared');
 const summaryText=nodes(legacy.render()).filter(n=>n.type==='summary').map(n=>[].concat(n.props.children||[]).filter(c=>typeof c==='string'||typeof c==='number').join('')).join(' ');
 assert.match(summaryText,/저장 3\/20 · 비교 2장 · 목록 밖 1장/,'the count says what is saved and what is compared');
 const remove=nodes(legacy.render()).find(n=>n.type==='button'&&[].concat(n.props.children||[]).includes('/fixture/gone.png'));remove.props.onClick();legacy.save();
 assert.deepEqual(JSON.parse(storage.get(`${key}:paths`)),['/fixture/one.png','/fixture/two.png'],'an unlisted saved path can be removed');assert.ok(probe);delete global.localStorage;});
test('removing unlisted paths keeps the listed ones, one at a time or all at once',async()=>{const storage=new Map();global.localStorage={getItem:key=>storage.get(key)||null,setItem:(key,value)=>storage.set(key,value)};const key=helper.exports.flowTestSetStorageKey({projectId:'project',projectDir:'/project',source:'/fixture',task:'segmentation',labelset:'labels',computeProfileId:'profile',apiIdentity:'shared:https://server-a'});
 storage.set(key,JSON.stringify(['/fixture/one.png','/fixture/gone-a.png','/fixture/gone-b.png','/fixture/two.png']));const panel=renderPanel({noRevision:true});await panel.load();
 nodes(panel.render()).find(n=>n.type==='button'&&[].concat(n.props.children||[]).includes('/fixture/gone-a.png')).props.onClick();
 assert.deepEqual(panel.values[7],['/fixture/one.png','/fixture/gone-b.png','/fixture/two.png'],'one ✕ removes only its path');
 nodes(panel.render()).find(n=>n.type==='button'&&n.props.children==='모두 빼기').props.onClick();
 assert.deepEqual(panel.values[7],['/fixture/one.png','/fixture/two.png'],'모두 빼기 keeps the listed paths');delete global.localStorage;});
for(const [state,options,summary] of [['loading',{listingHeld:true},/이미지 목록 확인 중/],['failed',{listingFails:true},/불러오지 못해 저장 경로를 확인할 수 없음/]])
test(`while the listing is ${state} no saved path is called unlisted or offered for removal`,async()=>{const storage=new Map();global.localStorage={getItem:key=>storage.get(key)||null,setItem:(key,value)=>storage.set(key,value)};const key=helper.exports.flowTestSetStorageKey({projectId:'project',projectDir:'/project',source:'/fixture',task:'segmentation',labelset:'labels',computeProfileId:'profile',apiIdentity:'shared:https://server-a'});
 storage.set(key,JSON.stringify(['/fixture/one.png','/fixture/two.png']));const panel=renderPanel({noRevision:true,...options});await panel.load();
 const tree=nodes(panel.render());assert.equal(tree.find(n=>n.props?.['aria-label']==='목록에 보이지 않는 저장 경로'),undefined);assert.equal(tree.find(n=>n.type==='button'&&n.props.children==='모두 빼기'),undefined);
 const text=tree.filter(n=>n.type==='summary').map(n=>[].concat(n.props.children||[]).filter(c=>typeof c==='string'||typeof c==='number').join('')).join(' ');assert.match(text,summary);
 panel.save();assert.deepEqual(JSON.parse(storage.get(`${key}:paths`)),['/fixture/one.png','/fixture/two.png'],'the saved paths stay saved');delete global.localStorage;});
test('saved paths outside the listed images never lock the 20 places: they are listed and can all be removed',async()=>{const storage=new Map();global.localStorage={getItem:key=>storage.get(key)||null,setItem:(key,value)=>storage.set(key,value)};const key=helper.exports.flowTestSetStorageKey({projectId:'project',projectDir:'/project',source:'/fixture',task:'segmentation',labelset:'labels',computeProfileId:'profile',apiIdentity:'shared:https://server-a'});
 storage.set(key,JSON.stringify(Array.from({length:20},(_,index)=>`/fixture/missing-${index}.png`)));const panel=renderPanel({noRevision:true});await panel.load();
 const checkbox=()=>nodes(panel.render()).find(n=>n.type==='input'&&n.props.type==='checkbox');assert.equal(checkbox().props.disabled,true,'twenty saved paths fill the places');
 const listed=nodes(panel.render()).find(n=>n.props?.['aria-label']==='목록에 보이지 않는 저장 경로');assert.equal([].concat(listed.props.children).length,20,'each one is shown');
 nodes(panel.render()).find(n=>n.type==='button'&&n.props.children==='모두 빼기').props.onClick();
 assert.deepEqual(panel.values[7],[]);assert.equal(checkbox().props.disabled,false,'removing them frees the places');delete global.localStorage;});
const template={template_id:'template',name:'Whole graph',kind:'flow',pipeline:{nodes:[],edges:[]},models:[],classes:{names:[],ids:[]},ports:{inputs:[],outputs:[]}};
test('a clean whole-flow template still requires explicit replacement confirmation',async()=>{const previous=global.window;let asked=0;global.window={confirm:()=>{asked++;return false;}};try{const panel=renderPanel({template});await panel.apply();assert.equal(asked,1);assert.equal(panel.sent(),undefined);assert.deepEqual(panel.changes,[]);}finally{global.window=previous;}});
for(const scenario of ['current','edited graph','namespace ABA','busy'])test(`mapped template adoption respects ${scenario}`,async()=>{const previous=global.window;global.window={confirm:()=>true};try{const panel=renderPanel({template}),pending=panel.apply();await tick();if(scenario==='edited graph')panel.flowState.pipeline={id:'newer',nodes:[],edges:[]};if(scenario==='namespace ABA')panel.context.generation+=2;if(scenario==='busy')panel.flowState.isRunning=true;panel.complete({kind:'flow',pipeline:{id:'mapped',nodes:[],edges:[]},ports:template.ports});await pending;assert.equal(panel.changes.length,scenario==='current'?1:0);const alert=nodes(panel.render()).find(n=>n.props?.role==='alert');if(['edited graph','busy'].includes(scenario))assert.match(String(alert?.props.children),/그래프가 바뀌었거나 실행 중/,'a dropped apply is said, not silent');else assert.equal(alert,undefined,'no message for the current apply or another project');}finally{global.window=previous;}});
const subgraph={template_id:'module',name:'ROI check module',kind:'subgraph',pipeline:{nodes:[],edges:[]},models:[],classes:{names:[],ids:[]},ports:{inputs:[],outputs:[]}};
test('a partial template is inserted into the current graph without whole-flow confirmation',async()=>{const previous=global.window;let asked=0;global.window={confirm:()=>{asked++;return true;}};try{
 const panel=renderPanel({template:subgraph}),pending=panel.apply();await tick();
 panel.complete({kind:'subgraph',pipeline:{id:'module',nodes:[{id:'check',position:{x:0,y:0},data:{node_type:'inspection',label:'Inserted check',task:'segmentation'}}],edges:[]},ports:subgraph.ports});await pending;
 assert.equal(asked,0,'insertion keeps the current graph, so it needs no replacement confirmation');assert.equal(panel.changes.length,1);
 const inserted=panel.changes[0];assert.ok(inserted.nodes.some(n=>n.data.label==='Inserted check'&&n.id.endsWith(':check')),'the module is added beside the existing nodes');}finally{global.window=previous;}});
