import {useEffect,useState} from 'react';
import type {FlowchartPipeline,GeometryPath,FlowExecutionResources} from '../../types';
import {geometryFlowApi} from '../../services/geometryFlowApi';
import {measurementThresholdUnit} from './flowchartGraph';
import {SpatialCalibrationPanel} from './SpatialCalibrationPanel';
const input='mt-1 w-full rounded border border-slate-600 bg-[#0E1722] px-2 py-1.5 text-slate-100';
const button='rounded border border-slate-600 px-2 py-1 text-xs hover:bg-slate-700 disabled:opacity-40';
type Params=Record<string,any>;
type EditorProps={params:Params;onChange:(params:Params)=>void};

export function MeasurementEditor({params,onChange,sourcePreview,sourceSize,imagePath}:{params:Params;onChange:(params:Params)=>void;sourcePreview?:string;sourceSize?:number[];imagePath?:string}) {
  const paths:GeometryPath[]=params.paths||[];
  const [activePath,setActivePath]=useState(0);
  const [nativeSource,setNativeSource]=useState<{source_size:number[];preview_data_url:string;source_sha256:string}|null>(null),[sourceError,setSourceError]=useState('');
  useEffect(()=>{let active=true;setNativeSource(null);setSourceError('');if(imagePath)geometryFlowApi.source(imagePath).then(row=>{if(active)setNativeSource(row);}).catch(cause=>{if(active)setSourceError(cause.message||String(cause));});return()=>{active=false;};},[imagePath]);
  const dimensions:number[]=nativeSource?.source_size||params.calibration?.source_size||params.drawing_source_size||sourceSize||[0,0];
  sourcePreview=nativeSource?.preview_data_url||sourcePreview;
  const path=paths[activePath];
  const updatePath=(patch:Partial<GeometryPath>)=>onChange({...params,paths:paths.map((row,index)=>index===activePath?{...row,...patch}:row)});
  const setDimensions=(index:number,value:number)=>{const size=[...dimensions];size[index]=value;onChange({...params,drawing_source_size:size,...(params.calibration?{calibration:{...params.calibration,source_size:size}}:{})});};
  const addPath=()=>{let n=paths.length+1;while(paths.some(p=>p.id===`경로 ${n}`))n++;onChange({...params,paths:[...paths,{id:`경로 ${n}`,interpolation:'polyline',points:[]}]});setActivePath(paths.length);};
  return <div className="space-y-3 rounded border border-teal-800 bg-teal-950/20 p-3">
    <h4 className="font-semibold text-teal-200">원본 좌표의 길이·면적</h4>
    <p className="text-[10px] leading-4 text-slate-400">분할 마스크 또는 검출 다각형의 면적과 지정 경로의 길이를 측정합니다. 곡선은 시작·제어점 2개·끝점 순으로 4점을 지정합니다.</p>
    {nativeSource&&<p className="text-[10px] text-teal-200">선택 원본 {nativeSource.source_size.join(' × ')} px · SHA {nativeSource.source_sha256.slice(0,12)}</p>}{sourceError&&<p role="alert" className="text-rose-300">{sourceError}</p>}
    {nativeSource&&params.calibration&&JSON.stringify(params.calibration.source_size)!==JSON.stringify(nativeSource.source_size)&&<div role="alert" className="space-y-1 text-rose-300"><p>교정 원본 크기 {params.calibration.source_size.join(' × ')} px가 선택 이미지와 다릅니다.</p><button type="button" className={button} onClick={()=>onChange({...params,calibration:{...params.calibration,source_size:nativeSource.source_size}})}>선택 원본 크기로 교정 적용</button></div>}
    <div className="grid grid-cols-2 gap-2">{['원본 너비','원본 높이'].map((label,index)=><label key={label}>{label} (px)<input aria-label={label} type="number" min="1" step="1" readOnly={!!nativeSource} value={dimensions[index]||''} onChange={e=>setDimensions(index,Number(e.target.value))} className={input}/></label>)}</div>
    <SpatialCalibrationPanel params={params} onChange={onChange} sourceSize={dimensions.every(n=>n>0)?dimensions:undefined} sourcePreview={sourcePreview}/>
    {params.calibration_ref?null
    :<label className="flex items-center gap-2"><input type="checkbox" checked={!!params.calibration} onChange={e=>{const next={...params};next.threshold_unit=measurementThresholdUnit(params);if(e.target.checked){next.calibration={unit:'mm',source_size:[...dimensions]};}else{delete next.calibration;}onChange(next);}}/>실제 길이 교정 (mm, 직접 입력·검증 안 됨)</label>}
    {params.calibration&&<div className="grid grid-cols-2 gap-2">{(['x','y'] as const).map(axis=><label key={axis}>{axis.toUpperCase()} 교정 (mm/px)<input type="number" min="0" step="0.001" value={params.calibration[`mm_per_pixel_${axis}`]??''} onChange={e=>{const calibration={...params.calibration};if(e.target.value==='')delete calibration[`mm_per_pixel_${axis}`];else calibration[`mm_per_pixel_${axis}`]=Number(e.target.value);onChange({...params,calibration});}} className={input}/></label>)}</div>}
    <div className="flex gap-2"><select aria-label="측정 경로" value={activePath} onChange={e=>setActivePath(Number(e.target.value))} className="min-w-0 flex-1 rounded bg-slate-800 p-1"><option value="-1">경로 선택</option>{paths.map((p,index)=><option key={index} value={index}>{p.id}</option>)}</select><button type="button" onClick={addPath} disabled={paths.length>=64} className={button}>경로 추가</button></div>
    {path&&<><div className="flex gap-2"><input aria-label="측정 경로 이름" value={path.id} onChange={e=>updatePath({id:e.target.value})} className={input}/><select aria-label="길이 측정 방식" value={path.interpolation||'polyline'} onChange={e=>updatePath({interpolation:e.target.value as GeometryPath['interpolation'],points:[]})} className="rounded bg-slate-800 p-1"><option value="polyline">다각선</option><option value="bezier">곡선</option></select><button type="button" aria-label="경로 삭제" onClick={()=>{onChange({...params,paths:paths.filter((_,index)=>index!==activePath)});setActivePath(0);}} className={button}>삭제</button></div>
      {sourcePreview&&dimensions.every(n=>n>0)&&<svg role="img" aria-label="원본 이미지에 측정점 지정" viewBox={`0 0 ${dimensions[0]} ${dimensions[1]}`} className="max-h-60 w-full cursor-crosshair rounded border border-slate-600 bg-slate-950" onClick={event=>{
        if(path.interpolation==='bezier'&&path.points.length>=4)return;
        const rect=event.currentTarget.getBoundingClientRect();const scale=Math.min(rect.width/dimensions[0],rect.height/dimensions[1]);
        const x=(event.clientX-rect.left-(rect.width-dimensions[0]*scale)/2)/scale,y=(event.clientY-rect.top-(rect.height-dimensions[1]*scale)/2)/scale;
        if(x>=0&&y>=0&&x<=dimensions[0]&&y<=dimensions[1])updatePath({points:[...path.points,[Math.round(x),Math.round(y)]]});
      }}><image href={sourcePreview} width={dimensions[0]} height={dimensions[1]}/><polyline points={path.points.map(p=>p.join(',')).join(' ')} fill="none" stroke="#2dd4bf" strokeWidth={Math.max(dimensions[0],dimensions[1])/300}/>{path.interpolation==='bezier'&&path.points.length===4&&<path d={`M ${path.points[0]} C ${path.points[1]} ${path.points[2]} ${path.points[3]}`} fill="none" stroke="#fbbf24" strokeWidth={Math.max(dimensions[0],dimensions[1])/250}/>}{path.points.map(([x,y],index)=><circle key={index} cx={x} cy={y} r={Math.max(dimensions[0],dimensions[1])/100} fill="#2dd4bf"/>)}</svg>}
      <div className="space-y-1">{path.points.map(([x,y],index)=><div key={index} className="flex items-center gap-1"><span className="w-4 text-slate-400">{index+1}</span>{[x,y].map((value,axis)=><input key={axis} aria-label={`${index+1}번 측정점 ${axis?'Y':'X'}`} type="number" value={value} onChange={e=>{const points=path.points.map(point=>[...point] as [number,number]);points[index][axis]=Number(e.target.value);updatePath({points});}} className={input}/>)}<button type="button" aria-label={`${index+1}번 측정점 삭제`} onClick={()=>updatePath({points:path.points.filter((_,i)=>i!==index)})} className={button}>×</button></div>)}</div>
      <button type="button" disabled={path.interpolation==='bezier'&&path.points.length>=4} onClick={()=>updatePath({points:[...path.points,[0,0]]})} className={button}>측정점 추가</button><button type="button" onClick={()=>updatePath({points:[]})} className={`${button} ml-2`}>점 지우기</button></>}
    <div className="grid grid-cols-2 gap-2">{(['min_length','max_length','min_area','max_area'] as const).map(key=><label key={key}>{({min_length:'최소 길이',max_length:'최대 길이',min_area:'최소 면적',max_area:'최대 면적'})[key]} ({measurementThresholdUnit(params)}{key.includes('area')?'²':''})<input type="number" min="0" value={params[key]??''} onChange={e=>{const next={...params};if(e.target.value==='')delete next[key];else next[key]=Number(e.target.value);onChange(next);}} className={input}/></label>)}</div>
  </div>;
}

export function ClassRulesEditor({params,onChange,blob=false,classes=[]}:EditorProps&{blob?:boolean;classes?:{id:number;name:string}[]}) {
  const [selected,setSelected]=useState((params.class_ids||[]).join(','));
  useEffect(()=>setSelected((params.class_ids||[]).join(',')),[JSON.stringify(params.class_ids)]);
  const rows:Params[]=params.class_rules||[];
  const update=(index:number,key:string,value:string)=>onChange({...params,class_rules:rows.map((row,i)=>{if(i!==index)return row;const next={...row};if(value==='')delete next[key];else next[key]=Number(value);return next;})});
  const fields=blob?['min_count','max_count','min_area_px','max_area_px','min_mean_grayscale','max_mean_grayscale']:['probability_threshold','min_area_px','max_area_px'];
  const labels:Record<string,string>={min_count:'최소 개수',max_count:'최대 개수',min_area_px:'최소 면적 (px²)',max_area_px:'최대 면적 (px²)',min_mean_grayscale:'최소 회색값',max_mean_grayscale:'최대 회색값',probability_threshold:'픽셀 확률 기준'};
  return <details className="space-y-2 rounded border border-slate-700 p-2"><summary className="cursor-pointer font-semibold">클래스별 {blob?'개수·면적·회색값':'픽셀 확률·면적'} 기준</summary>
    {blob&&<label className="block">판정 방식<select aria-label="Blob 판정 방식" value={params.rule_mode||'defect_presence'} onChange={e=>onChange({...params,rule_mode:e.target.value})} className={input}><option value="defect_presence">결함 존재</option><option value="required_structure">필수 구조 기준</option></select></label>}
    {!!classes.length&&<fieldset className="space-y-1"><legend>측정 클래스 · 모두 해제하면 전체</legend>{classes.map(option=><label key={option.id} className="mr-3 inline-flex items-center gap-1"><input type="checkbox" checked={(params.class_ids||[]).includes(option.id)} onChange={e=>{const ids=new Set<number>(params.class_ids||[]);if(e.target.checked)ids.add(option.id);else ids.delete(option.id);const next={...params};if(ids.size)next.class_ids=[...ids];else delete next.class_ids;onChange(next);}}/>{option.name} <span className="text-slate-500">#{option.id}</span></label>)}</fieldset>}
    <details className="text-slate-400"><summary className="cursor-pointer">고급 · 클래스 ID 직접 지정</summary><label className="block">쉼표 구분 · 비우면 전체<input value={selected} onChange={e=>setSelected(e.target.value)} onBlur={()=>{const next={...params};if(!selected.trim())delete next.class_ids;else next.class_ids=selected.split(',').map(Number);onChange(next);}} className={input}/></label></details>
    {!classes.length&&<p className="text-amber-200">선택 모델의 클래스 목록을 확인할 수 없습니다. 모델과 연결을 먼저 확인하세요. 이전 모델은 고급 설정에서 ID를 직접 지정할 수 있습니다.</p>}
    {rows.map((row,index)=><div key={index} className="space-y-1 border-t border-slate-700 pt-2"><div className="flex items-center gap-2"><label>클래스{classes.length?<select aria-label={`기준 ${index+1} 클래스`} value={row.class_id} onChange={e=>update(index,'class_id',e.target.value)} className={input}>{!classes.some(option=>option.id===row.class_id)&&<option value={row.class_id}>목록에 없는 ID {row.class_id} · 확인 필요</option>}{classes.map(option=><option key={option.id} value={option.id}>{option.name} · #{option.id}</option>)}</select>:<input aria-label={`기준 ${index+1} 클래스 ID`} type="number" min="1" step="1" value={row.class_id} onChange={e=>update(index,'class_id',e.target.value)} className={input}/>}</label><button type="button" onClick={()=>onChange({...params,class_rules:rows.filter((_,i)=>i!==index)})} className={button}>삭제</button></div><div className="grid grid-cols-2 gap-2">{fields.map(key=><label key={key} className="text-[10px]">{labels[key]}<input type="number" min={blob?0:key.includes('area')?1:0} max={key.includes('grayscale')?255:key==='probability_threshold'?1:undefined} step={key.includes('grayscale')||key==='probability_threshold'?'any':'1'} value={row[key]??''} onChange={e=>update(index,key,e.target.value)} className={input}/></label>)}</div></div>)}
    <button type="button" onClick={()=>{let id=classes.find(option=>!rows.some(row=>row.class_id===option.id))?.id??1;while(!classes.length&&rows.some(row=>row.class_id===id))id++;onChange({...params,class_rules:[...rows,{class_id:id}]});}} disabled={!!classes.length&&classes.every(option=>rows.some(row=>row.class_id===option.id))} className={button}>클래스 기준 추가</button>
    {blob&&<p className="text-[10px] leading-4 text-slate-400">필수 구조는 측정된 개수·총면적·평균 회색값이 기준 밖이면 NG입니다. 결함 존재 모드는 면적·회색값 조건에 맞는 덩어리를 셉니다. 선택 클래스의 증거가 없으면 REVIEW입니다.</p>}
  </details>;
}

export function OCRRulesEditor({params,onChange}:EditorProps) {
  const [from,setFrom]=useState(''),[to,setTo]=useState('');
  const mode=params.regex!==undefined?'regex':'expected_text';
  const rows:Params[]=params.position_rules||[];
  return <div className="space-y-2"><label className="block">문자 판정 방식<select value={mode} onChange={e=>{const next={...params};delete next.expected_text;delete next.regex;next[e.target.value]='';onChange(next);}} className={input}><option value="expected_text">문자열 정확 일치</option><option value="regex">정규식 전체 일치</option></select></label><input aria-label="기대 문자 또는 정규식" value={params[mode]||''} onChange={e=>onChange({...params,[mode]:e.target.value})} className={input}/>
    <details className="rounded border border-slate-700 p-2"><summary>문자 교정·위치별 규칙</summary><p className="my-2 text-[10px] text-slate-400">원본 인식 문자와 교정 문자는 결과에 함께 저장됩니다. 위치는 0부터 시작합니다.</p>
      {Object.entries(params.correction_map||{}).map(([a,b])=><div key={a} className="flex justify-between p-1"><span>{a} → {String(b)}</span><button type="button" onClick={()=>{const map={...params.correction_map};delete map[a];onChange({...params,correction_map:map});}} className={button}>삭제</button></div>)}
      <div className="flex items-end gap-1"><label>인식 문자<input value={from} onChange={e=>setFrom(e.target.value)} className={input}/></label><label>교정 문자<input value={to} onChange={e=>setTo(e.target.value)} className={input}/></label><button type="button" disabled={Array.from(from).length!==1||Array.from(to).length!==1} onClick={()=>{onChange({...params,correction_map:{...params.correction_map,[from]:to}});setFrom('');setTo('');}} className={button}>추가</button></div>
      {rows.map((row,index)=><div key={index} className="mt-2 space-y-1 border-t border-slate-700 pt-2"><label>문자 위치<input type="number" min="0" step="1" value={row.index} onChange={e=>onChange({...params,position_rules:rows.map((r,i)=>i===index?{...r,index:Number(e.target.value)}:r)})} className={input}/></label>{['allowed_chars','fixed_char'].map(key=><label key={key} className="block">{key==='fixed_char'?'고정 문자':'허용 문자 집합'}<input value={row[key]||''} onChange={e=>onChange({...params,position_rules:rows.map((r,i)=>{if(i!==index)return r;const next={...r};if(e.target.value==='')delete next[key];else next[key]=e.target.value;return next;})})} className={input}/></label>)}<button type="button" onClick={()=>onChange({...params,position_rules:rows.filter((_,i)=>i!==index)})} className={button}>위치 규칙 삭제</button></div>)}
      <button type="button" onClick={()=>{let index=0;while(rows.some(row=>row.index===index))index++;onChange({...params,position_rules:[...rows,{index,allowed_chars:''}]});}} className={`${button} mt-2`}>위치 규칙 추가</button>
    </details></div>;
}

export function FlowResourcesEditor({pipeline,onChange,disabled}:{pipeline:FlowchartPipeline;onChange:(p:FlowchartPipeline)=>void;disabled:boolean}) {
  const [resources,setResources]=useState<FlowExecutionResources|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  useEffect(()=>{let active=true;geometryFlowApi.resources().then(r=>{if(active)setResources(r);}).catch(e=>{if(active)setError(e.message||String(e));});return()=>{active=false;};},[]);
  const config=pipeline.execution_config||{max_workers:1,device_slots:1};
  return <details className="rounded border border-slate-700 bg-[#131822] p-2 text-xs"><summary className="cursor-pointer text-slate-300">병렬 실행 · 작업 {config.max_workers} / 장치 슬롯 {config.device_slots}</summary><div className="mt-2 grid grid-cols-2 gap-2">{(['max_workers','device_slots'] as const).map(key=><label key={key}>{key==='max_workers'?'독립 노드 작업 수':'요청 장치 슬롯'}<input type="number" min="1" max="8" step="1" disabled={disabled||busy} value={config[key]} onChange={e=>onChange({...pipeline,execution_config:{...config,[key]:Number(e.target.value)}})} className={input}/></label>)}</div><p className="mt-2 text-[10px] text-slate-400">선행 결과가 준비된 독립 노드만 병렬 처리합니다. 기본값은 순차 실행이며 결과 순서는 유지됩니다.</p>{resources&&<div className="mt-2 space-y-2"><p>현재 {resources.device} · 엔진 슬롯 {resources.engine_device_capacity} · 실행 중 {resources.active_executions}개</p><button type="button" disabled={disabled||busy||resources.active_executions>0||config.device_slots<1||config.device_slots>resources.maximum_cpu_slots} onClick={async()=>{setBusy(true);setError('');try{setResources(await geometryFlowApi.configureCPU(config.device_slots));}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}} className={button}>CPU 엔진에 슬롯 적용</button><p className="text-[10px] text-slate-400">CPU 최대 {resources.maximum_cpu_slots}슬롯. GPU 엔진 동시 실행은 현재 1슬롯을 유지합니다. 실행 중에는 자원을 변경할 수 없습니다.</p></div>}{error&&<p role="alert" className="mt-2 text-rose-300">{error}</p>}</details>;
}
