import {useEffect,useState} from 'react';
import {api,request,resolveApiUrl,getApiPersistenceIdentity,getProjectContextGeneration,type FlowModelCatalogItem,type SavedFlowVersion} from '../../services/api';
import {useProjectStore} from '../../stores/useProjectStore';
import {useDatasetStore} from '../../stores/useDatasetStore';
import {useFlowchartStore} from '../../stores/useFlowchartStore';
import type {FlowchartPipeline,ImageMeta,FlowchartExecutionResult} from '../../types';
import {insertSubgraph,flowTestSetStorageKey} from './flowWorkspace';
import {compatibleModelNode,modelScoreBinding} from './modelFlowHandoff';
import {useComputeStore} from '../../stores/useComputeStore';
import {ImageLibraryBrowser} from '../common/ImageLibraryBrowser';
import {applyResolution,legacySavedPaths,legacyStorageKey,parseSavedTestSet,testImageFrom,toggleTestImage,unresolvedReason,TEST_SET_LIMIT,type TestImage,type UnresolvedTestImage} from './flowTestSet';
interface Template {template_id:string;name:string;kind:'flow'|'subgraph';pipeline:FlowchartPipeline;models:Array<{node_id:string;name:string;task:string}>;classes:{names:string[];ids:number[]};classes_by_node?:Record<string,{names:string[];ids:number[]}>;ports:{inputs:Array<{node_id:string;payload_type:string}>;outputs:Array<{node_id:string;payload_type:string}>}}
interface Comparison {comparison_id:string;name:string;created_at:string;status:string;rows:Array<{image_path:string;file_name:string;image_sha256:string;error?:string;result_a?:FlowchartExecutionResult;result_b?:FlowchartExecutionResult;difference?:{verdict_changed:boolean;roi_changed:boolean;changed_nodes:string[];verdict_a:string;verdict_b:string;reason_a:string;reason_b:string}}>}
export function FlowWorkspacePanel({versions,models,onOpenImage,area}:{area?:'edit'|'test'|'evaluate'|'release';versions:SavedFlowVersion[];models:FlowModelCatalogItem[];onOpenImage:()=>void}) {
  const project=useProjectStore(s=>s.project);const folder=useDatasetStore(s=>s.folderPath);const task=useProjectStore(s=>s.task);const labelset=project?.active_labelset_id;const transport=useComputeStore(s=>s.transportRevision);const profile=useComputeStore(s=>s.selectedProfileId);const backendIdentity=getApiPersistenceIdentity();
  const {pipeline,replacePipeline,setSelectedImage,selectNode,isRunning}=useFlowchartStore();
  const [templates,setTemplates]=useState<Template[]>([]);const [selected,setSelected]=useState('');const [name,setName]=useState('내 검사 흐름');const [subset,setSubset]=useState<string[]>([]);
  const [mapping,setMapping]=useState<Record<string,string>>({});const [classMapping,setClassMapping]=useState<Record<string,string>>({});
  const [images,setImages]=useState<ImageMeta[]>([]);const [testImages,setTestImages]=useState<string[]>([]);const [va,setVa]=useState('');const [vb,setVb]=useState('');
  const [target,setTarget]=useState<'local'|'selected_compute'>('local');const [device,setDevice]=useState('cpu');
  const [loadedContext,setLoadedContext]=useState<string|null>(null);
  const [history,setHistory]=useState<Comparison[]>([]);const [comparison,setComparison]=useState<Comparison|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');
  // Test images are chosen from the validated revision and kept by identity; without an accepted revision the older
  // path list of the first 200 images is offered.
  const [testSet,setTestSet]=useState<TestImage[]>([]);const [library,setLibrary]=useState<'available'|'unavailable'>('available');
  // Saved images the current revision does not confirm stay saved (and listed) instead of vanishing after one load.
  const [unresolved,setUnresolved]=useState<UnresolvedTestImage[]>([]);
  const storageKey=project?flowTestSetStorageKey({projectId:project.id,projectDir:project.project_dir,source:folder,task,labelset,computeProfileId:profile,apiIdentity:backendIdentity}):null;
  const contextGeneration=getProjectContextGeneration();
  const context=JSON.stringify([storageKey,transport,contextGeneration]);
  useEffect(()=>{let active=true;setLoadedContext(null);setTarget('local');setDevice('cpu');setTemplates([]);setImages([]);setHistory([]);setComparison(null);setTestImages([]);setTestSet([]);setUnresolved([]);setLibrary('available');setSelected('');setVa('');setVb('');setSubset([]);setError('');setNotice('');setBusy(false);
    if(project&&folder&&storageKey)Promise.all([request<{templates:Template[]}>('/api/flow-workspace/templates'),request<{comparisons:Comparison[]}>('/api/flow-workspace/comparisons')]).then(async([t,h])=>{if(!active)return;setTemplates(t.templates);setHistory(h.comparisons);
      let raw:string|null=null;try{raw=localStorage.getItem(storageKey);}catch{}
      const {saved,legacyPaths}=parseSavedTestSet(raw);
      // asked even for an older path-only set: the answer says whether a validated revision exists (409 = legacy list)
      try{const resolved=saved.length||legacyPaths?await api.library.resolve(saved):null;if(!active)return;const {kept,unresolved:pending,notice:dropped}=applyResolution(saved,resolved?.results||[],legacyPaths);setTestSet(kept);setUnresolved(pending);if(dropped)setNotice(dropped);}
      catch(e){if(!active)return;if((e as {status?:number}).status!==409)throw e;let pathsRaw:string|null=null;try{pathsRaw=localStorage.getItem(legacyStorageKey(storageKey));}catch{}setLibrary('unavailable');setTestImages(legacySavedPaths(raw,pathsRaw));}
      setLoadedContext(context);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};
  },[context]);
  // The identity set and the legacy path list are saved under separate keys, so neither mode erases the other's entries.
  useEffect(()=>{if(!storageKey||loadedContext!==context)return;try{if(library==='available')localStorage.setItem(storageKey,JSON.stringify([...testSet,...unresolved]));else localStorage.setItem(legacyStorageKey(storageKey),JSON.stringify(testImages));}catch{}},[testImages,testSet,unresolved,library,context,loadedContext]);
  useEffect(()=>{if(library!=='unavailable'||!project||!folder||!storageKey)return;let active=true;api.dataset.getImages({folder_path:folder,task,limit:200}).then(imgs=>{if(!active)return;setImages(imgs.items);setTestImages(paths=>paths.filter(p=>imgs.items.some(i=>i.file_path===p)).slice(0,20));}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[library,context]);
  const testPaths=library==='available'?testSet.map(image=>image.file_path):testImages;
  const current=()=>getProjectContextGeneration()===contextGeneration&&useProjectStore.getState().project?.id===project?.id&&useProjectStore.getState().project?.project_dir===project?.project_dir&&useDatasetStore.getState().folderPath===folder&&useProjectStore.getState().task===task&&useProjectStore.getState().project?.active_labelset_id===labelset&&useComputeStore.getState().transportRevision===transport&&useComputeStore.getState().selectedProfileId===profile&&getApiPersistenceIdentity()===backendIdentity;
  const action=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');setNotice('');try{await fn();}catch(e){if(current())setError(e instanceof Error?e.message:String(e));}finally{if(current())setBusy(false);}};
  const save=()=>action(async()=>{if(!project||!pipeline)return;const r=await request<Template>('/api/flow-workspace/templates',{method:'POST',body:JSON.stringify({project_id:project.id,name,pipeline,...(subset.length?{node_ids:subset}:{})})});if(current()){setTemplates(t=>[r,...t]);setNotice('템플릿을 저장했습니다. 다른 프로젝트에서 모델·클래스를 매핑해 사용할 수 있습니다.');}});
  const chosen=templates.find(t=>t.template_id===selected);
  const classFields=chosen?Object.entries(chosen.classes_by_node||{'':chosen.classes}).flatMap(([id,c])=>[...c.names.map(v=>({key:`${id?`${id}:`:''}name:${v}`,label:`${chosen.pipeline.nodes.find(n=>n.id===id)?.data.label||'전체'} · 이름 ${v}`,numeric:false})),...c.ids.map(v=>({key:`${id?`${id}:`:''}id:${v}`,label:`${chosen.pipeline.nodes.find(n=>n.id===id)?.data.label||'전체'} · ID ${v}`,numeric:true}))]):[];
  const apply=()=>action(async()=>{
    if(!project||!chosen||!pipeline)return;
    if(useFlowchartStore.getState().isRunning||useFlowchartStore.getState().isSaving||useProjectStore.getState().isProjectBusy)throw new Error('실행·저장이 끝난 뒤 템플릿을 적용하세요.');
    const original=useFlowchartStore.getState().pipeline;
    if(chosen.kind==='flow'&&!window.confirm('모델·클래스 매핑을 확인했습니다. 현재 전체 그래프를 새 초안으로 교체할까요? 저장된 버전은 유지됩니다.'))return;
    const r=await request<{kind:string;pipeline:FlowchartPipeline;ports:Template['ports']}>(`/api/flow-workspace/templates/${selected}/map`,{method:'POST',body:JSON.stringify({project_id:project.id,models:mapping,classes:classMapping})});
    const live=useFlowchartStore.getState();
    if(!current())return;  // another project or context: its graph is not this template's target
    if(live.pipeline!==original||live.isRunning||live.isSaving||useProjectStore.getState().isProjectBusy)
      throw new Error('적용하는 동안 그래프가 바뀌었거나 실행 중입니다. 현재 그래프를 확인한 뒤 다시 적용하세요.');
    if(r.kind!==chosen.kind)throw new Error('템플릿 종류가 바뀌었습니다. 다시 확인하세요.');
    const mapped={...r.pipeline,nodes:r.pipeline.nodes.map(node=>{
      if(!node.data.model_job_id)return node;
      const model=models.find(item=>item.job_id===node.data.model_job_id);
      if(!model||!compatibleModelNode(node,model))throw new Error('매핑한 모델의 현재 호환 정보를 확인하세요.');
      return {...node,data:{...node.data,...modelScoreBinding(model)}};
    })};
    replacePipeline(r.kind==='flow'?mapped:insertSubgraph(live.pipeline!,mapped,`module-${Date.now()}`));
    setNotice(r.kind==='flow'?'모델·클래스를 매핑한 초안으로 열었습니다. 연결을 확인하고 저장하세요.':`부분 흐름을 추가했습니다. 입력 ${r.ports.inputs.length}개·출력 ${r.ports.outputs.length}개 경계 포트를 기존 노드와 연결하세요.`);
  });
  const compare=()=>action(async()=>{if(!project)return;const r=await request<Comparison>('/api/flow-workspace/comparisons',{method:'POST',body:JSON.stringify({project_id:project.id,version_a:va,version_b:vb,image_paths:testPaths,device,execution_target:target,compute_profile_id:target==='selected_compute'?profile:null})});if(current()){setComparison(r);setHistory(h=>[r,...h]);setNotice(`동일한 고정 이미지와 원본 해시로 비교 결과를 저장했습니다. 실행 대상: ${target==='local'?'현재 백엔드':profile} · ${device}`);}});
  return <details hidden={Boolean(area&&area!=='edit'&&area!=='evaluate')} className="shrink-0 border-t border-slate-700 bg-[#131822] text-xs">
    <summary className="cursor-pointer px-4 py-2 font-semibold text-sky-200">{area==='edit'?'내 템플릿 · 모델·클래스 매핑':area==='evaluate'?'고정 테스트 세트 · 플로우 버전 A/B 비교':'고정 테스트 세트 · 플로우 버전 비교 · 내 템플릿'}</summary>
    <div className={`grid ${area?'grid-cols-1':'grid-cols-2'} gap-4 px-4 pb-3 max-h-[42vh] overflow-auto`}>
      <section hidden={area==='evaluate'} className="space-y-2"><h3 className="text-sm font-bold">재사용할 검사 흐름</h3><div className="flex gap-2"><input aria-label="템플릿 이름" value={name} onChange={e=>setName(e.target.value)} className="flex-1 rounded bg-slate-800 p-2"/><button disabled={!pipeline||busy||isRunning} onClick={save} className="rounded border border-sky-700 p-2">{subset.length?'선택 노드 저장':'전체 흐름 저장'}</button></div>
        <details><summary className="cursor-pointer text-slate-400">부분 흐름으로 저장할 노드 선택</summary><div className="flex flex-wrap gap-2 mt-2">{pipeline?.nodes.filter(n=>!['input','decision','output'].includes(n.data.node_type)).map(n=><label key={n.id}><input type="checkbox" checked={subset.includes(n.id)} onChange={e=>setSubset(s=>e.target.checked?[...s,n.id]:s.filter(x=>x!==n.id))}/> {n.data.label}</label>)}</div></details>
        <select aria-label="내 템플릿 선택" value={selected} onChange={e=>{setSelected(e.target.value);setMapping({});setClassMapping({});}} className="w-full rounded bg-slate-800 p-2"><option value="">저장한 템플릿 선택</option>{templates.map(t=><option key={t.template_id} value={t.template_id}>{t.name} · {t.kind==='flow'?'전체':'부분'} 흐름</option>)}</select>
        {chosen&&<div className="space-y-2">{chosen.models.map(m=><label className="block" key={m.node_id}>{m.name} · {m.task}<select aria-label={`${m.name} 템플릿 모델 매핑`} value={mapping[m.node_id]||''} onChange={e=>setMapping(v=>({...v,[m.node_id]:e.target.value}))} className="w-full rounded bg-slate-800 p-2"><option value="">현재 프로젝트의 호환 모델 선택</option>{models.filter(v=>v.task===m.task).map(v=><option key={v.job_id} value={v.job_id}>{v.label}</option>)}</select></label>)}{classFields.map(c=><label key={c.key} className="flex items-center gap-2">{c.label} → <input aria-label={`${c.label} 매핑`} placeholder={c.numeric?'대상 클래스 ID':'대상 클래스 이름'} value={classMapping[c.key]||''} onChange={e=>setClassMapping(v=>({...v,[c.key]:e.target.value}))} className="flex-1 rounded bg-slate-800 p-2"/></label>)}<button disabled={busy||isRunning} onClick={apply} className="rounded border border-sky-700 p-2">모델·클래스 매핑 후 초안으로 열기</button></div>}
      </section>
      <section hidden={area==='edit'} className="space-y-2"><h3 className="text-sm font-bold">같은 이미지로 저장 버전 A/B 비교</h3><div className="grid grid-cols-2 gap-2">{[[va,setVa,'A'],[vb,setVb,'B']].map(([value,setter,label])=><label key={String(label)}>버전 {String(label)}<select aria-label={`비교 버전 ${label}`} value={value as string} onChange={e=>(setter as (v:string)=>void)(e.target.value)} className="w-full rounded bg-slate-800 p-2"><option value="">저장 버전 선택</option>{versions.map(v=><option key={v.version_id} value={v.version_id}>{v.name} · {new Date(v.saved_at).toLocaleString('ko-KR')}</option>)}</select></label>)}</div>
        {library==='available'?<details><summary className="cursor-pointer">고정 테스트 이미지 {testSet.length}/{TEST_SET_LIMIT}{unresolved.length?` · 확인 필요 ${unresolved.length}`:''} · 검증된 데이터 버전에서 선택</summary>
          {testSet.length>0&&<ul aria-label="선택한 고정 테스트 이미지" className="mt-2 flex flex-wrap gap-1">{testSet.map(image=><li key={image.image_uuid}><button type="button" title="선택 해제" onClick={()=>setTestSet(set=>toggleTestImage(set,image))} className="rounded border border-sky-800 px-1.5 py-0.5 font-mono text-[10px]">{image.relative_path} ✕</button></li>)}</ul>}
          {unresolved.length>0&&<ul aria-label="확인이 필요한 고정 테스트 이미지" className="mt-2 flex flex-wrap gap-1">{unresolved.map(image=><li key={image.image_uuid}><button type="button" title="저장 목록에서 빼기" onClick={()=>setUnresolved(rows=>rows.filter(row=>row.image_uuid!==image.image_uuid))} className="rounded border border-amber-700 px-1.5 py-0.5 font-mono text-[10px] text-amber-200">{image.relative_path} · {unresolvedReason(image)} ✕</button></li>)}</ul>}
          <div className="mt-2 flex h-[360px] flex-col"><ImageLibraryBrowser selectedIds={new Set(testSet.map(image=>image.image_uuid))} onPick={item=>setTestSet(set=>toggleTestImage(set,testImageFrom(item),unresolved.length))} onUnavailable={()=>setLibrary('unavailable')}/></div>
          {testSet.length+unresolved.length>=TEST_SET_LIMIT&&<p className="text-amber-200">최대 {TEST_SET_LIMIT}장까지 저장합니다(확인 필요 포함). 다른 이미지를 고르려면 선택을 해제하거나 확인 필요 항목을 빼세요.</p>}</details>
        :<details><summary className="cursor-pointer">고정 테스트 이미지 {testImages.length}/20 · 선택 (검증된 데이터 버전이 없어 처음 200장만 보이며 경로로 기억됩니다)</summary><div className="grid grid-cols-3 gap-2 max-h-44 overflow-auto mt-2">{images.map(im=><label key={im.file_path} className="truncate"><input type="checkbox" checked={testImages.includes(im.file_path)} disabled={!testImages.includes(im.file_path)&&testImages.length>=20} onChange={e=>setTestImages(s=>e.target.checked?[...s,im.file_path]:s.filter(x=>x!==im.file_path))}/><img src={resolveApiUrl(im.thumbnail_url)} alt={im.file_name} className="h-12 w-full object-contain"/>{im.file_name}</label>)}</div></details>}
        <div className="grid grid-cols-2 gap-2"><label>비교 실행 대상<select aria-label="플로우 비교 실행 대상" value={target} onChange={e=>{setTarget(e.target.value as 'local'|'selected_compute');setDevice(e.target.value==='local'?'cpu':'cuda');}} className="w-full rounded bg-slate-800 p-2"><option value="local">현재 백엔드</option><option value="selected_compute" disabled={!profile}>선택한 계산 서버</option></select></label><label>대상 장치<select aria-label="플로우 비교 장치" value={device} onChange={e=>setDevice(e.target.value)} className="w-full rounded bg-slate-800 p-2"><option value="cpu">CPU</option><option value="cuda">CUDA GPU</option>{target==='local'&&<option value="mps">Apple MPS</option>}</select></label></div><p className="text-slate-400">선택한 대상에서 두 버전을 실행합니다. 지원하지 않는 장치는 오류로 안내합니다. 공유 백엔드에 연결했다면 그 서버를 기준으로 실행합니다.</p>
        <button disabled={busy||isRunning||!va||!vb||va===vb||!testPaths.length||(target==='selected_compute'&&!profile)} onClick={compare} className="rounded border border-sky-700 p-2">{busy?'실행 중…':'선택 대상에서 비교 실행·결과 저장'}</button>
        <select aria-label="저장 비교 결과" value={comparison?.comparison_id||''} onChange={e=>setComparison(history.find(h=>h.comparison_id===e.target.value)||null)} className="w-full rounded bg-slate-800 p-2"><option value="">이전 비교 결과 다시 열기</option>{history.map(h=><option value={h.comparison_id} key={h.comparison_id}>{new Date(h.created_at).toLocaleString('ko-KR')} · {h.rows.length}장 · {h.status}</option>)}</select>
        {comparison?.rows.map(row=><div key={row.image_path} className="rounded border border-slate-700 p-2"><button className="text-sky-200 underline" onClick={()=>{setSelectedImage({source:'dataset',imagePath:row.image_path,fileName:row.file_name,thumbnailUrl:`/api/dataset/thumbnail/preview?file_path=${encodeURIComponent(row.image_path)}`});if(row.difference?.changed_nodes[0])selectNode(row.difference.changed_nodes[0]);onOpenImage();}}>{row.file_name}</button>{row.error?<p role="alert" className="text-amber-300">{row.error}</p>:<><p>{row.difference?.verdict_a} → {row.difference?.verdict_b} · {row.difference?.roi_changed?'ROI/영역 판정 변경':'ROI 동일'}</p><p className="text-slate-400">A: {row.difference?.reason_a}<br/>B: {row.difference?.reason_b}</p><p>변경 노드: {row.difference?.changed_nodes.join(', ')||'없음'}</p><details><summary>중간 이미지와 원본 해시</summary><p className="break-all">{row.image_sha256}</p><div className="grid grid-cols-2 gap-2">{[row.result_a,row.result_b].map((r,i)=><div key={i}>{r?.annotated_image&&<img alt={`버전 ${i?'B':'A'} 검사 결과`} src={r.annotated_image} className="w-full object-contain"/>}{r?.execution_steps.map(s=><p key={s.node_id}>{s.name}: {s.branch_verdict||s.status} ({s.input_count??0} → {s.output_count??0})</p>)}</div>)}</div></details></>}</div>)}
      </section>
    </div>{error&&<p role="alert" className="px-4 pb-3 text-amber-300">{error}</p>}{notice&&<p role="status" className="px-4 pb-3 text-sky-200">{notice}</p>}
  </details>;
}
