const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),Module=require('node:module'),ts=require('typescript'),crypto=require('node:crypto');
function load(){const file=path.join(__dirname,'distributionStatus.ts');assert.ok(fs.existsSync(file),'distribution manager must exist');const m=new Module(file,module);m.filename=file;m.paths=Module._nodeModulePaths(path.dirname(file));m._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,file);return m.exports;}
function fixture(t,extra={}){const {DistributionManager}=load(),directory=fs.mkdtempSync(path.join(os.tmpdir(),'desktop-distribution-'));t.after(()=>fs.rmSync(directory,{recursive:true,force:true}));return new DistributionManager({appVersion:'2.3.4',packaged:false,appPath:'/Application.app',executablePath:'/Application.app/executable',userDataPath:directory,platform:'darwin',arch:'arm64',...extra});}
function response(value){return new Response(typeof value==='string'?value:JSON.stringify(value),{status:200});}
test('actual app version and development state do not invent signing or updates',async t=>{const m=fixture(t,{runner:async()=>assert.fail('no signing in development')});const state=await m.status();assert.equal(state.app_version,'2.3.4');assert.equal(state.signature.status,'development');assert.equal(state.update.status,'not_configured');assert.equal(state.update.automatic_update_available,false);});
test('channel persists and validates target before presenting an update',async t=>{const m=fixture(t,{fetcher:async()=>response({version:'2.4.0',channel:'stable',platform:'win32',arch:'x64',url:'https://releases.example/app.exe',sha256:'a'.repeat(64),size:8})});await m.configure({channel:'stable',manifest_url:'https://releases.example/manifest.json'});await assert.rejects(()=>m.check(),/platform|architecture/);assert.equal((await m.status()).update.configured,true);await assert.rejects(()=>m.configure({channel:'stable',manifest_url:'http://unsafe.example/feed'}),/HTTPS/);});
test('bounded manifest and older release cannot become a candidate',async t=>{let value='x'.repeat(70*1024);const m=fixture(t,{fetcher:async()=>response(value)});await m.configure({channel:'stable',manifest_url:'https://releases.example/manifest.json'});await assert.rejects(()=>m.check(),/64 KiB/);value={version:'2.3.0',channel:'stable',platform:'darwin',arch:'arm64',url:'https://releases.example/app.dmg',sha256:'a'.repeat(64),size:8};assert.equal((await m.check()).update.status,'up_to_date');});
test('manual download checks bytes and cannot certify an unsigned artifact',async t=>{const bytes=Buffer.from('real artifact bytes'),release={version:'2.4.0',channel:'stable',platform:'darwin',arch:'arm64',url:'https://releases.example/app.dmg',sha256:crypto.createHash('sha256').update(bytes).digest('hex'),size:bytes.length};const m=fixture(t,{fetcher:async url=>String(url).endsWith('.dmg')?new Response(bytes):response(release),runner:async()=>{throw new Error('unsigned');}});await m.configure({channel:'stable',manifest_url:'https://releases.example/manifest.json'});await m.check();const result=await m.download();assert.equal(result.integrity_verified,true);assert.equal(result.handoff_ready,false);assert.equal(result.signature.status,'unsigned');assert.deepEqual(fs.readFileSync(result.path),bytes);});
test('changed feed or corrupt download never produces a manual delivery file',async t=>{const bytes=Buffer.from('wrong'),release={version:'2.4.0',channel:'stable',platform:'darwin',arch:'arm64',url:'https://releases.example/app.dmg',sha256:'a'.repeat(64),size:bytes.length};const m=fixture(t,{fetcher:async url=>String(url).endsWith('.dmg')?new Response(bytes):response(release)});await m.configure({channel:'stable',manifest_url:'https://releases.example/manifest.json'});await m.check();await assert.rejects(()=>m.download(),/checksum/);assert.equal(fs.existsSync(path.join(m.options.userDataPath,'updates'))&&fs.readdirSync(path.join(m.options.userDataPath,'updates')).some(x=>!x.startsWith('.')),false);});
test('a valid native signature needs a real publisher identifier',async t=>{let text='Signature=adhoc\nTeamIdentifier=not set';const m=fixture(t,{packaged:true,runner:async()=>({stdout:'',stderr:text})});assert.equal((await m.status()).signature.status,'unsigned');text='TeamIdentifier=not set';assert.equal((await m.status()).signature.status,'unsigned');text='Authority=Developer ID Application\nTeamIdentifier=ACTUAL-TEST-OUTPUT';assert.equal((await m.status()).signature.status,'verified');});
test('configuration change during a pending request cannot publish an old candidate',async t=>{let resolve;const m=fixture(t,{fetcher:()=>new Promise(r=>{resolve=r;})});await m.configure({channel:'stable',manifest_url:'https://releases.example/manifest.json'});const check=m.check();await m.configure(null);resolve(response({}));await assert.rejects(()=>check,/configuration changed/);assert.equal((await m.status()).update.configured,false);});
