const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto'),Module=require('node:module'),ts=require('typescript');
function load(name='portableUpdate.ts'){const file=path.join(__dirname,name),m=new Module(file,module);m.filename=file;m.paths=Module._nodeModulePaths(path.dirname(file));const requireOriginal=m.require.bind(m);m.require=k=>k==='./releaseTrust'?load('releaseTrust.ts'):requireOriginal(k);m._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,file);return m.exports;}
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
function setup(t,extra={}){const directory=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'portable-update-main-')));t.after(()=>fs.rmSync(directory,{recursive:true,force:true}));const resources=path.join(directory,'resources'),root=path.join(directory,'owned'),user=path.join(directory,'current-user');fs.mkdirSync(resources);fs.mkdirSync(root);fs.mkdirSync(user);fs.mkdirSync(path.join(resources,'backend_bin'));const binary=Buffer.from('controlled runtime file');fs.writeFileSync(path.join(resources,'backend_bin/vision_ai_backend'),binary);fs.writeFileSync(path.join(resources,'backend_bin/backend-release.json'),JSON.stringify({executable:'vision_ai_backend',executable_sha256:hash(binary),inventory:{build_identity_sha256:'a'.repeat(64),platform:'Darwin',architecture:'arm64'}}));const pair=crypto.generateKeyPairSync('ed25519');fs.writeFileSync(path.join(resources,'release-trust.json'),JSON.stringify({schema_version:1,publisher:'controlled-publisher',keys:{fixture:pair.publicKey.export({type:'spki',format:'der'}).toString('base64')},revoked_key_ids:[],allowed_origins:['https://release.example.test'],compatibility:{api_context:1,worker:1,runtime:1,dataset_index:1}}));const calls=[];let mutate;
const status={status:'ready',installation_id:'b'.repeat(32),version:'0.0.0',update_id:null,database_fence:0,allowed_recovery:[],application_started:false};
const review={status:'reviewed',installation_id:status.installation_id,plan_sha256:'c'.repeat(64),source_sha256:'d'.repeat(64),envelope_sha256:'e'.repeat(64),authority_sha256:hash(fs.readFileSync(path.join(resources,'release-trust.json'))),version:'1.0.0',current_version:'0.0.0',publisher:'controlled-publisher',channel:'stable',application_file_count:1,pack_count:0,artifact_bytes:100,database_fence:0,copied_session_policy:'revoked',application_started:false};
const {PortableUpdateManager}=load(),m=new PortableUpdateManager({packaged:true,platform:'darwin',arch:'arm64',resourcesPath:resources,userDataPath:user,appPath:path.join(directory,'Current.app'),signature:async()=>({status:'verified',publisher:'controlled-publisher'}),runner:async(file,args)=>{calls.push({file,args});if(mutate)await mutate(file,args);const cmd=args[1];return {stdout:JSON.stringify(cmd==='inspect'?status:cmd==='preview'?review:{status:'committed',update_id:'f'.repeat(32),version:'1.0.0',database_pointer:{fence:1}}),stderr:''};},...extra});return {m,directory,resources,root,user,calls,status,review,setMutate:f=>mutate=f};}
test('selection inspects an owned external installation; preparation is read-only',async t=>{const f=setup(t);await f.m.select(f.root);const preview=await f.m.preview(path.join(f.directory,'signed.json'),'stable');assert.ok(preview.review_id);assert.equal(preview.version,'1.0.0');assert.deepEqual(f.calls.map(c=>c.args[1]),['inspect','preview']);assert.equal(f.calls[1].args.includes('--use-owned-version'),true);assert.equal(f.calls[1].file,path.join(f.resources,'backend_bin/vision_ai_backend'));assert.equal(fs.readdirSync(f.root).length,0);});
test('a different or replayed UI review cannot install',async t=>{const f=setup(t);await f.m.select(f.root);const preview=await f.m.preview(path.join(f.directory,'signed.json'),'stable');await assert.rejects(()=>f.m.apply('wrong'),/review/i);assert.equal(f.calls.some(c=>c.args[1]==='install'),false);await f.m.apply(preview.review_id);const install=f.calls.find(c=>c.args[1]==='install');assert.equal(install.args[install.args.indexOf('--expected-plan-sha256')+1],f.review.plan_sha256);await assert.rejects(()=>f.m.apply(preview.review_id),/review/i);assert.equal(f.calls.filter(c=>c.args[1]==='install').length,1);});
test('failed or response-lost install requires readback instead of automatic retry',async t=>{const f=setup(t);await f.m.select(f.root);const p=await f.m.preview(path.join(f.directory,'signed.json'),'stable');f.setMutate((_file,args)=>{if(args[1]==='install')throw Error('controlled response loss');});await assert.rejects(()=>f.m.apply(p.review_id),/response loss/);await assert.rejects(()=>f.m.apply(p.review_id),/review/i);f.setMutate(null);await f.m.inspect();assert.equal(f.calls.filter(c=>c.args[1]==='install').length,1);});
for(const scope of ['current','parent','child','linked'])test(`selection refuses ${scope} current-home overlap or link`,async t=>{const f=setup(t);let root=f.user;if(scope==='parent')root=f.directory;if(scope==='child'){root=path.join(f.user,'nested');fs.mkdirSync(root);}if(scope==='linked'){root=path.join(f.directory,'alias');fs.symlinkSync(f.root,root);}await assert.rejects(()=>f.m.select(root),/current|link/i);assert.equal(f.calls.length,0);});
test('selected paths and review cannot change during a pending command',async t=>{const f=setup(t);await f.m.select(f.root);let release;f.setMutate((_file,args)=>args[1]==='preview'?new Promise(r=>release=r):undefined);const pending=f.m.preview(path.join(f.directory,'signed.json'),'stable');while(!release)await new Promise(r=>setImmediate(r));await assert.rejects(()=>f.m.select(f.root),/progress/i);await assert.rejects(()=>f.m.inspect(),/progress/i);release();await pending;});
test('runtime bytes or pinned authority changing after native checks refuse execution',async t=>{const f=setup(t);await f.m.select(f.root);let once=true;f.m.options.signature=async()=>{if(once){once=false;fs.appendFileSync(path.join(f.resources,'backend_bin/vision_ai_backend'),'changed');}return {status:'verified',publisher:'controlled-publisher'};};await assert.rejects(()=>f.m.preview(path.join(f.directory,'signed.json'),'stable'),/runtime|checksum|changed/i);assert.equal(f.calls.length,1);});
test('unsigned publisher and development mode cannot install or inspect',async t=>{for(const extra of [{packaged:false},{signature:async()=>({status:'unsigned'})},{platform:'win32'}]){const f=setup(t,extra);await assert.rejects(()=>f.m.select(f.root),/packaged|publisher|POSIX/i);assert.equal(f.calls.length,0);}});
test('recovery only uses the selected current intent and allowed action',async t=>{const f=setup(t);Object.assign(f.status,{status:'recovery_required',update_id:'f'.repeat(32),version:'1.0.0',allowed_recovery:['finish']});await f.m.select(f.root);await assert.rejects(()=>f.m.recover('abort',{installation_id:f.status.installation_id,update_id:f.status.update_id}),/recovery/i);await f.m.recover('finish',{installation_id:f.status.installation_id,update_id:f.status.update_id});const cmd=f.calls.find(c=>c.args[1]==='recover');assert.equal(cmd.args[cmd.args.indexOf('--intent')+1],f.status.update_id);assert.ok(cmd.args.includes('--pinned-authority-sha256'));});

test('a stale window recovery view cannot mutate a newly selected installation',async t=>{const f=setup(t);Object.assign(f.status,{status:'committed',update_id:'f'.repeat(32),allowed_recovery:['finish','forward']});await f.m.select(f.root);await assert.rejects(()=>f.m.recover('forward',{installation_id:'1'.repeat(32),update_id:f.status.update_id}),/installation/);await assert.rejects(()=>f.m.recover('forward',{installation_id:f.status.installation_id,update_id:'2'.repeat(32)}),/intent/);assert.equal(f.calls.some(c=>c.args[1]==='recover'),false);});
