const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),Module=require('node:module'),ts=require('typescript');
function load(){const file=path.join(__dirname,'releaseTrust.ts'),m=new Module(file,module);m.filename=file;m.paths=Module._nodeModulePaths(__dirname);m._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,file);return m.exports;}
function fixture(){const {publicKey,privateKey}=crypto.generateKeyPairSync('ed25519');const bytes=Buffer.from('owned installer fixture');const artifact={path:'application.dmg',kind:'installer',sha256:crypto.createHash('sha256').update(bytes).digest('hex'),size:bytes.length};
 const compatibility={api_context:1,worker:1,runtime:1,dataset_index:3};const root={schema_version:1,publisher:'fixture-publisher',keys:{'rotation-2':publicKey.export({type:'spki',format:'der'}).toString('base64')},revoked_key_ids:['retired-1'],allowed_origins:['https://releases.test'],compatibility};
 const value={version:'2.4.0',channel:'stable',platform:'darwin',arch:'arm64',url:'https://releases.test/application.dmg',sha256:artifact.sha256,size:artifact.size,publisher:root.publisher,compatibility,artifacts:[artifact]};
 const canonical=v=>v===null||typeof v!=='object'?JSON.stringify(v):Array.isArray(v)?'['+v.map(canonical).join(',')+']':'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}';
 const sign=(payload=value,key_id='rotation-2')=>{const raw=Buffer.from(canonical(payload));return {schema_version:1,key_id,payload_b64:raw.toString('base64'),signature_b64:crypto.sign(null,raw,privateKey).toString('base64')};};
 return {root,value,bytes,sign,target:{platform:'darwin',arch:'arm64',channel:'stable',current_version:'2.3.4',origin:'https://releases.test'}};
}
test('a pinned rotation key verifies the publisher, exact target, protocols and package inventory',()=>{const f=fixture();assert.deepEqual(load().verifySignedRelease(f.sign(),f.root,f.target),f.value);});
test('pinned authority is a bounded regular resource and replacement during its read is refused',t=>{
 const root=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'release-authority-'))),file=path.join(root,'authority.json'),old=path.join(root,'old.json');t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const f=fixture(),{readTrustAuthority}=load();fs.writeFileSync(file,JSON.stringify(f.root));assert.deepEqual(readTrustAuthority(file),f.root);
 const read=fs.readSync;let changed=false;fs.readSync=function(...args){const count=read.apply(fs,args);if(count&&!changed){changed=true;fs.renameSync(file,old);fs.writeFileSync(file,JSON.stringify(f.root));}return count;};try{assert.throws(()=>readTrustAuthority(file),/identity changed/);}finally{fs.readSync=read;}
 fs.writeFileSync(file,'x'.repeat(32769));assert.throws(()=>readTrustAuthority(file),/bound/);
});
test('manifest edits, unpinned or revoked keys and another publisher are refused',()=>{const f=fixture(),{verifySignedRelease}=load();const altered=f.sign();altered.payload_b64=Buffer.from(JSON.stringify({...f.value,version:'9.9.9'})).toString('base64');assert.throws(()=>verifySignedRelease(altered,f.root,f.target),/canonical|signature/);
 for(const id of ['unknown','retired-1'])assert.throws(()=>verifySignedRelease(f.sign(f.value,id),f.root,f.target),/key/);
 assert.throws(()=>verifySignedRelease(f.sign({...f.value,publisher:'another-publisher'}),f.root,f.target),/publisher/);
});
test('downgrade, wrong target/protocol/origin and ambiguous inventory cannot reach handoff',()=>{const f=fixture(),{verifySignedRelease}=load();for(const change of [{version:'2.3.0'},{platform:'win32'},{compatibility:{...f.value.compatibility,worker:2}},{url:'https://another.test/application.dmg'},{artifacts:[]},{artifacts:[...f.value.artifacts,...f.value.artifacts]},{artifacts:[{...f.value.artifacts[0],path:'../application.dmg'}]}])assert.throws(()=>verifySignedRelease(f.sign({...f.value,...change}),f.root,f.target));});
test('offline verification rejects missing/extra/changed packs and links, preserving the directory',t=>{const f=fixture(),{verifyOfflineRelease}=load(),root=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'offline-release-')));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const artifact=path.join(root,'application.dmg');fs.writeFileSync(artifact,f.bytes);assert.equal(verifyOfflineRelease(root,f.sign(),f.root,f.target).artifacts_verified,1);
 fs.writeFileSync(path.join(root,'extra.bin'),'unknown');assert.throws(()=>verifyOfflineRelease(root,f.sign(),f.root,f.target),/inventory/);fs.unlinkSync(path.join(root,'extra.bin'));fs.writeFileSync(artifact,'changed');assert.throws(()=>verifyOfflineRelease(root,f.sign(),f.root,f.target),/size|checksum/);fs.unlinkSync(artifact);assert.throws(()=>verifyOfflineRelease(root,f.sign(),f.root,f.target),/inventory/);const outside=path.join(root,'..',path.basename(root)+'-outside');fs.writeFileSync(outside,f.bytes);t.after(()=>fs.rmSync(outside,{force:true}));fs.symlinkSync(outside,artifact);assert.throws(()=>verifyOfflineRelease(root,f.sign(),f.root,f.target),/link/);assert.equal(fs.readFileSync(outside).toString(),f.bytes.toString());});
test('a directory or file identity changed during hashing cannot produce a verified offline inventory',t=>{const f=fixture(),{verifyOfflineRelease}=load();for(const change of ['extra','replace']){const root=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'offline-race-'))),outside=root+'-old';t.after(()=>{fs.rmSync(root,{recursive:true,force:true});fs.rmSync(outside,{force:true});});const file=path.join(root,'application.dmg');fs.writeFileSync(file,f.bytes);const read=fs.readSync;let once=false;fs.readSync=function(...args){const size=read.apply(fs,args);if(size&&!once){once=true;if(change==='extra')fs.writeFileSync(path.join(root,'late.bin'),'late');else {fs.renameSync(file,outside);fs.writeFileSync(file,f.bytes);}}return size;};try{assert.throws(()=>verifyOfflineRelease(root,f.sign(),f.root,f.target),/identity|inventory/);}finally{fs.readSync=read;}}});

test('bounded manifest read refuses growth and path replacement before JSON parsing',t=>{
 const root=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'bounded-release-'))),file=path.join(root,'release.json');t.after(()=>fs.rmSync(root,{recursive:true,force:true}));
 const {readBoundedStableFile}=load();fs.writeFileSync(file,'{}');assert.equal(readBoundedStableFile(file,64).toString(),'{}');
 const read=fs.readSync;let once=false;fs.readSync=function(...args){const size=read.apply(fs,args);if(size&&!once){once=true;fs.appendFileSync(file,' '.repeat(100));}return size;};
 try{assert.throws(()=>readBoundedStableFile(file,64),/changed|bound/);}finally{fs.readSync=read;}
 assert.throws(()=>readBoundedStableFile(file,64),/bound/);
});
