const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),ts=require('typescript');
function load(name,mocks){const file=path.resolve(__dirname,name),m=new Module(file,module);m.filename=file;m.paths=Module._nodeModulePaths(__dirname);const req=m.require.bind(m);m.require=id=>{if(mocks[id])return mocks[id];if(id.startsWith('.')&&fs.existsSync(path.resolve(path.dirname(file),id)+'.ts'))return load(id+'.ts',mocks);return req(id);};m._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText,file);return m.exports;}
function hooks(){let cursor=0;const slots=[],effects=[];return{react:{useState:v=>{const i=cursor++;if(!(i in slots))slots[i]=typeof v==='function'?v():v;return[slots[i],v=>slots[i]=typeof v==='function'?v(slots[i]):v];},useRef:v=>{const i=cursor++;if(!(i in slots))slots[i]={current:v};return slots[i];},useSyncExternalStore:(_,read)=>read(),useEffect:(fn,deps)=>{const i=cursor++;if(!slots[i]||deps.some((v,j)=>v!==slots[i].deps[j])){slots[i]?.cleanup?.();slots[i]={deps};effects.push(()=>slots[i].cleanup=fn());}}},render:fn=>{cursor=0;const result=fn();effects.splice(0).forEach(fn=>fn());return result;},unmount:()=>slots.forEach(s=>s?.cleanup?.())};}
const jsx=(type,props)=>({type,props:props||{},children:[props?.children].flat().filter(Boolean)});function nodes(t){return t&&typeof t==='object'?[t,...(t.children||[]).flat().flatMap(nodes)]:[];}
function fixture(){
 const h=hooks(),values=new Map(),listeners=new Set();let epoch=1,read;
 Object.defineProperty(globalThis,'localStorage',{configurable:true,value:{getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)}});globalThis.window={addEventListener(){},removeEventListener(){}};
 const project={projectDir:'/owned/p',project:{id:'p',task:'segmentation',source_dataset_dir:'/source',active_labelset_id:'default'}},context={project_id:'p',workspace_id:'w',actor_id:'a'};
 const meta={image_uuid:'a',file_path:'/source/a.png',content_hash:'a'.repeat(64),revision:1,width:32,height:32},initial=[{id:'server',type:'bbox',label:'Scratch',bbox:[1,2,3,4]}],local=[{id:'local',type:'bbox',label:'Scratch',bbox:[5,6,7,8]}];
 const state={currentImage:{image_id:'a',file_path:meta.file_path},task:'segmentation',reviewerName:'actor',metadata:meta,annotations:initial,history:[],future:[],isDirty:false,isSaving:false,annotationLoadStatus:'ready',loadedAnnotationContext:JSON.stringify(['local',epoch,'/source','segmentation'])};
 const annotation=Object.assign(()=>state,{getState:()=>state,setState:v=>{Object.assign(state,v);listeners.forEach(fn=>fn());},subscribe:fn=>{listeners.add(fn);return()=>listeners.delete(fn);}}),store=v=>Object.assign(selector=>selector?selector(v):v,{getState:()=>v});
 const workflow={annotations:()=>read?read():Promise.resolve({metadata:{...meta,revision:2},annotations:initial})};
 const m=load('./AnnotationDraftRecovery.tsx',{'react':h.react,'react/jsx-runtime':{jsx,jsxs:jsx},'../../stores/useAnnotationStore':{useAnnotationStore:annotation},'../../stores/useDatasetStore':{useDatasetStore:store({folderPath:'/source'})},'../../stores/useProjectStore':{useProjectStore:store(project)},'../../services/api':{getApiPersistenceIdentity:()=> 'local',getProjectContext:()=>context,getProjectContextGeneration:()=>epoch,subscribeProjectContext:()=>()=>{}},'../../services/datasetWorkflow':{datasetWorkflow:workflow,workflowError:e=>e.message},'../common/WorkspaceDialog':{WorkspaceDialog:()=>{}}});
 const render=()=>h.render(()=>m.AnnotationDraftRecovery()),button=(t,name)=>nodes(t).find(n=>n.type==='button'&&n.children.includes(name));
 const seed=()=>{render();annotation.setState({annotations:local,isDirty:true});render();annotation.setState({annotations:initial,isDirty:false});render();};
 return{h,values,state,annotation,meta,initial,local,render,button,seed,setRead:fn=>read=fn,accountChange:()=>{context.actor_id='b';epoch++;}};
}
async function preview(f){let t=f.render();await f.button(t,'저장 전 초안 비교·복구').props.onClick();t=f.render();nodes(t).find(n=>n.type==='input'&&n.props.type==='checkbox').props.onChange({target:{checked:true}});return f.render();}
test('late draft apply preserves edits made while the current server label is being read',async()=>{const f=fixture();try{f.seed();assert.equal(f.values.size,1);let t=await preview(f),resolve;f.setRead(()=>new Promise(done=>resolve=done));const pending=f.button(t,'비교한 초안을 명시적으로 적용').props.onClick();const concurrent=[{id:'new-edit',type:'tag',label:'OK'}];f.annotation.setState({annotations:concurrent,isDirty:true});resolve({metadata:{...f.meta,revision:2},annotations:f.initial});await pending;t=f.render();assert.equal(f.state.annotations,concurrent);assert.ok(nodes(t).some(n=>n.props.role==='alert'&&n.children.some(v=>String(v).includes('현재 편집 내용'))));assert.equal(f.values.size,1);}finally{f.h.unmount();}});
test('a late same-project comparison cannot expose the previous account draft',async()=>{const f=fixture();try{f.seed();let resolve;f.setRead(()=>new Promise(done=>resolve=done));const pending=f.button(f.render(),'저장 전 초안 비교·복구').props.onClick();f.accountChange();f.render();resolve({metadata:f.meta,annotations:f.initial});await pending;const t=f.render();assert.equal(f.button(t,'비교한 초안을 명시적으로 적용'),undefined);assert.equal(f.button(t,'저장 전 초안 비교·복구'),undefined);assert.equal(f.values.size,1);assert.deepEqual(f.state.annotations,f.initial);}finally{f.h.unmount();}});
test('source replacement after comparison refuses draft application and preserves server labels',async()=>{const f=fixture();try{f.seed();let t=await preview(f);f.setRead(async()=>({metadata:{...f.meta,revision:2,content_hash:'b'.repeat(64)},annotations:f.initial}));await f.button(t,'비교한 초안을 명시적으로 적용').props.onClick();t=f.render();assert.deepEqual(f.state.annotations,f.initial);assert.ok(nodes(t).some(n=>n.props.role==='alert'&&n.children.some(v=>String(v).includes('원본 이미지나 크기'))));assert.equal(f.values.size,1);}finally{f.h.unmount();}});
