import React,{useEffect,useRef,useState} from 'react';
import {resolveApiUrl,getApiPersistenceIdentity} from '../../services/api';
import {host,hostErrorMessage} from '../../services/hostAdapter';
import {dataWorkbench,dataWorkbenchScope,type DerivedVersion} from '../../services/dataWorkbench';
import {workflowError} from '../../services/datasetWorkflow';
import {useComputeStore} from '../../stores/useComputeStore';
import {useProjectStore} from '../../stores/useProjectStore';
import {useAnnotationStore} from '../../stores/useAnnotationStore';
import {cropPoint,cropRectangle} from './productDataWorkflow';
import type {AnnotationItem} from '../../types';
const button='rounded border border-slate-600 px-3 py-2 disabled:opacity-40';
function outline(a:AnnotationItem):string|undefined{
 if(a.polygon?.length)return a.polygon.map(p=>p.join(',')).join(' ');
 if(a.rotated_bbox){const [cx,cy,w,h,angle]=a.rotated_bbox;const r=angle*Math.PI/180;return [[-w/2,-h/2],[w/2,-h/2],[w/2,h/2],[-w/2,h/2]].map(([x,y])=>`${cx+x*Math.cos(r)-y*Math.sin(r)},${cy+x*Math.sin(r)+y*Math.cos(r)}`).join(' ');}
 if(a.bbox){const [x1,y1,x2,y2]=a.bbox;return `${x1},${y1} ${x2},${y1} ${x2},${y2} ${x1},${y2}`;}return undefined;
}
export const DerivedImagePanel:React.FC=()=>{
 const project=useProjectStore();const compute=useComputeStore();const {currentImage,metadata,isDirty,isSaving,annotationLoadStatus,annotations,reviewerName}=useAnnotationStore();
 const scope=`${dataWorkbenchScope({...project,...compute,apiTransportIdentity:getApiPersistenceIdentity()})}\n${currentImage?.file_path||''}`;const current=useRef(scope);current.current=scope;
 const [loaded,setLoaded]=useState<{scope:string;versions:DerivedVersion[]}|null>(null);const [selected,setSelected]=useState('');
 const [crop,setCrop]=useState<[number,number,number,number]|null>(null);const [anchor,setAnchor]=useState<[number,number]|null>(null);const [cropMode,setCropMode]=useState(false);
 const [brightness,setBrightness]=useState(1);
 const [alignAngle,setAlignAngle]=useState(0);const [reviewNote,setReviewNote]=useState('');const [branchName,setBranchName]=useState('검수한 파생 이미지 학습 버전');
 const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');
 const versions=loaded?.scope===scope?loaded.versions:[];const version=versions.find(row=>row.id===selected);
 const size:readonly[number,number]=version?.size||[metadata?.width||1,metadata?.height||1];const rows=version?.annotations||annotations;
 const same=()=>`${dataWorkbenchScope({...useProjectStore.getState(),...useComputeStore.getState(),apiTransportIdentity:getApiPersistenceIdentity()})}\n${useAnnotationStore.getState().currentImage?.file_path||''}`===scope;
 useEffect(()=>{let active=true;setLoaded(null);setSelected('');setCrop(null);setCropMode(false);setBusy(false);setError('');setNotice('');
  if(currentImage)void dataWorkbench.derivedHistory(currentImage.file_path).then(result=>{if(active&&same())setLoaded({scope,versions:result.versions});}).catch(cause=>{if(active&&same())setError(workflowError(cause));});return()=>{active=false;};
 },[scope]);
 const edit=async(operation:Record<string,unknown>)=>{
  if(!currentImage||!metadata||!same()||isDirty||isSaving)return;
  if(!reviewerName.trim()){setError('이미지 정보·검토에서 작업자 이름을 입력하세요.');return;}
  setBusy(true);setError('');setNotice('');try{
   const next=await dataWorkbench.derive({image_path:currentImage.file_path,expected_revision:metadata.revision,expected_sha256:metadata.content_hash,operation,actor:reviewerName,...(selected?{parent_id:selected}:{})});
   if(same()){setLoaded({scope,versions:[...versions,next]});setSelected(next.id);setCrop(null);setCropMode(false);setNotice(`파생 이미지와 라벨 ${next.annotations.length}개를 새 버전으로 저장했습니다.${next.omitted_annotation_ids.length?` 영역 밖 라벨 ${next.omitted_annotation_ids.length}개 제외.`:''}`);}
  }catch(cause){if(same())setError(workflowError(cause));}finally{if(same())setBusy(false);}
 };
 const review=async(decision:'approve'|'reject')=>{
  if(!version||!same())return;setBusy(true);setError('');setNotice('');
  try{const row=await dataWorkbench.reviewDerived(version,reviewerName,decision,reviewNote);if(same()){setLoaded({scope,versions:versions.map(old=>old.id===row.id?row:old)});setNotice(decision==='approve'?'파생 이미지와 변환 라벨의 검수 기록을 저장했습니다.':'파생본 제외 검수를 저장했습니다.');}}
  catch(cause){if(same())setError(workflowError(cause));}finally{if(same())setBusy(false);}
 };
 if(!currentImage)return null;
 const disabled=busy||isDirty||isSaving||annotationLoadStatus!=='ready';
 const imageUrl=version?resolveApiUrl(version.image_url):resolveApiUrl(`/api/dataset/raw/${encodeURIComponent(currentImage.file_name)}?file_path=${encodeURIComponent(currentImage.file_path)}`);
 return <details className="shrink-0 border-b border-slate-700 bg-[#111D2B] text-xs"><summary className="cursor-pointer px-4 py-2 font-semibold text-cyan-100">원본 보존 이미지 편집 · 파생 버전 {versions.length}개</summary><section aria-label="파생 이미지 편집" className="max-h-[65vh] space-y-3 overflow-auto px-4 pb-4">
  <p className="text-slate-300">현재 저장 라벨을 함께 변환합니다. 자르기·회전·각도 정렬·반전·밝기 결과는 별도 이미지와 변경 기록으로 저장됩니다. 학습에 사용하기 전 변환 라벨을 검수하세요. 일부만 잘리는 회전 박스는 다각형으로 바꾼 후 편집하세요.</p>
  <label>편집 기준<select aria-label="파생 편집 기준 버전" disabled={busy} value={selected} onChange={e=>{setSelected(e.target.value);setCrop(null);setCropMode(false);setReviewNote('');}} className="ml-2 rounded border border-slate-600 bg-slate-900 p-2"><option value="">원본과 현재 저장 라벨</option>{versions.map((row,index)=><option key={row.id} value={row.id}>버전 {index+1} · {row.operation.kind==='crop'?'자르기':row.operation.kind==='rotate'?'회전':row.operation.kind==='align'?`정렬 ${row.operation.degrees}°`:row.operation.kind==='brightness'?`밝기 ${row.operation.factor}배`:'반전'} · {new Date(row.created_at*1000).toLocaleString('ko-KR')}</option>)}</select></label>
  <div className="flex flex-wrap gap-2"><button type="button" disabled={disabled} className={`${button} ${cropMode?'border-cyan-400 text-cyan-200':''}`} onClick={()=>{setCropMode(!cropMode);setCrop(null);}}>이미지에서 자르기 영역 선택</button>{[90,180,270].map(degrees=><button type="button" disabled={disabled} className={button} key={degrees} onClick={()=>void edit({kind:'rotate',degrees})}>{degrees}° 회전</button>)}<button type="button" disabled={disabled} className={button} onClick={()=>void edit({kind:'flip',axis:'horizontal'})}>좌우 반전</button><button type="button" disabled={disabled} className={button} onClick={()=>void edit({kind:'flip',axis:'vertical'})}>상하 반전</button></div>
  <div className="flex flex-wrap items-center gap-2"><label>밝기 배율<input aria-label="파생 이미지 밝기 배율" type="number" min="0" max="4" step="0.1" value={brightness} onChange={event=>setBrightness(Number(event.target.value))} className="ml-2 w-20 rounded border border-slate-600 bg-slate-900 p-2"/></label><button type="button" disabled={disabled||!Number.isFinite(brightness)||brightness<0||brightness>4} className={button} onClick={()=>void edit({kind:'brightness',factor:brightness})}>밝기 새 버전 저장</button><span className="text-slate-400">1 = 원본 밝기 · 0–4 배</span></div>
  <div className="flex flex-wrap items-center gap-2"><label>시계 방향 정렬 각도<input aria-label="파생 이미지 정렬 각도" type="number" min="-180" max="180" step="0.1" value={alignAngle} onChange={event=>setAlignAngle(Number(event.target.value))} className="ml-2 w-20 rounded border border-slate-600 bg-slate-900 p-2"/></label><button type="button" disabled={disabled||!Number.isFinite(alignAngle)||alignAngle<-180||alignAngle>180} className={button} onClick={()=>void edit({kind:'align',degrees:alignAngle})}>정렬 새 버전 저장</button><span className="text-slate-400">전체 영역을 보존합니다. 박스는 다각형으로 변환하며 빈 가장자리는 검수가 필요합니다.</span></div>
  <svg role="img" aria-label="편집 원본과 변환 라벨 미리보기" viewBox={`0 0 ${size[0]} ${size[1]}`} preserveAspectRatio="xMidYMid meet" className={`max-h-[360px] min-h-[180px] w-full rounded border border-slate-700 bg-black ${cropMode?'cursor-crosshair':''}`} onPointerDown={event=>{if(!cropMode||disabled)return;const point=cropPoint(event.currentTarget.getBoundingClientRect(),size,[event.clientX,event.clientY]);if(point){event.currentTarget.setPointerCapture(event.pointerId);setAnchor(point);setCrop(cropRectangle(point,point,size));}}} onPointerMove={event=>{if(!anchor||!cropMode)return;const point=cropPoint(event.currentTarget.getBoundingClientRect(),size,[event.clientX,event.clientY]);if(point)setCrop(cropRectangle(anchor,point,size));}} onPointerUp={()=>setAnchor(null)} onPointerCancel={()=>setAnchor(null)}>
   <image href={imageUrl} width={size[0]} height={size[1]}/>{rows.map((row,index)=>row.type==='brush_mask'?<image key={row.id||index} href={row.mask_rle} width={size[0]} height={size[1]} opacity={.4}/>:outline(row)&&<polygon key={row.id||index} points={outline(row)} fill="none" stroke={row.color||'#22d3ee'} strokeWidth={Math.max(...size)/250}/>)}{crop&&<rect x={crop[0]} y={crop[1]} width={crop[2]-crop[0]} height={crop[3]-crop[1]} fill="#fbbf2430" stroke="#fbbf24" strokeWidth={Math.max(...size)/200}/>}
  </svg>
  {cropMode&&<div className="flex flex-wrap items-center gap-2">{(['왼쪽','위','오른쪽','아래'] as const).map((name,index)=><label key={name}>{name}<input aria-label={`자르기 ${name} 좌표`} type="number" step="1" value={crop?.[index]??(index<2?0:size[index%2])} onChange={e=>setCrop(old=>{const next:[number,number,number,number]=old?[...old]:[0,0,size[0],size[1]];next[index]=Number(e.target.value);return next;})} className="ml-1 w-20 rounded border border-slate-600 bg-slate-900 p-2"/></label>)}<button type="button" disabled={disabled||!crop||crop[0]>=crop[2]||crop[1]>=crop[3]} className={`${button} border-cyan-600`} onClick={()=>crop&&void edit({kind:'crop',rect:crop})}>자르기 새 버전 저장</button></div>}
  {isDirty&&<p className="text-amber-200">라벨을 저장한 뒤 이미지 편집을 실행하세요.</p>}{busy&&<p role="status">이미지와 라벨을 새 버전으로 저장하는 중…</p>}{error&&<p role="alert" className="text-rose-200">{error}</p>}{notice&&<p role="status" className="text-emerald-200">{notice}</p>}
  {version&&<><div className="space-y-2 rounded border border-slate-700 p-3" aria-label="파생본 검수와 학습 연결"><p>검수 {version.review?`${version.review.decision==='approve'?'채택 후보':'제외'} · ${version.review.actor}`:'대기'} · 작업자 {reviewerName||'이미지 정보·검토에서 이름 입력'}</p><input aria-label="파생본 검수 근거" value={reviewNote} maxLength={2000} onChange={e=>setReviewNote(e.target.value)} placeholder="변환 좌표·라벨·가장자리 검수 근거" className="w-full rounded border border-slate-600 bg-slate-900 p-2"/><div className="flex flex-wrap gap-2"><button type="button" className={button} disabled={disabled||!reviewerName.trim()||!reviewNote.trim()} onClick={()=>void review('approve')}>변환 이미지·라벨 검수 후 채택 후보</button><button type="button" className={button} disabled={disabled||!reviewerName.trim()||!reviewNote.trim()} onClick={()=>void review('reject')}>파생본 제외 검수</button></div><input aria-label="파생본 새 학습 데이터 이름" value={branchName} maxLength={200} onChange={e=>setBranchName(e.target.value)} className="w-full rounded border border-slate-600 bg-slate-900 p-2"/><button type="button" className={button} disabled={disabled||version.review?.decision!=='approve'||!reviewerName.trim()||!branchName.trim()} onClick={()=>{if(!same())return;setBusy(true);setError('');void dataWorkbench.adoptDerived([version.id],reviewerName,branchName).then(row=>{if(same()){setNotice(`새 학습 데이터 ${row.name}를 저장했습니다. 1단계의 파생 편집 데이터 버전에서 명시적으로 선택하세요.`);window.dispatchEvent(new Event('derived-adoptions-changed'));}}).catch(cause=>{if(same())setError(workflowError(cause));}).finally(()=>{if(same())setBusy(false);});}}>검수한 파생본으로 새 학습 데이터 저장</button><p className="text-amber-200">고정 분할의 학습 원본만 채택하며 검증·시험 이미지는 보존합니다. 새 이미지는 학습 제외·라벨 검토 필요로 시작합니다. 원본 선택·학습 포함·새 학습·동일 시험 비교·모델 재승인은 각각 확인합니다.</p></div><button type="button" className={button} onClick={()=>void host.openPath(version.dataset_path).catch(cause=>setError(hostErrorMessage(cause,'저장 폴더를 열 수 없습니다.')))}>파생 이미지·라벨 저장 폴더 열기</button><details><summary className="cursor-pointer text-slate-400">버전 출처와 보존 해시</summary><pre className="max-h-40 overflow-auto whitespace-pre-wrap break-all">{JSON.stringify({version:version.id,parent:version.parent_id,actor:version.actor,operation:version.operation,original_sha256:version.source_sha256,derived_sha256:version.derived_sha256,dataset_path:version.dataset_path},null,2)}</pre></details></>}
 </section></details>;
}
