const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),ts=require('typescript');
function helper(){const file=path.join(__dirname,'evidenceLabeling.ts'),m=new Module(file,module);m.filename=file;m.paths=Module._nodeModulePaths(__dirname);m._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,file);return m.exports;}
const binding=()=>({comparison_id:'comparison-a',project_id:'p',source:'/source',task:'classification',labelset_id:'labels',image_id:'part',file_path:'/source/part.png',image_sha256:'a'.repeat(64),product_filter:'product',lot_filter:'lot'});
function fixture(){let current=true,opened=[];const b=binding();const metadata={file_path:b.file_path,content_hash:b.image_sha256,revision:7,team:{edit_lease:null}};const workspace={scope:{project_id:b.project_id,source:b.source,labelset_id:b.labelset_id},actor:{name:'kai',role:'labeler'}};return{b,metadata,workspace,opened,leave(){current=false;},ports:{sameContext:()=>current,mode:'team',actor:'kai',task:'classification',metadata:async()=>metadata,workspace:async()=>workspace,open:async(...args)=>{opened.push(args);return true;}}};}
test('current-label entry binds exact captured hash, scope and live revision without writing labels',async()=>{const h=helper(),f=fixture();const result=await h.openEvidenceLabeling(f.b,f.ports);assert.equal(result.revision,7);assert.deepEqual(f.opened,[['part','/source/part.png',{imageSha256:'a'.repeat(64),revision:7}]]);});
for(const field of ['content_hash','file_path'])test('changed image '+field+' refuses current-label entry',async()=>{const f=fixture();f.metadata[field]='changed';await assert.rejects(helper().openEvidenceLabeling(f.b,f.ports),/원본/);assert.equal(f.opened.length,0);});
for(const field of ['project_id','source','labelset_id'])test('different current '+field+' refuses label entry',async()=>{const f=fixture();f.workspace.scope[field]='other';await assert.rejects(helper().openEvidenceLabeling(f.b,f.ports),/프로젝트|라벨/);assert.equal(f.opened.length,0);});
test('legacy missing labelset and missing captured hash remain read-only',async()=>{for(const field of ['labelset_id','image_sha256']){const f=fixture();delete f.b[field];await assert.rejects(helper().openEvidenceLabeling(f.b,f.ports),/기록/);assert.equal(f.opened.length,0);}});
test('viewer and missing team actor cannot enter editing; another active lease is not acquired or displaced',async()=>{for(const actor of [{name:'kai',role:'viewer'},null]){const f=fixture();f.workspace.actor=actor;await assert.rejects(helper().openEvidenceLabeling(f.b,f.ports),/역할/);}const f=fixture();f.metadata.team.edit_lease={owner:'other',expires_at:Date.now()/1000+120};await assert.rejects(helper().openEvidenceLabeling(f.b,f.ports),/편집 중/);assert.equal(f.opened.length,0);});
test('delayed context response never opens another server, project or labelset',async()=>{const f=fixture();f.ports.metadata=async()=>{f.leave();return f.metadata;};await assert.rejects(helper().openEvidenceLabeling(f.b,f.ports),/연결/);assert.equal(f.opened.length,0);});
test('refused annotation load does not produce a return receipt',async()=>{const f=fixture();f.ports.open=async()=>false;await assert.rejects(helper().openEvidenceLabeling(f.b,f.ports),/라벨/);});
test('saved edit origin survives reopen only in its exact scope and retains both filters',()=>{const h=helper(),map=new Map(),s={getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)};h.rememberEvidenceEdit(s,'scope',{...binding(),revision:7});assert.equal(h.readEvidenceEdit(s,'other'),null);assert.deepEqual(h.readEvidenceEdit(s,'scope'),{...binding(),revision:7});h.clearEvidenceEdit(s,'scope');assert.equal(h.readEvidenceEdit(s,'scope'),null);});

test('specialist task without the current labeling contract remains read-only',async()=>{const f=fixture();f.b.task='patch_classification';await assert.rejects(helper().openEvidenceLabeling(f.b,f.ports),/작업 종류/);assert.equal(f.opened.length,0);});
test('edit origin is isolated between two actors on the same API and project',()=>{const h=helper();assert.notEqual(h.evidenceEditScope('same-project-api','actor-a'),h.evidenceEditScope('same-project-api','actor-b'));});
