const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),ts=require('typescript');
const tick=()=>new Promise(resolve=>setImmediate(resolve));const nodes=t=>Array.isArray(t)?t.flatMap(nodes):t&&typeof t==='object'?[t,...nodes(t.props?.children)]:[];
function load(file,mocks={}){const m=new Module(file,module);m.filename=file;m.paths=Module._nodeModulePaths(path.dirname(file));const req=m.require.bind(m);m.require=n=>mocks[n]??req(n);m._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText,file);return m.exports;}
const originHelper=load(path.resolve(__dirname,'evidenceLabeling.ts')),reviewHelper=load(path.resolve(__dirname,'productDataWorkflow.ts'));
function fixture(){
 const previous={storage:global.localStorage,window:global.window};const map=new Map();global.localStorage={getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)};global.window={dispatchEvent(){}};
 const context={generation:1,actor:'actor-a',identity:'local'},project={project:{id:'project',source_dataset_dir:'/source',active_labelset_id:'labels'},task:'classification',activeStep:2},compute={transportRevision:0,selectedProfileId:null},annotation={isDirty:false,isSaving:false,currentImage:{file_path:'/source/a.png'},reviewerName:'owner'};let pendingStep=null,pendingMetadata=null,opens=[];
 const scope=()=>reviewHelper.evaluationOriginScope(project.project.id,project.project.source_dataset_dir,project.task,project.project.active_labelset_id,{...compute,apiTransportIdentity:context.identity}),editScope=()=>originHelper.evidenceEditScope(scope(),context.actor);
 const makeOrigin=name=>({comparison_id:'report-'+name,project_id:project.project.id,source:'/source',task:'classification',labelset_id:'labels',image_id:name,file_path:'/source/'+name+'.png',image_sha256:'a'.repeat(64),product_filter:'product',lot_filter:'lot',revision:7});
 let origin=makeOrigin('a');originHelper.rememberEvidenceEdit(global.localStorage,editScope(),origin);
 project.setStep=async()=>{if(pendingStep)await pendingStep;project.activeStep=4;};project.openImageForLabeling=async(...args)=>{opens.push(args);return true;};
 const store=s=>{const fn=()=>s;fn.getState=()=>s;return fn;};let cursor=0,dirty=true,tree;const slots=[],effects=[];const same=(a,b)=>a?.length===b?.length&&a.every((v,i)=>Object.is(v,b[i]));
 const react={useState(initial){const i=cursor++;if(!(i in slots))slots[i]=initial;return[slots[i],v=>{const next=typeof v==='function'?v(slots[i]):v;if(!Object.is(next,slots[i])){slots[i]=next;dirty=true;}}];},useRef(initial){const i=cursor++;if(!(i in slots))slots[i]={current:initial};return slots[i];},useEffect(fn,deps){const i=cursor++;if(!same(slots[i]?.deps,deps)){const previous=slots[i];slots[i]={deps};effects.push(()=>{previous?.cleanup?.();slots[i].cleanup=fn();});}},useSyncExternalStore(subscribe,snapshot){return snapshot();}};const jsx=(type,props)=>({type,props});
 const component=load(path.resolve(__dirname,'EvidenceEditReturn.tsx'),{react,'react/jsx-runtime':{jsx,jsxs:jsx},'../../stores/useProjectStore':{useProjectStore:store(project)},'../../stores/useComputeStore':{useComputeStore:store(compute)},'../../stores/useAnnotationStore':{useAnnotationStore:store(annotation)},'../../services/api':{getApiPersistenceIdentity:()=>context.identity,getProjectContextGeneration:()=>context.generation,getProjectContext:()=>({actor_id:context.actor,mode:'local'})},'../../services/datasetWorkflow':{datasetWorkflow:{image:async(file)=>pendingMetadata?pendingMetadata:{file_path:file,content_hash:'a'.repeat(64),revision:7,team:{edit_lease:null}}}},'../../services/teamDataApi':{teamDataApi:{workspace:async()=>({scope:{project_id:project.project.id,source:'/source',labelset_id:'labels'},actor:{name:'owner',role:'owner'}})}},'./productDataWorkflow':reviewHelper,'./evidenceLabeling':originHelper}).EvidenceEditReturn;
 function render(){dirty=true;for(let i=0;i<10&&dirty;i++){cursor=0;dirty=false;tree=component();effects.splice(0).forEach(f=>f());}assert(!dirty);return tree;}
 const button=name=>nodes(tree).find(n=>n.type==='button'&&n.props.children===name),back=()=>button('원래 판정 근거로 돌아가기'),reopen=()=>button('근거 이미지의 현재 라벨 다시 열기');
 render();return{project,compute,annotation,context,map,render,back,reopen,opens,originHelper,origin:()=>origin,currentOrigin:()=>originHelper.readEvidenceEdit(global.localStorage,editScope()),setOrigin(name){origin=makeOrigin(name);originHelper.rememberEvidenceEdit(global.localStorage,editScope(),origin);render();},unmount(){slots.forEach(s=>s?.cleanup?.());slots.length=0;},setStepPromise(p){pendingStep=p;},setMetadataPromise(p){pendingMetadata=p;},alerts:()=>nodes(tree).filter(n=>n.props?.role==='alert'),clear(){originHelper.clearEvidenceEdit(global.localStorage,editScope());render();},close(){global.localStorage=previous.storage;global.window=previous.window;}};
}
test('an empty edit origin has no executable return and dirty/saving labels block both controls',()=>{const f=fixture();try{f.annotation.isDirty=true;f.render();assert(f.back().props.disabled&&f.reopen().props.disabled);f.annotation.isDirty=false;f.annotation.isSaving=true;f.render();assert(f.back().props.disabled&&f.reopen().props.disabled);f.clear();assert.equal(f.render(),null);assert.deepEqual(f.opens,[]);}finally{f.close();}});
test('an old metadata reopen cannot hold the next origin busy or open its image',async()=>{const f=fixture();let release;try{f.setMetadataPromise(new Promise(resolve=>release=resolve));f.reopen().props.onClick();f.render();assert.equal(f.reopen().props.disabled,true);f.context.generation++;f.compute.transportRevision++;f.setOrigin('b');assert.equal(f.reopen().props.disabled,false,'a new authority is not busy with the old request');release({file_path:'/source/a.png',content_hash:'a'.repeat(64),revision:7});await tick();await tick();f.render();assert.equal(f.currentOrigin().image_id,'b');assert.deepEqual(f.opens,[]);assert.equal(f.alerts().length,0);}finally{f.close();}});
test('a delayed return cannot clear a newer origin in the same project and actor',async()=>{const f=fixture();let release;try{f.setStepPromise(new Promise(resolve=>release=resolve));f.back().props.onClick();f.render();f.setOrigin('b');release();await tick();await tick();f.render();assert.equal(f.currentOrigin()?.image_id,'b','the newer saved origin must survive completion of the old return');assert.equal(f.back().props.disabled,false);}finally{f.close();}});
test('a late return error from a changed authority does not show in the new editor',async()=>{const f=fixture();let reject;try{f.setStepPromise(new Promise((_,r)=>reject=r));f.back().props.onClick();f.render();f.context.generation+=2;f.setOrigin('b');reject(Error('Old navigation failed'));await tick();await tick();f.render();assert.equal(f.alerts().length,0);assert.equal(f.back().props.disabled,false);assert.equal(f.currentOrigin().image_id,'b');}finally{f.close();}});
test('current metadata failure preserves the origin and permits a deliberate retry',async()=>{const f=fixture();try{f.setMetadataPromise(Promise.reject(Error('Controlled metadata503')));f.reopen().props.onClick();await tick();await tick();f.render();assert.equal(f.alerts().length,1);assert.equal(f.reopen().props.disabled,false);assert.equal(f.currentOrigin().image_id,'a');f.setMetadataPromise(null);f.reopen().props.onClick();await tick();await tick();f.render();assert.equal(f.alerts().length,0);assert.equal(f.opens.length,1);assert.equal(f.currentOrigin().image_id,'a');}finally{f.close();}});

test('leaving the label editor cancels a pending reopen even when the same stage is opened again',async()=>{const f=fixture();let release;try{f.setMetadataPromise(new Promise(resolve=>release=resolve));f.reopen().props.onClick();f.render();f.project.activeStep=4;f.unmount();f.project.activeStep=2;f.render();release({file_path:'/source/a.png',content_hash:'a'.repeat(64),revision:7});await tick();await tick();f.render();assert.deepEqual(f.opens,[],'a request from the unmounted editor cannot navigate into a later editor');assert.equal(f.alerts().length,0);assert.equal(f.reopen().props.disabled,false);}finally{f.close();}});
test('a current successful return clears its own origin after reaching the exact comparison stage',async()=>{const f=fixture();try{f.back().props.onClick();await tick();f.render();assert.equal(f.project.activeStep,4);assert.equal(f.currentOrigin(),null);assert.equal(f.render(),null);}finally{f.close();}});
