const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const Module=require('node:module');const test=require('node:test');const ts=require('typescript');
function harness(canConfigure=true){const file=path.join(__dirname,'KoreanConditionLabeler.tsx');assert.ok(fs.existsSync(file),'Korean condition labeling UI must exist');let cursor=0;const slots=[],effects=[];const projectState={projectDir:'p',task:'detection',project:{id:'p',task:'detection',source_dataset_dir:'s',active_labelset_id:'default'}};const compute={transportRevision:0,selectedProfileId:null};const annotation={currentImage:{file_path:'s/part.png',image_id:'part'},activeCategory:{name:'스크래치'},annotations:[{id:'box',bbox:[1,2,10,12]}],selectedAnnotationId:'box',categories:[{id:1,name:'스크래치'}]};const created=[],requests=[];let resolve;
 const react={createElement:(type,props,...children)=>({type,props:props||{},children:children.flat()}),useState:initial=>{const i=cursor++;if(!(i in slots))slots[i]=typeof initial==='function'?initial():initial;return[slots[i],value=>{slots[i]=typeof value==='function'?value(slots[i]):value;}];},useEffect:(fn,deps)=>{const i=cursor++;if(!slots[i]||deps.some((v,j)=>v!==slots[i].deps[j])){slots[i]?.cleanup?.();slots[i]={deps};effects.push(()=>{slots[i].cleanup=fn();});}},useRef:initial=>{const i=cursor++;if(!(i in slots))slots[i]={current:initial};return slots[i];}};
 const store=value=>{const fn=sel=>sel?sel(value):value;fn.getState=()=>value;return fn;};const setup={can_configure_vlm:canConfigure,configuration:{vlm:{enabled:true,endpoint:'http://127.0.0.1/v1/chat/completions',model:'local',api_key_env:null}},providers:{vlm:{ready:true}},labelset_id:'default',labelset_version:'v1'};const provider={setup:async()=>setup,generate:body=>{requests.push(body);return new Promise(r=>resolve=r);},configure:async()=>setup};const m=new Module(file,module);m.filename=file;m.paths=Module._nodeModulePaths(__dirname);m.require=name=>name==='react'?react:name==='../../services/api'?{getApiPersistenceIdentity:()=> 'local'}:name.includes('useProjectStore')?{useProjectStore:store(projectState)}:name.includes('useComputeStore')?{useComputeStore:store(compute)}:name.includes('useAnnotationStore')?{useAnnotationStore:store(annotation)}:name.includes('useDatasetStore')?{useDatasetStore:store({images:[]})}:name.includes('useModelAssistRunStore')?{useModelAssistRunStore:store({begin(){},end(){}})}:name.includes('foundationLabelingApi')?{foundationLabelingApi:provider}:name.includes('datasetWorkflow')?{workflowError:e=>e.message}:name.includes('dataWorkbench')?{dataWorkbenchScope:s=>JSON.stringify([s.project,s.transportRevision||0,s.selectedProfileId||'local'])}:name.includes('foundationRequest')?{regionExample:(p,a)=>({image_path:p,roi:a.bbox})}:Module.prototype.require.call(m,name);m._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{jsx:ts.JsxEmit.React,module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,file);
 const render=()=>{cursor=0;const tree=m.exports.KoreanConditionLabeler({disabled:false,onCreated:p=>created.push(p)});effects.splice(0).forEach(f=>f());return tree;};const nodes=tree=>{const result=[];const walk=n=>{if(n&&typeof n==='object'){result.push(n);n.children?.forEach(walk);}};walk(tree);return result;};return{render,nodes,requests,created,annotation,projectState,compute,resolve:v=>resolve(v)};}
test('condition UI sends Korean prompt and selected image references then discards stale image response',async()=>{const h=harness();h.render();await new Promise(setImmediate);let tree=h.render();h.nodes(tree).find(n=>n.props['aria-label']==='한국어 라벨 조건').props.onChange({target:{value:'길고 가는 손상만 찾으세요'}});tree=h.render();h.nodes(tree).find(n=>n.type==='button'&&n.children.includes('선택 라벨 → 긍정 예시')).props.onClick();tree=h.render();const pending=h.nodes(tree).find(n=>n.type==='button'&&n.children.includes('한국어 조건 후보 생성')).props.onClick();await new Promise(setImmediate);assert.equal(h.requests[0].prompt,'길고 가는 손상만 찾으세요');assert.deepEqual(h.requests[0].positive_examples,[{image_path:'s/part.png',roi:[1,2,10,12]}]);h.annotation.currentImage.file_path='s/another.png';h.render();h.resolve({id:'stale',candidates:[]});await pending;assert.equal(h.created.length,0);});

test('non-admin uses saved provider while configuration controls are disabled',async()=>{const h=harness(false);h.render();await new Promise(setImmediate);const tree=h.render();for(const name of ['VLM 공급자 주소','VLM 모델 이름','VLM 키 환경 변수 이름'])assert.equal(h.nodes(tree).find(n=>n.props['aria-label']===name).props.disabled,true);assert.equal(h.nodes(tree).find(n=>n.type==='button'&&n.children.includes('VLM 설정 저장')).props.disabled,true);});

test('transport-only switch rejects a pending VLM proposal from the previous server',async()=>{const h=harness();h.render();await new Promise(setImmediate);let tree=h.render();h.nodes(tree).find(n=>n.props['aria-label']==='한국어 라벨 조건').props.onChange({target:{value:'작은 손상만 찾으세요'}});tree=h.render();const pending=h.nodes(tree).find(n=>n.type==='button'&&n.children.includes('한국어 조건 후보 생성')).props.onClick();await new Promise(setImmediate);h.compute.transportRevision=1;h.render();h.resolve({id:'previous-server',candidates:[]});await pending;assert.equal(h.created.length,0);});
