import {useEffect,useState} from 'react';
import type {Category} from '../../types';
import type {ImageReviewMetadata} from '../../services/datasetWorkflow';
import type {BookCategory,LabelBook} from '../../services/teamDataApi';
import {validatedBookCategories} from './teamDataWorkflow';
const input='mt-1 w-full rounded border border-slate-600 bg-slate-950 p-2 text-sm';
const button='rounded border border-slate-600 px-3 py-2 text-sm disabled:opacity-40';
const entry=(row:Category):BookCategory=>({...row,definition:'',inclusion:'',exclusion:'',annotation_guidance:'',examples:[]});
export function LabelbookEditor({scope,book,history,palette,image,canManage,busy,onPublish}:{scope:string;book:LabelBook|null;history:LabelBook[];palette:Category[];image:ImageReviewMetadata|null;canManage:boolean;busy:boolean;onPublish:(title:string,categories:BookCategory[])=>Promise<void>}){
 const [title,setTitle]=useState('라벨 기준서');const [rows,setRows]=useState<BookCategory[]>([]);const [selected,setSelected]=useState(0);const [name,setName]=useState('');const [error,setError]=useState('');const [historical,setHistorical]=useState('');
 useEffect(()=>{setTitle(book?.title||'라벨 기준서');setRows(book?.categories.map(row=>({...row,examples:[...row.examples]}))||palette.map(entry));setSelected(0);setHistorical('');setError('');},[scope,book?.sha256]);
 const viewed=historical?history.find(row=>String(row.version)===historical):null;const categories=viewed?.categories||rows;const current=categories[selected];const readonly=!!viewed||!canManage;
 const edit=(changes:Partial<BookCategory>)=>setRows(all=>all.map((row,index)=>index===selected?{...row,...changes}:row));
 const publish=async()=>{setError('');try{await onPublish(title.trim()||'라벨 기준서',validatedBookCategories(rows));}catch(cause){setError(cause instanceof Error?cause.message:String(cause));}};
 return <section aria-label="공유 라벨 기준서" className="space-y-4">
  <div className="flex flex-wrap items-end gap-3"><label className="min-w-64 flex-1 text-sm">기준서 제목<input aria-label="라벨 기준서 제목" value={viewed?.title||title} disabled={readonly||busy} onChange={e=>setTitle(e.target.value)} className={input}/></label><label className="text-sm">버전<select aria-label="라벨 기준서 버전" value={historical} onChange={e=>{setHistorical(e.target.value);setSelected(0);}} className={input}><option value="">현재 {book?`v${book.version}`:'미발행'}</option>{history.map(row=><option key={row.id} value={String(row.version)}>v{row.version} · {row.actor}</option>)}</select></label></div>
  <p className="text-sm text-slate-400">클래스별 포함·제외 기준과 예시를 공유합니다. 발행한 버전은 수정되지 않습니다. 새 버전을 발행하면 이전 기준의 검수는 다시 확인해야 합니다.</p>
  <div className="grid gap-4 md:grid-cols-[220px_1fr]"><div className="space-y-2"><div className="max-h-80 space-y-1 overflow-auto">{categories.map((row,index)=><button key={row.id} type="button" aria-pressed={selected===index} onClick={()=>setSelected(index)} className={`flex w-full items-center gap-2 rounded border p-3 text-left text-sm ${selected===index?'border-cyan-500 bg-cyan-950/40':'border-slate-700 bg-slate-900'}`}><span style={{backgroundColor:row.color}} className="h-3 w-3 shrink-0 rounded"/><span>{row.name}</span></button>)}</div>
   {!readonly&&<div className="space-y-2 rounded border border-slate-700 p-3"><label className="text-sm">새 클래스<input aria-label="기준서 새 클래스" value={name} onChange={e=>setName(e.target.value)} className={input}/></label><button type="button" disabled={busy||!name.trim()} className={button} onClick={()=>{const next=entry({id:Math.max(-1,...rows.map(row=>row.id))+1,name:name.trim(),color:'#38bdf8'});setRows([...rows,next]);setSelected(rows.length);setName('');}}>클래스 추가</button></div>}
  </div><div className="min-w-0 space-y-3 rounded border border-slate-700 bg-slate-900/60 p-4">
   {current?<><div className="flex items-center gap-3"><h3 className="font-semibold">{current.name}</h3><label className="text-xs text-slate-400">색상<input aria-label="클래스 색상" type="color" value={current.color} disabled={readonly||busy} onChange={e=>edit({color:e.target.value})} className="ml-2 h-7 w-10 align-middle"/></label></div>
    {([['definition','클래스 정의'],['inclusion','포함하는 경우'],['exclusion','제외하는 경우'],['annotation_guidance','영역·경계·라벨 작성 기준']] as const).map(([key,label])=><label key={key} className="block text-sm">{label}<textarea aria-label={label} value={current[key]} disabled={readonly||busy} maxLength={4000} onChange={e=>edit({[key]:e.target.value})} rows={key==='definition'?2:3} className={input}/></label>)}
    <div className="space-y-2"><h4 className="text-sm font-semibold">예시 이미지</h4>{current.examples.length?current.examples.map((example,index)=><div key={`${example.relative_path}-${index}`} className="rounded border border-slate-700 p-2 text-sm"><p className="break-all text-slate-300">{example.relative_path}</p><input aria-label={`예시 설명 ${index+1}`} disabled={readonly||busy} value={example.caption} onChange={e=>edit({examples:current.examples.map((row,i)=>i===index?{...row,caption:e.target.value}:row)})} placeholder="포함 또는 제외 이유" className={input}/>{!readonly&&<button type="button" className="mt-1 text-xs text-rose-200" onClick={()=>edit({examples:current.examples.filter((_,i)=>i!==index)})}>예시에서 제거</button>}</div>):<p className="text-sm text-slate-500">등록된 예시가 없습니다.</p>}
     {!readonly&&<button type="button" className={button} disabled={busy||!image||current.examples.some(row=>row.relative_path===image.relative_path)} onClick={()=>image&&edit({examples:[...current.examples,{relative_path:image.relative_path,content_hash:image.content_hash,caption:''}]})}>현재 이미지를 예시로 추가</button>}
    </div><details className="text-xs text-slate-400"><summary className="cursor-pointer">클래스 ID·기준 해시</summary><p>ID {current.id} · {viewed?.sha256||book?.sha256||'발행 전'}</p></details>
   </>:<p className="text-sm">클래스를 추가하면 기준을 작성할 수 있습니다.</p>}
  </div></div>
  <div className="flex flex-wrap items-center gap-3">{!readonly&&<button type="button" onClick={()=>void publish()} disabled={busy||!rows.length} className={`${button} border-cyan-600 bg-cyan-950/40`}>새 기준 버전 발행</button>}{viewed&&<p className="text-sm text-amber-200">과거 버전 열람 중 · 변경하려면 현재 버전을 선택하세요.</p>}{!canManage&&<p className="text-sm text-slate-400">기준 발행은 프로젝트 관리자·검토자가 할 수 있습니다.</p>}{error&&<p role="alert" className="text-sm text-rose-200">{error}</p>}</div>
 </section>;
}
