import {getApiPersistenceIdentity} from '../../services/api';
import React,{useEffect,useState} from 'react';
import {dataWorkbench,dataWorkbenchScope,dataWorkbenchPersistenceScope,type SavedReviewQueue,type ReviewEvaluation} from '../../services/dataWorkbench';
import {workflowError} from '../../services/datasetWorkflow';
import {useComputeStore} from '../../stores/useComputeStore';
import {useProjectStore} from '../../stores/useProjectStore';
import {useAnnotationStore} from '../../stores/useAnnotationStore';
import {rememberReviewOrigin,evaluationOriginScope} from './productDataWorkflow';
const reasons:Record<string,string>={error:'오류',disagreement:'모델 불일치',threshold:'임계값 근처'};
const button='rounded border border-slate-600 px-3 py-2 disabled:opacity-40';
export const SavedReviewQueuePanel:React.FC=()=>{
 const project=useProjectStore();const compute=useComputeStore();const {currentImage,isDirty,isSaving,reviewerName}=useAnnotationStore();const scope=dataWorkbenchScope({...project,...compute,apiTransportIdentity:getApiPersistenceIdentity()});
 const stableScope=dataWorkbenchPersistenceScope({...project,...compute,apiTransportIdentity:getApiPersistenceIdentity()});
 const [loaded,setLoaded]=useState<{scope:string;queues:SavedReviewQueue[];evaluations:ReviewEvaluation[]}|null>(null);const [selected,setSelected]=useState('');const [evaluation,setEvaluation]=useState('');
 const [threshold,setThreshold]=useState(.5);const [margin,setMargin]=useState(.05);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const same=()=>dataWorkbenchScope({...useProjectStore.getState(),...useComputeStore.getState(),apiTransportIdentity:getApiPersistenceIdentity()})===scope;const queues=loaded?.scope===scope?loaded.queues:[];const evaluations=loaded?.scope===scope?loaded.evaluations:[];const queue=queues.find(q=>q.id===selected);const item=queue?.items[queue.cursor];
 useEffect(()=>{let active=true;setLoaded(null);setSelected('');setEvaluation('');setError('');setBusy(false);if(!project.project?.source_dataset_dir)return;
  void Promise.all([dataWorkbench.queues(),dataWorkbench.evaluations()]).then(([q,e])=>{if(active&&same()){setLoaded({scope,queues:q.queues,evaluations:e.evaluations});const remembered=localStorage.getItem(`modu-review-queue:${stableScope}`);setSelected(q.queues.find(row=>row.id===remembered)?.id||q.queues[0]?.id||'');setEvaluation(e.evaluations[0]?.id||'');}}).catch(cause=>{if(active&&same())setError(workflowError(cause));});return()=>{active=false;};
 },[scope]);
 const remember=(id:string)=>{setSelected(id);localStorage.setItem(`modu-review-queue:${stableScope}`,id);};
 const run=async(action:()=>Promise<void>)=>{if(!same())return;setBusy(true);setError('');try{await action();}catch(cause){if(same())setError(workflowError(cause));}finally{if(same())setBusy(false);}};
 const create=()=>run(async()=>{const next=await dataWorkbench.createQueue(evaluations.find(row=>row.id===evaluation)!,threshold,margin);if(same()){setLoaded({scope,queues:[next,...queues],evaluations});remember(next.id);}});
 const open=()=>run(async()=>{if(!queue)return;const reopened=await dataWorkbench.queue(queue.id);if(!same())return;setLoaded({scope,queues:queues.map(q=>q.id===queue.id?reopened:q),evaluations});const row=reopened.items[reopened.cursor];if(row)await useProjectStore.getState().openImageForLabeling(row.file_path.split(/[\\/]/).pop()!.replace(/\.[^.]+$/,''),row.file_path);});
 const advance=(state:'reviewed'|'skipped')=>run(async()=>{if(!queue||!item||isDirty||isSaving)return;if(!reviewerName.trim())throw new Error('이미지 정보·검토에서 검토자 이름을 입력하세요.');const next=await dataWorkbench.advance(queue,state,reviewerName);if(same()){setLoaded({scope,queues:queues.map(q=>q.id===next.id?next:q),evaluations});const row=next.items[next.cursor];if(row)await useProjectStore.getState().openImageForLabeling(row.file_path.split(/[\\/]/).pop()!.replace(/\.[^.]+$/,''),row.file_path);}});
 const returnToOrigin=()=>run(async()=>{if(!queue||!project.project)return;await dataWorkbench.queue(queue.id);if(!same())return;rememberReviewOrigin(localStorage,evaluationOriginScope(project.project.id,queue.scope.source,queue.scope.task,queue.scope.labelset_id,{...compute,apiTransportIdentity:getApiPersistenceIdentity()}),queue.origin.comparison_id||queue.origin.evaluation_id!,currentImage?.image_id,currentImage?.file_path,queue.origin.comparison_id?'comparison':'evaluation');await useProjectStore.getState().setStep(4);});
 if(!project.project?.source_dataset_dir)return null;
 return <details className="shrink-0 border-b border-slate-700 bg-[#111D2B] text-xs"><summary className="cursor-pointer px-4 py-2 font-semibold text-amber-100">저장 검토 큐 · 오류·불일치·임계값 우선</summary><section aria-label="저장된 검토 큐" className="max-h-[50vh] space-y-3 overflow-auto px-4 pb-4">
  <div className="flex flex-wrap items-end gap-2"><label>시작 평가·비교<select aria-label="검토 큐 원본 평가" value={evaluation} onChange={e=>setEvaluation(e.target.value)} className="ml-2 rounded border border-slate-600 bg-slate-900 p-2"><option value="">저장 평가 선택</option>{evaluations.map(e=><option key={e.id} value={e.id}>{e.kind==='comparison'?'모델 비교':'평가'} · {new Date(e.created_at*1000).toLocaleString('ko-KR')} · 이미지 {e.sample_count}장</option>)}</select></label><label>임계값<input aria-label="검토 큐 임계값" type="number" min="0" max="1" step=".01" value={threshold} onChange={e=>setThreshold(Number(e.target.value))} className="ml-1 w-20 rounded border border-slate-600 bg-slate-900 p-2"/></label><label>주변 범위 ±<input aria-label="검토 큐 임계 주변 범위" type="number" min="0" max="1" step=".01" value={margin} onChange={e=>setMargin(Number(e.target.value))} className="ml-1 w-20 rounded border border-slate-600 bg-slate-900 p-2"/></label><button type="button" className={button} disabled={busy||!evaluation} onClick={()=>void create()}>우선순위 큐 저장</button></div>
  <label>검토 이어가기<select aria-label="저장 검토 큐 선택" value={selected} onChange={e=>remember(e.target.value)} className="ml-2 rounded border border-slate-600 bg-slate-900 p-2"><option value="">큐 선택</option>{queues.map(q=><option key={q.id} value={q.id}>{new Date(q.created_at*1000).toLocaleString('ko-KR')} · {q.cursor}/{q.items.length} 완료{q.stale?' · 원본 변경':''}</option>)}</select></label>
  {queue&&<><p>검토 진행 {queue.cursor} / {queue.items.length}{queue.stale?' · 원본 변경으로 재생성 필요':''}</p>{queue.error&&<p role="alert" className="text-rose-200">{queue.error}</p>}{item?<p className="text-amber-200">다음: {item.relative_path} · {item.reasons.map(reason=>reasons[reason]||reason).join(' · ')}</p>:<p className="text-emerald-200">큐의 모든 항목을 검토했습니다.</p>}
   <div className="flex flex-wrap gap-2"><button type="button" className={button} disabled={busy||!item||queue.stale} onClick={()=>void open()}>현재 항목 열기</button><button type="button" className={button} disabled={busy||!item||queue.stale||isDirty||isSaving||currentImage?.file_path!==item.file_path} onClick={()=>void advance('reviewed')}>검토 완료 · 다음</button><button type="button" className={button} disabled={busy||!item||queue.stale||isDirty||isSaving} onClick={()=>void advance('skipped')}>보류 · 다음</button><button type="button" className={`${button} border-cyan-700`} disabled={busy||queue.stale} onClick={()=>void returnToOrigin()}>원래 평가·비교로 돌아가기</button></div>
   <p className="text-slate-400">큐 검토 완료는 라벨 승인과 별도입니다. 저장되지 않은 편집은 먼저 저장하세요. 진행 위치·검토자·보류 기록을 프로젝트에 보관합니다.</p><details><summary className="cursor-pointer">우선순위 목록</summary><ol className="max-h-40 overflow-auto">{queue.items.map((row,index)=><li key={row.relative_path} className="border-t border-slate-700 py-1">{index+1}. {row.relative_path} · {row.reasons.map(reason=>reasons[reason]).join(' · ')} · {row.state==='pending'?'대기':row.state==='reviewed'?'검토 완료':'보류'}</li>)}</ol></details></>}
  {busy&&<p role="status">검토 큐 처리 중…</p>}{error&&<p role="alert" className="text-rose-200">{error}</p>}{!evaluations.length&&<p className="text-slate-400">4단계에서 현재 데이터의 평가를 저장하면 검토 큐를 만들 수 있습니다.</p>}
 </section></details>;
}
