import {useEffect,useRef,useState} from 'react';
import {BookOpen,Users,ShieldCheck,RefreshCw} from 'lucide-react';
import {useProjectStore} from '../../stores/useProjectStore';
import {useComputeStore} from '../../stores/useComputeStore';
import {useAnnotationStore} from '../../stores/useAnnotationStore';
import {getApiPersistenceIdentity} from '../../services/api';
import {teamDataApi,type TeamQueue,type TeamReadiness,type TeamWorkspace} from '../../services/teamDataApi';
import {workflowError,type ImageReviewMetadata} from '../../services/datasetWorkflow';
import {WorkspaceDialog} from '../common/WorkspaceDialog';
import {LabelbookEditor} from './LabelbookEditor';
import {imageLeaseToken,reviewTrainingMessage,teamDataScope} from './teamDataWorkflow';
const input='rounded border border-slate-600 bg-slate-950 p-2 text-sm';
const button='rounded border border-slate-600 px-3 py-2 text-sm disabled:opacity-40';
const statusNames={pending:'검수 대기',approved:'승인',rejected:'반려',disputed:'의견 불일치'};
export function TeamDataPanel({compact=false}:{compact?:boolean}={}){
 const project=useProjectStore();const compute=useComputeStore();const annotation=useAnnotationStore();
 const scope=teamDataScope({...project,...compute,apiTransportIdentity:getApiPersistenceIdentity()});const scopeRef=useRef(scope);scopeRef.current=scope;
 const [workspace,setWorkspace]=useState<{scope:string;value:TeamWorkspace}|null>(null);const [ready,setReady]=useState<TeamReadiness|null>(null);const [queue,setQueue]=useState<TeamQueue|null>(null);
 const [open,setOpen]=useState(false);const [tab,setTab]=useState<'work'|'book'|'settings'>('work');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');
 const [assignee,setAssignee]=useState('');const [priority,setPriority]=useState(50);const [filterActor,setFilterActor]=useState('');const [filterState,setFilterState]=useState('');const [offset,setOffset]=useState(0);const [reason,setReason]=useState('');const [now,setNow]=useState(Date.now()/1000);
 const value=workspace?.scope===scope?workspace.value:null;const actor=value?.actor?.name||annotation.reviewerName.trim();const role=value?.actor?.role;const canManage=!value?.actor||['owner','reviewer'].includes(role||'');const metadata=annotation.metadata;
 const token=imageLeaseToken(annotation.editLease,metadata?.image_uuid,now);const ownLease=!!token;
 const team=metadata?.team;const reviewResolved=!!team&&(['approved','disputed'].includes(team.review_status)||(team.review_status==='rejected'&&team.reviews.length>=(value?.settings.required_reviews||1)));
 const same=()=>scopeRef.current===scope&&teamDataScope({...useProjectStore.getState(),...useComputeStore.getState(),apiTransportIdentity:getApiPersistenceIdentity()})===scope;
 const applyImage=(image:ImageReviewMetadata)=>{const current=useAnnotationStore.getState();if(same()&&current.metadata?.image_uuid===image.image_uuid&&image.revision>=current.metadata.revision)current.setMetadata(image);};
 const reload=async()=>{const id=useAnnotationStore.getState().metadata?.image_uuid;const [next,readiness,work,image]=await Promise.all([teamDataApi.workspace(),teamDataApi.readiness(),teamDataApi.queue({assignee:filterActor,state:filterState,offset,limit:30}),id?teamDataApi.image(id):Promise.resolve(null)]);if(!same())return;setWorkspace({scope,value:next});setReady(readiness);setQueue(work);if(image)applyImage(image.image);useAnnotationStore.getState().setTeamEditingEnabled(next.settings.editing_enabled);useAnnotationStore.getState().setTeamReviewEnabled(next.settings.review_enabled);useAnnotationStore.getState().setLabelbook(next.book?.version||null,next.book?.categories);};
 const run=async(action:()=>Promise<void>)=>{if(busy)return;setBusy(true);setError('');setNotice('');try{await action();}catch(cause){if(same())setError(workflowError(cause));}finally{if(same())setBusy(false);}};
 useEffect(()=>{let active=true;setWorkspace(null);setReady(null);setQueue(null);setError('');setNotice('');setBusy(false);setOpen(false);setOffset(0);setFilterActor('');setFilterState('');useAnnotationStore.getState().setEditLease(null);useAnnotationStore.getState().setTeamEditingEnabled(false);useAnnotationStore.getState().setTeamReviewEnabled(false);useAnnotationStore.getState().setLabelbook(null);
  if(project.project?.source_dataset_dir)void reload().catch(cause=>{if(active&&same())setError(workflowError(cause));});return()=>{active=false;};
 },[scope]);
 useEffect(()=>{const show=()=>{setTab('work');setOpen(true);};window.addEventListener('modu-team-review',show);return()=>window.removeEventListener('modu-team-review',show);},[scope]);
 useEffect(()=>{if(!value)return;let active=true;void teamDataApi.queue({assignee:filterActor,state:filterState,offset,limit:30}).then(next=>{if(active&&same())setQueue(next);}).catch(cause=>{if(active&&same())setError(workflowError(cause));});return()=>{active=false;};},[scope,filterActor,filterState,offset,value?.settings.revision]);
 useEffect(()=>{setAssignee(metadata?.team?.assignment?.assignee||'');setPriority(metadata?.team?.assignment?.priority??50);setReason('');},[metadata?.image_uuid,scope]);
 useEffect(()=>{if(!annotation.editLease||!value?.settings.editing_enabled)return;const lease=annotation.editLease;const timer=setInterval(()=>{setNow(Date.now()/1000);const current=useAnnotationStore.getState();if(!same()||current.editLease?.token!==lease.token||current.metadata?.image_uuid!==lease.image_uuid)return;const body=current.metadata;
   if(!imageLeaseToken(current.editLease,body.image_uuid)){current.setEditLease(null);setError('편집 권한이 만료됐습니다. 수정 내용은 유지됩니다. 편집 시작을 다시 누르세요.');return;}
   if(current.isSaving||busy)return;
   void teamDataApi.renew(body,actor,lease.token).then(result=>{if(!same()||useAnnotationStore.getState().editLease?.token!==lease.token)return;applyImage(result.image);if(result.lease_token&&result.image.team?.edit_lease)useAnnotationStore.getState().setEditLease({image_uuid:body.image_uuid,token:result.lease_token,...result.image.team.edit_lease});}).catch(cause=>{if(same()){setError(workflowError(cause));useAnnotationStore.getState().setEditLease(null);}});
  },30000);return()=>clearInterval(timer);
 },[scope,annotation.editLease?.token,annotation.editLease?.image_uuid,value?.settings.editing_enabled,actor,busy]);
 const imageAction=async(action:'acquire'|'release'|'assign'|'approve'|'reject'|'adjudicate-approve'|'adjudicate-reject')=>{if(!metadata||!actor)throw new Error('이미지와 작업자 이름을 먼저 선택하세요.');const imageUuid=metadata.image_uuid;
  if(action==='release'&&!token)throw new Error('현재 이미지의 편집 권한을 확인하지 못했습니다.');
  const result=action==='acquire'?await teamDataApi.acquire(metadata,actor):action==='release'?await teamDataApi.release(metadata,actor,token!):action==='assign'?await teamDataApi.assign(metadata,actor,assignee||null,priority):action.startsWith('adjudicate-')?await teamDataApi.adjudicate(metadata,actor,action.endsWith('approve')?'approve':'reject',reason):await teamDataApi.review(metadata,actor,action==='approve'?'approve':'reject',reason);
  if(!same())return;applyImage(result.image);if(action==='acquire'&&result.lease_token&&result.image.team?.edit_lease&&useAnnotationStore.getState().metadata?.image_uuid===imageUuid)useAnnotationStore.getState().setEditLease({image_uuid:imageUuid,token:result.lease_token,...result.image.team.edit_lease});if(action==='release')useAnnotationStore.getState().setEditLease(null);await reload();
 };
 const toTraining=()=>run(async()=>{const next=await teamDataApi.readiness();if(!same())return;setReady(next);if(!next.ready)throw new Error(reviewTrainingMessage(next));await useProjectStore.getState().setStep(3);if(same())setOpen(false);});
 if(!project.project?.source_dataset_dir)return null;
 return <div className={`shrink-0 border-b border-slate-700 bg-[#102033] px-4 text-xs ${compact?'py-1':'py-2'}`}><div className="flex flex-wrap items-center gap-3"><button type="button" onClick={()=>setOpen(true)} className="flex items-center gap-2 rounded border border-cyan-700 px-3 py-1.5 font-semibold text-cyan-100"><Users className="h-4 w-4"/>팀 작업 · 라벨 기준·검수</button><span className="text-slate-300">기준 {value?.book?`v${value.book.version}`:'미발행'} · 승인 {ready?.counts.approved??'—'} / {ready?.counts.total??'—'}</span>{value?.settings.editing_enabled&&<span className={ownLease?'text-emerald-300':'text-amber-200'}>{ownLease?'현재 이미지 편집 중':'편집 시작 필요'}</span>}
  {/* The lock is taken and given back here too, so it never depends on the dialog (or on helper panels being shown). */}
  {value?.settings.editing_enabled&&metadata&&(ownLease
   ?<button type="button" disabled={busy||annotation.isDirty||annotation.isSaving} title={annotation.isDirty?'저장한 뒤 편집을 종료하세요':undefined} onClick={()=>void run(()=>imageAction('release'))} className="rounded border border-slate-600 px-2 py-0.5 disabled:opacity-40">편집 종료</button>
   :<button type="button" disabled={busy||!actor||annotation.isSaving} onClick={()=>void run(()=>imageAction('acquire'))} className="rounded border border-cyan-600 px-2 py-0.5 text-cyan-100 disabled:opacity-40">편집 시작</button>)}
  {value?.settings.editing_enabled&&metadata&&!actor&&<span className="text-slate-400">작업자 이름은 팀 작업에서 입력하세요</span>}{annotation.isDirty&&value?.settings.review_enabled&&<span className="text-amber-200">저장하면 이전 검수 무효화 · 재검수 필요</span>}</div>
  {error&&!open&&<p role="alert" className="mt-2 text-rose-200">{error}</p>}
  {open&&<WorkspaceDialog title="팀 데이터 작업" onClose={()=>setOpen(false)}><div className="space-y-4 text-slate-200">
   <div className="flex flex-wrap items-center gap-3"><div className="flex gap-2" role="tablist" aria-label="팀 데이터 메뉴">{([['work','작업·검수'],['book','라벨 기준서'],['settings','검수 정책']] as const).map(([key,label])=><button type="button" role="tab" aria-selected={tab===key} key={key} onClick={()=>setTab(key)} className={`${button} ${tab===key?'border-cyan-500 bg-cyan-950/40':''}`}>{label}</button>)}</div><button type="button" disabled={busy} onClick={()=>void run(reload)} className={button}><RefreshCw className="mr-1 inline h-3 w-3"/>새로고침</button><label className="ml-auto text-sm">작업자 {value?.actor?<strong>{value.actor.name} · {role}</strong>:<input aria-label="팀 작업자 이름" value={annotation.reviewerName} onChange={e=>annotation.setReviewerName(e.target.value)} className={`${input} ml-2`} placeholder="작업자 이름"/>}</label></div>
   {busy&&<p role="status" className="text-sm text-cyan-200">처리 중…</p>}{error&&<p role="alert" className="rounded border border-rose-700 bg-rose-950/30 p-3 text-sm text-rose-200">{error} · 새로고침으로 현재 상태를 확인하세요.</p>}{notice&&<p role="status" className="text-sm text-emerald-200">{notice}</p>}
   {!value?<p className="py-8 text-center text-slate-400">팀 작업 정보를 불러오는 중입니다.</p>:<>
    {tab==='book'&&<LabelbookEditor scope={scope} book={value.book} history={value.book_history} palette={annotation.categories} image={metadata} canManage={canManage} busy={busy} onPublish={async(title,categories)=>{await run(async()=>{if(!actor)throw new Error('작업자 이름을 입력하세요.');await teamDataApi.publish(value.book?.version||0,actor,title,categories);await reload();if(same())setNotice('새 라벨 기준 버전을 발행했습니다. 이전 기준의 검수는 다시 확인하세요.');});}}/>}
    {tab==='settings'&&<section aria-label="팀 검수 정책" className="max-w-3xl space-y-4 rounded border border-slate-700 p-5"><h3 className="flex items-center gap-2 font-semibold"><ShieldCheck className="h-4 w-4 text-cyan-300"/>프로젝트 검수·학습 정책</h3><p className="text-sm text-slate-400">기존 프로젝트는 현재 정책을 유지합니다. 변경은 다음 저장·검수·학습부터 서버에서 검사하며 기준 변경 후 이전 검수는 무효화됩니다.</p>
     {([['editing_enabled','공동 편집 잠금 사용','편집 시작·자동 연장·종료로 동시 덮어쓰기를 막습니다.'],['review_enabled','검토표 기반 승인','정해진 수의 다른 검토자가 저장한 라벨을 확인합니다.'],['prevent_self_review','자기 라벨 승인 금지','라벨을 마지막으로 수정한 사람은 승인 표를 낼 수 없습니다.'],['approved_only_training','승인 데이터만 학습','검수 대기·반려·불일치 데이터는 학습 입력에서 제외합니다.']] as const).map(([key,label,help])=><label key={key} className="flex items-start gap-3 rounded border border-slate-700 p-3 text-sm"><input type="checkbox" aria-label={label} checked={value.settings[key]} disabled={busy||!canManage||!actor} onChange={e=>void run(async()=>{await teamDataApi.settings(value.settings,actor,{[key]:e.target.checked});await reload();})}/><span><strong>{label}</strong><span className="mt-1 block text-slate-400">{help}</span></span></label>)}
     <label className="block text-sm">필요 승인 검토자 수<select aria-label="필요 승인 검토자 수" value={value.settings.required_reviews} disabled={busy||!canManage||!actor} onChange={e=>void run(async()=>{await teamDataApi.settings(value.settings,actor,{required_reviews:Number(e.target.value) as 1|2});await reload();})} className={`${input} ml-3`}><option value="1">1명</option><option value="2">서로 다른 2명</option></select></label><p className="text-sm text-slate-400">두 사람 검토는 동일 라벨의 검수입니다. 독립된 두 라벨 작업의 자동 합의와 구분합니다.</p>
    </section>}
    {tab==='work'&&<div className="grid gap-4 xl:grid-cols-[1fr_1fr]"><section aria-label="현재 이미지 팀 작업" className="space-y-3 rounded border border-slate-700 bg-slate-900/50 p-4"><h3 className="font-semibold">현재 이미지</h3>{metadata?<><p className="break-all text-sm text-slate-300">{metadata.relative_path}</p><p className="text-sm">{metadata.team?statusNames[metadata.team.review_status]:'검수 대기'} · 작성자 {metadata.team?.annotation_actor||'기록 없음'} · 승인 표 {metadata.team?.reviews.filter(row=>row.decision==='approve').length||0}/{value.settings.required_reviews}</p>
     <div className="flex flex-wrap items-center gap-2">{value.settings.editing_enabled?<><span className="text-sm text-slate-400">{metadata.team?.edit_lease?`${metadata.team.edit_lease.owner} · ${new Date(metadata.team.edit_lease.expires_at*1000).toLocaleTimeString('ko-KR')}까지`:'현재 편집자 없음'}</span><button type="button" disabled={busy||!actor||ownLease||annotation.isSaving} className={`${button} border-cyan-600`} onClick={()=>void run(()=>imageAction('acquire'))}>편집 시작</button><button type="button" disabled={busy||!ownLease||annotation.isDirty||annotation.isSaving} className={button} onClick={()=>void run(()=>imageAction('release'))}>편집 종료</button></>:<span className="text-sm text-slate-400">공동 편집 잠금 사용 안 함</span>}</div>
     <div className="flex flex-wrap items-end gap-2"><label className="text-sm">담당자{value.members.length?<select aria-label="이미지 담당자" value={assignee} onChange={e=>setAssignee(e.target.value)} disabled={!canManage||busy} className={`${input} ml-2`}><option value="">미배정</option>{value.members.filter(row=>row.role!=='viewer').map(row=><option key={row.id} value={row.name}>{row.name} · {row.role}</option>)}</select>:<input aria-label="이미지 담당자" value={assignee} onChange={e=>setAssignee(e.target.value)} disabled={!canManage||busy} className={`${input} ml-2`} placeholder="담당자 이름"/>}</label><label className="text-sm">우선순위<input aria-label="작업 우선순위" type="number" min="0" max="100" value={priority} onChange={e=>setPriority(Number(e.target.value))} disabled={!canManage||busy} className={`${input} ml-2 w-20`}/></label><button type="button" disabled={busy||!actor||!canManage} className={button} onClick={()=>void run(()=>imageAction('assign'))}>작업 배정</button></div>
     <label className="block text-sm">검수·반려·조정 이유<textarea aria-label="검수 이유" rows={2} maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)} className={`${input} mt-1 w-full`}/></label>
     <div className="flex flex-wrap gap-2"><button type="button" disabled={busy||!canManage||!actor||annotation.isDirty||annotation.isSaving||!value.settings.review_enabled||reviewResolved} className={`${button} border-emerald-700`} onClick={()=>void run(()=>imageAction('approve'))}>승인 표 제출</button><button type="button" disabled={busy||!canManage||!actor||annotation.isDirty||annotation.isSaving||!reason.trim()||!value.settings.review_enabled||reviewResolved} className={`${button} border-rose-700`} onClick={()=>void run(()=>imageAction('reject'))}>반려 표 제출</button>{['disputed','rejected'].includes(metadata.team?.review_status||'')&&<><button type="button" disabled={busy||!canManage||!actor||!reason.trim()||annotation.isDirty} className={button} onClick={()=>void run(()=>imageAction('adjudicate-approve'))}>최종 승인 조정</button><button type="button" disabled={busy||!canManage||!actor||!reason.trim()||annotation.isDirty} className={button} onClick={()=>void run(()=>imageAction('adjudicate-reject'))}>최종 반려 조정</button></>}</div>
     {!!metadata.team?.reviews.length&&<ul className="space-y-1 text-sm">{metadata.team.reviews.map((row,index)=><li key={`${row.actor}-${index}`} className="rounded bg-slate-950 p-2">{row.actor} · {row.decision==='approve'?'승인':'반려'} · {row.reason||'의견 없음'}</li>)}</ul>}{team?.adjudication&&<div className="rounded border border-cyan-700 bg-cyan-950/20 p-3 text-sm"><p>최종 판정 조정 · {team.adjudication.actor} · {team.adjudication.decision==='approve'?'승인':'반려'}</p><p className="mt-1 text-slate-300">{team.adjudication.reason}</p></div>}<p className="text-sm text-slate-400">검수할 라벨은 먼저 저장하세요. 원본·라벨·기준·정책이 바뀌면 이전 표는 승인 근거로 쓰지 않습니다.</p>
    </>:<p className="text-sm text-slate-400">이미지를 선택하세요.</p>}
    {ready&&<div className="space-y-2 border-t border-slate-700 pt-3"><p className="text-sm">{reviewTrainingMessage(ready)}</p>{ready.blockers.map(row=><p key={row} className="text-sm text-amber-200">{row}</p>)}<button type="button" disabled={busy||!ready.ready||annotation.isDirty||annotation.isSaving} className={`${button} border-cyan-700`} onClick={()=>void toTraining()}>검수 데이터로 학습 준비</button><p className="text-xs text-slate-400">3단계에서 부모 모델과 실행 자원을 선택합니다. 기존 시험 이미지는 학습으로 옮기지 않습니다.</p></div>}
    </section><section aria-label="팀 작업 목록" className="space-y-3 rounded border border-slate-700 p-4"><h3 className="flex items-center gap-2 font-semibold"><BookOpen className="h-4 w-4 text-cyan-300"/>담당·검수 작업 목록</h3><div className="flex flex-wrap gap-2"><label className="text-sm">담당 필터<input aria-label="작업 목록 담당 필터" value={filterActor} onChange={e=>{setFilterActor(e.target.value);setOffset(0);}} className={`${input} ml-2 w-32`} placeholder="전체"/></label><select aria-label="작업 목록 상태" value={filterState} onChange={e=>{setFilterState(e.target.value);setOffset(0);}} className={input}><option value="">모든 상태</option><option value="pending">검수 대기</option><option value="approved">승인</option><option value="rejected">반려</option><option value="disputed">의견 불일치</option></select></div>
     <p className="text-xs text-slate-400">총 {queue?.total??0}장 · 우선순위 높은 작업부터 표시</p><ol className="max-h-[45vh] space-y-2 overflow-auto">{queue?.items.map(row=><li key={row.image_uuid} className={`rounded border p-3 ${metadata?.image_uuid===row.image_uuid?'border-cyan-600 bg-cyan-950/20':'border-slate-700'}`}><button type="button" disabled={busy||annotation.isSaving} onClick={()=>void run(async()=>{await useProjectStore.getState().openImageForLabeling(row.relative_path.split(/[\\/]/).pop()!.replace(/\.[^.]+$/,''),row.file_path);})} className="w-full break-all text-left text-sm text-cyan-100">{row.relative_path}</button><p className="mt-1 text-xs text-slate-400">{row.team?statusNames[row.team.review_status]:'검수 대기'} · 담당 {value.members.find(member=>member.id===row.team?.assignment?.assignee)?.name||row.team?.assignment?.assignee||'미배정'} · 우선 {row.team?.assignment?.priority??0}</p></li>)}</ol><div className="flex items-center gap-2"><button type="button" disabled={busy||offset===0} onClick={()=>setOffset(Math.max(0,offset-30))} className={button}>이전</button><span className="text-xs">{queue?.total?`${offset+1}–${Math.min(offset+30,queue.total)}`:"0건"}</span><button type="button" disabled={busy||offset+30>=(queue?.total||0)} onClick={()=>setOffset(offset+30)} className={button}>다음</button></div>
    </section></div>}
   </>}
  </div></WorkspaceDialog>}
 </div>;
}
