import React,{useEffect,useState,useRef} from 'react';
import {request} from '../../services/api';
import {useProjectStore} from '../../stores/useProjectStore';
import {useComputeStore} from '../../stores/useComputeStore';
import {useAnnotationStore} from '../../stores/useAnnotationStore';

type Target={id:string;name:string;gpu_selector:string|null;allow_sharing:boolean;memory_budget_mb:number|null;distributed_processes:number};
type Job={job_id:string;task:string;operation:string;status:string;phase:string|null;compute_profile_id:string;current_epoch:number;total_epochs:number;current_step:number;total_steps:number;metrics:Record<string,number>;error:{message?:string}|null};
const names:Record<string,string>={classification:'분류',patch_classification:'패치 분류',detection:'객체 검출',segmentation:'분할',anomaly:'이상 분석',rotation:'회전 보정',ocr:'문자 인식',rotated_detection:'회전 객체 검출',enhancement:'이미지 개선',defect_gan:'결함 생성',labeling:'AI 라벨 후보'};
const states:Record<string,string>={queued:'대기',running:'실행 중',stopping:'취소 중',completed:'완료',aborted:'취소됨',failed:'실패',disconnected:'연결 끊김'};
export const ComputeJobsPanel:React.FC<{onOpenReview?:()=>void}>=({onOpenReview})=>{
  const project=useProjectStore(state=>state.project);
  const revision=useComputeStore(state=>state.transportRevision);
  const selectedImage=useAnnotationStore(state=>state.currentImage);
  const contextKey=`${project?.id}:${revision}`;const currentContext=useRef(contextKey);currentContext.current=contextKey;
  const [targets,setTargets]=useState<Target[]>([]),[target,setTarget]=useState(''),[task,setTask]=useState('classification'),[inputs,setInputs]=useState<{dataset_path:string;name:string}[]>([]),[input,setInput]=useState(''),[epochs,setEpochs]=useState(1),[batch,setBatch]=useState(4),[prompt,setPrompt]=useState(''),[label,setLabel]=useState('defect'),[rows,setRows]=useState<Job[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[result,setResult]=useState<Record<string,unknown>|null>(null);
  const refresh=async()=>{const scope=currentContext.current;const value=await request<{jobs:Job[]}>('/api/compute/jobs');if(scope===currentContext.current)setRows(value.jobs);};
  useEffect(()=>{let live=true;setRows([]);setTargets([]);setResult(null);setError('');setBusy(false);const poll=async()=>{try{const [values,jobs]=await Promise.all([request<{targets:Target[]}>('/api/compute/targets'),request<{jobs:Job[]}>('/api/compute/jobs')]);if(live){setTargets(values.targets);setRows(jobs.jobs);setTarget(previous=>values.targets.some(row=>row.id===previous)?previous:values.targets[0]?.id||'');}}catch(cause){if(live)setError(cause instanceof Error?cause.message:String(cause));}};void poll();const timer=window.setInterval(poll,5000);return()=>{live=false;window.clearInterval(timer);};},[project?.id,revision]);
  useEffect(()=>{let live=true;setInputs([]);setInput('');request<{inputs:{dataset_path:string;name:string}[]}>(`/api/compute/inputs?task=${encodeURIComponent(task)}`).then(value=>{if(live){setInputs(value.inputs);setInput(value.inputs[0]?.dataset_path||'');}}).catch(cause=>{if(live)setError(String(cause));});return()=>{live=false;};},[task,project?.id,revision]);
  const run=async(action:()=>Promise<void>)=>{const scope=currentContext.current;setBusy(true);setError('');try{await action();}catch(cause){if(scope===currentContext.current)setError(cause instanceof Error?cause.message:String(cause));}finally{if(scope===currentContext.current)setBusy(false);}};
  const submit=async()=>{const selected=targets.find(row=>row.id===target);await request('/api/compute/jobs',{method:'POST',body:JSON.stringify({task,operation:task==='labeling'?'label':'train',dataset_path:project?.source_dataset_dir,family_dataset_path:input,compute_profile_id:target,device:selected?.gpu_selector?'cuda:0':'cpu',config_overrides:{epochs,batch_size:batch},labeling:task==='labeling'?{prompt,label,output_geometry:'polygon',threshold:.5}:{} })});await refresh();};
  const control=async(row:Job,action:'cancel'|'reconnect')=>{await request(`/api/compute/jobs/${encodeURIComponent(row.job_id)}/${action}`,{method:'POST'});await refresh();};
  const field='rounded border border-slate-600 bg-slate-950 px-2 py-1.5 text-xs text-slate-200';
  return <details className="mt-3 rounded border border-slate-700 p-3 text-xs"><summary className="cursor-pointer font-bold text-cyan-200">서버 작업과 대기열</summary><p className="mt-2 text-[11px] text-slate-400">원본과 라벨 버전을 고정해 선택한 서버에서 실행합니다. AI 라벨은 검토할 후보로 저장됩니다.</p>
    <div className="mt-3 grid grid-cols-2 gap-2"><label>작업 종류<select aria-label="서버 작업 종류" value={task} onChange={e=>setTask(e.target.value)} className={`${field} mt-1 w-full`}>{Object.entries(names).map(([key,name])=><option key={key} value={key}>{name}</option>)}</select></label><label>실행 서버<select aria-label="작업 실행 서버" value={target} onChange={e=>setTarget(e.target.value)} className={`${field} mt-1 w-full`}><option value="">서버 선택</option>{targets.map(row=><option key={row.id} value={row.id}>{row.name} · {row.distributed_processes>1?`${row.distributed_processes} GPU 분산`:row.allow_sharing?`${row.memory_budget_mb} MiB 공유`:row.gpu_selector||'CPU'}</option>)}</select></label></div>
    <label className="mt-2 block">검증된 학습 입력<select aria-label="서버 작업 학습 입력" value={input} onChange={e=>setInput(e.target.value)} className={`${field} mt-1 w-full`}><option value="">입력을 준비하세요</option>{inputs.map(row=><option key={row.dataset_path} value={row.dataset_path}>{row.name}</option>)}</select></label>
    {task==='labeling'?<div className="mt-2 space-y-2"><input aria-label="원격 라벨 후보 텍스트" value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="찾을 구조나 결함 설명" className={`${field} w-full`}/><input aria-label="원격 라벨 클래스 이름" value={label} onChange={e=>setLabel(e.target.value)} placeholder="라벨 클래스" className={`${field} w-full`}/><p className="text-[10px] text-slate-500">서버 관리자가 SAM2와 텍스트 모델 경로를 설정해야 실행할 수 있습니다.</p></div>:<div className="mt-2 grid grid-cols-2 gap-2"><label>학습 반복<input aria-label="서버 학습 반복" type="number" min={1} max={500} value={epochs} onChange={e=>setEpochs(Number(e.target.value))} className={`${field} mt-1 w-full`}/></label><label>배치 크기<input aria-label="서버 학습 배치" type="number" min={1} max={128} value={batch} onChange={e=>setBatch(Number(e.target.value))} className={`${field} mt-1 w-full`}/></label></div>}
    <button disabled={busy||!target||!input||!project?.source_dataset_dir||(task==='labeling'&&!prompt.trim())} onClick={()=>void run(submit)} className="mt-3 rounded bg-cyan-800 px-3 py-2 font-semibold disabled:opacity-40">작업 등록</button>
    <div className="mt-3 space-y-2">{rows.length===0&&<p className="text-slate-500">이 프로젝트에 등록된 서버 작업이 없습니다.</p>}{rows.map(row=><article key={row.job_id} className="rounded bg-slate-950/60 p-2"><div className="flex justify-between gap-2"><span>{names[row.task]||row.task} · {targets.find(t=>t.id===row.compute_profile_id)?.name||'서버'}</span><span className={row.status==='failed'?'text-red-300':row.status==='completed'?'text-emerald-300':'text-slate-300'}>{states[row.status]||row.status}</span></div><p className="mt-1 text-[10px] text-slate-500">{row.total_epochs>0?`${row.current_epoch}/${row.total_epochs} 반복`:row.total_steps>0?`${row.current_step}/${row.total_steps} 이미지`:'진행 정보 대기'}</p><div className="mt-2 flex gap-2">{['running','queued','stopping'].includes(row.status)&&<button disabled={busy} onClick={()=>void run(()=>control(row,'cancel'))} className="rounded border border-red-700 px-2 py-1 text-red-200">취소</button>}{row.status==='disconnected'&&<button disabled={busy} onClick={()=>void run(()=>control(row,'reconnect'))} className="rounded border border-amber-700 px-2 py-1 text-amber-200">같은 작업 재연결</button>}{row.status==='completed'&&row.operation==='train'&&<button disabled={busy||!selectedImage?.file_path} onClick={()=>void run(async()=>{const scope=currentContext.current;const value=await request<Record<string,unknown>>(`/api/compute/jobs/${encodeURIComponent(row.job_id)}/predict`,{method:'POST',body:JSON.stringify({image_path:selectedImage?.file_path})});if(scope===currentContext.current)setResult(value);})} className="rounded border border-emerald-700 px-2 py-1 disabled:opacity-40">{row.task==='defect_gan'?'서버에서 후보 생성':'선택 이미지로 서버 확인'}</button>}{row.status==='completed'&&<button disabled={busy} onClick={()=>void run(async()=>{const scope=currentContext.current;const value=await request<Record<string,unknown>>(`/api/compute/jobs/${encodeURIComponent(row.job_id)}/results`);if(scope===currentContext.current)setResult(value);})} className="rounded border border-cyan-700 px-2 py-1">결과 확인</button>}</div>{row.error?.message&&<p role="alert" className="mt-1 break-words text-red-300">{row.error.message}</p>}</article>)}</div>
    {result&&<div className="mt-3 rounded border border-slate-600 p-2"><div className="flex justify-between"><strong>저장된 결과</strong><button onClick={()=>setResult(null)} className="text-slate-400">닫기</button></div>{Array.isArray(result.results)?<div><p className="mt-2">라벨 후보가 {result.results.length}개 이미지에 저장됐습니다. 검토 상태: 대기.</p><button disabled={busy} onClick={()=>void run(async()=>{const scope=currentContext.current;await request(`/api/compute/jobs/${encodeURIComponent(String(result.job_id))}/label-proposals`,{method:'POST'});if(scope===currentContext.current){await useProjectStore.getState().setStep(2);onOpenReview?.();}})} className="mt-2 rounded bg-cyan-800 px-3 py-2 font-semibold disabled:opacity-40">라벨 검토에 불러오기</button></div>:<p className="mt-2">{names[String(result.task)]||String(result.task)} · 검증 지표 {typeof result.best_metric==='number'?result.best_metric.toFixed(5):'상세 모델 정보에 저장'}</p>}</div>}
    {typeof result?.overlay_base64==='string'&&<div className="mt-2"><img src={result.overlay_base64} alt="서버에서 확인한 저장 모델의 실제 출력" className="max-h-64 max-w-full rounded"/>{result.task==='defect_gan'&&<p className="mt-1 text-amber-200">생성 후보 · 검토 전 · 품질 승인 없음</p>}<details className="mt-2 text-slate-400"><summary>실제 추론 결과</summary><pre className="max-h-40 overflow-auto whitespace-pre-wrap">{JSON.stringify(result.predictions,null,2)}</pre></details></div>}
    {error&&<p role="alert" className="mt-2 break-words text-red-300">{error}</p>}
  </details>;
};
