import {useEffect,useState} from 'react';
import {type ComputeProfile} from '../../services/api';
import {useComputeStore} from '../../stores/useComputeStore';
import {productDeliveryApi} from '../../services/productDeliveryApi';
import {useDeliveryScope} from '../runtime/useDeliveryScope';
import {ImageSearchSelect} from '../common/ImageSearchSelect';

export function ServerConnectionWizard({onAdd,onEdit}:{onAdd:()=>void;onEdit:(value:ComputeProfile)=>void}){
 const {scope,key,project}=useDeliveryScope(),profiles=useComputeStore(s=>s.profiles),probeProfile=useComputeStore(s=>s.probeProfile),selectTarget=useComputeStore(s=>s.selectTarget);
 const [target,setTarget]=useState(''),[step,setStep]=useState(1),[image,setImage]=useState(''),[report,setReport]=useState<Awaited<ReturnType<typeof productDeliveryApi.preflight>>|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{setStep(1);setReport(null);setTarget('');setImage('');setError('');setBusy(false);},[key]);
 const run=async(fn:()=>Promise<void>)=>{const started=scope.current;setBusy(true);setError('');try{await fn();}catch(e){if(scope.current===started)setError(String((e as Error).message||e));}finally{if(scope.current===started)setBusy(false);}};
 const selected=profiles.find(p=>p.id===target);
 return <details className="mt-3 rounded border border-blue-700 bg-blue-950/15 p-3 text-xs"><summary className="cursor-pointer font-semibold text-blue-200">서버 연결 안내 · 실제 입력 확인</summary><ol className="my-3 flex flex-wrap gap-2 text-slate-400">{['서버 설정','실행 환경 확인','실제 입력 확인'].map((name,index)=><li key={name} className={step===index+1?'font-semibold text-blue-200':''}>{index+1}. {name}</li>)}</ol>
  {step===1&&<div className="space-y-2"><p className="text-slate-400">어떤 SSH 서버든 저장한 프로필로 연결합니다. 키·SSH agent와 알려진 호스트 인증을 사용합니다.</p><select aria-label="연결 안내 서버" value={target} disabled={busy} onChange={e=>{setTarget(e.target.value);setReport(null);}} className="w-full rounded bg-slate-800 p-2"><option value="">저장한 서버 선택</option>{profiles.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><div className="flex gap-2"><button type="button" onClick={onAdd} className="rounded border border-slate-600 px-3 py-2">새 서버 설정</button>{selected&&<button type="button" onClick={()=>onEdit(selected)} className="rounded border border-slate-600 px-3 py-2">선택 서버 수정</button>}<button type="button" disabled={!selected||busy} onClick={()=>setStep(2)} className="rounded bg-blue-700 px-3 py-2 disabled:opacity-40">환경 확인으로</button></div></div>}
  {step===2&&selected&&<div className="space-y-2"><p>{selected.name} · {selected.runtime_kind} · {selected.gpu_selector?'선택 GPU '+selected.gpu_selector:'CPU'}</p><p className="text-slate-400">SSH·실행 파일·공간·필수 패키지·장치 UUID를 검사합니다. 작업은 시작하지 않습니다.</p><button type="button" disabled={busy} onClick={()=>void run(async()=>{const started=scope.current;const result=await probeProfile(target);if(scope.current===started){if(!result.ready)throw new Error(result.message||'실행 환경을 준비하세요.');setStep(3);}})} className="rounded bg-blue-700 px-3 py-2 disabled:opacity-40">연결·환경 검사</button><button type="button" onClick={()=>onEdit(selected)} className="ml-2 rounded border border-slate-600 px-3 py-2">설정 수정</button></div>}
  {step===3&&<div className="space-y-2"><p className="text-slate-400">프로젝트 원본으로 전송·SHA-256·디코딩·CPU tensor 계산을 검사합니다. 학습이나 모델 품질 평가를 시작하지 않습니다.</p><ImageSearchSelect label="서버 사전 검사 이미지" value={image} onChange={setImage} disabled={busy} autoSelectFirst folder={project?.source_dataset_dir} task={project?.task}/><p className="text-slate-500">원본 64 MiB·1억5천만 픽셀까지 전송하며 계산은 최대 1024×1024 CPU 미리보기로 제한합니다.</p><button type="button" disabled={busy||!image} onClick={()=>void run(async()=>{const started=scope.current;const result=await productDeliveryApi.preflight(target,image);if(scope.current===started)setReport(result);})} className="rounded bg-blue-700 px-3 py-2 disabled:opacity-40">실제 입력 사전 검사</button>{report&&<div role="status" className={report.ready?'text-emerald-300':'text-amber-300'}>{report.ready?'입력 전송·실행 확인':'준비 확인 필요'}{report.input&&<p className="mt-1">{report.input.width} × {report.input.height} · 원본/서버 해시 {report.input.local_sha256===report.input.remote_sha256?'일치':'불일치'}</p>}<p>학습 시작 없음 · {new Date(report.observed_at*1000).toLocaleString()}</p>{report.ready&&<button type="button" disabled={busy} onClick={()=>void run(()=>selectTarget(target))} className="mt-2 rounded border border-emerald-700 px-3 py-2">이 서버를 새 작업 대상으로</button>}</div>}</div>}
  {step>1&&<button type="button" disabled={busy} onClick={()=>{setStep(step-1);setReport(null);}} className="mt-2 text-slate-400">이전 단계</button>}{busy&&<p role="status" className="mt-2 text-blue-300">서버 응답 확인 중…</p>}{error&&<p role="alert" className="mt-2 break-all text-red-300">{error}</p>}
 </details>;
}
